### ISSUE TITLE
Connect to sysrepo over TCP socket

### ISSUE THREAD

**Issue by przemekr** [sysrepo/sysrepo#1000]
Enhancement: Make it possible to connect to the Sysrepo over a TCP socket. 

This would be very useful for distributed applications (device with multiple blades, application running in cloud or container environment).

**Comment by michalvasko** [comment]
Hi,
it is currently possible to connect to sysrepo indirectly through *netopeer2-server*, to which you connect securely using SSH or TLS transport (underneath is also TCP/IP, but okay) and transport *NETCONF* protocol application data.

You would like to connect to sysrepo through *another-daemon*, to which you connect insecurely using TCP directly (I guess) and transport *some-protocol* application data. As you see, we are short of *another-daemon* and *some-protocol*. Even though they both could be quite simple, I would not classify this as an enhancement and so we will not implement this. If you need it, you will have to write it yourself and optionally send us a patch to include it in the main repository.

Regards,
Michal

**Comment by przemekr** [comment]
Hi, thank you for the quick reply/feedback.  I guess the NETCONF doesn't have the same functionality as Sysrepo client-server IF. For example it wouldn't be possible to make an application a data-provider. 

I am not sure if another daemon/protocol would really be needed, Sysrepo could use the same protocol as it has on unix domain sockets only listen to some TCP port.  This is how the most of the database servers do.

**Comment by michalvasko** [comment]
Please, use clear terminology, I am getting lost. The only *sysrepo* client-server interface I know of is `libsysrepo` meaning the client is either a deamon (*netopeer2-server*) or a plugin for *sysrepo-plugind* (our *keystored*, for example), there are currently no other ways of communicating with *sysrepo*. Also, I do not know what you mean by "data-provider" at all, we usually use the term for applications that provide YANG state data for *sysrepo* but that is probably not what you had in mind.

Having cleared it a bit, your proposal is to skip the remote communication and send directly what is communicated internally between `libsysrepo` and `sysrepod` using TCP. *sysrepo* was designed quite heavily with having security concerns and access control in mind because it is meant to manage all system configuration, which are often sensitive data. Your use-case is different in this aspect so what I have said previously mostly remains true, we will likely not help you with the implementation directly. Also, it basically breaks the current architecture so without the need to modify *sysrepo*, you are left only with my original suggestion, a separate daemon and protocol.

Regards,
Michal
