### ISSUE TITLE
Updating running DB 

### ISSUE THREAD

**Issue by rosy8** [sysrepo/sysrepo#1042]
Hi Michal,

We can set/update the running db directly  by using the sr_set_item  right ?
I donot think  we need to  execute sr_commit() is  explicitly post sr_set_item(..) call for the data to be persistent on DB.

Please correct me if I am wrong.

Regards,
Rosy

**Comment by michalvasko** [comment]
Hi Rosy,
you need to execute `sr_commit()` for the data to be persistent and visible for other sessions.

Regards,
Michal

**Comment by rosy8** [comment]
Hi Michal,

Thanks for your response.
 Is there any other API which I can use for this purpose ?
 Which will  copy already validated/verified data in to sysrepo running DB and it will be persistent .
 If I do sr_commit, I will get SR_EV_VERIFY/SR_EV_APPLY  which I want to skip .

Regards,
Rosy

**Comment by michalvasko** [comment]
Hi Rosy,
you should be able to do this if you perform those additional changes in a separate thread.

Regards,
Michal

**Comment by rosy8** [comment]
Hi Michal,

edit-config - commit
SR_EV_VERIFY
-- Everything OK
SR_EV_APPLY
====>> Here I am adding data manipulation of the Sysrepo running DB by using sr_set_item  and have skipped sr_commit .
====>>
return Ok (Response  for SR_EV_APPLY event processing)

And for this I could see data is persistent between  different sessions .
I am talking about this specific scenario..

Please let me know your feedback on this.

Regards,
Rosy

**Comment by michalvasko** [comment]
Hi Rosy,
I cannot tell you for sure whether it is supported and will not cause some problems but I would try what I have suggested, when processing `SR_EV_APPLY` I would create another thread and do `sr_set_item` and `sr_commit`. Not the most elegant way, but may work.

Regards,
Michal

**Comment by rosy8** [comment]
Hi Michal,

Thanks for responding back.
 I create a new thread and perform the sr_set_items/sr_commit on the new thread.
Then after sr_commit, it will generate SR_EV_VERIFY/SR_EV_APPLY events right ?
So how sysrepo is going to handle that ?? 
As per my knowledge  sysrepo data manipulation are blocking call.
So sysrepo is not going to process the new SR_EV_VERIFY unless it gets the response back for the earlier
event (SR_EV_APPLY from the main thread ). Also here only one connection is there.

But i donot want that to happen..I want the data manipulation to be done when the main thread returns the response for SR_EV_APPLY.

Not sure how its going to take care if I create a another connection on the new thread.

Please correct me if I am missing something.
Regards,
Rosy

**Comment by michalvasko** [comment]
Hi Rosy,
the main problem with your whole scenario is that you want to make some additional changes in the `running` configuration that should not trigger sysrepo callbacks. That goes against the whole idea of sysrepo, what if there was some other application subscribed to the value you want to silently change? It would hardly work properly.

So, I am suggesting only workarounds, more-or-less. This whole problem is more complex and the solution is being worked on with [NMDA](https://tools.ietf.org/html/draft-ietf-netconf-nmda-netconf-02). Until it is finished and implemented in sysrepo, there is no proper solution.

Having said that, just try what I am proposing. If it hangs (possible because of the reason you mentioned), you can create the thread detached and not wait for it to finish in the original callback handling `SR_EV_APPLY`. That could solve the deadlock but you will then also need to handle the second callback call for that change performed in the detached thread (which I think should occur).

Regards,
Michal

**Comment by knoll01** [comment]
+1 for an enhancement like this. Ideally, this would be a "split-horizon" type thing. Don't call the callback on the session that commits the changes, but call it on all the other sessions. Perhaps a session option could be added to enable and disable this.

**Comment by maksimvuleta** [comment]
@rosy8 Did you succeeded to implement this mechanism to update the running datastore?

**Comment by michalvasko** [comment]
Fixed.
