### ISSUE TITLE
Query on sr_commit 

### ISSUE THREAD

**Issue by rosy8** [sysrepo/sysrepo#1070]
Hi Michal,

When we do sr_commit(), we get events like 
                                 ------->>SR_EV_VERIFY
                                   --->>SR_EV_APPLY( If SR_EV_VERIFY returns OK --For successful  verify)
                                  ----->> SR_EV_ABORT (If SR_EV_VERIFY returns OK  ---For verify failed case).
So as per my understanding, only after it returns OK response for the SR_EV_APPLY (for successful) case..
That commit cycle gets completed successfully  and sysrepo performs post commit operation . (i.e Unlocking the datastore etc.. )

But when I do execute through netconf browser..what I do see is that the "Ok" reply for "commit" rpc operation  comes quite early. (Even though by looking at the debuglog, its still in the middle of processing the client code related to SR_EV_APPLY (i.e It has not return OK response for event SR_EV_APPLY ).

I do observe after the Ok response for SR_EV_VERIFY is returned, the browser shows the rpc-reply with Ok msg. 

```
<?xml version="1.0" encoding="utf-8"?>
<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="9">
  <commit/>
</rpc>

<?xml version="1.0" encoding="utf-8"?>
<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="9">
  <ok/>
</rpc-reply>
```
Is it because of the following reason ?

    SR_EV_VERIFY,  /**< Occurs just before the changes are committed to the datastore,
                        the subscriber is supposed to verify that the changes are valid and can be applied
                        and prepare all resources required for the changes. The subscriber can still deny the changes
                        in this phase by returning an error from the callback. */
    SR_EV_APPLY,   < Occurs just after the changes have been successfully committed to the datastore,
                        the subscriber is supposed to apply the changes now, **but it cannot deny the changes in this
                        phase anymore (any returned errors are just logged and ignored)**. 

Please let me know if I am missing something here.

Regards,
Rosy

**Comment by michalvasko** [comment]
Hi Rosy,
`sr_commit()` and NETCONF `<commit>` are quite different operations, unfortunately. `sr_commit()` is basically apply changes meaning it only applies temporary changes in a session so that they are permanently stored and visible for all the sessions (except `candidate` datastore, that one is never shared between sessions). Equivalent of NETCONF `<commit>` would be a `sr_copy_config()` from `SR_DS_CANDIDATE` to `SR_DS_RUNNING` (that is how *netopeer2* implements it).

I think I answered your question but I am not completely sure, did I?

Regards,
Michal

**Comment by rosy8** [comment]
hehe.
Thank you  very much Michal for replying  :)
Yeah..U answered to some extent but still would bug you little more to get clarity on this. Sorry for that :)

sr_commit() and NETCONF commit may be different internally..
But in both the cases finally sysrepo generates events like (SR_EV_VERIFY followed by SR_EV_APPLY for successful SR_EV_VERIFY case).

But when does it returns rpc-reply "OK" msg to client. ( I mean afters which event ?? )

Regards,
Rosy

**Comment by michalvasko** [comment]
Hi Rosy,
I will try to explain in more detail.

There is a NETCONF client connected to NETCONF server (*netopeer2-server*) communicating with *sysrepo*. The client first performs some changes in `candidate` and then decides to execute NETCONF `<commit>`. This is what happens.

After every small change in `candidate`, *netopeer2* issues `sr_set_item()` followed by `sr_commit()`. The former sets the value, the latter verifies access control and NACM (if the datastore was `startup` or `running`, `sr_commit()` would additionally "apply" the changes, make them permanent, however, as `candidate` is always only temporary, this does not happen now).

Next, NETCONF `<commit>` is translated to `sr_copy_config()` inside *netopeer2* because `sr_commit()` would not do anything (which is clear from what I just said, I hope). However, `sr_copy_config()` from any datastore to `running` (right now we are performing copy-config `candidate` -> `running`) correctly triggers callbacks (application events). So, once `sr_copy_config()` succeeds, *netopeer2* successfully performed a NETCONF `<commit>` and can return a NETCONF rpc-reply `<ok>`.

Regards,
Michal

**Comment by rosy8** [comment]
Hi Michal,

Thanks again..
I do understand what you have pointed out here..

But as you have mentioned  above, during commit operation internally "sr_copy_config()" is being invoked..which copies the config from candidate to running.. And since there is a change in the running DB, the client main module callback will get triggered (first with sysrepo event SR_EV_VERIFY followed by SR_EV_APPLY). 

So what you saying is that just after this sr_copy_config is done,  netconf client will get the OK reply ??
It does not wait for the SR_EV_VERIFY/SR_EV_APPLY to get complete ?

Regards,
Rosy

**Comment by rosy8** [comment]
Hi Michal,

I hope you talking about the below code...

struct nc_server_reply *
**op_commit**(struct lyd_node *UNUSED(rpc), struct nc_session *ncs)
{
    struct np2_sessions *sessions;
    int rc;
    bool permitted;

    /* get sysrepo connections for this session */
    sessions = (struct np2_sessions *)nc_session_get_data(ncs);

    /* check NACM */
    rc = sr_check_exec_permission(sessions->srs, "/ietf-netconf:commit", &permitted);
    if (rc != SR_ERR_OK) {
        return op_build_err_sr(NULL, sessions->srs);
    } else if (!permitted) {
        return op_build_err_nacm(NULL);
    }

    rc = **sr_copy_config(sessions->srs, NULL, SR_DS_CANDIDATE, SR_DS_RUNNING);**
    if (rc != SR_ERR_OK) {
        /* get the error */
        return op_build_err_sr(NULL, sessions->srs);
    }

    /* remove modify flag */
    sessions->flags &= ~NP2S_CAND_CHANGED;

    return nc_server_reply_ok();
}

**Comment by michalvasko** [comment]
As far as I know, `sr_copy_config()` will not finish unless all the generated events are handled. Your experience is different?

**Comment by rosy8** [comment]
Hi Michal,

Yeah, even i was having that assumption that netopeer will wait for all events to be handled  before replying rpc-reply msg.

But as I had specified above for sure it does not wait for the SR_EV_APPLY to get complete.

Regards
Rosy

**Comment by michalvasko** [comment]
Hi Rosy,
you are right, I have never really enquired about this myself. However, it makes sense with respect to how *sysrepo* callbacks were designed. Normally, you receive first `SR_EV_VERIFY` event followed by `SR_EV_APPLY`. When handling the verify event, the application has the chance to verify that the prepared change is fine or refuse it if it is not. Once the change is verified, the application commits itself to successfully apply the change when called on the apply event. *Sysrepo* commit waits for `SR_EV_VERIFY` but has no reason to wait for `SR_EV_APPLY` since it know it will succeed.

Just a note, this design is not perfect because there are always corner cases when `SR_EV_VERIFY` will succeed and `SR_EV_APPLY` will not (race conditions, ...) but in the rare case it happens, it is not a fatal problem.

Regards,
Michal

**Comment by rosy8** [comment]
Hi Michal,

Thanks for the update.
But when commits are triggered frequently.. then there is a chance that this race condition may occur.
For example 
1) Config 1 
      --> Commit triggered
      ---> Got event SR_EV_VERIFY 
            It return SR_ERR_OK for this event.
So now netopeer will also rpc-reply with OK and since client has already got rpc-reply, it can push the config2 (next config) on the candidate db..

In this kind of scenario there is a chance of timeout happening before even the SR_EV_APPLY is triggered or as you had specified something may go wrong during SR_EV_APPLY phase also.

So it would be better if netopeer2 would wait for all events to get completed and once processing of all events are done then only  returning the rpc-reply message.

Regards,
Rosy

**Comment by michalvasko** [comment]
Hi Rosy,
like I said, this design is not perfect but it is what it is and *netopeer2* currently has no way of waiting for `SR_EV_APPLY` events to be applied. Actually, if you know that in your case you cannot verify with certainty whether a change can be applied in advance, you can apply the changes in `SR_EV_VERIFY` and then simply ignore `SR_EV_APPLY` events. So, to solve you problem, I would suggest you increase commit timeout if you know you issue many successive commits. Overall callback design of *sysrepo* will not be changed.

Regards,
Michal
