### ISSUE TITLE
Understanding of sysrepo commit call 

### ISSUE THREAD

**Issue by rosy8** [sysrepo/sysrepo#1159]
Hi,

In the sysrepo.h file, its mentioned that "Each data access/manipulation request call is blocking".

So by that what i used to understand is that, for  edit-config commit case,  sysrepo will not start processing the next commit untill the on going commit is completed. (i.e its done with both SR_EV_VERIFY and SR_EV_APPLY event for successful verification case). 

But I have observed that the 2nd commit  gets processed even if the 1st commit cycle has not been completed. 
-1st commit started.
     -- SR_EV_VERIFY returns ok 
Now if somehow if  a 2nd commit is triggered then again SR_EV_VERIFY for the 2nd commit starts even though the SR_EV_APPLY for 1st commit has not been completed yet.

I know In file syrepo.h, its been mentioned that once SR_EV_VERIFY is successful and after that if  any error happens in SR_EV_APPLY event then sysrepo ignores that.  So from this i am got that SR_EV_VERIFY is the important event based on which the next action is taken. 

But by blocking means , does not it has to wait for the next event(SR_EV_APPLY) to get completed ?
Also as per my understanding lock is released after the SR_EV_APPLY is completed. Then why sysrepo processed the 2nd commit before the completion of the 1st ?
 
Would appreciate if anybody can help me in understanding this.

Regard's
Rosy

**Comment by michalvasko** [comment]
Hi Rosy,
you correctly described the commit, not sure what to add. And by blocking is meant what follows: `blocks the connection until the response from Sysrepo Engine comes, or until an error occurs` Response from sysrepo comes right after `SR_EV_VERIFY` is finished in case of `sr_commit`.

It is, then, true that an application may get `SR_EV_VERIFY` value `1`, then `SR_EV_VERIFY` value `2` followed by `SR_EV_APPLY` value `1` and `SR_EV_APPLY` value `2`. But that should not really matter.

Regards,
Michal

**Comment by michalvasko** [comment]
Hi Rosy,
now I am also a bit confused but I will try to elaborate and we will see. This is what I think is happening, I will use a scenario when session 1 (`S1`) tries to commit `leaf` value `a` and session 2 (`S2`) right after tries to commit `leaf` value `b`.

Commit of `S1` is started, it blocks `S1`. Callback with `SR_EV_VERIFY` on `leaf` value `a` is called. It succeeds. `S1` gets OK and now it is moved to the next phase and wants to call callback with `SR_EV_APPLY` on `leaf` value `a`. But, since this is the actual modification of datastore, it locks `commit` lock. Now `S2` can issue another commit and the first phase can take place because it does not require any global resources. So, callback is now called with `SR_EV_VERIFY` `leaf` value `b`. It ends with success so now this commit on `S2` wants to move to apply phase but it will fail to acquire the global `commit` lock (held by apply phase of commit on `S1`, this is what you meant now?). So, `S1` commit must continue, callback is called with `SR_EV_APPLY` `leaf` value `a`. Succeeds, first commit is finished, so `S2` commit can call the callback with `SR_EV_APPLY` `leaf` value `b`.

That is what I meant, that you may think the order of calling the events will always be `SR_EV_VERIFY` `a`, then `SR_EV_APPLY` `a` but in this case I tried to illustrate that it is possible for events to be `SR_EV_VERIFY` `a`, `SR_EV_VERIFY` `b`, and then `SR_EV_APPLY` `a` and `SR_EV_APPLY` `b`.

Regards,
Michal

**Comment by rosy8** [comment]
Hi Michal,

he he he..  Yeah its little bit confusing.  Did not want to confuse you but  just wanted to understand the behavior :) Thank you very much for your time.  I got what you tried to write in the 2nd para but still not clear on the behavior of sysrepo.

You have mentioned modification of data happens in SR_EV_APPLY phase..but as per my understanding it happens prior to that . Same has been mentioned in the  sysrepo.h file too..
SR_EV_APPLY,   /**< Occurs just after the changes have been successfully committed to the datastore,

So by this time even data has been committed to the db...So why not to release the lock.. That was my query..

Regard's
Rosy
