### ISSUE TITLE
datastore may be locked forever when two client send commit request

### ISSUE THREAD

**Issue by qmm161** [sysrepo/sysrepo#1195]
* [x] Did you check if this is a duplicate issue?
* [x] Did you test it on the latest sysrepo devel branch?

### Description
datastore may be locked forever when two client send commit req.
1. [thread 1]receive commit req
2. [thread 1]run into _rp_req_dispatch_ get write lock _rp_ctx->commit_lock_ success and release lock _rp_ctx->commit_block_mutex_
3. [thread 2]receive commit req
4. [thread 2]run into _rp_req_dispatch_ and get lock  _rp_ctx->commit_block_mutex_ success, and then, try get write lock _rp_ctx->commit_lock_ failed and **blocked** and **hold** the lock _rp_ctx->commit_block_mutex_ 
5. [thread 1]run into _rp_commit_req_process_ and try to get lock _rp_ctx->commit_block_mutex_ with timeout because the lock has been hold by [threa 2] which is in blocked state
6. [thread 1]goto cleanup in _rp_commit_req_process_ but the datastore can't be unlock and the commit context can't be released forever

**Comment by michalvasko** [comment]
Hi,
should not happen any more.

Regards,
Michal

**Comment by qmm161** [comment]
Hi,
you sure the lock is useless? cause I found the boolean value will be set true when client call disconnect.

**Comment by michalvasko** [comment]
The removed lock's only purpose was to manage concurrent access to a boolean value. As long as that value is `volatile` and there is no read and write race of the value in a critical section, there should be no functional changes whether the lock is used or not.

Anyway, if you think something does not work properly then present the whole issue. When a client disconnected before, the value was not set to true?

Regards,
Michal

**Comment by qmm161** [comment]
ok, I get it.

**Comment by jwwilcox** [comment]
> As long as that value is volatile and there is no read and write race of the value in a critical section, there should be no functional changes whether the lock is used or not.

FWIW `volatile` does not mean atomic. While volatile may prevent compiler-reordering/removal of memory accesses, it will not prevent CPU reordering of the accesses. `volatile` is only really useful for memory-mapped I/O and other esoteric use cases. For more info, here's [an article from Intel](https://software.intel.com/en-us/blogs/2007/11/30/volatile-almost-useless-for-multi-threaded-programming) (there is a lot more that can be found in Google).

Since libyang requires C11 support, [atomics from the standard lib](https://en.cppreference.com/w/c/atomic) should be available.

**Comment by michalvasko** [comment]
Hi,
I have read some articles before making this change to make sure I have it right and after reading the article you posted I still stand by what I said and disagree with what was written there (and I am not alone if you read the comments).

General definition is that `volatile` is used to specify a variable that can be changed outside the context it is used (e.g. by another thread) which in turn generates code that does not cache that value and always reads it from memory so that it is up-to-date. That is exactly what I was trying to achieve here. I also believe that reading/writing this particular value (`boolean`) will be atomic on all the platforms *sysrepo* can be compiled on. However, in the extreme case it is not (please, point me to such a platform because I would really like to know the rationale for implementing boolean value with a non-atomic primitive type), **it does not make a functional difference**. If, for instance, one threads writes half of the value before the planner interrupts its execution (how is that even possible when writing `0` or `1`?) and then another thread reads the value, it will always correctly read either `true` or `false`. Also, like I mentioned, in this case no read-write coherence or any other kind is required so it should be fine as it is.

Nevertheless, I am used to working with only basic C features and did not really consider using atomic variables even though they are available now as you correctly pointed out. Having used them would save us this discussion.

Regards,
Michal
