### ISSUE TITLE
configuration error 

### ISSUE THREAD

**Issue by shubhtrix** [sysrepo/sysrepo#1221]
Hi @michalvasko 

I cloned master branch and during configuration, in any mode (i.e., Release/Debug) it's giving error ......

-- Lua version 5.1 was selected
-- Found Lua51: /usr/lib/x86_64-linux-gnu/liblua5.1.so;/usr/lib/x86_64-linux-gnu/libm.so (found version "5.1.5") 
-- Python version 3 was selected
-- Found PythonLibs: /usr/local/lib/libpython3.6m.so (found suitable version "3.6.5", minimum required is "3") 
-- Found PythonInterp: /usr/local/bin/python3.6 (found version "3.6.5") 
-- Found SWIG: /usr/bin/swig3.0 (found suitable version "3.0.12", minimum required is "3.0.5") 
CMake Error at swig/python3/CMakeLists.txt:17 (swig_add_module):
  Unknown CMake command "swig_add_module".

Should I need to down grade my swig version or I can simply replace `swig_add_module` to `swig_add_library` in CMake under swig.
What is the correct way.....

**Comment by michalvasko** [comment]
Hi,
this is quite weird because I also use swig `3.0.12` but it only warns that `SWIG_ADD_MODULE is deprecated. Use SWIG_ADD_LIBRARY instead.` and compiles normally. What distribution are you on? Anyway, either of the solutions is fine, but replacing it with `swig_add_library` seems better.

Regards,
Michal

**Comment by shubhtrix** [comment]
Ya Hi!!

I'm using Ubuntu 18.04 LTS. 
Did that... I mean replaced with `swig_add_library` . Thanks for your reply. Closing the issue.

Regards,
Shubham
