### ISSUE TITLE
Question - A lot of data, frequent changes

### ISSUE THREAD

**Issue by min9kyu-park** [sysrepo/sysrepo#1337]
Hi,

In my project, it's a system where a large amount of data can be changed in a short period of time using YANG.
So, I am considering whether sysrepo is database suitable for my project.

When i checked sysrepo code, it seems to be lock in module unit, right?
In that case, if multiple application approach the same module to write leaf, just one application will use that module and other applications will be block until the first application.

Does sysrepo support partial lock?
For example, A application want to write /A_container/B_list/C_leaf and B application want to write /A_container/D_list/E_leaf at the same time.

During A application is writting C_leaf, I want B application can write E_leaf without blocking.

In additional, I would like to ask you if there is anything else you can advise me about applying sysrpo to my project.

Thanks,
Mr.Park

**Comment by michalvasko** [comment]
Hi,
no, sysrepo does not support partial lock and neither will the new sysrepo. We have decided the gain is not worth the added complexity because, among other issues, we would have to track whether C_leaf does not depend on E_leaf in some way and allow simultaneous access only if not. Generally, for such a use-case to be efficient you could separate the data handled by one application into a single module so that you achieve the concurrency you asked for.

I do not really have more to add, for sysrepo to work well you need to have a well-designed YANG modules but I think that goes for every software that works with YANG. It offers a large variety of features so that as many use-cases can be covered as possible but there is also a disadvantage to this approach. If someone uses some more complex statements when not necessary, the result is worse performance.

Regards,
Michal
