### ISSUE TITLE
What is the goal of sysrepo?

### ISSUE THREAD

**Issue by charach** [sysrepo/sysrepo#1339]
Hi! 

I want to participate to develop Sysrepo project.
Before i start, i want to know the goal of Sysrepoproject.
For examples, Sysrepo is used at many connections and Large-scale System.
Or Sysrepo concentrate on small but fast(like Femto-cell) environment.

What is the goal of Sysrepo project?

Thanks you.

**Comment by rkrejci** [comment]
Hi, actually both. So far, we have focused more on small environments mainly with memory limitation, because it seems this is the main usage for now. However, it seems that there is willing to use it also in bigger systems (much bigger schemas and data sets, not so limited regarding the memory, but time must not grow lineary with the data scale), so we are working on modifications helping to handle it.

Overall information about the project can be found at http://sysrepo.org and the prefered communication channel for developers is [sysrepo-devel@sysrepo.org](http://lists.sysrepo.org/listinfo/sysrepo-devel) mailing list.

**Comment by michalvasko** [comment]
I would just like to add that we are happy about any contribution, mainly in testing, writing new test cases, or even creating pull requests with patches for existing bugs. However, I would like to ask you to wait with helping us with *sysrepo* because we are currently working on a new *sysrepo* version that will significantly differ from the current one (but mainly internally, API will stay more-or-less the same) so there is not much use working on the current *sysrepo*.
