### ISSUE TITLE
multiple datastores / sysrepo instances

### ISSUE THREAD

**Issue by cromlegionar** [sysrepo/sysrepo#1427]
Hello all,

I am already using sysrepo with multiple netopeer2 servers and currently trying to store data collected from these servers for further processing with a custom client. 
Now I want to store this collected data in a datastore on the client system. I already succeded in merging the data from multiple servers and storing it on the running datastore in sysrepo with the approach suggested by michal in this [libyang question](https://github.com/CESNET/libyang/issues/710), though i am aware of the fact that this is neither a nice nor clean solution (Also for this scenario all yang schemas used in the server have to be created by myself).

My actual question is if it is possible to either initiate multiple independent datastores in one sysrepo to store the data from each server individually. Alternativly - and I know this is not a nice approach either - it would be ok if I could start multiple sysrepo instances on one system. I know I can start a local sysrepo instance by using the sr_connect() function with the SR_CONN_DEFAULT flag, but I am guessing this does not create independent sysrepo instances with repetitive calling, am I right? 
(Through all of this I am fully aware that sysrepo probably wasn't designed to do this, in this case it will only be used for demonstrative purposes)

I want to mention that I have read the sysrepo documentation, I just want to make sure that i didn't miss something before I move on to solving the problem in my own implementation.

Thank you in advance for your time and answer.

**Comment by michalvasko** [comment]
Hi,
*sysrepo*, *netopeer2*, or YANG in general are designed to operate on one global datastore, which is further differentiated only in its purpose (`running`, `startup`, ...), not in supported modules. So, your use-case is not and should not be supported, if I understand it correctly. There shouls always be only one *sysrepo* and *netopeer2* instance running on one machine.

Now, is this some real use or not? If it is, it should be possible to handle without the need for several server instances.

Regards,
Michal

**Comment by cromlegionar** [comment]
I think you anwsered my question but I want to make clear what I'm aiming to achieve, sorry if i did not explain my case properly:

 I meant I have multiple systems all connected by a local network. All but one host a netopeer server and an application. This application is represented by a custom yang schema. Now additionally  to all those devices (nc-servers with applications connecte to the sysrepos) there is one system in the network which hosts a custom netconf client. This client is supposed to catch all configuration/state data from all servers in the system, modify/process this incomming data and write it back to each server periodically. Because of the fact, that my part in this scenario mostly deals with the netconf part of this whole use case (collecting data, storing it, providing to processing unit and writing new data back to servers) I wanted to keep the incomming data in the "yang format" as long as possible, because i was/will be writing it back anyway. Thats why I wanted to store the data in a sysrepo on the client system. 

Because of the fact that all data trees from each server are built from the same schema, my first attempt was to create a list which contains multiple of these server data-models and use this list in the "client-sysrepo". Thats where I learnt that the namespace is not kept when using a grouping in a model and properly inserting a server data-tree into such a server list is only possible by copying the data from one tree/namespace to the other (which again goes against all rules of this concept).

I know sysrepo is not designed for this and we will have to build our own datastore sooner or later but this is not part of my work right now, thats why i wanted to "hack" sysrepo for now into doing this (Thats where you confirmed that sysrepo is not capable of running neither multiple sysrepo instances nor multiple running data stores on one system - i think) 

I think the cleanest way will be to leave/enter the yang encoding directly after recieving /before sending the data, but I will have to discuss that with my supervisor.

**Comment by michalvasko** [comment]
Hi,
okay, so you have
```
server client server
   \     |     /
    \    |    /
      network
    /    |    \
   /     |     \
server server server
```
**server** is a machine that has *sysrepo* and *netopeer2-server* running on it. **client** is a machine that should (you were not specific, so I am going to assume the worst case) be notified about all the configuration changes, make some modifications, and then write these modified data back to the **servers**. I will further assume you are running a NETCONF client on the **client** and communicate with **servers** only using NETCONF.

Now, you say you want to have a *sysrepo* on the client. Depending on the exact work the **client** does it may be useful (setting callbacks for writing server data into *sysrepo* so you do not have to analyze the data yourself) but maybe all you need is *libyang*.

So, this is quite a complex distributed use-case, which I do not think YANG or NETCONF was envisioned to cover, but at the same time they offer a lot of features so it may be possible. I still do not know everything that may matter (What prompts the initial configuration changes on **servers**? Does the application react to these changes using *sysrepo* callbacks? All the servers use one YANG module or each a different one? Should the **servers** react to the updated configuration they receive from the **client**?) so I can hardly suggest an exact solution.

Nevertheless, you say the **client** somehow periodically modifies the configuration from the **servers**, which seems to me is a good use-case for notifications, which even do not use a *polling* mechanism but a *push* (asynchronous) one. Furthermore, **servers** can initiate Call Home connections when a notification is to be delivered so that the **client** can be completely disconnected from them otherwise.

That is all I can suggest because I am already doing a lot of guess-work so none of it may be relevant, anyway.

Regards,
Michal

**Comment by cromlegionar** [comment]
Hello Michal,

You covered the situation pretty well. As all of this will be part of my bachelor thesis not everything was defined to the detail yet. It should be possible for the client to ask the server specifically at any time what their current configuration is but most of the time it will be sufficient to get an update when something on the servers change. 

The servers start their application which then loads an inital (slim) configuration (which does not fill all parameters of the server-module) into sysrepo, depending on the physical properties of the server. Now the client - which recieves said inital config will determine the rest of the parameters depending on many factors and write the fully calculated configuration back into the server. From There on both the client and the server may change the configuration on the server depending on different events, but both the server and client have to hold the newest data at all times ( or at least be able to get an update on the data whenever they need).

The application on the servers indeed reacts via sysrepo callbacks. For the schemas on the servers we will use multiple schemas (partly from external providers) in each server and it is possible (though not yet confirmed) that they will differ from server to server (I just got that information as I previously worked with the fact that we will use one schema for all servers, which will be designed in a way that it can hold different variables depending on the server it runs on). The Servers subscribe to the yang data modules on their system sysrepo, so they will get the updated data and apply it to the physical parameters. So the application can be imagined to be a deamonized plugin for sysrepo.

I already read about the call home functionality and like the idea of only using notifications very much, i think I can make this part of my system work. 

The real problem is that the "calculation unit" on the client will not be developed by myself so I have to provide the data to and recieve the updated data from it. Thats why I wanted to use a sysrepo on the client, use a server-list module on it and provide a plugin-library which connects to sysrepo and provides different functions for extracting, writing and encoding data from and to the sysrepo/yang world (So that the developer working on the calulation unit does not have to bother with all of this). 

I hope I made the situation a little bit clearer, in any case feel free to ask where I should elaborate further and thank you for dealing with my question!

With best regards,
Kilian

**Comment by michalvasko** [comment]
Hi Kilian,
okay, that all makes sense to me. Just a note regarding the **client** calculation unit. Your NETCONF client will receive YANG data. You can either pass these directly to the unit in XML or JSON format (which is generic enough so that any application can handle them) or, like you said, send these data to *sysrepo* first so that the calculation unit can simply be a set of callbacks that will react to *sysrepo* changes. You should probably discuss this with your collaborator, what suits them better. Good luck with your thesis.

Regards,
Michal

**Comment by cromlegionar** [comment]
Hi Michal,
sorry for not replying for so long - thank you very much for your answers and input! I discussed the situation with my supervisor and i think we found a good solution.

With best regards,
Kilian
