### ISSUE TITLE
Segmentation fault on sr_rpc_subscribe()

### ISSUE THREAD

**Issue by michalvasko** [sysrepo/sysrepo#149]
Hi,
recent changes cause this example application to crash.

```C
#include <stdio.h>
#include <stdlib.h>
#include <signal.h>
#include <unistd.h>
#include <string.h>

#include <sysrepo.h>

int
rpc_clb(const char *xpath, const sr_val_t *input, const size_t input_cnt, sr_val_t **output, size_t *output_cnt, void *private_ctx)
{
    return SR_ERR_OK;
}

int
main()
{
    int rc;
    sr_subscription_ctx_t *sr_subs;
    sr_conn_ctx_t *sr_ctx;
    sr_session_ctx_t *sr_sess;

    rc = sr_connect("test-app", SR_CONN_DAEMON_REQUIRED, &sr_ctx);
    if (rc != SR_ERR_OK) {
        printf("sr_connect fail (%s).\n", sr_strerror(rc));
        return 1;
    }

    rc = sr_session_start(sr_ctx, SR_DS_RUNNING, 0, &sr_sess);
    if (rc != SR_ERR_OK) {
        printf("sr_session_start fail (%s).\n", sr_strerror(rc));
        return 1;
    }

    rc = sr_rpc_subscribe(sr_sess, "/test-module:activate-software-image", rpc_clb, NULL, &sr_subs);
    if (rc != SR_ERR_OK) {
        printf("sr_rpc_subscribe fail (%s).\n", sr_strerror(rc));
        return 1;
    }

    sr_unsubscribe(sr_sess, sr_subs);
    sr_session_stop(sr_sess);
    sr_disconnect(sr_ctx);
    return 0;
}
```

Regards,
Michal

**Comment by rastislavszabo** [comment]
Hi,

sorry for the inconvenience. The reason why the application crashes is that the pointer to sr_subscription_ctx_t is supposed to be initialized to NULL before passing to subscribe call - but we forgot to mention it in the documentation. 

The reason for this is that we have added the possibility to reuse the same subscription context for multiple *_subscribe calls, so that the application does not need to file so many subscription contexts. I will update the documentation regarding to this.

This feature may be misleading if someone is not used to initialize variables allocated on stack, so in the next version of _subscribe API calls we will make it optional and turned off by default (we will add an option argument to all _subscribe calls).

**Comment by michalvasko** [comment]
Hi,
as long as it is mentioned in the documentation, no other options are really required.

Regards,
Michal
