### ISSUE TITLE
One question about the validation of configuration data

### ISSUE THREAD

**Issue by darcyllingyan** [sysrepo/sysrepo#1494]
Hi,
As we know, now we mainly define the YANG module to validate the configuration data(must/when,etc.), when the YANG built-in validation constructs ('must', 'unique',etc.) are not expressive enough, whether sysrepo support some other method to extend  the validation.

such as the confD supports the tailf:validate as a validation callback which is invoked when a configuration value is to be validated.  Or other methods supporting some plugins for users to add their own validation rule?

Thanks
Darcy

**Comment by michalvasko** [comment]
Hi Darcy,
it depends what exactly is your use-case. If you really want to perform some additional validation of a value (which is unlikely due to XPath being not expressive enough but rather because of a poorly-written module), there is a *libyang* mechanism of [user types](https://netopeer.liberouter.org/doc/libyang/master/howtoschemaplugins.html#usertypes) (with [example](https://github.com/CESNET/libyang/blob/master/src/user_types/user_yang_types.c#L97) of a validation callback) that can be used.

However, if there is simply a condition that cannot be expressed using YANG as a matter of principle and depends only on the managed device, that is one of the main use-cases for the [verify](http://www.sysrepo.org/static/doc/html/group__cl.html#gga94740180bfd5e1761cccc8e6485eee68acefd1079184ed6d5391264181f72c70e) callback event, when you can refuse the changes as invalid.

I think that covers whatever use-case you have.

Regards,
Michal
