### ISSUE TITLE
Sysrepo ignoring return value of APPLY event

### ISSUE THREAD

**Issue by bharath154** [sysrepo/sysrepo#1499]
### Things you may try first
(put "x" in "[]" if you already tried following)
* [x] Did you check if this is a duplicate issue?

### Description
Sysrepo seems to validate the return value of only SR_VERIFY event and ignore the return value of SR_APPLY event from the subscriber. Is this intentional? 
I understand that VERIFY event is supposed to return errors if there are some data input errors or verification for these values on the device failed etc., But that does not necessarily guarantee that the APPLY event will pass for sure. There could be changes in the underlying device behavior between a VERIFY and APPLY event.

#### Code where the issue happens ####
In src/notification_processor.c:
        if (SR_EV_VERIFY == event && SR_ERR_OK != result) {
            /* error returned from the verifier */
            commit->result = result;
            np_commit_error_add(commit, subs_xpath, do_not_send_abort, err_msg, err_xpath);
            SR_LOG_ERR("Verifier for '%s' returned an error (msg: '%s', xpath: '%s'), commit will be aborted.",
                    subs_xpath, err_msg, err_xpath);
        }
#### Proposed Solution ####
        if ((SR_EV_VERIFY == event || SR_EV_APPLY == event) && SR_ERR_OK != result) {

### Steps to Reproduce
Return failure from one of the APPLY event callbacks and see that the return value is ignored in sysrepo, which eventually returns OK to client.

**Expected behavior:**
return the failure returned by callback to netconf client.

**Actual behavior:**
returns OK to netconf client.

### Versions
Please provide versions for software needed to reproduce the bug:
Sysrepo version: `sysrepod -v`.
version 0.7.3

**Comment by michalvasko** [comment]
Hi,
yes, ignoring `SR_EV_APPLY` return value is intentional and we are aware of the race condition you mentioned. That is why you can "apply" all the changes already during `SR_EV_VERIFY` and then ignore `SR_EV_APPLY`, for example. Just a final note, the return value of `SR_EV_APPLY` is ignored because by then all the changes are written into the datastore and no rollback is possible.

Regards,
Michal

**Comment by bharath154** [comment]
Hi Michal,
This seems counter intuitive though. Is there a standard that says something about this?  What you are saying seems like a work around. Doesn't this need to be fixed properly though ?
Regards
bharath

**Comment by michalvasko** [comment]
Hi,
firstly, there is no standard anywhere, this is strictly proprietary *sysrepo* callback implementation. The "fix" was to rename these events to `SR_EV_CHANGE` and `SR_EV_DONE` in the new *sysrepo* so that users are not hinted on what to do on which event and decide that for themselves. I do not think there is more to be done.

Regards,
Michal

**Comment by bharath154** [comment]
Hi Michal,
Thanks for the reply. Yeah I agree with some kind of name change. But anyways, thanks for letting me know.
Cheers
Bharath
