### ISSUE TITLE
How to discriminate module change notifications

### ISSUE THREAD

**Issue by molyland** [sysrepo/sysrepo#1524]
On my linux embedded system already exists a proprietary configuration "datastore", let's call
it PROP_DATASTORE, then there is a sysrepo instance with its datastore let's call it SR_DATASTORE.
I implemented a netconf manager with a simple sysrepo client, and also module change subscription for all installed module, then when we exec edit-config (set/add/del) by netopeer2 cli sysrepo send notifications of "module-change", the callback run and apply new data on PROP_DATASTORE, (also on SR_DATASTORE).
When I do some operations (set/add/del) on our proprietary shell new data are update on PROP_DATASTORE, then make a temporary xml file and update SR_DATASTORE by sysrepocfg tool, but when sysrepo update its datastore (SR_DATASTORE) send notifications of "module-change" and repeat update to PROP_DATASTORE.
Can I discriminate module change notifications for skip these when produced by sysrepocfg update ? I try to show session id of callback but sysrepo always open internal connection for send module change notifications.
Can you help me ? Thanks

**Comment by michalvasko** [comment]
Hi,
I am afraid there is no simple solution, it is not possible to differentiate between various sources of changes. The problem is you having the same configuration in two places. You will probably need to remember somehow that particular changes were already applied and do not apply them again, but it all depends on your specific application.

Regards,
Michal
