### ISSUE TITLE
sysrepo threads initialization function

### ISSUE THREAD

**Issue by ranje93** [sysrepo/sysrepo#1552]
Hello,
From what I understand, sysrepo is a multi-threaded application that uses thread pool.

I need every thread to register to a certain system (unrelated to sysrepo).
On the start of the application I registered the main thread to this system and continue with the rest of the sysrepo code. i.e `sr_connect` and so on.
However, whenever a state callback is called, I see that a different thread is executing the request.

The problem is that the thread that is executing it, did not register to the my system so it doesn't have access to a certain data.
my quick fix was to have a static variable that checks if the thread is registered or not and so it will do a self registration on first demand.

Is there a different way to have this functionality. I want to register all sysrepo threads to my system on the start. is there a callback that I can provide to sysrepo that will execute a certain code for all the threads. some sort of "init_thread" function?

Thanks

**Comment by michalvasko** [comment]
Hi,
no, this thread (handling one client subscriptions) is created automatically. What you can do for it to be proper is to use [sr_fd_watcher_init()](http://www.sysrepo.org/static/doc/html/group__cl.html#ga473f5f57ade8b448d373e34493dd58c6) and create your own thread that will process *sysrepo* events. Otherwise you can keep your workaround.

Regards,
Michal
