### ISSUE TITLE
[New-Sysrepo] [sysrepoctl] Request for enhancement

### ISSUE THREAD

**Issue by sriramkandukuri** [sysrepo/sysrepo#1565]
Hi,

This is a request to add some enhancements to sysrepoctl commands as below.
I have isolated these from original issue[#1561 ] for tracking separately.

1. It would be helpful if we can set libyang debug logs with logging groups in all sysrepo 
 executables.(ofcourse this needs libyang to be compiled in debug mode.)
2. If module is installed already, it is considered as error. This can be ignored as the installation is already successfull. It will be very helpful for installing yangs in a script.
3. It would be very helpfull if we can have a command which allows to uninstall multiple modules at a time. Now its throwing operation already specified error.
Points 2,3 used to work in old sysrepoctl

**Comment by michalvasko** [comment]
Hi,

1. Is that so important to you? Logging will most likely work differently with new *libyang* (which is still months away from being ready) so I prefer to keep it the way it is for now.
2. Should work now.
3. It is also possible now but not really needed. This possibility was added into old *sysrepoctl* because there were many cases when a single module could not be uninstalled because of a cross dependency on another module, so they had to be uninstalled together. New *sysrepoctl* handles modules in a different way and it only prepares module uninstallation, so it should never be required to uninstall more modules at once. But like I said, it is possible now.

Regards,
Michal

**Comment by sriramkandukuri** [comment]
Hi Michal,

Thanks for the update. Will check and let you know the status.

**Comment by sriramkandukuri** [comment]
Hi Michal,

Both enhancements are working with commits https://github.com/sysrepo/sysrepo/commit/8e51b891a74a1e70ec51c8bd0ee2d97191c4d588 and https://github.com/sysrepo/sysrepo/commit/8a13bbc53f1306a7439639430bf0b0314db57fdf . Thank you
