### ISSUE TITLE
Configuration recovery if the application(which accepts configuration from custom sysrepo plugin developed)crashed/killed

### ISSUE THREAD

**Issue by navya46** [sysrepo/sysrepo#1570]
Hi,
In order to recover the configurations on system restart, we have subscribed for SR_SUBSCR_EV_ENABLED , the module callback is getting called, changes are getting applied automatically.
To make the configurations persistent on the device, all the configurations are maintained in startup datastore as well.

Lets say if the application(which accepts the configuration from custom sysrepo plugin we developed) crashed/abnormal-killed,
once the application is recovered, it has to be restored with the configurations.

Monitoring system on the device is capable to know if application is crashed/recovered/failed-to-recovered.
Once the application is recovered, to restore the configurations, we tried 

1. Initially copying from startup to running for a module,
as there is no new addition to the module, change notification is not raised.

2. Later performed the below steps, for a module, as the restoration is not needed for all the supported modules

copy startup -> candidate
delete running
copy candidate -> running

These steps invokes the necessary callback and configurations are pushed accordingly.

Could you please suggest if the steps choose in 2, is correct way to restore the configuration?

Thanks,
Navya

**Comment by jktjkt** [comment]
The problem that you're describing happens when just your application crashes, while `sysrepod` **and** your plugin which registers callbacks within `sysrepod` both remain running, right? Sysrepo has code which propagates the "initial configuration" during module enabling, so perhaps you could disconnect your plugin from sysrepo once it detects that your app has crashed, and let your app re-initialize its sysrepo connection?

That's what we've been using locally and it works well. We don't really have a "plugin", the part of code which talks to sysrepo lives in the app's main address space, so our exit-on-app-crash is free for us :).

**Comment by navya46** [comment]
Thanks for replying.
We can notify from the process(which identifies the abnormal exit of an application) to plugin(which registers for the callbacks).
Plugin can re-initalize the sysrepo connections for that module.

Thank you,
Navya

**Comment by michalvasko** [comment]
Hi,
I think what @jktjkt suggested is a correct and natural way of handling this situation.

Regards,
Michal
