### ISSUE TITLE
Why is sysrepocfg or sysrepo client library limited to set only read-write configs?

### ISSUE THREAD

**Issue by balag1986** [sysrepo/sysrepo#1600]
First and foremost a big thanks to the crew developed this robust sysrepo, netopeer2 etc followed by a quesiton :)

Either sysrepocfg or sysrepo client library API's doesnt allow to set read only config of a module's datastores in the sysrepo engine.

For eg:
If an element is defined as "config false" in Schema and if that element is set via sysrepocfg or sysrepo client library, it fails.

I understand from the netconf client point of view, it makes sense to not allow edit-config of a read only/state data element. However, the application behind the sysrepo engine should be able to set any metrics or state data back to the sysrepo engine when the underlying device layer updates the application.

Lets check the following example:
In this below example, speed is a configuration data and observed-speed is a state data. netconf-client is not supposed to do edit-config on a state-data. However, the observed speed can come from the device application that needs to be updated back to the sysrepo db for the end user to see.

 list interface {
         key "name";

         leaf name {
             type string;
         }
         leaf speed {
             type enumeration {
                 enum 10m;
                 enum 100m;
                 enum auto;
             }
         }
         leaf observed-speed {
             type uint32;
             config false;
         }
     }

Let me know if i am missing something here.

**Comment by michalvasko** [comment]
Hi,
the idea was to always provide up-to-date values of state data. Since they can change often, they are retrieved every time they are requested by another client. So, instead of calling `sr_set_item()` and `sr_commit()` to set these values persistently, you register a callback using [sr_dp_get_items_subscribe()](http://www.sysrepo.org/static/doc/html/group__cl.html#ga9e68dfe535ddabfebe056b43047ad7e8) that provides specific state data and *sysrepo* will call it as needed.

Regards,
Michal

**Comment by brchiu** [comment]
@michalvasko, I have the same question as @newbie's and I agree with you that state data should be provided up-to-date. 

However, during my implementation of some modules, I found that sometimes `config false` schema are used to represent certain capabilities of devices which will not change from time to time. A mechanism , perhaps callback function similar to the one passed to `sr_dp_get_items_subscribe()`, accept XML or json fit to this schema as input instead of variable length array used in callback of `sr_dp_get_items_subscribe()` will be handy.

**Comment by balag1986** [comment]
Thanks Michal. It worked well. Closing the issue.
