### ISSUE TITLE
Question how to delete item from running datastore

### ISSUE THREAD

**Issue by maksimvuleta** [sysrepo/sysrepo#1626]
Here is my case:
I deleted the leaf A from running configuration by sending edit-config replace operation without leaf A in the config. 
The specific thing is that I need to remove one other leaf (leaf B) if leaf A is deleted from configuration. So, when callback for leaf A is triggered with delete operation I need to manually delete leaf B from the running configuration in the callback for leaf A.
I tried to do this with sr_delete_item function but a got this error :
"[DBG] Sending delete-item request.
[DBG] delete-item request sent, waiting for response.
[ERR] While waiting for a response, timeout has expired.
[ERR] Unable to receive the message with response (session id=2145023361, operation=delete-item).
[ERR] Error by processing of the request."

Is it possible to do this with function sr_delete_item? 
As a session, I used the session for which the callback for leaf A is triggered.

**Comment by michalvasko** [comment]
Hi,
this is a threading problem in sysrepo. If you delete the leaf in a separate thread, I think it should work. But I am not positive because this use-case is not really supported. If you use the new *sysrepo* from `devel`, there is a special event that allows what you want.

Note that this seems to be a perfect example of using a `when` expression on the leaf B so that it gets autodeleted when leaf A is deleted and you would not have any of these problems.

Regards,
Michal

**Comment by maksimvuleta** [comment]
"If you use the new sysrepo from devel, there is a special event that allows what you want."
Where can we find an explanation of using that event? 

The proposal to modify the yang module is good, but currently, we are not allowed to modify the yang files for our project.

**Comment by jktjkt** [comment]
> I deleted the leaf A from running configuration by sending edit-config replace operation without leaf A in the config.
> The specific thing is that I need to remove one other leaf (leaf B) if leaf A is deleted from configuration. So, when callback for leaf A is triggered with delete operation I need to manually delete leaf B from the running configuration in the callback for leaf A.

You might try looking at the problem from another perspective: a configuration which contains `leafB` is invalid unless `leafA` is also present.

This is a constraint that can be enforced in two ways with current sysrepo: either a proper YANG-level constraint (via `must` or `leafref`, for example), or via a validity checking callback. You said that you are not willing to modyif the YANG models for some reason, which leaves you with option 2. Basically, instead of getting just the `SR_EV_APPLY` event and applying this configuration, you can check the validity upfront via `SR_EV_VERIFY`. That way, your application can reject any configuration which has `leafB` present while `leafA` is missing.

This is, as far as I understand, fully in line with how YANG and NETCONF is supposed to be implemented. NETCONF is not intended for direct consumption by humans, so it's not a problem that a NETCONF client has to "remove all things which refer to A" before "A" can be actually deleted. This can still well happen within a single NETCONF transaction (i.e., a sysrepo-level commit).

Just out of couriosity, what is the real-world meaning of A and B in your use case?

**Comment by michalvasko** [comment]
> Where can we find an explanation of using that event?

The documentation is not yet generated and available online, but you can do so yourself and the event is mentioned [here](https://github.com/sysrepo/sysrepo/blob/devel/doc/subs.dox#L31).

Regards,
Michal
