### ISSUE TITLE
Callback function is only called for first instance of app restart for same module .

### ISSUE THREAD

**Issue by iGovindY** [sysrepo/sysrepo#1641]
Running multiple instances of an application, which subscribe to a model doesn't result in callback getting called with event `SR_EV_ENABLED` for every instance.

The only first instance of application receives event `SR_EV_ENABLED` in case of `sr_module_change_subscribe()`. However, both instances of application receive event `SR_EV_ENABLED` when subscription is `sr_subtree_change_subscribe()` 

Is it intentional? or a bug?

Following are my subscription calls.

` rc = sr_module_change_subscribe(session, "oven", my_module_change_cb, NULL,0, SR_SUBSCR_DEFAULT | SR_SUBSCR_EV_ENABLED, &subscription);`

`sr_subtree_change_subscribe (session, "/oven:oven", my_subtree_example_change_cb, NULL, 0, SR_SUBSCR_DEFAULT | SR_SUBSCR_CTX_REUSE | SR_SUBSCR_EV_ENABLED, &subscription);`

Sysrepo version: `sysrepod - sysrepo daemon, version 0.7.8`.
libyang version: `yanglint 1.1.52`
netopeer2-server: `netopeer2-server 0.7.13`

**Comment by michalvasko** [comment]
Hi,
to my knowledge, `SR_EV_ENABLED` was being generated only when the module/subtree was being enabled. Meaning, only the first subscription gets the event, no following ones. But based on what you said, it is true only for `sr_module_change_subscribe()` and not for `sr_subtree_change_subscribe()`. Are you running multiple instances of the exact same application? Whatever the case, I do not think this behavior will be changed because it can be considered a feature and not a bug. Whether it was intentional I do not know.

Regards,
Michal

**Comment by iGovindY** [comment]
Hi Michal,

Yes same application with multiple instances.

Thanks
Govind

**Comment by deepthib29** [comment]
Michal, we are using below function
sr_module_change_subscribe(session_running, NTS_NF_ORAN_DU_MODULE, NTS_NF_ORAN_DU_SUBSCRIPTION_STREAMS_SCHEMA_XPATH, subscription_streams_change_cb, NULL, 0, SR_SUBSCR_CTX_REUSE, &session_subscription)

subscription_streams_change_cb function is not getting called.. please let me know why?
