### ISSUE TITLE
sr_commit is failing/timeout

### ISSUE THREAD

**Issue by rank1985** [sysrepo/sysrepo#1642]
### Description

sr_commit is failing. Looks like its is timeout. We configured time out value as 30 second.
sr_commit is failure is happening after 5 hour .
Application is committing statistics every 5 minute to sysrepo using sr_commit.

There are other application, writing data/stats to disk (not used sysrepo) and the IO is little high around 50MB/second is this cause issue ? 

### Versions
sysrepo-0.7.4

Thanks!

**Comment by michalvasko** [comment]
Hi,
it depends on your disk but 50 MB/s is likely the write limit so yes, *sysrepo* not being able to write data to disk will probably be the reason for the timeout.

Regards,
Michal

**Comment by rank1985** [comment]
Hi Michal,

But I am not able to answer why sr_commit failure is coming only after long run? .Application is always writing 50MB/sec . 

We have logical partitions sda1 and sda6 . sda1 is used by sysrepo and sda6 used by application.

Regards,
Ranjith

**Comment by michalvasko** [comment]
Hi Ranjith,
you having logical partitions will not make any difference for the actual disk but it is possible it is not responsible for the timeout. You will have to provide more information. Do you know how exactly *sysrepo* behaves? Whether the commit time slowly increases after each call or whether the timeout always occurs after exactly same number of commits. It is also worth updating *sysrepo* to 0.7.8, quite a lot of changes since the version you have used.

Regards,
Michal

**Comment by rank1985** [comment]
Hi Michal,

Commit failure is at random time .But we observed it always happening after 5 to 6 hours.

Regards,
Ranjith
