### ISSUE TITLE
New sysrepo: sr_oper_get_items_subscribe callback behavior

### ISSUE THREAD

**Issue by ishidawataru** [sysrepo/sysrepo#1647]
### Things you may try first
* [x] Did you check if this is a duplicate issue?
* [x] Did you test it on the latest sysrepo devel branch?

### Description

I'm not sure this is a bug or expected behavior but with the following YANG model,  oper_get_items_subscribe callback gets called even if the xpath specified by `sysrepocfg -X -f json --xpath <xpath> -d operational` is outside of the scope of the xpath which given to `sr_oper_get_items_subscribe()`.

#### a.yang

```yang
module a {
    namespace a;
    prefix a;

    container state {
        config false;

        leaf v {
            type string;
        }
    }

    container state2 {
        config false;

        leaf v {
            type string;
        }
    }

}
```

### Steps to Reproduce
1. `$ sysrepoctl --install ./a.yang`
2. `$ ./examples/oper_data_example a "/a:state"`
3. `$ sysrepocfg -X -f json --xpath "/a:state2" -d operational`

This will invoke the oper_data_example callback

```
$ ./examples/oper_data_example a "/a:state"
Application will provide data "/a:state" of "a".

 ========== LISTENING FOR REQUESTS ==========



 ========== DATA FOR "a" "/a:state" REQUESTED =======================

```

**Expected behavior:**

I'd expect the callback doesn't get called when the xpath is outside of what is registered.

**Actual behavior:**

The callback get called.

### Versions
Please provide versions for software needed to reproduce the bug:
Sysrepo version: 1.2.6
libyang version: 1.0.77

**Comment by michalvasko** [comment]
Hi,
I believe this is actually the expected behavior. Sorry for not replying sooner but I am quite busy with some *sysrepo* improvements. Once they are finished (a week or so) I will take a look, I had planned on fixing this.

Regards,
Michal

**Comment by ishidawataru** [comment]
Thanks. Meanwhile, I'll use a single callback and dispatch to sub-routines based on the requested xpath.f

**Comment by ishidawataru** [comment]
using the push method for state values solved my use case. 

@michalvasko Thanks a lot for your great work!

**Comment by michalvasko** [comment]
Hi,
what you originally wanted should now be supported meaning if the state data are filtered out, they should not be requested.

I have skipped this feature initially because the comparisons must be performed textually as there are no data and *libyang* XPath cannot be used. It was not such a problem for standard paths and they should work reliably but it is not that simple with predicates. Only one case is covered, when you subscribe to `/list[key='val']` and request `/list[key='val2']`, the operational callback will not be called. As soon as either of the predicates will be just slightly different, the textual comparison will not work and the callback will be called. Just for your information, I still believe 99% of real use-cases are now covered.

Regards,
Michal
