### ISSUE TITLE
Queries on sysrepo behavior for yang model revisions.

### ISSUE THREAD

**Issue by iGovindY** [sysrepo/sysrepo#1665]
Hi, 
During the internal discussions in my organization, while evaluating sysrepo for use, some points came up, I would like to know your thoughts around it.

1. Module version 1 changed to version 2, what happens to old persistence? 
2. What if some attribute is removed from one model to the next version, how will old persistence work?
3. What if some attribute is changed in yang, Let's say from a container to a list, in one version to another? How sysrepo and datastores behave to such change?
4. Can sysrepo/ NETCONF work with 2 versions of the same Module?

**Comment by michalvasko** [comment]
Hi,
I will answer first with regard to the current *sysrepo*.

1. I assume you mean persistence files. In any case, you have to uninstall the old revision and install the new revision, no other way. However, in case these modules were **not implemented**, just imported, then the 2 revisions can coexists without problems and both be in *sysrepo*.
2. What exactly do you mean by attribute? But, generally, my answer is the same as the previous one, in case it is an **installed** module, you have to remove it first.
3. The same, because when you remove the module, all data are removed as well, so there is no problem.
4. NETCONF/YANG (and *sysrepo*) all follow the same principle, you can have many revisions of a single module, but only **one** can be implemented.

Now for the new *sysrepo*, I will rather just explain the differences and the answer to each question should be obvious. There is a new (API) operation for updating a (implemented) module. What it does is it tries to use the new module, enable all the same features (use the old persistence file if I am to use the principles from the old *sysrepo*), and then tries to load the old stored data. If it succeeds, the module is updated. If not, the state is kept unmodified. This process should allow for the maximum set of possible changes between module revisions (so it allows even more than [YANG](https://tools.ietf.org/html/rfc7950#section-11)). Just note that the module cannot really be updated during *sysrepo* operation ([ref](https://github.com/sysrepo/sysrepo/blob/devel/doc/schema.dox)), but that is simply not possible anyway.


Regards,
Michal
