### ISSUE TITLE
New sysrepo design

### ISSUE THREAD

**Issue by meghna-doshi** [sysrepo/sysrepo#1670]
Hi, 
I have updated to the latest devel branch code.
I have generated the documentation for the new code. But could not find a good description of the high level module design the way it was in the earlier version.

1. Do you have some figures/information on the new design.
2. As per new code, following are the 3 ways to use the new sysrepo:
    1. Indirect approach, separate daemon.
    2. Direct approach, linked to app 
    3. Indirect approach, using sysrepo-plugind
Can you please provide some details about design on how sysrepo communicates with application and netopeer2 (like UDP, TCP etc) and also point out to sample examples which are using each of these approaches.

Thanks!

**Comment by meghna-doshi** [comment]
Hi,
One more query, we are looking for a solution where application and sysrepo are hosted on different linux containers. 
1. Is this possible to achieve this with the new sysrepo. Earlier UNIX domain socket could have been replaced with INET socket and it would have worked.

Thanks!

**Comment by michalvasko** [comment]
Hi,

1. What exactly do you mean, the first or the second diagram in [docs](http://www.sysrepo.org/static/doc/html/index.html)? Anyway, the [general principles](https://github.com/sysrepo/sysrepo/blob/devel/doc/main.dox#L33) are described in the documentation, what more are you interested in?
2. These 3 approaches are exactly the same as in the old *sysrepo*, I have just documented them. As written in the general principles, shared memory is used for all IPC, so that is how even *netopeer2* communicates with *sysrepo*. As for any examples, all of them use the direct approach because it is better. The indirect one is useful mainly for adding *sysrepo* support for existing applications (which is also mentioned at the [docs beginning](https://github.com/sysrepo/sysrepo/blob/devel/doc/main.dox#L10)) and we do not have any examples of that at the moment.

I believe I have also answered your second question, this is not possible. *sysrepo* is meant to be used locally on a system, there is NETCONF for remote configuration.

Regards,
Michal

Regards,
Michal

**Comment by meghna-doshi** [comment]
Hi Michal,
Let me clarify few things first.
Our understanding till now is 
netopeer2 + sysrepo = netconf
i.e netopeer2 + sysrepo s/w together gives the complete implemenation of NETCONF protocol (as per rfcs 6241, 6243, 6470 etc)
Since we wanted to have a NETCONF interface in our s/w, instead of developing the full protocol from scratch, we decided to go with netopeer2 + sysrepo.

So now, with this understanding, applications needed to register with sysrepo and use the configuration data as per the system requirements. Our system has a distributed design where applications can run on multiple containers, where shared memory cannot be used.

Your earlier design of sysrepo using UNIX domain socket was more generic, in the sense, we could have modified it to use INET sockets but this current shared memory approach is very restrictive.

Do you see any understanding problem here? Is netopeer2 + sysrepo not a open source solution for the NETCONF protocol?

**Comment by meghna-doshi** [comment]
Hi Michal,
One query, any reason why UNIX domain socket is replaced with shared memory in the new version of sysrepo.

Thanks,
Meghna

**Comment by michalvasko** [comment]
Hi,
one of the reasons for writing the new *sysrepo* was efficiency. Shared memory offers the best performance and scalability compared to other IPC solutions, that is why we have decided to use it.

Regards,
Michal

**Comment by meghna-doshi** [comment]
Hi,
One info, if for our internal need, if we replace shared memory with INET socket, do you see any feasibility issue with that, with the new design?

**Comment by michalvasko** [comment]
Hi,
I do not think this will be possible without major changes. Subscriptions were designed so that they fully utilize the advantages of shared memory so there can be several subscriptions (there is no limit) using one shared memory segment. To simulate that using a socket, you would have to use one for each subscription pair that needs to communicate.

Also, can I ask what exactly is your use-case? Because even with the old *sysrepo*, if you replace the UNIX sockets with INET ones, all you would get is a remote *sysrepo* client, not a fully distributed architecture. Is that all you are trying to achieve?

Regards,
Michal

**Comment by meghna-doshi** [comment]
Hi,
Actually ours is a split architecture, where there is one CU node which has 
1. multiple applications running in multiple containers.
2. the CU needs only one NETCONF interface towards a NETCONF client.
3. Each application (in any container) would register with the single sysrepo instance so that it can operate on a specific module configuration data.

I hope i have made myself clear here. Let me know if you have any doubts.

Thanks!
Meghna

**Comment by meghna-doshi** [comment]
[sysrepo-usecase.pptx](https://github.com/sysrepo/sysrepo/files/3839976/sysrepo-usecase.pptx)

Figure depicting our use case.

**Comment by michalvasko** [comment]
Hi Meghna,
thanks, it seems clear enough. You do not need remote *sysrepo* clients to access *sysrepo* from a different physical machine but from a container within one machine.

It would probably be possible to write a daemon that would have an INET interface and translate events from the remote end to actual changes in the shared memory on the local end. The remote clients would just use a different `sr_connect()` call, for example, to connect to this remote daemon and otherwise the communication method would be transparent. We would be happy to merge such a pull request if you are willing to implement it. Maybe we will implement this ourselves but that is hard to say now, it would certainly not be anytime soon.

Regards,
Michal

Regards,
Michal

**Comment by ishidawataru** [comment]
> Our system has a distributed design where applications can run on multiple containers, where shared memory cannot be used.

@meghna-doshi If you are using docker, you can use `--ipc` flag to share the shared memory among multiple containers.

**Comment by meghna-doshi** [comment]
Thanks @ishidawataru.
But we have a cloud like environment so we dont know whether dockers would be running in same server or not. 
I am assuming that this --ipc flag cannot work across servers.

Thanks,
Meghna

**Comment by kobi-ca** [comment]
> Hi Meghna, thanks, it seems clear enough. You do not need remote _sysrepo_ clients to access _sysrepo_ from a different physical machine but from a container within one machine.
> 
> It would probably be possible to write a daemon that would have an INET interface and translate events from the remote end to actual changes in the shared memory on the local end. The remote clients would just use a different `sr_connect()` call, for example, to connect to this remote daemon and otherwise the communication method would be transparent. We would be happy to merge such a pull request if you are willing to implement it. Maybe we will implement this ourselves but that is hard to say now, it would certainly not be anytime soon.
> 
> Regards, Michal

Hi @michalvasko - is there any new design and implementation of such arch with a IP based proxy server to SR ?

**Comment by michalvasko** [comment]
No and we do not plan to implement any.
