### ISSUE TITLE
[New sysrepo] operational data callback with a predicate

### ISSUE THREAD

**Issue by ishidawataru** [sysrepo/sysrepo#1676]
### Things you may try first
(put "x" in "[]" if you already tried following)
* [x] Did you check if this is a duplicate issue?
* [x] Did you test it on the latest sysrepo devel branch?

### Description

With the following model and data, when trying to get a state of one node in a list, the oper callback will get called the same times as the number of nodes in the list (with the same `request_xpath` ).

__model__

```yang
module a {

  yang-version "1.1";

  namespace "http://a";

  prefix "a";

  list l {
      key "name";
      leaf name {
          type string;
      }
      container state {
        config false;
        leaf x {
          type uint32;
        }
      }
  }
}
```

__data__

```json
{
    "a:l":[
        {
            "name":"a"
        },
        {
            "name":"b"
        }
    ]
}
```

```
root@e8dd22f926ee:/sysrepo/builds/examples# ./oper_data_example a "/a:l/state"
Application will provide data "/a:l/state" of "a".



 ========== LISTENING FOR REQUESTS ==========



 ========== DATA FOR "a" "/a:l/state" REQUESTED =======================



 ========== DATA FOR "a" "/a:l/state" REQUESTED =======================
```

related to https://github.com/sysrepo/sysrepo/issues/1647

### Steps to Reproduce

```
$ sysrepoctl --install a.yang
$ sysrepocfg -f json  -Ea.json -m a
$ oper_data_example a "/a:l/state"

---

$ # from a different terminal
$ sysrepocfg -f json -d operational -X -x "/a:l[name='a']"
```

**Expected behavior:**

I expect the callback gets called only once.

**Actual behavior:**

It is called twice.

### Versions
Please provide versions for software needed to reproduce the bug:
Sysrepo version: devel branch https://github.com/sysrepo/sysrepo/commit/c6a76349b1102829dca907c939f30ff7337b30f0
libyang version: devel branch  https://github.com/CESNET/libyang/commit/2beb41a72d83913a8e61372e4956a8ececd79f02

**Comment by ishidawataru** [comment]
Adding to the above case, it would be nice if sysrepo can set `request_xpath` ( or add another argument ) to the xpath of each node in the `list`.

For example, when calling 

```
$ sysrepocfg -f json -d operational -X -m a
```

with the setup above, the callback will get called twice with the `request_xpath` set to `/a:*`.

Since the callback can't know what to populate in `parent`, it is useful if the `request_xpath` is set to `/a:l[name='a']` and `/a:l[name='b']` respectively.

**Comment by michalvasko** [comment]
Hi,
this all works as expected, operational data subscriptions always return a **subtree**, so in case there can be more instances of any of the parents, it will be called for each of them separately.

Now, I have somewhat extended the redundancy check I have implemented for #1647, I have just forgotten to reference it, sorry (version 1.3.8). This particular use-case you posted should now be covered and the callback called only once, but only because you have used the single exact predicate that supports this filtering (it can again be done only textually).

As for your other question, `request_xpath` is always simply the high-level XPath that was used for retrieving the whole data tree that your one callback call is just a part of. It is there mostly for backward compatibility but can still be used for some manual filtering in the callback to learn what data are not needed to be returned. With these latest improvements of mine it should be redundant in the majority of cases but there still are some which are simply not possible to cover automatically.

Example, you subscribe to providing the whole `/ietf-interfaces:interfaces-state` container and then request data `/ietf-interfaces:interfaces-state/interface[name='eth0']`. In this case *sysrepo* must call your callback but it does not have to return the whole container, just that one interface and this filtering must be done in the callback. Also, this situation could be handled automatically with some creativity. If you are interested in the details, say so.

But, to actually answer you, you can get paths `/a:l[name='a']` and `/a:l[name='b']` if you are interested, just call `path = lyd_path(*parent)`. However, this usually just complicates things (you do not have to work with text XPaths in new *sysrepo*) and it would be best to just use `((struct lyd_node_leaf_list *)(*parent)->child)->value_str` to get the key value `a` or `b`.

Regards,
Michal

**Comment by ishidawataru** [comment]
Thanks for your support.

I tried the latest devel branch.

It worked as expected when I subscribed to `/a:l`.

However, when I subscribed to `/a:l/state`, the callback doesn't get called with any of the following commands.

- `sysrepocfg -f json -d operational -X -x "/a:l/state"`
- `sysrepocfg -f json -d operational -X -x "/a:l[name='a']/state"`
- `sysrepocfg -f json -d operational -X -x "/a:l[name='a']"`

Is this intended or not?

It would be great if you can summarize the expected behavior of the oper data subscription.

**Comment by michalvasko** [comment]
Hi,
so I have added some information about the behavior to the documentation, let me know if you think of some improvements. For your case, did you have any `/a:l` instances existing in the _operational_ datastore? Meaning they were in _running_ and were subscribed to? _Operational_ datastore is quite a complex one, hence all the confusion, but it was [defined](https://tools.ietf.org/html/rfc8342#section-5.3) that way.

Regards,
Michal
