### ISSUE TITLE
it failed when i use "netopeer2+sysrepo+libnetconf2+libyang" to edit enumeration leaf 

### ISSUE THREAD

**Issue by ZhaoGuangYue** [sysrepo/sysrepo#168]
The  log  of sysrepo is 
[ERR][rp_dt_edit.c:378] Setting of item failed /ME:ME/BBUTYPE 34

**Comment by lukasmacko** [comment]
Hi,
according to the log the failure might have various causes, could you provide some more details?

1. branch of projects you are using (latest master of all or different ones?)
2. data store you are trying to modify value in (startup/running/candidate)
3. the yang model of the configurarion you are editing
4. netconf request or C call you are using for edit

thanks,
Lukas

**Comment by ZhaoGuangYue** [comment]
the detail is like:
1.latest master
2.running
3.model:
`module TopModule {
  namespace "urn:ietf:params:xml:ns:yang:zte";
  prefix TopModule;
  revision 2016-05-10;
  container AAA {
    leaf testenum{
	  type enumeration{
	    enum enum-eee;
		enum enum-fff;
	  }
	}
	
    leaf aaa {
      type int32;
      default 100;
    }
    container BBB {
      leaf bbb {
        type int32;
      }
      container CCC {
        leaf ccc {
          type int32;
          default 300;
        }
      }
    }
  }
}
`
**edit data**
`<AAA xmlns="urn:ietf:params:xml:ns:yang:zte">
  <testenum>enum-eee</testenum>
  <aaa>111</aaa>
  <BBB>
    <bbb>222</bbb>
	<CCC>
      <ccc>333</ccc>
    </CCC>
  </BBB>
</AAA>`

**Comment by lukasmacko** [comment]
I see, the cause is that TopModule's running configuration is not enabled. To enable the module, there must be an application subscribed for the changes. It is explained more precisely [here](http://www.sysrepo.org/static/doc/html/ds_page.html#rds).

For the testing purposes you can use [application_example](https://github.com/sysrepo/sysrepo/blob/master/examples/application_example.c). When you start 'application_example' it will enable the model and the set_item call should be successfull. The name of the module to be enabled must be specified as the first argument.
