### ISSUE TITLE
Memory leak in application using sysrepo

### ISSUE THREAD

**Issue by dchechel** [sysrepo/sysrepo#1690]
Memory is allocated in our application and pointer is passed (as void* private_ctx parameter) to one of following functions:

    sr_subtree_change_subscribe()
    sr_rpc_init_rpc_cb()
    sr_event_notif_subscribe().

Finally it's assigned to: sr_subscription_ctx_t : sm_subscriptions[]->private_ctx in cl_subscription_init() function in all cases above.

We don't have direct access from our application to private_ctx because sr_subscription_ctx_t is defined in .c file (client_library.c).

The assumption is we don't keep pointer to this memory as long as is used by sysrepo, because it would require a great refactoring in our code. We wonder if that's any function defined in sysrepo which allows freeing this memory?

In order to illustrate approximated flow in this situation we can use modified code of rpc_example application (
[rpc_example.txt](https://github.com/sysrepo/sysrepo/files/3905868/rpc_example.txt)

attached). The change from the original is that we don't pass sr_session_ctx_t* as parameter to rpc_handler() function. We declare this pointer inside rpc_handler() function and allocate memory there using malloc. Our question: 'is that possible to free this memory in function main() or - generalizing - from anywhere in code, out of scope sr_session_ctx_t *session pointer'?

**Comment by michalvasko** [comment]
Hi,
it is not possible to free this private context automatically. It would not be too much trouble to add an option to set a function for freeing it but we would like to keep the old *sysrepo* the way it is now. We are hoping to release the new *sysrepo* quite soon and I could add this functionality there. Would that be fine for you?

Regards,
Michal

**Comment by dchechel** [comment]
Hi, 

thank you for your answer. It will be really a good idea to solve this problem in new sysrepo. 

BR,
Dawid

**Comment by michalvasko** [comment]
Hi Dawid,
I wanted to add a callback to the new *sysrepo* that would be called for every `private_ctx` but it is not as simple as it seems. The problem is that every single subscribe call can set its own private data. Having separate callback for each of them is just not worth it but having only one callback for all the subscriptions in a single subscription structure does not seem versatile enough. But the latter is the solution I am leaning to, what do you think?

But, regarding your particular use-case, are you setting only a *sysrepo* session as the private data? In the new *sysrepo*, when you call `sr_disconnect()` all sessions and subscriptions created on the connection are automatically freed meaning even this session would be freed.

Regards,
Michal
