### ISSUE TITLE
Efficient way to get only immediate leaves under a node from the application?

### ISSUE THREAD

**Issue by iGovindY** [sysrepo/sysrepo#1704]
There are three APIs to get data from sysrepo:
```
sr_get_items()
sr_get_subtree()
sr_get_data()
```

Is there a way to get only immediate leaves under a XPath?
or sysrepo always give everything under a xpath, and application has to process and filter such leaves?

**Comment by michalvasko** [comment]
Hi,
`sr_get_items()` should do what you need, what is the problem with that function?

Regards,
Michal

**Comment by iGovindY** [comment]
Lets take an example of the Oven Module.

```
rc = sr_get_items(session,  /oven:oven/*, 0, &vals, &val_count);

```
Above subscribe call returns everything under container oven.
What I need is only immediate leaves under container oven i.e. `turned-on`, `temperature `only

So my query is, how to only get that, not everything?
Is there a way to achieve it using xpath in `sr_get_items `API.

**Comment by michalvasko** [comment]
Hi,
I see. Well, you can request only nodes without descendants with something like `/oven:oven/*[not(*)]` but you cannot directly express node types in XPath. And since you are also worried about efficiency, know that it is best to always use `sr_get_data()` with as restrictive XPath as possible. Every getter function uses it and then just further transforms the output, so you can skip that transformation.

Regards,
Michal
