### ISSUE TITLE
[New sysrepo] sr_connect() load into mutex of sr_main_shm_t as status acquired from previous stored sr_main even it is its first execution 

### ISSUE THREAD

**Issue by brchiu** [sysrepo/sysrepo#1711]
Execute `sysrepo-plugind -d -v 4` and randomly press `ctrl-c` to end it, then re-run `sysrepo-plugin` again, it blocks at `pthread_mutex_timedlock` inside `sr_rwlock_with_recovery`.

The reason seems to be that shm stores `rwlock` and `mutex` status, and `sr_shm_remap` will reload their previous status from file then, though rarely happen but still possible, the lock status might be already acquired. See below :

```
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[INF]: Scheduled changes not applied because of other existing connections.

Breakpoint 1, sr_rwlock_with_recovery (rwlock=0x7ffff7feb000, timeout_ms=15000, mode=SR_LOCK_WRITE, 
    conn=0x5555557592d0, func=0x7ffff7bc0070 <__func__.8804> "sr_shmmain_lock_remap")
    at /media/brchiu/79918428768101F8/DocCollect/Project/sysrepo/src/common.c:2117
2117	{
(gdb) n
2118	    sr_error_info_t *err_info = NULL;
(gdb) n
2122	    assert(timeout_ms > 0);
(gdb) n
2123	    assert((mode == SR_LOCK_READ) || (mode == SR_LOCK_WRITE));
(gdb) n
2125	    sr_time_get(&timeout_ts, timeout_ms);
(gdb) n
2128	    ret = pthread_mutex_timedlock(&rwlock->mutex, &timeout_ts);
(gdb) p rwlock->mutex
$2 = pthread_mutex_t = {Type = Normal, Status = Acquired, possibly with waiters, Owner ID = 9924, Robust = No, 
  Shared = Yes, Protocol = None}
```

**Comment by michalvasko** [comment]
Hi,
you will have to provide more information so that I can understand what is actually going on. Firstly, "randomly" terminating `sysrepo-plugind` is quite difficult to reproduce. In your case there are some existing connections, which are probably a result of `sysrepo-plugind` not correctly disconnecting them and I would focus on the reason why. So, do you have some plugins? Have you terminated `sysrepo-plugind` forcefully (sending SIGINT twice, for example)? If you pull the `devel`, I have added an error that should inform about this when it happens.

Regards,
Michal

**Comment by brchiu** [comment]
Please refer to : https://gist.github.com/brchiu/4ef178e21a27b33f84bcdd94200c474e
I use gdb to stop inside plugin, ctrl-c to quit, restart .... so on and so on.

But my point is, the procedure to re-produce this problem might not be that important, you might think gdb is not a common operation for user. However, I think the problem is the design decision to store those data need to be persistent, e.g. repository info that I have not dig into it, along with lock status data into file which should be valid only when needed.

You can still use share memory to share lock status for different processes as synchronization mechanism, but remove them from stored file and re-init it when first create time might be better. That's just my two cents.

**Comment by michalvasko** [comment]
Hi,
I do not really understand what exactly you do not like. How are 2 processes supposed to synchronize using shared memory if they do not store a mutex in it? You will always get data races unless you use some other synchronization primitive.

Regards,
Michal

**Comment by brchiu** [comment]
hi, Michal, 
I should not suggest any possible solution, my idea might be too naive and not be practical. My bad.
This problem should be re-addressed as "`sr_connect` load into mutex of sr_main_shm_t as status acquired from previous stored sr_main even it is the first execution" which make it fails to lock it at sr_rwlock_with_recovery.

**Comment by michalvasko** [comment]
Hi,
okay, no problem. As for your issue, whenever you have a crashed *sysrepo* client (or terminate `sysrepo-plugind` with it printing information about not performing a cleanup), you are supposed to recover the stale connection (you can use `sysrepoctl -R`). If you encounter a problem after you do this, then I will consider it an issue.

Regards,
Michal

**Comment by brchiu** [comment]
hi, Michal,

`sysrepoctl -R` does not work due to it is a chicken-egg dilemma that it has to acquire the mutex to do subsequent process but be blocked due to mutex is already initialized by loaded value as acquired.
```
~$ sudo sysrepoctl -R
[ERR]: Locking a mutex failed (sr_shmmain_lock_remap: Connection timed out).
sysrepoctl error: Failed to connect (Timeout expired)
```

**Comment by michalvasko** [comment]
Hi,
yes, you already have invalid shared memory state, clear it with `make shm_clean`. Then refer to my previous reply.

Regards,
Michal

**Comment by brchiu** [comment]
hi, Michal, frankly speaking, it does not make sense to have to recover share memory state by `make shm_clean` if this device equipped with `sysrepo` is already deployed in the field. We can even no way to be fault tolerant (to certain level) or to recover it ?

**Comment by michalvasko** [comment]
Look, I am not sure what else to tell you, I just keep repeating myself, but fine, one last time.

You start with a valid state, no shared memory created. Then as long as no *sysrepo* client crashes everything should work fine. So, we are now discussing what happens when an app crashes. If it crashes in its own code (not executing a *sysrepo* function or an application callback is being called by *sysrepo*) all that should be needed is to call `sr_connection_recover()`, which should properly clean everything after the crashed connection. If it does not, it is a bug that should be reported and fixed. Also, if the app crashes in *sysrepo* code it is also a *sysrepo* bug.

I do not think it makes much sense to handle all possible situations when *sysrepo* can crash due to its bugs. The recovery procedure may help even in these cases but it may not. Also, it should always work fine after the device is restarted (all shared memory is implicitly removed) so those are probably the steps that should be taken in this case. Report the problem, use the provided fix, and restart the device.

Regards,
Michal

**Comment by dwbxm** [comment]
hi,Michal,brchiu,
I have encountered the problem.  sysrepo-plugind is running in virtual machine, VMware, centos8.

my operations are following:
1、built the sysrepo and installed , then built the examples--oven.
2、installed yang model ,sysrepoctl -i sysrepo/examples/plugin/oven.yang
3、mkdir /usr/lib64/sysrepo/plugins -p, 
     cp sysrepo/examples/liboven.so /usr/lib64/sysrepo/plugins/
4、sysrepo-plugind -v debug -d . everything is ok.

then , i shutdown the vm when sysrepo-plugind is running.After a day, i start the vm, 
**sysrepo-plugind -v debug -d, output
[INF]: Scheduled changes not applied because of other existing connections.
[ERR]: Locking a mutex failed (sr_shmmain_lock_remap: Connection timed out).
sysrepo-plugind error: Failed to connect (Timeout expired).**

Then,I want to see whether the oven.yang model is installed or not,
**sysrepoctl -l, output** 
**[ERR]: Locking a mutex failed (sr_shmmain_lock_remap: Connection timed out).
sysrepoctl error: Failed to connect (Timeout expired).**

I think the error is the same as above. Yes?
