### ISSUE TITLE
Sysrepo slows down significantly (openconfig-interfaces).

### ISSUE THREAD

**Issue by iljatab** [sysrepo/sysrepo#1729]
Using "devel" branches for libyang and sysrepo (cloned on Dec 25).

sysrepoctl -V
sysrepocfg - sysrepo YANG schema manipulation tool, compiled with libsysrepo v1.3.27 (SO v4.1.14)

yanglint --version
yanglint SO 1.5.5

Steps to reproduce:

1. YANG model list before the test is inside attached apps.tar.gz.

2. Unpack attached apps.tgz and compile two applications - application_changes_example and sr_set_item_example.

3. Start application_changes_example:

$./application_changes_example openconfig-interfaces
Application will watch for changes in "openconfig-interfaces".

 ========== LISTENING FOR CHANGES ==========

4. Run sr_set_item_example several times.
This executable creates N openconfig-interfaces objects and sets some basic fields for each interface. Before creating an interface it checks the interface is not already there.
So overall for each interface there is one sr_get_itrem() call and five sr_set_item_str() calls.
After creating all interfaces sr_apply_changes() is called.
The lower and upper interface indexes should be specified on command line.
The command prints time in seconds, spent in setting items and then the total time (sets + sr_apply_changes).

First create interfaces in batches of 100:

$ ./sr_set_item_example 101 200 2>/dev/null
Started
Completed set: 4
Completed commit: 18

$ ./sr_set_item_example 201 300 2>/dev/null
Started
Completed set: 15
Completed commit: 30

$ ./sr_set_item_example 1301 1400 2>/dev/null
Started
Completed set: 27
Completed commit: 43

$ ./sr_set_item_example 1401 1500 2>/dev/null
Started
Completed set: 36
Completed commit: 54

$ ./sr_set_item_example 301 400 2>/dev/null
Started
Completed set: 50
Completed commit: 70

$ ./sr_set_item_example 401 500 2>/dev/null
Started
Completed set: 70
Completed commit: 93

$ ./sr_set_item_example 701 800 2>/dev/null
Started
Completed set: 92
Completed commit: 119

So the total time to add 100 entries rises from 18 sec to 119 sec.

Now add just one single entry and it takes 14 seconds, spent in sr_apply_changes():

$ ./sr_set_item_example 1000 1000 2>/dev/null
Started
Completed set: 0
Completed commit: 14

It is actually SLOWER than it used to be with old sysrepo :-(

Could you please clarify if there are any performance tuning options for sysrepo?

Thanks!

**Comment by iljatab** [comment]
[apps.tar.gz](https://github.com/sysrepo/sysrepo/files/4003149/apps.tar.gz)

**Comment by michalvasko** [comment]
Hi,
there will definitely be a problem because this is my output
```
vasko@pcvasko:~/Downloads/apps> ./sr_set_item_example 101 200 2>/dev/null
Started
Completed set: 0
Completed commit: 1
vasko@pcvasko:~/Downloads/apps> ./sr_set_item_example 201 300 2>/dev/null
Started
Completed set: 1
Completed commit: 1
vasko@pcvasko:~/Downloads/apps> ./sr_set_item_example 1301 1400 2>/dev/null
Started
Completed set: 1
Completed commit: 2
vasko@pcvasko:~/Downloads/apps> ./sr_set_item_example 1401 1500 2>/dev/null
Started
Completed set: 1
Completed commit: 1
vasko@pcvasko:~/Downloads/apps> ./sr_set_item_example 301 400 2>/dev/null
Started
Completed set: 1
Completed commit: 2
vasko@pcvasko:~/Downloads/apps> ./sr_set_item_example 401 500 2>/dev/null
Started
Completed set: 2
Completed commit: 2
vasko@pcvasko:~/Downloads/apps> ./sr_set_item_example 701 800 2>/dev/null
Started
Completed set: 2
Completed commit: 2
vasko@pcvasko:~/Downloads/apps> ./sr_set_item_example 1000 1000 2>/dev/null
Started
Completed set: 0
Completed commit: 0
```
There is one option that could definitely make such a huge difference and that is `ENABLE_CACHE` of *libyang*. It should be ON by default but maybe you have it OFF for some reason?

Regards,
Michal

**Comment by iljatab** [comment]
Thanks for response, Michal!

I switched again to the latest sysrep:
    $ sysrepoctl -V
    sysrepocfg - sysrepo YANG schema manipulation tool, compiled with libsysrepo v1.3.28 (SO v4.1.15)

Also I used the device with the fastest available for me CPU:
    model name      : Intel(R) Xeon(R) CPU D-1527 @ 2.20GHz

And, to my understanding, I have libyang ENABLE_CACHE set to ON.

And still the performance is very far from one I see in your example:
    $ sr_set_item_example 101 200 2>/dev/null
    Started
    Completed set: 1
    Completed commit: 6
    $ sr_set_item_example 201 300 2>/dev/null
    Started
    Completed set: 3
    Completed commit: 8
    $ sr_set_item_example 1301 1400 2>/dev/null
    Started
    Completed set: 6
    Completed commit: 11
    $ sr_set_item_example 1401 1500 2>/dev/null
    Started
    Completed set: 8
    Completed commit: 13
    $ sr_set_item_example 301 400 2>/dev/null
    Started
    Completed set: 10
    Completed commit: 16
    $ sr_set_item_example 401 500 2>/dev/null
    Started
    Completed set: 13
    Completed commit: 19
    $ sr_set_item_example 701 800 2>/dev/null
    Started
    Completed set: 15
    Completed commit: 21

Looks like still something is wrong.
Is there a way to check in the run-time if ENABLE_CACHE is ON?
Any other checks I could do?

This is my list of installed YANG models:

    Sysrepo repository: /etc/sysrepo
    
    Module Name                       | Revision   | Flags | Owner     | Permissions | Submodules 
    ----------------------------------------------------------------------------------------------
    iana-if-type                      | 2017-01-19 | I     | root:root | 600         |
    ietf-interfaces                   | 2018-02-20 | I     | root:root | 600         |
    ietf-netconf                      | 2011-06-01 | I     | root:root | 666         |
    ietf-netconf-notifications        | 2012-02-06 | I     | root:root | 666         |
    ietf-netconf-with-defaults        | 2011-06-01 | I     | root:root | 666         |
    ietf-origin                       | 2018-02-14 | I     | root:root | 666         |
    ietf-yang-library                 | 2019-01-04 | I     | root:root | 666         |
    openconfig-acl                    | 2018-11-21 | I     | root:root | 600         |
    openconfig-aft                    | 2019-08-01 | i     |           |             |
    openconfig-bgp                    | 2019-05-28 | i     |           |             |
    openconfig-bgp-policy             | 2019-02-01 | I     | root:root | 600         |
    openconfig-bgp-types              | 2018-11-21 | i     |           |             |
    openconfig-extensions             | 2018-10-17 | i     |           |             |
    openconfig-if-aggregate           | 2019-04-16 | I     | root:root | 600         |
    openconfig-if-ethernet            | 2019-04-16 | I     | root:root | 600         |
    openconfig-if-ethernet-ext        | 2018-11-21 | I     | root:root | 600         |
    openconfig-if-ip                  | 2019-01-08 | I     | root:root | 600         |
    openconfig-if-types               | 2018-11-21 | i     |           |             |
    openconfig-igmp                   | 2019-07-09 | i     |           |             |
    openconfig-igmp-types             | 2018-11-21 | i     |           |             |
    openconfig-inet-types             | 2019-04-25 | i     |           |             |
    openconfig-interfaces             | 2019-07-10 | I     | root:root | 600         |
    openconfig-isis                   | 2018-11-21 | i     |           |             |
    openconfig-isis-types             | 2018-11-21 | i     |           |             |
    openconfig-local-routing          | 2018-11-21 | i     |           |             |
    openconfig-mpls                   | 2019-03-26 | i     |           |             |
    openconfig-mpls-ldp               | 2019-07-09 | i     |           |             |
    openconfig-mpls-rsvp              | 2018-11-21 | i     |           |             |
    openconfig-mpls-types             | 2019-03-26 | i     |           |             |
    openconfig-network-instance       | 2019-05-14 | I     | root:root | 600         | openconfig-network-instance-l2
    openconfig-network-instance-l3    | 2018-11-21 | i     |           |             |
    openconfig-network-instance-types | 2018-11-21 | i     |           |             |
    openconfig-ospfv2                 | 2019-07-09 | I     | root:root | 600         | openconfig-ospfv2-global ...
    openconfig-packet-match           | 2018-11-21 | i     |           |             |
    openconfig-packet-match-types     | 2018-11-21 | i     |           |             |
    openconfig-pim                    | 2019-07-09 | i     |           |             |
    openconfig-pim-types              | 2018-11-21 | i     |           |             |
    openconfig-policy-forwarding      | 2018-11-21 | i     |           |             |
    openconfig-policy-types           | 2018-11-21 | i     |           |             |
    openconfig-rib-bgp                | 2019-04-25 | i     |           |             |
    openconfig-routing-policy         | 2018-11-21 | I     | root:root | 600         |
    openconfig-segment-routing        | 2018-11-21 | i     |           |             |
    openconfig-types                  | 2019-04-16 | i     |           |             |
    openconfig-vlan                   | 2019-04-16 | I     | root:root | 600         |
    openconfig-vlan-types             | 2019-01-31 | I     | root:root | 600         |
    openconfig-yang-types             | 2018-11-21 | i     |           |             |
    yang                              | 2017-02-20 | I     | root:root | 666         |
    
    Flags meaning: I - Installed/i - Imported; R - Replay support; N - New/X - Removed/U - Updated; F - Feature changes

**Comment by iljatab** [comment]
BTW, in the old sysrepo there were configurable ENABLE_CONFIG_CHANGE_NOTIF and STORE_CONFIG_CHANGE_NOTIF that already affected performance.

However in new sysrepo I cannot find how to disable configuration change notifications.
Is it possible to do somehow?

Ilja.

**Comment by michalvasko** [comment]
Hi Ilja,
I have tried it again having all your modules installed and then I got similar numbers than you. After a quick check with `callgrind` I learnt what the problem is, specifically a module has added some leafref into `openconfig-interfaces` or some data that are being modified. *libyang* has a rather unfortunate leafref "optimization" that was actually taking 87% of the whole time spent. We had some problems with it before but there was no specific reason to change it until now. So, please use the latest `devel` of *libyang* (commit https://github.com/CESNET/libyang/commit/1544f48b3b7385200bf69e3f4a8136125e0c40b5) and you should get the time I originally measured.

I am also attaching the measurements of `sr_set_item_example` after using the fixed *libyang*. In short, now 60% of the whole work is performed by `sr_get_item()` when you are checking that an interface does not exist yet and only 35% is `sr_apply_changes()`.

[callgrind.tar.gz](https://github.com/sysrepo/sysrepo/files/4019254/callgrind.tar.gz)

As for some other optimization you can do, there are none really. `netconf-config-change` notification is actually not generated by default. By far the greatest performance problem was storing this notification for replay, not just generating the notification. If you look at your `sysrepoctl -l` output, you will see that `ietf-netconf-notification` (the notification is defined in this module) does not have the `R` flag meaning its replay support is off and hence the notification is never stored.

You have correctly used the `SR_CONN_CACHE_RUNNING` flag, which is probably the only optimization that the user can do. You would see the difference if you have not used it; `sr_get_item()` would take even more time.

Nevertheless, if you really want to get the best possible performance, you should always use *libyang* function variants (as mentioned in the [docs](http://www.sysrepo.org/static/doc/html/index.html#features)). Getting data can be quite faster this way (but is not seen in your examples, you would actually have to get any items) and you may also try using `sr_edit_batch()` to set data. But note that the latter is an advanced function (that is used efficiently mainly by *netopeer2*) so you must know what `edit` to use in order to make the changes you want.

Lastly, I have not performed any specific optimization in the new *sysrepo* yet, we were focused on it being correct, have all the functionality implemented, and its design to generally perform better. So, if you encounter any other suspicious behavior, please let us know. It may be fairly easy to fix, such as in this case.

Regards,
Michal

**Comment by iljatab** [comment]
Thanks, now performance looks improved!
