### ISSUE TITLE
[Sysrepo-legacy] Validation of not modified modules taking too much time

### ISSUE THREAD

**Issue by sriramkandukuri** [sysrepo/sysrepo#1730]
Hi Michal,
As you know we have large set of yang files.Even single interface configuration increasing validation time to multifold.

I have seen that info->modified is being true for non modified modules also and all of them are validating with dependencies iteratively.

Why a non modified data is being marked as modified and is it possible to validate all modules (modified + deps) in single lyd_validate call.

I have send sample debug logs over mail.

Thanks & Regards,
Sriram.K

**Comment by michalvasko** [comment]
Hi Sriram,
I am sorry but there are way too many other issues not even mentioning some actual work I should be doing for me to spend time on optimizing the old *sysrepo*. Most likely, there is a reason why it is all validated again and instead of optimizing all these inefficiencies we have developed the new *sysrepo*. There is a small chance I may have some time to take a look at this but not anytime soon.

Regards,
Michal
