### ISSUE TITLE
[New sysrepo] Cannot change config from action handler callback

### ISSUE THREAD

**Issue by gitter-runner** [sysrepo/sysrepo#1735]
Hello,

I need to change the configuration of a list item from an action handler callback registered using _sr_rpc_subscribe()_.
This was possible in the old sysrepo 0.7.x but in the new sysrepo I get an error on _sr_apply_changes()_:

`[ERR]: Locking a mutex failed (sr_process_events: Connection timed out).`

I tried _SR_SUBSCR_UNLOCKED_ flag but it didn't solve the problem.

sysrepo version: 1.3.32
libyang version: 1.0.114

Thanks!

**Comment by michalvasko** [comment]
Hi,
you are right, it needed a bit of tuning to allow this and it should work now.

However, note that the problem manifested only if you executed an action (was fine for RPC) and this action input either had a dependency on or the action itself was from the module whose data were being changed. Also note that you will still get a timeout in case you subscribe to the **action** on the same subscription that you subscribe to the **data being changed**, it is the same problem from the old *sysrepo* when one thread is supposed to process 2 events simultaneously. I am mentioning it just because this happened to me in a test I added for this use-case.

Regards,
Michal
