### ISSUE TITLE
[New sysrepo] Cannot stop session in oper get items callback

### ISSUE THREAD

**Issue by gitter-runner** [sysrepo/sysrepo#1736]
Hi,
I need to read configuration data from oper get items callback registered using _sr_oper_get_items_subscribe()_.
Starting a session and reading from running datastore works, but _sr_session_stop()_ returns with a timeout error:

`[ERR]: Waiting on a conditional variable failed (sr_shmmain_lock_remap: Connection timed out).`

sysrepo version: 1.3.32
libyang version: 1.0.114

Thanks!

**Comment by michalvasko** [comment]
Hi,
you will need to provide more details. Based on the issue title, are you creating and then stopping a session in the callback? Are you stopping the callback session? What is your general setup, are you simply subscribed to providing oper data and then request these data from your application? Or the data are requested from another callback?

Regards,
Michal

**Comment by gitter-runner** [comment]
Hi,
I start a new session in the callback and stop it after reading. I don't try to stop the callback session.
I attached a simple example using _ietf-system_ for reproduction. It gets stuck in _sr_session_stop()_ and works if it is commented out.

By the way I created the new session because I had issue with callback session formerly.
It is already solved, so it may be a better solution to use it instead of creating a new one.

I attached the example c file in txt format because of github attachment type restrictions.
[oper_data_example_c.txt](https://github.com/sysrepo/sysrepo/files/4030955/oper_data_example_c.txt)


Thanks

**Comment by michalvasko** [comment]
Hi,
you are right, a lock is trying to be locked that is needed only if there are any subscriptions on the particular session. However, I do not see a valid reason why you should be creating sessions in a callback and not use the provided one. Moreover, you may get different data in some cases because the current changes (in `sr_module_change_cb`) are applied only if the callback session is used. So, please use the callback session and if there are any problems with it, let us know.

Regards,
Michal
