### ISSUE TITLE
sysrepocfg hangs if earlier configuration timedout

### ISSUE THREAD

**Issue by sriramkandukuri** [sysrepo/sysrepo#1751]
Hi,

Here is the scenario

sysrepo_application --> listener runs in background
sysrepocfg1 --> applies a configuration and it gets timeout, 
sysrepocfg2 --> tries to apply another configuration and hangs. actually it updated request id in multi_sub_shm
sysrepo_application --> For sysrepocfg1 completes the callback and asserts with (requestid == multi_sub_shm->requestid) as the sysrepocfg2 already started....
As sysrepo_application exits with assert and sysrepocfg2 still see readers in shm and it hangs at conditional wait.
Sysrepocfg2 starts good as it see the listener works good,

Is it possible to avoid such hangs?

Thanks & Regards,
Sriram.K

**Comment by michalvasko** [comment]
Hi,
you are right, I have added such a test case and it should now work properly (no assert).

Regards,
Michal

**Comment by sriramkandukuri** [comment]
Hi,

So as you changed it to error now, Can we expect ABORT after such failure occurs?

Thanks & Regards,
Sriram.K

**Comment by michalvasko** [comment]
Hi,
yes, it is treated as a standard callback error. However, the timed out callback will not get this event because it is considered to be in an error state and not have applied the change even though it may finish successfully after (I suppose it would be quite simple to manually generate the abort event for this callback in this case). You can specify exact timeout for every commit and if still a callback times out, I would consider it a fatal error.

Regards,
Michal

**Comment by sriramkandukuri** [comment]
Hi,

Are you planning to add code for manually generating ABORT event after timedout callback?
How to specify a timeout for commit? Is it possible through sysrepocfg?

Thanks & Regards,
Sriram.K

**Comment by sriramkandukuri** [comment]
Hi Michal,

Thanks for the changes.
Will check and update the status.

Thanks & Regards,
Sriram.K

**Comment by sriramkandukuri** [comment]
Hi Michal,

Below cases working fine.

1. Next config over previous timed out configuration not hanging.
2. Abort event published after timed out and successfull configuration callback.
3. Time out can be given from sysrepocfg.

Thanks & Regards,
Sriram.K
