### ISSUE TITLE
persist file loss issues

### ISSUE THREAD

**Issue by zyboy2000** [sysrepo/sysrepo#1753]
When using fast frequency to access a private node openconfig-platform through netopeer2-server, there will be a probability of access timeout,
    When timeout occurs, netopeer2-server log:
            np2srv_sr_get_items_iter failed (sysrepo: Timeout has expired).
    The sysrepod side will have the following error logs:
            (rp_handle_get_call_state:690) Time out waiting for operational data expired before all responses have been received, session id = 535144792, req = 686
    At this time, check the openconfig-platform.persist file and find that the file is much smaller than normal.
    Want to consult:
            1. Under what circumstances will the openconfig-platform.persist file be modified?
            2. Is the above access timeout due to the modification of the  openconfig-platform.persist file or the modification of the openconfig-platform..persist file cause the access timeout

**Comment by michalvasko** [comment]
Hi,
1. I assume whenever any data from [the module](https://github.com/sysrepo/sysrepo/blob/legacy/yang/sysrepo-persistent-data.yang) change.
2. Not sure hat causes the error.

Maybe you can fix this somehow yourself but note that I will not because this seems like quite a specific use-case. You can always switch to the current *sysrepo*.

Regards,
Michal

**Comment by zyboy2000** [comment]
Can you tell me where the source code modified this file（persist）?  Thanks
