### ISSUE TITLE
sr_get_item performance

### ISSUE THREAD

**Issue by sriramkandukuri** [sysrepo/sysrepo#1758]
Hi,

When there is huge data with a diff in current session all below options takes same time.
- `sr_get_item`
- `sr_get_items` with all data
- `sr_get_items` with a filter which return only single leaf.

Is there any chance to optimize these.

Thanks & Regards,
Sriram.K

**Comment by michalvasko** [comment]
Hi Sriram,
looking at the code it probably would be possible to first filter the diff before applying it on the data but I would need to think about it more to make certain it is safe. However, I will not optimize anything until I have some actual numbers and can see which code needs optimizing. It would be nice if you could provide, for example, `callgrind` output of that `sr_get_item(s)` call. It is quite simple, all the details are [here](http://valgrind.org/docs/manual/cl-manual.html#cl-manual.limits) but, in short, you simply define `CALLGRIND_START_INSTRUMENTATION;` before the call, `CALLGRIND_STOP_INSTRUMENTATION;` after the call, compile, and start the application with `--tool=callgrind --instr-atstart=no`. But you will need to download and include `valgrind-devel` package or something similar.

Nevertheless, your use-case is not a crucial one. You are not really supposed to use these getters in module change callback but rather be fine with the changes themselves. It is supported because there are cases when it is the simplest thing to do but the performance overhead will always be significant compared to just iterating over the changes.

Regards,
Michal

**Comment by sriramkandukuri** [comment]
Hi Michal,

With 4000 leafs in a list I have collected callgrind output for `sr_get_items` to get all and `sr_get_item` with single node. Please find below output files.

[callgrind.out.getsingle.txt](https://github.com/sysrepo/sysrepo/files/4077057/callgrind.out.getsingle.txt)
[callgrind.out.getall.txt](https://github.com/sysrepo/sysrepo/files/4077058/callgrind.out.getall.txt)

Thanks & Regards,
Sriram.K

**Comment by sriramkandukuri** [comment]
Hi Michal,

Please find below flamegraph where I have calling two APIs and they are taking almost same time.

![image](https://user-images.githubusercontent.com/5476956/72618807-f304a400-3961-11ea-9872-7c510b231b2d.png)

Thanks & Regards,
Sriram.K

**Comment by michalvasko** [comment]
Hi Sriram,
the flame graph is not too helpful and your `callgrind` outputs are also weird. It does not seem to me you have measured both `sr_get_item` and `sr_get_items` in the same circumstances. Did you call `sr_get_item` in a module change callback on `SR_EV_CHANGE` event and `sr_get_items` directly from your application? Then the `callgrind` files would make sense. But I am not able to understand the flame graph at all.

Regards,
Michal

**Comment by sriramkandukuri** [comment]
Hi Michal,

I have used application changes example only, for flame graph, and both callgrind outputs.

Testes with a Yang module  having one list with one leaf. And config contains 4K nodes for the list node.
sr_get_items for all nodes, and sr_get_item for single node. 

As you said I have enclosed `sr_get_item(s)` with CALLGRIND macros and obtained callgrind outputs.

While obtaining flame graph i have used both sr_get_item calls in `print_current_config` and you can see same area covered by both APIs which means both taking almost same time.

Thanks & Regards,
Sriram.K

**Comment by michalvasko** [comment]
Hi Sriram,
I would believe that for `sr_get_items()` but in `sr_get_item()` `callgrind` output there is the call of `module_change_cb()`, you can take a look. Maybe you have attached some other file.

As for the flame graph, firstly, I am not sure why you get 4 equally-sized columns, but it may be some kind of am approximation. But it definitely does not make sense that `sr_get_item()` calls `sr_diff_mod_apply()` and `sr_get_items()` does not. If they were called in the same context, both must either call it or neither of them will.

Regards,
Michal

**Comment by sriramkandukuri** [comment]
Hi Michal,

Please find below flame graph. Previous one might be error as I used 99HZ freq. Now this I ran with 999HZ.

**Flame graph for print_current_config alone**
![image](https://user-images.githubusercontent.com/5476956/72731472-d06cc800-3bb9-11ea-9c8d-9660d7bd57a1.png)

**Full flame graph**
![image](https://user-images.githubusercontent.com/5476956/72731601-0316c080-3bba-11ea-8ad5-c4443d05dc88.png)

Thanks & Regards,
Sriram.K

**Comment by michalvasko** [comment]
Hi Sriram,
okay, that looks much better. Looking at the flame graph (which is now supported by the `callgrind` output), it seems good to me. All the steps that I would expect to take a considerable time can be seen and there are no others.

The only interesting result is why `lyd_find_path` takes so much time for `sr_get_item` than for `sr_get_items` but it is quite natural. The XPath used for `sr_get_items` is `/a:*//.` whereas for `sr_get_item` it is `/a:ac1/acl1[acs1='sriram22']/acs1`, which is way more specific and hence the difference. Actually, since only filtering takes such a major portion of the instructions executed, I would say *sysrepo* performs very well.

You can try using `SR_CONN_CACHE_RUNNING` in the example (once #1768 is fixed even in your application) and measure it again but the difference may not be that significant. At least not for `callgrind` benchmarks because it measures instructions executed, not the actual time each function took. By caching the data, you will get `lyd_dup_withsiblings()` instead of `lyd_parse_fd()`, which may require a similar amount of instructions but the former does not access disk, which can make a huge difference for the final execution time. But the main problem here is you getting data in `SR_EV_CHANGE` callback, which is definitely the most expensive place to do so.

Regards,
Michal

**Comment by sriramkandukuri** [comment]
Hi Michal,

Atleast `sr_get_item` API taking too much time when compared to old sysrepo.

We have a test which handles on large data which runs in ~2s with old sysrepo where as it is running around ~42s in new sysrepo. When I profiled that test case it seems `sr_get_item` taking much time.

It would be very helpful if there is a way to reduce that.

Thanks & Regards,
Sriram.K

**Comment by michalvasko** [comment]
Hi Sriram,
well, can you post (at least privately) the `callgrind` output of that use-case with some basic information (such as the XPath used)?  It is hard to guess what part has the scaling problem based on the previous measurements.

But I repeat, it is very possible this particular use-case (getting items in `SR_EV_CHANGE`) is much faster in the old *sysrepo* because it was not an optimization priority in the new one. I believe in the old *sysrepo* the prepared new data are kept as a full data tree so getting items works with the same efficiency as in other cases whereas the new *sysrepo* always stores only one copy of the data store (saving potentially 100s of MiBs) meaning that in this case a new copy of the datastore is created, the current changes applied, and only then can the updated data be returned.

Regards,
Michal

**Comment by michalvasko** [comment]
Hi,
please try your previous use-case again. In the benchmarks, `sr_edit_find_userord_predicate` should no longer take so much time. Actually, it should now have a constant complexity so you should not even see it in any graph.

Regards,
Michal

**Comment by sriramkandukuri** [comment]
Hi Michal,

I could see significang performance improvement in this change which improve time for the testcase to ~13s where it used to take ~42s

Please find below flame graph.
![image](https://user-images.githubusercontent.com/5476956/73193819-2bba2f80-4151-11ea-879d-a2298eaad7ae.png)

But `sr_get_item(s)` takes good amount of time. By the way using `sr_get_data` improved the performance very well.

Thanks & Regards,
Sriram.K

**Comment by michalvasko** [comment]
Hi Sriram,
okay, just wanted to make sure the effect is the expected one, thanks.

Regards,
Michal
