### ISSUE TITLE
Query: ietf-netconf yang version 

### ISSUE THREAD

**Issue by sriramkandukuri** [sysrepo/sysrepo#1761]
Hi,

There is a difference in netopeer2 server's ietf-netconf.yang and sysrepo's.
When trying to install both on a device sysrepoctl throws some errors.

Which one need to be installed finally? Does sysrepo's yang file needs any upgrade?

Thanks & Regards,
Sriram.K

**Comment by michalvasko** [comment]
Hi,
you first install *sysrepo* and then *netopeer2-server*, naturally. The server then [updates](https://github.com/CESNET/Netopeer2/blob/master/server/setup.sh#L18) the module, because it requires the newer one, so that is the required one.

Regards,
Michal

**Comment by sriramkandukuri** [comment]
Hi,

Is there any specific reason for maintaining two versions in two repos?

Thanks & Regards,
Sriram.K

**Comment by michalvasko** [comment]
Hi,
naturally. We have tried avoiding this solution but it seemed like the best option compared to others. *sysrepo* requires only `ietf-netconf`, but the latest revision uses extensions and imports `ietf-netconf-acm`, so if it used this revision, `ietf-netconf-acm` would have to be implemented. However, *sysrepo* does not implement NACM so this would not be a correct situation. Hence, *netopeer2* installs this newer revision with `ietf-netconf-acm` because it implements both of them.

Regards,
Michal

**Comment by sriramkandukuri** [comment]
Hi Michal,

Thank you for the clarification

Thanks & Regards,
Sriram.K
