### ISSUE TITLE
Query : sysrepoctl why permission setting forbidden while installation

### ISSUE THREAD

**Issue by sriramkandukuri** [sysrepo/sysrepo#1763]
Hi,

Permission setting argument to sysrepoctl `-p` not working while installation.
We have to use change operation using `-c` after installation to change the permissions of module.

Old sysrepo supports permission setting while module installation.

Any reason behind such restriction?

Thanks & Regards,
Sriram.K

**Comment by michalvasko** [comment]
Hi,
I am a bit surprised you have not encountered any unexpected behavior connected to this feature. The reason is that the modules are not installed when you run `--install` command, they are just scheduled to be installed later. The permissions can be set only after the module is actually installed. Run `sysrepoctl` with `-v3` and you will see all the information.

But I suppose there are several ways of allowing this, I will think about it.

Regards,
Michal

**Comment by sriramkandukuri** [comment]
Hi,

In our testing we run listener process first which subscribes for all modules. So I think I have not faced any issue with installation.

If module permissions are using for NACM or access management it would be better to give them while install commands, As we dont know when they actually gets installed to system.

Please correct me if I am wrong.

Thanks & Regards,
Sriram.K

**Comment by michalvasko** [comment]
Hi,
what you should probably do is to install every module on 2 `sysrepoctl` calls. On the first call, you schedule the installation, on the second call you modify the permissions however you want. When doing this you should have no other *sysrepo* clients running, which should not be a problem. Then, if changing the permissions fails, you know the module was not successfully installed.

Regards,
Michal

**Comment by sriramkandukuri** [comment]
Hi Michal,

Will do that.

If a module(`b`) imports another module(`a`). installing `b` before `a` causes below error. It would be better if it is just an INF.

```
[ERR]: Module "ietf-ip" not scheduled for deletion.
[ERR]: Module "ietf-ip" is already in sysrepo.
```

Thanks & Regards,
Sriram.K

**Comment by michalvasko** [comment]
Hi,
well, I have already discussed with someone whether this is an error or not. The result was that `sysrepoctl` does return `0` in this case, which should be fine for scripts. Your use-case is also using a script, as far as I know, so what you should do is turn logging off and just check return values of all `sysrepoctl` calls. Does such a solution not suit you for some reason?

Regards,
Michal

**Comment by sriramkandukuri** [comment]
Hi Michal,

Yes I have verified it and command returns `0` which is successful exit.
Will proceed with two commands approach as you mentioned.

Thanks & Regards,
Sriram.K

**Comment by v-chanikya** [comment]
Hi Michal,

The solution you provided below for this issue might lead to `Time Of Creation and Time Of Access` type of vulnerability.

> Hi,
> what you should probably do is to install every module on 2 `sysrepoctl` calls. On the first call, you schedule the installation, on the second call you modify the permissions however you want. When doing this you should have no other _sysrepo_ clients running, which should not be a problem. Then, if changing the permissions fails, you know the module was not successfully installed.
> 
> Regards,
> Michal

https://github.com/sysrepo/sysrepo/issues/1763#issuecomment-576220875

**Example:** If we install a module named `a`, the default permissions for that module are `664` which results to granting read access to any user. Now lets assume we have a exploiting application running under a user `rouge` (in a multi user system)  who is not supposed to have access to the datastore, and this application can subscribe to sysrepo and read the data, because there is a time delay between the module being installed and me changing the permissions to the module with a another sysrepoctl cmd.

I would suggest to allow user to set the permissions in one sysrepoctl cmd. Internally this permission can be saved and applied when ever the installation of the module is complete.

Thanks & Regards,
Chanikya

**Comment by michalvasko** [comment]
Hi,
well, because of this the default permissions are `600` so your example does not apply. However, it seems I have implemented this some time ago and if you use `-a` parameter when installing a module, you can also set owner/permissions for the module for it.

Regards,
Michal
