### ISSUE TITLE
[New sysrepo] NACM moved to netopeer2

### ISSUE THREAD

**Issue by jjin62** [sysrepo/sysrepo#1766]
I noticed that the NACM is moved to netpeer2-server. so new sysrepo no longer provides access control as in the old sysrepo. the API  sr_session_start_user is removed.

So the question is if we want to using sysrepo for management interfaces other than netconf, such as CLI, how can still use NACM?

**Comment by michalvasko** [comment]
Hi,
NACM was moved to *netopeer2* because it is defined for NETCONF and *sysrepo* should not have 2 access control policies (file system and NACM). So if you access *sysrepo* data from other sources than NETCONF you cannot enforce NACM, which is intentional. Note that `sr_session_start_user` was only changed to `sr_session_set_user` (as mentioned in [CHANGES](https://github.com/sysrepo/sysrepo/blob/master/CHANGES#L30)).

Strictly speaking, you can enforce NACM in other applications but you would have to do so manually, *sysrepo* will not do it for you. But you could simply copy *netopeer2* NACM code to do so.

Regards,
Michal

**Comment by jjin62** [comment]
Hi Michal,
thanks for the reply. In sr_session_set_user, user is the system (linux) user, while in old sr_session_start_user, the user can be users for management clients. So these two APIs are not really equivalent??

Your suggestion would work, but for a system supporting Netconf and other management interfaces, ex. CLI and REST, it would be better to have a central (code and run time) access control mechanism. As of today, netopper2 and sysrepo are coupled anyway, so there is no difference where the NACM is implemented. Can we still keep the NACM in sysrepo as optional feature?? or make NACM generic lib??

Jimmy

**Comment by michalvasko** [comment]
Hi Jimmy,
well, yes, it is not equivalent precisely because NACM is no longer a part of *sysrepo*.

Look, one of changes in the new *sysrepo* was that we have made it into a more stand-alone software that does not entirely depend on *netopeer2*. It is simply a YANG datastore used as a central management system for configuration replacing all the other configuration mechanisms as simple configuration files. For this reason we have kept only the standard file access control, which is still quite well customizable.

NACM, as I said before, is currently defined only for the NETCONF (and RESTCONF) protocol and that is now correctly implemented and it is not enforced for any other type of access. I agree that the concept could be used generally for all YANG data but that is simply not the case right now. Hence the implementation stays the way it is now, at least for the time being.

Regards,
Michal

**Comment by jjin62** [comment]
Michal,
Understand your point. We will look at new Netopeer2's NACM and figure out how to reuse it. I think this is a generic issue, as a device always need to support multiple management interfaces.

Jimmy

**Comment by michalvasko** [comment]
Yes, that seems to me is the correct approach. The only access control that is enforced for all *sysrepo* clients is by the file system and that seems to me is correct and clear.

Regards,
Michal

**Comment by jjin62** [comment]
Michal,
Your point is well taken. I have some additional feedback for your consideration in future. It is more how do we position the usage of sysrepo/libyang.

NETCONF is the standard protocol for network devices management while YANG is used to model both conﬁguration and state data of network elements. Based on this definition,  I would think majority of sysrepo/libyang application is network device, in which all processes are usually running as root or a user with root privilege, so file based access control has little value here. Functionality wise, NACM is a super set of file based access control. So it is desirable that a sysrepo based system has a generic solution to support access control for all the management interfaces.  

BR,
Jimmy
