### ISSUE TITLE
SR_EV_UPDATE not getting triggered

### ISSUE THREAD

**Issue by andrei-pavel** [sysrepo/sysrepo#1773]
I'm having problems triggering `SR_EV_UPDATE` even though subscription is done with `SR_SUBSCR_UPDATE` option.

```
    subscription_->module_change_subscribe(model_.c_str(),
                                           std::make_shared<SysrepoCallback>(),
                                           0, 0, SR_SUBSCR_UPDATE);
```

I would appreciate it if you could take a look at https://github.com/andrei-pavel/sysrepo-example.
It's probably something I'm doing wrong.

What I get after a change in sysrepocfg is always:
```
change
done
```

**Comment by michalvasko** [comment]
Hi,
you should change [this](https://github.com/andrei-pavel/sysrepo-example/blob/master/main.cpp#L86) to
```C++
subscription_->module_change_subscribe(model_.c_str(),
                                           std::make_shared<SysrepoCallback>(),
                                           nullptr, nullptr, 0, SR_SUBSCR_UPDATE);
```
Update subscriptions are not called with any other event. You would have to subscribe without the flag with the same callback if it should be called.

Regards,
Michal

**Comment by andrei-pavel** [comment]
Hello,

Right, so I was passing priority instead of options. And because I was using 0 instead of nullptr, the call was compatible with the legacy version.

I did the change and the callbacks are the same:
```
SR_EV_CHANGE
SR_EV_DONE
```

I looked through the code and a necessary step to triggering the update callback seems to be a call to `sr_apply_changes()` which never gets called for me.

But anyway, If I do what I did up until now, which was to modify data on a different session and thread on the `SR_EV_CHANGE` callback, i do get the `SR_EV_UPDATE` for that change.

Is it possible that I get `SR_EV_UPDATE` for the initial `sysrepocfg` change? This is what I'm aiming for.

**Comment by michalvasko** [comment]
Hi,
I have examined your example a bit more and you definitely cannot call `sr_apply_changes()` while another one is being executed on the same modules, that is a dead lock. I have not written that into the documentation (amended) but on `SR_EV_UPDATE` you are supposed to set the new changes __on the callback session__ and return. Only in that case they are sent back to the originator and the change set is updated, otherwise not. You are over-complicating things and an application generally has no reason to have more connections.

Regards,
Michal

**Comment by andrei-pavel** [comment]
Sorry, Michal, please don't get pestered by me, but I have to insist. The problem is simple.

I wrote `simple.cpp` to exemplify my problem. I am not getting `SR_EV_UPDATE` for a `sysrepocfg` change. Is this intended or not?

As for `main.cpp`:
```
 cannot call sr_apply_changes() 
```
I'm not doing that on `SR_EV_UPDATE`, that is well documented. I'm doing that on `SR_EV_CHANGE` because that was the way I did it in legacy and it was the only way this could be done in legacy, even if it wasn't meant to be used this way, do you agree with this? I am however trying to migrate to `SR_EV_UPDATE` which does simplify this a lot.

```
that is a dead lock
```
Not if I use a different thread, while I let the current `SR_EV_CHANGE` end it's lifetime.

```
 set the new changes on the callback session and return
```
If you could just see that it is what I'm doing...

**Comment by michalvasko** [comment]
Hi,
firstly, sorry for saying that `SR_SUBSCR_UPDATE` subscriber does not get `SR_EV_CHANGE` and `SR_EV_DONE` events because it does, ignoring them is simple. I have also made the documentation more clear because it obviously was not.

As for your example, when I actually tried it I understood that you need to run `sysrepocfg` to get any changes, which was the issue. I guess this is also my fault because you wrote it in the README. Anyway, `sysrepocfg` uses a `sr_replace_config()` to apply changes instead of `sr_apply_changes()` and their functionality differed (one was generating update event at all). Now a single function is used and it should work correctly.

Regards,
Michal

**Comment by andrei-pavel** [comment]
Thank you very much! :1st_place_medal:
