### ISSUE TITLE
Query regarding diff check callback 

### ISSUE THREAD

**Issue by sriramkandukuri** [sysrepo/sysrepo#1775]
Hi,

Due to #1758 I am thinking to change some things in listener process to use `sr_get_data` API and hold all modules data.

To apply changes I am planning to use `sr_diff_check_cb` for updating data trees held.

But going through code it seems the diff check callback is not getting called for subscriber processes. its being called only for data provider process. Is there a way to get diff for all modules in a callback in listener process similar to 'sr_diff_check_cb`?

I can get the diff in change callbacks but how to get the diff for all modules changed in current transaction. (eg. candidate committed with more than one module changed.)

Please correct me if I missed some thing.

Thanks & Regards,
Sriram.K

**Comment by michalvasko** [comment]
Hi,

> But going through code it seems the diff check callback is not getting called for subscriber processes. its being called only for data provider process. Is there a way to get diff for all modules in a callback in listener process similar to 'sr_diff_check_cb`?

`sr_diff_check_cb` was implemented so that *netopeer2-server* can properly apply its NACM, not for updating it and there is no such function, not sure what its point would be anyway. Actually, the whole commit diff should be available for all the subscribers, so any call to `sr_get_*` (even for data in another module) should get you the correct data.

Firstly, we are discussing of how to improve the efficiency of these calls so please be patient, your issues have the same priority as others. However, if you need to read a lot of additional data in your `SR_EV_CHANGE` callback (which is a characteristic of a bad callback/YANG module), it would probably be more efficient to just call `sr_get_data()` on all the interesting data and then getting individual values from it instead of multiple calls to `sr_get_*`. Also, I was thinking of adding another getter function which, depending on the node type, would just return one leaf value/inform about existence of a list/container. It could be implemented quite efficiently without any data duplication and just XPath querying would be used.

Regards,
Michal

**Comment by sriramkandukuri** [comment]
Hi Michal,

Thank you for the clarification on diff_check_cb.

I implemented the way you suggested using `sr_get_data` on every callback. But I thought that merging diff to existing data whould be faster than getting whole data again and again. So asked about any such API which returns  whole diff if requested.

Right now `sr_get_data` approach improved performance well. I can proceed with this which avoid all calls to `sr_get_item(s)`.Thank you very much for suggesting that approach.

Regarding other optimizations you are planning we can track them in #1758 .  

Thanks & Regards,
Sriram.K
