### ISSUE TITLE
STARTUP to RUNNING not happening while subscribing

### ISSUE THREAD

**Issue by sriramkandukuri** [sysrepo/sysrepo#1781]
Hi Michal,

If any data written into startup data store. This data is not being copied to running while subscription.
Is it implemented differently than old sysrepo?

In old sysrepo subscription to any module copies all startup data to running.
Please correct me if I miss something.

Thanks & Regards,
Sriram.K

**Comment by michalvasko** [comment]
Hi,
yes, it is implemented differently as mentioned in the [docs](http://www.sysrepo.org/static/doc/html/index.html#datastores) (second paragraph), it could probably be improved (done). What it means, basically, is that `running` contents no longer depend on subscriptions. This functionality was moved to the `operational` datastore (as defined by NMDA).

Regards,
Michal

**Comment by sriramkandukuri** [comment]
Hi Michal,

Thank you for the information.

When I tried below steps ENABLE event doesn't have any changes.

> Configure some data to startup data store.
> Start application with session->ds as SR_DS_RUNNING

Please correct my understanding over below points.
1. So as per the documents before starting any application there must be *.startup and yang files in repository.
2. Then very first sysrepo application starts get the data in those files to running and eventually it gets that data in ENABLE event
3. After first application if someone configures data to startup data store doesnt affect current running datastore.

Thanks & Regards,
Sriram.K

**Comment by michalvasko** [comment]
Hi,
yes, that all makes sense. You set some `startup` data but *sysrepo* had already its shared memory, it was operating in other works, so `running` data was not changed. Then you subscribed to them and got no data in `SR_EV_ENABLED`, that is correct.

You must change your understanding of the datastores. Now they behave much more according to their original definitions meaning you generally edit configuration in `running` and write data into `startup` only if you really want to change the startup data for the next system boot. The old *sysrepo* `running` had a different meaning because it included the functionality of `operational`, which is now a separate datastore.

Also, if you subscribe with `SR_SUBSCR_ENABLED`, you will simply get the current `running` data at the time of subscription, that is all. Its purpose is to allow to apply all those values by the application so that it is consistent with the `operational` datastore. Because by subscribing to `running` data, they appear in `operational` (a known concept from the old *sysrepo* but different datastore).

Regards,
Michal

**Comment by sriramkandukuri** [comment]
Hi Michal,

Thank you for the info.
One last query, so any application starts after first application gets startup data in ENABLED event as it presents in running right?

Thanks & Regards,
Sriram.K

**Comment by michalvasko** [comment]
Hi,
when subscribing with `SR_SUBSCR_ENABLED`, you get the current `running` data. If you have not changed them since boot, they are the same as `startup`.

Regards,
Michal

**Comment by gkatsikas** [comment]
Hi,

I have a (very relevant) question to this old topic.

I implemented my own sysrepo plugin in which I explicitly set some default startup configuration.
My plan is to populate (i.e., copy) this startup configuration into the running datastore once my plugin starts. From that point on, a remote controller can modify the running datastore at its own will.

By reading the docs I thought that startup would automatically be copied to running by sysrepo, however this is not the case.
Would a manual invocation of sr_copy_config() (with SR_DS_STARTUP as a source ds) simply do the job for me or am I missing something?
Any advice is welcome!

**Comment by michalvasko** [comment]
Hi,
I suppose you refer to [this](https://netopeer.liberouter.org/doc/sysrepo/master/index.html#datastores) section in the documentation, which clearly specifies when is the automatic copying of `startup` into `running` occurring. If you want the data to also be copied when your plugin is being initialized (not sure if that really is correct, but it is your call), you are free to call `sr_copy_config()` like you said.

Regards,
Michal
