### ISSUE TITLE
Question related to ietf-keystore

### ISSUE THREAD

**Issue by Roky7250** [sysrepo/sysrepo#1782]
Hi, I am currently using sysrepo **0.7.7** version.
When I start sysyrepod, sysrepo-plugind and netopeer2-server I get this error in **daemon.log** file:

[ERR] File "/etc/keystored/keys/ssh_host_rsa_key.pem.pub" could not be accessed (No such file or directory)."

After that I removed removed **libietf-kesystore.so** file.
Reboot was done and I had this error inside daemon.log:
[ERR] libyang error: Leafref "/ietf-keystore:keystore/ietf-keystore:private-keys/ietf-keystore:private-key/ietf-keystore:name" of value "ssh_host_rsa_key" points to a non-existing leaf.
Also I was not able to connect to netopeer2-server using netopeer2-cli.

After that I uninstalled **ietf-kesystore** module.
To be able to uninstall iet-kesystore module I had to uninstall also:
**ietf-ssh-server**
**ietf-netconf-server**
**ietf-tls-server.**
After uninstalling those modules I did reboot.
sysrepod, sysrepo-plugind and netopeer2-server where running.
Now in daemon.log I had this errors:

 sysrepod[1303]: [ERR] libyang error: Failed to find matching hash for a child of "system".
 sysrepod[1303]: [ERR] Parsing data tree from file /etc/sysrepo/data/ietf-system.running failed: Failed to find matching hash for a child of "s$
 sysrepod[1303]: [ERR] Getting data tree for ietf-system failed.
 sysrepod[1303]: [ERR] Getting data tree failed (4) for xpath '/ietf-system:*//.'
 sysrepod[1303]: [ERR] rp_dt_prepare_data failed
 sysrepod[1303]: [ERR] Get items failed for '/ietf-system:*//.', session id=2074087404.
 netopeer2-server[1402]: np2srv_sr_get_items_iter failed (sysrepo: Sysrepo-internal error).

and get request on cli returns:
> get
ERROR
        type:     application
        tag:      operation-failed
        severity: error
        message:  np2srv_sr_get_items_iter failed (sysrepo: Sysrepo-internal error).

After that I uninstalled **ietf-system** module and did reboot. . In daemon.log I did not have the above errors and I was able to connect to netopeer2-server using cli.
Everything worked fine, get, get-config and edit-config requests and there was no more error inside daemon.log file.

Can you please explain the purpose of ietf-keystore module and its .so file?
Also can removing libietf-keystore.so file and uninstalling the above modules  
lead to unexpected behavior of sysrepo?

Note: For now I have to use sysrepo with 0.7.7 version.

Thanks in advance.
Best regards

**Comment by michalvasko** [comment]
Hi,
I am a bit confused as to what are you talking about. I do not think there is any `libietf-keystore.so` module, `keystored` should install `keystored.so`. Basically, you uninstalled the modules step-by-step instead of simply clearing the whole repository and installing only stuff you actually want. That way there could be some leftover things that could cause some issues but it is hard to know. Also, you have originally not installed `keystored` properly because otherwise you would not get the first error but I have no idea whether you want server configuration or not, so you maybe do not want to install it at all. Sorry for what is perhaps a confusing reply but so is your issue.

Regards,
Michal
