### ISSUE TITLE
Q: oper data subscription callback repeated calls?

### ISSUE THREAD

**Issue by iljatab** [sysrepo/sysrepo#1786]
$ sysrepoctl --version
sysrepoctl - sysrepo YANG schema manipulation tool, compiled with libsysrepo v1.3.62 (SO v4.3.11)

$ yanglint --version
yanglint SO 1.6.0

$ netopeer2-server -V
netopeer2-server 1.1.1

Hello Michal,

We have a question regarding oper data provider API.
The below discussion is based on openconfig-interfaces.yang, however it should not matter, IMHO.

Our application subscribes to:
```
sr_oper_get_items_subscribe(sess,"/openconfig-interfaces:interfaces/interface/state", ... );
```
We use netopeer2-cli and run:
> get --filter-xpath /openconfig-interfaces:interfaces/interface/state

It turns out that our callback is called as many times as the number of interfaces we have.
However each call is absolutely indistinguishable from each other.
All calls are done with the same path and request_xpath arguments:
```
path == /openconfig-interfaces:interfaces/interface/state
request_xpath == /openconfig-interfaces:interfaces/interface/state
```
So my question is: what application logic is expected in that case?
The application could of course supply oper data for _all_ interfaces during the _first_ call.
But what to do during next calls? Ignore those because they are useless? How do the application is supposed to track it?

This is different from sysrepo 0.7.x.
The callback was called also for each interface but xpath argument used to contain the keys (interface name) like:
```
xpath == /openconfig-interfaces:interfaces/interface[name='eth-N']/state
orig_xpath == /openconfig-interfaces:interfaces/interface/state
```
This schema was understandable.

Could you please clarify?

Thanks in advance!

Ilja.

**Comment by michalvasko** [comment]
Hi Ilja,
> The application could of course supply oper data for all interfaces during the first call.
But what to do during next calls? Ignore those because they are useless? How do the application is supposed to track it?

Unfortunately, you cannot supply oper data for all interfaces in one call because `interface` is a configuration node (my guess) and so you must provide `state` descendant for every `interface` parent. More on this later.

> However each call is absolutely indistinguishable from each other.
All calls are done with the same path and request_xpath arguments:

Yeah, the string arguments are the same because that is how they are described. `path` is now always the path used when subscribing. Its use is mainly to distinguish between different calls in case you use a single callback for several operational subscriptions, not sure if there is any other. And, finally to the point, the calls can be distinguished from each other. If you just call `lyd_path()` on `*parent`, you will get
```
/openconfig-interfaces:interfaces/interface[name='eth-N']
```
which is basically the same as in the old *sysrepo*. This is one of the main differences, the new *sysrepo* uses *libyang* trees instead of `sr_val_t` structures. Except, while in most cases it is optional, for operational data callback it is mandatory. What you can also do is simply get the leaf value
```C
((struct lyd_node_leaf_list *)(*parent)->child)->value_str // "eth-N"
```
and you do not have to parse any XPath. Of course, there is a lot of other information in the data tree but that is for you to discover by using some *libyang* functions or simply accessing the attributes. I have mentioned the most common usage.

Now, these new operational subscriptions are extremely versatile and allow many solutions to a single problem. For example, depending mostly on whether you have a lot of interfaces or not, you can also subscribe to `/openconfig-interfaces:interfaces/interface`. By that you are saying that you will provide all data (whether configuration or state) of all `interface` instances with all their children. The main advantage is that your callback will be called only once and you can gather all the required information from the system (about the interfaces) at once. The problem would be that if there were also any configuration data as children of `interface` (I assume there are), these are effectively replaced by your subscription. To keep them, you could either simply get them from the `running` datastore in the callback and append them to `*parent` again or, in case you can read this information from the system as well, create all the provided nodes together not distinguishing between configuration and state data. I think no optimal solution exists for this YANG module.

Generally, these subscriptions were optimized for [NMDA](https://tools.ietf.org/html/rfc8342) and modules that were designed with compliance to it even though there is probably not many such modules yet. For those other cases the subscriptions can work just like in the old *sysrepo*, which I hope I have explained clearly.

Regards,
Michal

**Comment by iljatab** [comment]
Thanks for clarification!

However it looks like we still missing some bits.

Using your advise gives us:
```
path == /openconfig-interfaces:interfaces/interface/state
request_xpath == /openconfig-interfaces:interfaces/interface/state
lyd_path(*parent) == /openconfig-interfaces:interfaces/interface[name='eth-N']
```
Indeed, lyd_path(*parent) contains the keys, however it misses the trailing "/state" part.

Could you maybe clarify how exactly the lyd_path(*parent) is different from path argument  (except for keys)?
I'd like to have some general understanding - we have tens of YANG models with lot of hierarchical objects. Figuring out each case by trial and fail would be too complicated.

Soy if this is dumb question but I couldn't find it in the docs :-(

Ilja.

**Comment by michalvasko** [comment]
Hi Ilja,
I am not really sure what to add to the [function documentation](http://www.sysrepo.org/static/doc/html/group__oper__subs__api.html#ga6baa2bd56bd6cebb605c547d80863e78). All the information is there, I would say, but it does assume you have basic understanding of *libyang* data trees and also NMDA.

> Could you maybe clarify how exactly the lyd_path(*parent) is different from path argument (except for keys)?

I am sorry, but this really is a bad question. As mentioned in the docs, `path` is simply the path you have used in `sr_oper_get_items_subscribe()`. As long as you subscribe your callback only one, it will __never__ change and you can almost certainly ignore it. Now, the point here is the meaning of the `parent` parameter, it is by far the most important one. What you need to understand is that it represent a *libyang* data tree. While not being anything complicated, you must know how to modify and append data to these trees because that is how you return your operational data from the callback now.

> Indeed, lyd_path(*parent) contains the keys, however it misses the trailing "/state" part.

Again, from the docs `Any parent children (selected by path) are removed and should be provided by the callback instead, if they exist`. Meaning `state` node was removed because that is the node you subscribed to.

The following is a brief explanation of your specific data tree, which you should know from *libyang*. Quoting the docs, `parent - Pointer to an existing parent of the requested nodes`. So in your case, it is a subtree of nodes
```
  interfaces
      /\
(pointer child)
      \/
  interface   < (*parent)
      /\
(pointer child)
      \/
     name < ((struct lyd_node_leaf_list *)name)->value_str == 'eth-n'
```
The confusing thing in this case may be that parent does not point to the last node. This is the only exception because the last node is a list instance, which always has its keys as children. What you are now supposed to do is append all the operational data you subscribed to providing. You probably want to create the `state` container and add some other descendants (children) to it. There are several ways this can be done but the simplest one is using `lyd_new_path()` from *libyang*. I will leave the rest for you to figure out, you should know what you are doing. You can take a look at the [oven](https://github.com/sysrepo/sysrepo/blob/master/examples/plugin/oven.c#L130) example plugin callback, for instance.

Regards,
Michal

**Comment by iljatab** [comment]
Ok, I likely understand - "/state" is not there because it is container and does not exist until populated by oper data.
Thank for explaining!

**Comment by michalvasko** [comment]
Hi,
not really, `state` does not exist because it is the node you subscribed to (`/openconfig-interfaces:interfaces/interface/state`) as stated in docs
```
Any parent children (selected by path) are removed and should be provided by the callback instead, if they exist.
```

Regards,
Michal
