### ISSUE TITLE
NACM empty configuration import causes abort to subscriber

### ISSUE THREAD

**Issue by sriramkandukuri** [sysrepo/sysrepo#1795]
Hi,

I am importing multi module xml file to sysrepo. It doesnt contain any NACM data which means deletion of whole module.

In addition to netopeer2-server there is one more subscriber for whole NACM module with priority-1(netopeer uses priotiry - 0)

This configuration causes abort to second subscriber. If deletion is not accepted it should fail while importing, but should not cause any abort to other subscribers.

Thanks & Regards,
Sriram.K

**Comment by michalvasko** [comment]
Hi Sriram,
it all depends on the exact `edit-config`. The idea is that if a callback was called with `SR_EV_CHANGE` and the commit fails, then it should be called with `SR_EV_ABORT`. If it was not yet called, it should not get the abort. In case this is not happening please add some information such as what callbacks for which modules are called and which one fails so that I can reproduce it.

Regards,
Michal
