### ISSUE TITLE
EV_DONE not waiting till subscriber replies

### ISSUE THREAD

**Issue by sriramkandukuri** [sysrepo/sysrepo#1796]
Hi Michal,

While configuring multiple modules using single file. Sysrepocfg sending EV_DONE without waiting for the subscriber reply. But subscriber thread collects all the changes in EV_CHANGE and applies them in EV_DONE.

If sysrepocfg/client not waits till subscriber completes the EV_DONE that makes user to think the configuration is completed.

Is it expected behavior or is there any other way to inform user that configuration is really completed after processing all EV_DONE events.

Thanks & Regards,
Sriram.K

**Comment by michalvasko** [comment]
Hi Sriram,
yes, this is intentional. The idea is to finish the commit as soon as possible, no reason not to. And since you can refuse the changes only on `SR_EV_CHANGE`, after they all finish successfully, the commit will (eventually) succeed. That is why the subscriber does not have to wait for `SR_EV_DONE` and can already return the final result.

Regards,
Michal

**Comment by sriramkandukuri** [comment]
Hi Michal,

Thank you for the explanation.

Is there a way to know whether a CHANGE event is the last one in current transaction, So that I can apply all collective changes to system in that one, as EV_DONE is not waiting for subscriber's reply.

Or any other approach to know whether the change is final one.

Thanks & Regards,
Sriram.K

**Comment by michalvasko** [comment]
Hi Sriram,
unfortunately, there is no such mechanism. However, the use-case of the originator wanting to know when the whole commit is finished seems valid to me so, I suppose, a flag could be added that will cause the originator to wait until also DONE events are handled.

Regards,
Michal

**Comment by sriramkandukuri** [comment]
Hi Michal, 

Thank you, It helps a lot.

Thanks & Regards,
Sriram.K

**Comment by michalvasko** [comment]
Hi,
it should now be supported, new parameter for `sr_apply_changes()` was added, among other API functions. I have not increased the SO version even though this is a non-backwards compatible change because I have increased in a few days ago. However, this is an exception and the API will now stay the way it is for now.

Regards,
Michal

**Comment by sriramkandukuri** [comment]
Hi Michal,

Thank you for the changes,
Will test and update.

Is it possible to make these two timeouts EDIT and DONE compile time configurable in Netopeer2.
As all the references are hard coded to '0'

Thanks & Regards,
Sriram.K

**Comment by michalvasko** [comment]
Hi,
okay, added. But note that it is not a specific timeout, it is just a flag and if it is set, the same timeout for all events is used.

Regards,
Michal
