### ISSUE TITLE
Question on Operational datastore

### ISSUE THREAD

**Issue by iGovindY** [sysrepo/sysrepo#1797]
Three queries:
1. When a client does a get RPC on a model
config data (i.e: config true) will be returned from `running `datastore, and sysrepo will take config false from operational datastore.
Now if an application has subscribed to provide operational data,
sysrepo will call the callback and application will provide the data:
    Here two cases: 
    - only state data to be provided by callback.
    - both state and config data to be provided by callback.

2. As per my understanding,
Old sysrepo used to call `sr_dp_get_items_cb` for every node (container/ list) and the application had to provide all leaves and keys for a node.
But new sysrepo API (`sr_oper_get_items_cb`) only gets a call once for a subscription for one get RPC.
It becomes the responsibility of the application to expand the requested XPath to its child nodes, recursively.
Is there a way to do what we were doing in old sysrepo.?
If not, how complex will it be to find out all config false data nodes under requested XPath to provide data? (As most of the cases, the application won't be interested in providing config true data.)

3. Is my below assumption correct?
session context passed to `sr_oper_get_items_cb` is not dependent on datastore. this API is always for `Operational `Datastore.

Thanks,
Govind.

**Comment by michalvasko** [comment]
Hi Govind,
1. You are right about this. Because of this confusion a new operation `get-data` was defined (which is supported by *netopeer2*) but, unfortunately, the old `get` will remain supported as well.
2. Firstly, I never thought anyone could think this new mechanism to be more complicated and all the callbacks I have seen and written were always much more simple than in the old *sysrepo*. Anyway, in the callback you are not meant to do anything else but return the subtree of the data you subscribed to. Generally, there are optimizations that try not to perform any unnecessary work (call redundant callbacks) so you should not worry about this in the callback itself. For example, if your subscription provides only `config true` data, it should not be called on a `get` RPC at all. The only problem is when you subscribe to both `config true` and `config false` nodes in one subscription. In that case you may want to, in case only `config false` data are needed such as for `get`, not return the `config true` nodes. However, I do not think this makes sense or there are any relevant use-cases. Connected to your question whether you can provide the data as in the old *sysrepo*, you actually can. There are quite many options in this respect and the final functionality depends quite a lot on your subscriptions. For instance, these subscriptions can overlap (you can get the old *sysrepo* functionality this way, by subscribing to all the subtrees the old *sysrepo* would call your callback) and you can even use XPath predicates. The exact rules should be described [here](http://www.sysrepo.org/static/doc/html/subs.html#oper_subs) and in the functions API [here](http://www.sysrepo.org/static/doc/html/group__oper__subs__api.html#ga6baa2bd56bd6cebb605c547d80863e78). If you have any more specific questions, just ask. I do not feel like explaining it all again.
3. It is correct. You know which functions depend on the session datastore by them having either *DS-specific* or [not DS-specific](http://www.sysrepo.org/static/doc/html/group__oper__subs__api.html#ga2915a5b53a6495ca246c44f7aae58ed5) in the `session` parameter documentation.

Regards,
Michal

**Comment by iGovindY** [comment]
Hi Michal,
Thanks for the reply.

For now, looks like the documentation link is not working, giving 404 error. http://www.sysrepo.org/static/doc/html/index.html.

Will come back if I have further question.

**Comment by iGovindY** [comment]
Hi @michalvasko 

I am trying to create an entry from application side on config false list for oven3 model (added below.)
#### Set of config false node on operational DS.
**I have changed sr_set_item_example.c file a bit to take Datastore as input.**
like in below **3** is for operational.
### Steps followed:

**1.**
```
# ./examples/sr_set_item_example 3 "/oven3:oven/X/Y[Yc='5']/d" 30
Application will set "/oven3:oven/X/Y[Yc='5']/d" to "30" in 3 datastore
[INF]: Scheduled changes not applied because of other existing connections.
[INF]: Session 43 (user "root") created.

Passed
```
**2.** 
```
# ./examples/sr_get_items_example "/oven3:oven/X/Y[Yc='5']/d" operational
Application will get "/oven3:oven/X/Y[Yc='5']/d" from "operational" datastore.

[INF]: Scheduled changes not applied because of other existing connections.
[INF]: Session 46 (user "root") created.
[INF]: Published event "operational" with ID 2.
[INF]: Event "operational" with ID 2 succeeded.
```
**3.**
```
> get --filter-xpath /oven3:oven/*
DATA
```

#### Set of config true node on running DS
**1.**
```
./examples/sr_set_item_example 1 "/oven3:oven/A/B[Bc='5']/d" 60
Application will set "/oven3:oven/A/B[Bc='5']/d" to "60" in 1 datastore
[INF]: Scheduled changes not applied because of other existing connections.
[INF]: Session 66 (user "root") created.
[INF]: There are no subscribers for changes of the module "oven3" in running DS.

Passed
```

**2.**
```
# ./examples/sr_get_items_example "/oven3:oven/A/B[Bc='5']/d"
Application will get "/oven3:oven/A/B[Bc='5']/d" from "running" datastore.

[INF]: Scheduled changes not applied because of other existing connections.
[INF]: Session 68 (user "root") created.
/oven3:oven/A/B[Bc='5']/d = 60
[INF]: Ext SHM was defragmented and 4392 B were saved.
```
**3.**
```
> get --filter-xpath /oven3:oven/*
DATA
<oven xmlns="urn:sysrepo:oven3">
  <A>
    <B>
      <Bc>5</Bc>
      <d>60</d>
    </B>
  </A>
</oven>
```
## Question
Even after a sucess set on operational DB get doesn't return value neither with client get RPC or sr_get_items_example application.
where as same on running for config true node works fine
as seen above.

# Files

#### changed model  oven3.yang
```
module oven3 {
  namespace "urn:sysrepo:oven3";
  prefix ov;

  revision 2022-05-21 {
    description
      "Initial revision.";
  }

  typedef oven-temperature {
    type uint8 {
      range "0..250";
    }
    description
      "Temperature range that is accepted by the oven.";
  }

  container oven {
    description
      "Configuration container of the oven.";
    leaf turned-on {
      type boolean;
      default "false";
      description
        "Main switch determining whether the oven is on or off.";
    }

    leaf temperature {
      type oven-temperature;
      default "0";
      description
        "Slider for configuring the desired temperature.";
    }

    container A {
      list B {
        key "Bc";
        leaf Bc {
          type oven-temperature;
        }

        leaf d {
          type oven-temperature;
          default "0";
        }

        leaf e {
          type oven-temperature;
        }

        leaf f {
          type oven-temperature;
          config false;
        }

        container C {
          config false;
          leaf Cb {
            type oven-temperature;
            default "0";
          }

          leaf eb {
            type oven-temperature;
          }

          leaf fb {
            type oven-temperature;
            config false;
          }
        }
      }
    }

    container X {
      list Y {
        key "Yc";
        config false;
        leaf Yc {
          type oven-temperature;
        }

        leaf d {
          type oven-temperature;
          default "0";
        }

        leaf e {
          type oven-temperature;
        }

        leaf f {
          type oven-temperature;
          config false;
        }

        container Z {
          leaf Zb {
            type oven-temperature;
            default "0";
          }

          leaf eb {
            type oven-temperature;
          }

          leaf fb {
            type oven-temperature;
          }
        }
      }
    }
  }
}

```
#### Changed _sr_set_item_example.c_ for specifying operational store.
```
#define _GNU_SOURCE

#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <string.h>
#include <signal.h>
#include <inttypes.h>

#include "sysrepo.h"

int
main(int argc, char **argv)
{
    sr_conn_ctx_t *connection = NULL;
    sr_session_ctx_t *session = NULL;
    int rc = SR_ERR_OK;
    const char *xpath, *value;
        int dataStore = 1;
    if (argc != 4) {
        printf("%s <datastore-> 0:startup, 1:running, 2: candidate, 3: operational> <xpath-to-set> <value-to-set>\n", argv[0]);
        return EXIT_FAILURE;
    }
    dataStore = atoi(argv[1]);
    xpath = argv[2];
    value = argv[3];

    printf("Application will set \"%s\" to \"%s\" in %d datastore\n", xpath, value, dataStore);

    /* turn logging on */
    sr_log_stderr(SR_LL_DBG);

    /* connect to sysrepo */
    rc = sr_connect(0, &connection);
    if (rc != SR_ERR_OK) {
        goto cleanup;
    }

    /* start session */
    rc = sr_session_start(connection, dataStore, &session);
    if (rc != SR_ERR_OK) {
        goto cleanup;
    }

    /* set the value */
    rc = sr_set_item_str(session, xpath, value, NULL, 0);
    if (rc != SR_ERR_OK) {
        goto cleanup;
    }

    /* apply the change */
    rc = sr_apply_changes(session, 0);
    if (rc != SR_ERR_OK) {
        goto cleanup;
    }

cleanup:
    sr_disconnect(connection);
    rc ? printf("\nFailed\n") : printf("\nPassed\n");
    return rc ? EXIT_FAILURE : EXIT_SUCCESS;
}

```

**Comment by michalvasko** [comment]
Hi,
this is a feature mentioned [here](https://github.com/sysrepo/sysrepo/blob/master/doc/main.dox#L132) (sorry, the online docs are not available currently).

Regards,
Michal
