### ISSUE TITLE
adding multiple sr_oper_get_items_cb,  for one module, overides values with default values 

### ISSUE THREAD

**Issue by berstrob** [sysrepo/sysrepo#1799]
With devel from last week. 
If more than one sr_oper_get_items_cb are called, the defaults from the last called callback will override manual set values. 
Tested with openconfig-system.yang:  callbacks for  
1: openconfig-system:system/ntp/state 
2: openconfig-system:system/ntp/servers/servers[addresse='google.com']/state 

calling sysrepocfg -X -x "openconfig-system:sytem/ntp" -d operational 
calls both and returns the default:  /ntp/state/enabeled false  
(and the correct server stuff + defaults for that)

calling just sysrepocfg -X -x "openconfig-system:sytem/ntp/state" -d operational  
returns the set  /ntp/state/enabeled true. 

Removing the part in modinfo.c the commit 5877c8cfebf755316749e6d26299002c2d99c4f3 seems to fix it (and workes for my use case, but does remove all other "empty" defaults as well), maybe add the default values back through a validate later.

**Comment by michalvasko** [comment]
Hi,
you are right about the problem and even the fix. I have removed the flag before because otherwise the default values were missing instead of explicitly set ones. Your suggestion to add the default values later is a valid suggestion, but unfortunately not a correct one. There may be a nested subscription, whose callback will not be called unless its (default) parent exists, so default values must be added after every callback. It is also more efficient that way.

So, I have committed the only possible fix and that was to add support for these use-cases into `lyd_merge()` with `LYD_OPT_EXPLICIT`. Until now there was an optimization that caused this problem because it expected the merged trees to both have all the default values. Please update *libyang* and *sysrepo*, it should work correctly now and I have also added a test for your use-case.

Regards,
Michal

**Comment by berstrob** [comment]
Thank you for the quick response and fix.
