### ISSUE TITLE
Replacing a subtree with `sr_edit_batch`

### ISSUE THREAD

**Issue by pieterlexis** [sysrepo/sysrepo#1809]
I would like to use `sr_edit_batch` to replace a subtree. Let's see there is a subtree at `/module:foo/tree[name='bar']/subtree` already in the datastore (where `tree` is a list and `subtree` another list) and I'd like to replace the whole `subtree` element.

I have prepared the JSON I want there (and use `ly_parse_mem`) e.g.

```json
{
  "module:foo": {
    "tree": [
      {
        "name": "bar",
        "subtree": {
          "a": [
            {"b": ["c"]}
          ]
        }
      }
    ]
  }
}
```

* When I use the `"merge"` strategy for `sr_edit_batch`, any existing values for "b" are kept.
* When I use the `"replace"` strategy, I get an error because nodes in `tree` that are of no concern to me don't exist
* When I fetch first, remove `subtree` from the json, do an `edit_batch` with `"replace"`, fill `subtree` and then do an `edit_batch`, sysrepo tells me that there are already changes pending in the session.

So what is the easiest (and best) way to replace a subtree when setting data?

**Comment by pieterlexis** [comment]
My current workaround is calling `sr_delete_path` with `/module:foo/tree[name='bar']`, then applying that change and then setting the data, but this can lead to a small race condition. However it looks like I can *either* use `sr_delete_item` and `sr_set_item*` to make changes in the session *or* use `sr_edit_batch` that'll require me to use the `"replace"` strategy, meaning I need to get the whole config tree and manipulate that

**Comment by michalvasko** [comment]
Hi,
> When I fetch first, remove subtree from the json, do an edit_batch with "replace", fill subtree and then do an edit_batch, sysrepo tells me that there are already changes pending in the session.

The reason for this is that if you already have an edit and you want to add another one, they would need to be merged. That is not trivial and initially *sysrepo* did not have functions for this. Now it does and I think it could be allowed but, at the same time, I do not really see any use-case for this because you can always use `sr_edit_batch()` to set whatever edit you want.

> So what is the easiest (and best) way to replace a subtree when setting data?

The right solution for this case would be to use `sr_edit_batch()` with this JSON
```json
{
  "module:foo": {
    "tree": [
      {
        "name": "bar",
        "subtree": {
          "@": {
            "ietf-netconf:operation": "replace"
          },
          "a": [
            {"b": ["c"]}
          ]
        }
      }
    ]
  }
}
```
It is probably obvious now, but to create such an edit requires a fairly good knowledge of 2 RFCs. The NETCONF RFC is referenced directly from the [docs](https://netopeer.liberouter.org/doc/sysrepo/master/group__edit__data__api.html#ga6661900582c6948622efb54a15ef8fa7). If you read it all, you will learn that you can **add a specific operation to each node**, in addition to the default operation. So far so good, not too difficult in XML (NETCONF). However, you have used JSON, which does not natively support attributes. But the metadata extension is available in all the supported formats of YANG data, so there was a separate [specification](https://tools.ietf.org/html/rfc7952#section-5.2) created. *sysrepo*/*libyang* just put all this together and basically an `edit-config` in JSON is thus supported even though it can never come by NETCONF itself (at least for now).

Back to the issue, it is probably worth noting that you could create a similar edit by
```C
sr_replace_item("/module:foo/tree[name='bar']/subtree");
sr_set_item_str("/module:foo/tree[name='bar']/subtree/a[1]/b", "c");
```
if there was a function `sr_replace_item()` in the API. The implementation would be trivial but all these edit functions were only taken from the old *sysrepo*, which did not support replacing. Would you make use of such a function?

Regards,
Michal

**Comment by pieterlexis** [comment]
> Back to the issue, it is probably worth noting that you could create a similar edit by
>
> ```
> sr_replace_item("/module:foo/tree[name='bar']/subtree");
> sr_set_item_str("/module:foo/tree[name='bar']/subtree/a[1]/b", "c");
> ```
>
> if there was a function sr_replace_item() in the API. The implementation would be trivial but all these edit functions were only taken from the old sysrepo, which did not support replacing. Would you make use of such a function?

This function would clear out the whole container/list at the final element of the xpath so it can be filled again? That would (in my usecase) come in _very_ handy. I can easily switch from `sr_edit_batch` to multiple calls to `sr_set_item_str`. That'll make everything better in the end, as there's no conversions to json anymore :)

**Comment by pieterlexis** [comment]
I was just wonder if this could be accomplished by `sr_delete_item` with `"/module:foo/tree[name='bar']/subtree//*"` and then using `sr_set_item_str`?

**Comment by michalvasko** [comment]
HI,
yeah, it works because internally it is all handled properly. Meaning if you first delete a node and then create it (with any children), you are effectively, using NETCONF `edit-config` operations, replacing the node. So, I guess you can just use that and no new function is needed. Just a note, internally every edit creates (or appends to) a `edit-config` tree, which you can also directly provide using `sr_edit_batch()`. The edit functions are only a simpler and easier-to-use API (and provide backwards compatibility).

Regards,
Michal

**Comment by pieterlexis** [comment]
>  The edit functions are only a simpler and easier-to-use API (and provide backwards compatibility).

They are indeed easier, it also prevents me (as an application developer) to not think about the intricacies of the NETCONF `edit-config` messages. :)

**Comment by michalvasko** [comment]
Maybe so, but it is good to be aware of them especially when performing more complex edits such as yours. Because, like I said, it is always a NETCONF `edit-config` that is being applied internally.

Regards,
Michal
