### ISSUE TITLE
Question about rpc_tree in  cpp_rpc_example.

### ISSUE THREAD

**Issue by MickAbson** [sysrepo/sysrepo#1812]
In cpp_rpc_example.cpp, there is an example of the callback function of rpc_tree, but this example only shows how to fill the output data, not how to get the input data in the client RPC from the input. I researched it all day and didn't solve the problem.
Can you please give me a suggestion what can I do to fix the problem?
Thanks in advance.
Best regards
Fizz

**Comment by michalvasko** [comment]
Hi Fizz,
I have idea what the problem is, you will have to explain more because the input is being printed both from a `val` [callback](https://github.com/sysrepo/sysrepo/blob/master/bindings/cpp/examples/cpp_rpc_example.cpp#L112) and from a `tree` [callback](https://github.com/sysrepo/sysrepo/blob/master/bindings/cpp/examples/cpp_rpc_example.cpp#L131).

Regards,
Michal

**Comment by MickAbson** [comment]
![W$76E}OI)08N8~(G3$_U ON](https://user-images.githubusercontent.com/49752884/74231099-b62d9200-4d00-11ea-939d-54a46f93eacf.png)

This diagram is taken from the sysrepo C++ interface sample file cpp_rpc_example.cpp, but it only shows populating data from the output parameter in the case of rpc_tree, not how to retrieve data from the input parameter.I've been working on this for a long time and haven't found a member function that gets the element in the S_Data_Node class that looks like S_Val val(size_t n) in the S_Vals class.

**Comment by michalvasko** [comment]
Hi Fizz,
it seems you have misunderstood something. In the [docs](https://netopeer.liberouter.org/doc/sysrepo/master/index.html#features) it is mentioned that you either work with `sr_val_t` (`S_Val` in C++) or *libyang* data tree (`S_Data_Node` in C++) so you must choose one. If you want to work with structures, use the first `rpc` callback and subscribe with `rpc_subscribe` method. If you want *libyang* structures, use `rpc_tree` callback and subscribe with `rpc_subscribe_tree`. Simple enough, the example shows usage of both. Are you confused because both callbacks are defined in a single object? No special reason for that, just that creating 2 objects is redundant.

Regards,
Michal

**Comment by MickAbson** [comment]
Hi Michal
My problem is how to get data from libyang data tree (S_Data_Node in C++), the S_Data_Node class doesn't seem to have any members that can get data, like I can do this 
int32_t data1 = input->val(0)->data()->get_int32;)
to get the first data from S_Val.

**Comment by michalvasko** [comment]
What are you talking about? Even the namespace is *libyang* so if you are looking for the functions in *sysrepo*, then you are correct, they are not there. Try [libyang](https://github.com/CESNET/libyang/blob/master/swig/cpp/src/Tree_Data.hpp#L97) instead. But note that that API is much larger and so a bit more difficult to use. For example, you will need to cast `Data_Node` to `Data_Node_Leaf_List` to get values from leaves/leaf-lists.

Regards,
Michal

**Comment by MickAbson** [comment]
You're right, this API is more complicated...And I will try to  cast Data_Node to Data_Node_Leaf_List to get values from leaves/leaf-lists.
But can you tell me where I can learn more about that API.
Thanks in advance.
Best regards
Fizz

**Comment by michalvasko** [comment]
Hi,
well, it is again a good idea to go through the examples, which should show you the basics (including the casting). Then, you should probably just go briefly through the API and see what functions are available. Generally, you should be able to do anything sensible with YANG data, some operations even have several approaches that will all get you the result (such as creating data).

Regards,
Michal
