### ISSUE TITLE
sr_apply_changes 

### ISSUE THREAD

**Issue by rosy8** [sysrepo/sysrepo#1813]
Hi Michal,

In the new sysrepo,  I just tried to call sr_apply_changes assuming its equivalent to sr_commit and was expecting the registered callback to get hit for events (SR_EV_CHANGE/SR_EV_DONE) etc.. 

But to my surprise, the callback did not get invoked.  Not sure if I have missed something (will check the same again).

However, in the mean time just wanted to confirm that "sr_apply_changes" is equivalent to "sr_commit". Right?
And once it's called it should be taking care of copying the CANDIDATE DB data into RUNNING_DB and we should get the SR_EV_CHANGE/SR_EV_DONE notification (Based on the module subscription flag).

Thank you in advance.

Regards,
Rosy

**Comment by michalvasko** [comment]
Hi Rosy,
the reason will probably be that it is not totally equivalent with the functionality of `sr_commit()` in the old *sysrepo* but I believe the change to be for the better. You see, `sr_commit()` shared the functionality of NETCONF `<commit>` and simple applying changes for other datastores than `candidate`. In the new *sysrepo* it is simple, `sr_apply_changes()` only applies prepared changes for any datastore. If you want to do NETCONF `<commit>`, you should do `sr_copy_config()` from `candidate` to `running`.

Regards,
Michal

**Comment by rosy8** [comment]
Hi Michal,

Thank you for responding.
So by this sr_apply_changes, it means we only have applied the changes on the datastore and it does only yang type validation (irrespective of on which datastore the data has been applied) ?

And for the registered event to get called we need to call sr_copy_config ?

What if I have already applied the changes directly on the RUNNING_DB Or we cannot do this ?


Regards,
Rosy

**Comment by michalvasko** [comment]
Hi Rosy,
okay, it seems it is still not clear so I will just explain how ti works in the new *sysrepo*, please do not assume anything I do not mention.

You first prepare modifications on a datastore. Then they are stored only in your session and are not visible for other sessions, no callbacks are called. But when you work with data using this session, they are presented with the prepared changes (getting/validating/...). You can then call `sr_apply_changes()` to apply your prepared changes. That means they are made available for all the sessions and any data change callbacks are called. This is true for __ALL__ the datastores. This has an obvious consequence (which may differ from the old *sysrepo*) that you can edit and subscribe to changes for all the datastores. You can use `sr_copy_config()` to copy data from one datastore to another without regard to any prepared changes that you may have made in the session.

That is all, the complete behaviour should now be clear. But to answer your specific question, `sr_validate()` just takes your prepared changes and validates them being applied on the current datastore content, no callbacks called. Also note that if you are performing some additional validation in your callbacks and you want to make sure your prepared changes are valid both with respect to YANG restrictions and to your additional requirements, this is what you should do. Firstly, you need to register your callbacks for `candidate` datastore changes. Then, you should prepare your changes in an application and call `sr_validate()`. This will validate the YANG restrictions. Finally, you should apply these changes and then even your callback will be called and, in effect, finish the validation. Just a last note, by calling `sr_apply_changes()` on `candidate`, it is not validated because this datastore is allowed to be invalid, hence the need to call `sr_validate()` manually.

Regards,
Michal

**Comment by rosy8** [comment]
Thank you, Michal, for the detailed explanation.

Just doing " sr_set_item" also does the Yang validation for that session right?

Regards,
Rosy

**Comment by michalvasko** [comment]
No, any edit function simply prepares the change. If you want to validate it, you must call `sr_validate()` afterwards. This is the same for all datastores.

Regards,
Michal

**Comment by rosy8** [comment]
Hi Michal,

When I set a wrong value then we do get the error "[ERR]: Invalid datastore edit.".
So is not this one level of yang validation as its validating against the yang node type ?

Or according to you it just trying to set/create the value of a  node  (leaf, list, ..etc) So we don't consider it as validation.

Sorry, I may be asking a very basic question. But would like to have clarity on this.

Thank you in advance.

Regards,
Rosy

**Comment by michalvasko** [comment]
Hi Rosy,
it is fine and this is a sensible question. The point here is that all the prepared changes I was mentioning before are actually internally stored as an edit *libyang* data tree and `lyd_new_path()` is used to add to this tree. This function does perform some basic value validation so that is why you are seeing the error. Strictly speaking, *sysrepo* would create the node even with an invalid value if *libyang* allowed it, but it does not.

Regards,
Michal
