### ISSUE TITLE
SR_EV_ABORT not called on failure

### ISSUE THREAD

**Issue by sriramkandukuri** [sysrepo/sysrepo#1819]
Hi,

When returning `SR_ERR_*` from `SR_EV_CHANGE`, it is expected that sysrepo to call callback with `SR_EV_ABORT` but not happening.
Please find below details to reproduce with patch for application changes example

**patch**
```
diff --git a/examples/application_changes_example.c b/examples/application_changes_example.c
index 9ee0f02..3f8f789 100644
--- a/examples/application_changes_example.c
+++ b/examples/application_changes_example.c
@@ -163,13 +163,16 @@ const char *
 ev_to_str(sr_event_t ev)
 {
     switch (ev) {
+    case SR_EV_ENABLED:
+        return "enabled";
     case SR_EV_CHANGE:
         return "change";
     case SR_EV_DONE:
         return "done";
     case SR_EV_ABORT:
-    default:
         return "abort";
+    default:
+        return "default";
     }
 }
 
@@ -207,7 +210,8 @@ module_change_cb(sr_session_ctx_t *session, const char *module_name, const char
 
 cleanup:
     sr_free_change_iter(it);
-    return SR_ERR_OK;
+//    return SR_ERR_OK;
+    return SR_ERR_VALIDATION_FAILED;
 }
 
 static void
```

**a.yang**
```
module a {
    prefix a;
    namespace a;

    container ac{
        leaf al{
            type string;
        }
    }
}
```
**a.xml**
```
<ac xmlns="a">
    <al>sri</al>
</ac>
```

**steps**
```
sysrepoctl -i a.yang
sysrepocfg --import=a.xml -f xml
```

**Output log**
```
[INF]: [140642812417792] [/opt/samba/skandukuri/sriram/new/sysrepo/src/shm_sub.c 1937] Processing "a" "change" event with ID 1 priority 0 (remaining 1 subscribers).


 ========== EVENT change CHANGES: ====================================

CREATED: /a:ac/al = sri

 ========== END OF CHANGES =======================================

 ========== CONFIG HAS CHANGED, CURRENT RUNNING CONFIG: ==========

/a:ac (container)
/a:ac/al = sri
[INF]: [140642812417792] [/opt/samba/skandukuri/sriram/new/sysrepo/src/shm_sub.c 1833] Finished processing "change" event (callback fail) with ID 1 priority 0 (remaining 1 subscribers).
[ERR]: Validation failed
sysrepocfg error: Replace config failed (User callback failed)
```

Thanks & Regards,
Sriram.K

**Comment by michalvasko** [comment]
Hi Sriram,
please read the documentation for [SR_EV_ABORT](https://netopeer.liberouter.org/doc/sysrepo/master/group__change__subs__api.html#ggaf5289764c79d867bab642997c23b355aa6a7bc850ab09aeb7385a0e10f2391d3f). Anyway, what sense does it make to call the failed callback again? Obviously it knows it failed so it can revert whatever changes it made immediately. The idea is that a callback gets `SR_EV_ABORT` **only** if it returned success for `SR_EV_CHANGE`.

Regards,
Michal

**Comment by sriramkandukuri** [comment]
Hi Michal,

This used to work in old sysrepo.

We used to handle any changes done to managed application in ABORT event as the reverse changes come in only ABORT event.

For example if I have converted certain configuration and restarted the application which internally verifies the configuration and throws error. I have to revert the changes to working state. We were doing the same in SR_EV_ABORT in old sysrepo.

SR_EV_ABORT also confirms that configuration is reverted correctly in sysrepo. And then we apply back original config.
Or is there a way to get the reverted changes in SR_EV_CHANGE itself?

Thanks & Regards,
Sriram.K

**Comment by michalvasko** [comment]
Hi Sriram,
I know it worked in the old *sysrepo*, there was a flag for changing the behavior to what is the default one in the new *sysrepo*. I considered the flag to be useless that is why I changed it. You got a point that you cannot get reverted changes in `SR_EV_CHANGE` callback, only in the abort. However, only in the callback itself you know what change exactly failed meaning which changes were successfully applied and which were not, you revert only those that were. If you let the work for `SR_EV_ABORT` event, you may revert changes that were not applied, that is my reasoning for the change. I am now unsure as to what to do, whether anything at all because handling abort with all its possible cases is not trivial no matter what. And just because you have some use-case or it worked somehow in the old *sysrepo* is not enough. I need a general justification.

Regards,
Michal

**Comment by sriramkandukuri** [comment]
Hi Michal,

Thank you for the info.

Thanks & Regards,
Sriram.K
