### ISSUE TITLE
Recent Lock refactoring causing some issue with rpc

### ISSUE THREAD

**Issue by sriramkandukuri** [sysrepo/sysrepo#1837]
Hi,

After upgrading sysrepo to latest devel, observing timeout due to waiting on conditional variable when `sysrepocfg --import` called from rpc callback.
Same rpc was working before recent lock refactoring.

Sysrepocfg process' `sr_connect` is failing.

Thanks & Regards,
Sriram.K

**Comment by michalvasko** [comment]
Hi Sriram,
yep, that would be correct. Note that you have absolutely no reason to execute `sysrepocfg` nor `sysrepoctl` in any application, you can always simply use the corresponding API calls. If you do that, it should work fine because both operations require only READ lock, while creating a new connection needs a WRITE lock.

Regards,
Michal

**Comment by sriramkandukuri** [comment]
Hi Michal,

Actually we have some system status/diagnostics generation scripts in which we use `sysrepocfg` commands to get some parts of that report.

And some scripts get config file from central server and imports them to running config.  

These scripts execute as part of some rpcs.
In old sysrepo and new sysrepo upto this commit everything working fine.

Is there a simpler way to support this functionality?

Thanks & Regards,
Sriram.K

**Comment by michalvasko** [comment]
Hi Sriram,
it worked in the *sysrepo* only by chance, I assure you it was not correct. Do what I said before, just implement the particular `sysrepocfg` command yourself, it is [trivial](https://github.com/sysrepo/sysrepo/blob/master/src/executables/sysrepocfg.c#L278). It is also likely to be much faster as you will not be creating a redundant connection, those are expensive.

Regards,
Michal
