### ISSUE TITLE
How to print value of lyd_node

### ISSUE THREAD

**Issue by Roky7250** [sysrepo/sysrepo#1839]
Hi, on older version of sysrepo, argument of **sr_get_subtree** function was **sr_node_t** structure.
That structure had filed data, so I could print out value of that node.
For example: 
**pom->data.enum_val**

Now function as argument takes **struct lyd_node **.
So my question is how to print value in this case?

Best regards

**Comment by michalvasko** [comment]
Hi,
that is all part of the *libyang* library, which you should learn to work with. To get leaf value do this
```C
struct lyd_node *pom;
if (pom->schema->nodetype == LYS_LEAF) {
    ((struct lyd_node_leaf_list *)pom)->value.enm->name;
}
```
It may be slightly more complex but the reason is that now you have **all** the data/schema information of the node available, not just some specific fields as it was for `sr_node_t`.

Regards,
Michal

**Comment by Roky7250** [comment]
Thank you
