### ISSUE TITLE
[🐛 bug] sysrepocfg -E file.xml

### ISSUE THREAD

**Issue by andrei-pavel** [sysrepo/sysrepo#1840]
Hello,

It seems that if I want to edit in a configuration written in a file with `sysrepocfg -E file.xml`, sysrepo assumes I want to open an editor because I get `sysrepocfg error: Redundant parameters (file.xml)`.

`sysrepocfg -E=file.xml` gives `sysrepocfg error: Exec failed (No such file or directory)`, but the file exists. Same if I give absolute path.

It works however with `sysrepocfg --edit=file.xml`.

Usage would suggest that this is possible:
```
  -E, --edit[=<file-path>/<editor>]
                               Edit configuration data by merging (applying) a configuration (edit) file or
                               by editing the current datastore content using a text editor.
```

A minor issue nevertheless

**Comment by michalvasko** [comment]
Hi,
actually, it should work fine and even the documentation is fine. In other words, I do not think it can be improved and you have encountered a `getopt_long(3)` feature. The problem is only with optional arguments when you must write either `-Efile.xml` or `--edit=file.xml`. Neither `-E file.xml` nor `--edit file.xml` will work because it will be parsed as a separate parameter and not the optional argument. Nothing I can do about that.

Regards,
Michal

**Comment by andrei-pavel** [comment]
But then `-d` and `-m` are not handled via `getopt`? Because I can specify
`-d running -m model`.

**Comment by michalvasko** [comment]
Like I said, the problem happens only for **optional** arguments, both parameters `-d` and `-m` have **mandatory** arguments.

Regards,
Michal

**Comment by andrei-pavel** [comment]
Thank you!
