### ISSUE TITLE
how to send output data by rpc

### ISSUE THREAD

**Issue by xxyy0906** [sysrepo/sysrepo#1841]
hi:
I have a question for you:
It is known that the output value of RPC can only be filled in the callback function,Can sysrepo RPC actively send output data now? Similar to notify active send(sr_event_notif_send),The purpose of this time is to realize an asynchronous data synchronization process in RPC callback function.
Thanks!

**Comment by michalvasko** [comment]
Hi,
I am not completely sure I understand what you are asking but I will try to answer. You are supposed to generate any output only in the RPC/action callback, which is only natural as the output can only be sent as a reply to an input. But, since you mentioned an asynchronous reply, it is possible. What you must do is first return `SR_ERR_CALLBACK_SHELVE` in the RPC/action callback. This way you tell *sysrepo* that you have not processed the RPC/action yet. Then, depending on the [event handling](https://netopeer.liberouter.org/doc/sysrepo/master/index.html#threads) you have chosen, you will most likely need to manually call `sr_process_events()` later, which will again call your RPC/action callback and give you the chance to return your prepared output data. This mechanism allows implementing asynchronous replies.

Regards,
Michal

**Comment by xxyy0906** [comment]
hi:
If you follow your steps in the subscription function return SR_ERR_CALLBACK_SHELVE.Is timeout error displayed on netopper cli?

**Comment by michalvasko** [comment]
Hi,
please read more about it in the [documentation](https://netopeer.liberouter.org/doc/sysrepo/master/subs.html#change_subs) and try to understand it.

Regards,
Michal
