### ISSUE TITLE
Can't use sysrepocfg command in a callback function

### ISSUE THREAD

**Issue by qjwu888** [sysrepo/sysrepo#1843]
Hi Michal:
sysrepo-1.4.2   netopeer2 (devel-server version 1.1.15)
```C
rc = sr_module_change_subscribe(session, "ietf-interfaces", "/ietf-interfaces:interfaces/interface/ietf-ip:ipv4", ipv4_change_cb, *private_ctx,97, SR_SUBSCR_CTX_REUSE, &ctx->subscription);
	
rc = sr_module_change_subscribe(session, "gwtt-dhcpd", NULL, module_dhcp_cb, *private_ctx,
                                    0, SR_SUBSCR_DEFAULT, &dhcp_subscription);
```
In ipv4_change_cb callback,  use `sysrepocfg --edit=/var/dhcp_xml  -f xml -m gwtt-dhcpd` got t.he following error log. Can't use sysrepocfg command in a callback function?
Hope to get your help ,thanks!

```
[INF]: Processing "ietf-interfaces" "change" event with ID 2 priority 100 (remaining 1 subscribers).
[INF]: Finished processing "change" event with ID 2 priority 100 (remaining 0 subscribers).
[INF]: Processing "ietf-interfaces" "change" event with ID 2 priority 99 (remaining 1 subscribers).
[INF]: Finished processing "change" event with ID 2 priority 99 (remaining 0 subscribers).
[INF]: Processing "ietf-interfaces" "change" event with ID 2 priority 98 (remaining 1 subscribers).
[INF]: Finished processing "change" event with ID 2 priority 98 (remaining 0 subscribers).
[INF]: Processing "ietf-interfaces" "change" event with ID 2 priority 97 (remaining 1 subscribers).
[INF]: Published event "notif" with ID 2 priority 0 for 1 subscribers.
[ERR]: Module "gwtt-dhcpd" is locked by session 17 (NC SID 1).
sysrepocfg error: Failed to merge edit data (Requested resource already locked)
[INF]: Finished processing "change" event with ID 2 priority 97 (remaining 0 subscribers).
[INF]: Processing "ietf-interfaces" "done" event with ID 2 priority 100 (remaining 1 subscribers).
[INF]: plugin: Applying changes.
[INF]: Finished processing "done" event with ID 2 priority 100 (remaining 0 subscribers).
[INF]: Processing "ietf-interfaces" "done" event with ID 2 priority 99 (remaining 1 subscribers).
[INF]: Finished processing "done" event with ID 2 priority 99 (remaining 0 subscribers).
[INF]: Processing "ietf-interfaces" "done" event with ID 2 priority 98 (remaining 1 subscribers).
[INF]: Finished processing "done" event with ID 2 priority 98 (remaining 0 subscribers).
[INF]: Processing "ietf-interfaces" "done" event with ID 2 priority 97 (remaining 1 subscribers).
[INF]: Finished processing "done" event with ID 2 priority 97 (remaining 0 subscribers).
```

**Comment by michalvasko** [comment]
Hi,
the error is correct and should be understandable. If you are applying changes for both `ietf-interfaces` and `gwtt-dhcpd` in one edit, it will never work because you are at the same trying to change `gwtt-dhcpd` data, which are already being changed. However, if not, then you can implement this simply by not calling `sysrepocfg`, which you should **never** do in an application. Except for the significant performance hit by executing another process and creating a new connection, you get these synchronization problems because then a different `session` is used that is used for processing the initial change so *sysrepo* will not allow it. You are always supposed to use only API functions in every *sysrepo* application, implementing `sysrepocfg` edit command with a file is [trivial](https://github.com/sysrepo/sysrepo/blob/devel/src/executables/sysrepocfg.c#L360).

Regards,
Michal

**Comment by qjwu888** [comment]
Hi Michal:
Thanks for your reply.
In this case , Only use API ,In ipv4_change_cb callback to write gwtt_dhcp module, ok ?

**Comment by michalvasko** [comment]
Hi,
yes except for the detail I have mentioned that you then cannot change data of `ietf-interfaces` and `gwtt_dhcp` in __a single edit__ because you will still get a deadlock that way.

Regards,
Michal

**Comment by qjwu888** [comment]
I am clear,thanks!
