### ISSUE TITLE
module subscription

### ISSUE THREAD

**Issue by ghost** [sysrepo/sysrepo#1860]
Hi Michal,

Is it ok to subscribe oper module with module_change_subscribe?
I know for oper module the flow is through "sr_oper_get_items_subscribe " but would like to know is there any harm if my purpose is getting fulfilled .

**Comment by michalvasko** [comment]
Hi,
are you asking whether you can subscribe with `sr_module_change_subscribe()` to some state data? It is mentioned in the [docs (5th paragraph)](https://netopeer.liberouter.org/doc/sysrepo/master/subs.html#change_subs). It will all work normally as long as you only take `push` operational data into consideration, only those are stored in *sysrepo*. You will not be notified about changes originating from data returned by `sr_oper_get_items_subscribe()` (`pull`) callbacks.

Regards,
Michal

**Comment by Sneha-star** [comment]
Hi Michal,

Thank you .
So if  go with sr_module_change_subscribe() to subscribe for oper module, then i don't need to subscribe using sr_oper_get_items_subscribe().

Hence it would be like subscribing to a config module. And when user fills the data (i.e equivalent to edit-config/push") then the corresponding oper module callback will be called.

I am little confused with push/pull -- Push means when user configuring data right (i.e in case of config module)
And pull means- Get (in case of oper module subscribed through sr_oper_get_items_subscribe  call)

**Comment by michalvasko** [comment]
Hi,
that is the reason it got renamed, they are simply module change subscriptions, not about configuration because it is not limited to that. Anyway, please go through the configuration and try to understand everything that is written [there](https://netopeer.liberouter.org/doc/sysrepo/master/index.html#oper_data). The information is quite concentrated but should all be there.

Regards,
Michal
