### ISSUE TITLE
Query : sysrepoctl and yang and data permissions 

### ISSUE THREAD

**Issue by sriramkandukuri** [sysrepo/sysrepo#1864]
Hi,

In our deployment we build `/etc/sysrepo/(data,yang)` directories to rootfs.
While installing any modules at build time with specific permissions we observed those permissions were applied to data files but not to yang files.

Example:
`sysrpeoctl --install x.yang -a -p 660`
Results in `/etc/sysrepo/data/x.startup` with `660` permissions and `/etc/sysrepo/yang/x.yang@TIMESTAMP` with `664` permissions.

After booting system with these directories in rootfs. `sysrepoctl -l` show `664` permissions to all modules on device.

Please help me to understand.

Thank & Regards,
Sriram.K

**Comment by michalvasko** [comment]
Hi Sriram,
not sure what the problem is but I can add some details. All YANG files always have mode set to `664` because they are generally public and must be read by all the clients, no reason to restrict them in any way. Permissions are always set to the startup data file of each module because that is the only persistent data file. Whenever an access check is performed or the mode is queried (using `sysrepoctl -l`, for example), the permissions are read from these startup files. And is there are some permissions and after restart they change to something else, I would only blame the system itself. You can check for yourself whether the permissions on the startup files were changed on their own accord before starting any *sysrepo* application.

Regards,
Michal

**Comment by sriramkandukuri** [comment]
Hi Michal,

Thank yo for the information.
