### ISSUE TITLE
set functionality

### ISSUE THREAD

**Issue by ghost** [sysrepo/sysrepo#1869]
Hi Michal,

Why can't i set (sr_set_item) a leaf node multiple times (i.e before applying ).
I don't want to do sr_discard_changes as that discards the whole config. 
How can I make this functionality works (so that user can set data multiple times before they are ready to commit)

**Comment by michalvasko** [comment]
Hi,
the reason is the way the changes are stored and it is expected you will either apply all the changes or discard them, nothing else really makes sense for most use-cases. However, this is possible if you use the `SR_EDIT_ISOLATE` flag (meaning the edits will be isolated and not merged into one). Then the changes will be applied in the same order they were performed.

Regards,
Michal

**Comment by Sneha-star** [comment]
Hi Michal,

Yes applying part is correct..
But before applying, user can change mind or by mistake had set a wrong config and correct the same before applying..
How does SR_EDIT_ISOLATE works if there are rae 1000 of leaf nodes (with different constraints )

**Comment by michalvasko** [comment]
Hi,
whenever you use the flag, it will create an isolated change meaning if there are 1000 changes of a leaf, then there really will be 1000 changes applied when you call `sr_apply_changes()`. But, of course, the callbacks will only be notified about the final changes.

Regards,
Michal
