### ISSUE TITLE
Set sr_val_t in oper_get_items Callback

### ISSUE THREAD

**Issue by smalls12** [sysrepo/sysrepo#1873]
Hello,

The previous sysrepo ( legacy ) allowed setting sr_val_t values for state data callbacks.

I understand after reading the documents that it is much more efficient to set the libyang data nodes directly, I however have a lot of clients that would require a large refactoring to support this.

I see that the RPC callbacks still support setting sr_val_t values and looking at the `shm_sub.c` those sr_val_t values are then converted into libyang data nodes via `sr_val_sr2ly_str` and `sr_val_sr2ly` functions.

So my question, can this functionality be brought back? I'm not sure that those functions could be used for the state data callbacks.

Thanks for your time.

**Comment by michalvasko** [comment]
Hi,
I am sorry but you will need to refactor those clients. The problem is that even the mechanism work differently now. Your callback is not called recursively for every parent but rather only once and you need to return all the existing data with all their descendants. However, it should not be difficult at all.

Before, you had (simplified)
```C
sr_val_t* val;

val->xpath = "<xpath>";
val->type = <type>;
val->data.<type> = <value>;

*output = val;
```
which you need to rewrite to
```C
lyd_new_path(*parent, NULL, "<xpath>", "<value>", 0, 0);
```
Working example can seen in [oper_data_example](https://github.com/sysrepo/sysrepo/blob/master/examples/oper_data_example.c#L31). Just be careful for top-level subscriptions (such is the one in the example) because in those cases you get `*parent` set to `NULL` and you have to set it before connecting other nodes to it (if you use `*parent` as a parameter for `lyd_new_path()`, nodes get connected to it). This change should make your code shorter and simpler and you do not need any special functions for it.

Regards,
Michal

**Comment by smalls12** [comment]
Okay Michal.

Thanks for providing the detailed response.
