### ISSUE TITLE
Editing datastores with Python

### ISSUE THREAD

**Issue by iicc1** [sysrepo/sysrepo#1895]
Hello,
Is it possible to edit datastores by using the Python bindings?
In case Sysrepo allows this feature, is there any example or documentation available?

Sorry if these questions are already explained, I couldn't find them.

Thanks in advance.

**Comment by michalvasko** [comment]
Hi,
so the docs should now be generated and found [here](https://netopeer.liberouter.org/doc/sysrepo/devel/group__classes.html). However, they are only links to C functions because it would be redundant to document C++/Python classes/methods separately since they are only wrappers. So, you could go through [C examples](https://github.com/sysrepo/sysrepo/tree/master/examples) and then just use corresponding Python methods.

Regards,
Michal

**Comment by iicc1** [comment]
Thanks!
