### ISSUE TITLE
Changing a node of other module in SR_EV_UPDATE

### ISSUE THREAD

**Issue by sriramkandukuri** [sysrepo/sysrepo#1899]
Hi,

We need to replicate a value of node in some other module(say `b`) if a leaf changed in module (say `a`). To achieve this I have added `SR_EV_UPDATE` handling for `a` and used `sr_set_item_str` to set the node with expected value.

After changing the value in `a` everything looks fine without error. but the value in `b` has not been updated.

Thanks & Regards,
Sriram.K

**Comment by michalvasko** [comment]
Hi Sriram,
I did not even think about such a use-case but as long as it doesn't crash, I would say it is fine. What you are doing is highly questionable and should be discouraged so I will not be adding support for it.

Regards,
Michal

**Comment by sriramkandukuri** [comment]
HI Michal,

Thanks for the info. Can I `sr_apply_changes` from `SR_EV_CHANGE/UPDATE`? If yes what else need to be considered to do that?

Thanks & Regards,
Sriram.K

**Comment by michalvasko** [comment]
Hi,
I believe you can do that even though, again, it is not really a good practice. You just need to make you will not change data of modules you are currently processing because then you will get a dead lock. It should even work if you are processing changes of a module, which is a dependency of a module you are changing recursively but I have never tried it myself.

Regards,
Michal

**Comment by sriramkandukuri** [comment]
Hi Michal,

Thank you for the info.

Thanks & Regards,
Sriram.K
