### ISSUE TITLE
clarification regarding cleanup of shm/sr* and /etc/sysrepo/*

### ISSUE THREAD

**Issue by iGovindY** [sysrepo/sysrepo#1904]
Hi,

As per my understanding, if an application A1 which subscribe to a model M1.yang gets killed abruptly, before restarting we should remove shm/srsub_M1.*
A. is this understanding correct?
B. Also likewise,
1. when we should remove shm/sr_* files?
2. what files should be removed when we are restarting the Netopeer2 server after the server was killed abruptly.
3. In what case should we remove /etc/sysrepo/*

Thanks
Govind.

**Comment by michalvasko** [comment]
Hi,
please read the [documentation](https://netopeer.liberouter.org/doc/sysrepo/master/index.html#recovery) and you should learn the detailed answer to all your questions. But the short and general one is, you should __never__ need to remove any files. The only exception is if an app crashes in a *sysrepo* function (which is a bug that should be reported and will then be fixed) but you do not really need to concern yourself with that.

Naturally, if your experience is different and something does not work properly even though it should, you need to report that as well.

Regards,
Michal

**Comment by bbergquist0930** [comment]
Michal, in a similar question, when a callback function crashes, sysrepo will often now work correctly after the fact.  Technically this is within a sysrepo function because the callback function is called within a thread of control of sysrepo.  

Of course, we should try to strive to ensure that a callback function does not crash, but there will be cases that are missed and it will happen especially during the development of the callback function.

The proper mechanism is according to the documentation in this case is to remove the shared memory.   

Is there any mechanism to detect the shared memory corruption.  The issue that I see is that I have a failure in a callback, I restart the application and then there hangs, etc. in the application.  Now I must kill the application, remove the shared memory, and restart again.

What I am wondering is if there is anything that could detect the shared memory corruption before starting the application again.  Almost like a "fsck" for sysrepo.

If you have any ideas on how something like that might be written, I would be willing to see if I can implement it and provide it back.

**Comment by michalvasko** [comment]
Hi,
actually, an application crashing in its own callback should be handled properly (mentioned in the docs) and *sysrepo* continue to work. Can you please describe your exact use-case so that I can fix it?

Also, it would be possible to enable such checking but like I said, it should not be required.

Regards,
Michal

**Comment by bbergquist0930** [comment]
I have mostly seen this while debugging the application and I stop the debugger in the middle of the callback.  Sometimes I have to clear out the shared memory before I can run the application again.  I will attempt to get a reproducible test case over the next few days.

**Comment by michalvasko** [comment]
Hi,
that should be fairly easy to simulate, just call `exit()` in the callback. Also, there is already [one such a test](https://github.com/sysrepo/sysrepo/blob/devel/tests/test_process.c#L303).

Regards,
Michal
