### ISSUE TITLE
Cannot subscribe async callbacks with SR_SUBSCR_ENABLED

### ISSUE THREAD

**Issue by rjarry** [sysrepo/sysrepo#1914]
Hi Michal,

When using our own event loop (i.e. callbacks are scheduled for later, and return `SR_ERR_CALLBACK_SHELVE` when they are not finished), there is no way to subscribe to module changes with the `SR_SUBSCR_ENABLED` option. Here is a dummy example:

```
>>> sr_connect()
Applying scheduled changes.
No scheduled changes.
>>> sr_session_start()
Session 30 (user "root") created.
>>> sr_module_change_subscribe("example", my_async_callback, SR_SUBSCR_ENABLED)
Triggering "example" "enabled" event on enabled data.
>>> my_async_callback called with SR_EV_ENABLED, returns SR_ERR_CALLBACK_SHELVE
Subscribing to "example" changes failed.
```

Looking at the code, it seems like the `SR_EV_DONE` callback is also not expected to return `SR_ERR_CALLBACK_SHELVE` (even though the return code is ignored).

https://github.com/sysrepo/sysrepo/blob/master/src/sysrepo.c#L3160-L3178

I don't know what could be done to fix that problem. Ideally, these callbacks should be allowed to return `SR_ERR_CALLBACK_SHELVE` and the application running its own event loop should be allowed to call `sr_process_events` when the callbacks have finished running.

I understand this is complex as the `SR_EV_ENABLED` and `SR_EV_DONE` events are simulated upon the call of `sr_module_change_subscribe()`. If the callback returns `SR_ERR_CALLBACK_SHELVE`, there should be some kind of flag telling the subscription is still "pending" until the callback has called `sr_process_events` for both `SR_EV_ENABLED` and `SR_EV_DONE`.

Thanks in advance for your help.

**Comment by michalvasko** [comment]
Hi,
firstly some background information. The problem with `SR_EV_ENABLED` event is that it works completely differently than other events. Normally, there is an originator that communicates the event to the subscriber using shared memory and then reads the reply, in short. But since none of this was required for this event, it simply generates the event right at the moment of subscribing by directly calling the callback.

For this reason there is no simple way of making it wait as there are absolutely no synchronization or other mechanisms used. So, I think the way to go here would be not to use flag `SR_SUBSCR_ENABLED` at all. What you can do instead is simulate this event yourself before subscribing, which is quite trivial. You can implement a simplified version of the [real code](https://github.com/sysrepo/sysrepo/blob/master/src/sysrepo.c#L3094) or even skip this whole step as far as *sysrepo* is concerned and simply make your application apply the `startup` data in some way.

Regards,
Michal

**Comment by rjarry** [comment]
I understand the complexity behind all this.

I think the best workaround (for now) is to return immediately when called with `SR_EV_ENABLED` and not defer the callback in that case. Maybe limitations around `SR_ERR_CALLBACK_SHELVE` should be mentioned in the docs.

Thanks for the reply.

**Comment by michalvasko** [comment]
Hi,
yeah, docs should now be updated and warn about this.

Regards,
Michal

**Comment by rjarry** [comment]
Thanks Michal.
