### ISSUE TITLE
Request: could you please please release or tag?

### ISSUE THREAD

**Issue by igortern** [sysrepo/sysrepo#1920]
Hi,

As it stands, there is no stable release of sysrepo, libyang, libnetconf2 and netopeer2 bundle. 
The last version released on Feb 4 has too many issues for practical use. 
In result, we are forced to work with devel, which breaks from time to time by definition. In my case every breakage (such as "issue 1919: sysrepoctl link failure") affects a group of people. 
Since there are no tags, the only recourse is to pull by commit id, which is inconvenient.

Would it be possible to either release or at least tag the last-known-good version?

Regards,
Igor

**Comment by michalvasko** [comment]
Hi Igor,
I am now actively working on wrapping everything up so that it is ready for a new release. Just know that "last known good version" changes with every new bug found, which is almost every day, so our policy was rather making new releases when enough major bugfixes were made. Which I think happened already.

Also, you can help speed this up by helping me with the #1919 issue.

Regards,
Michal

**Comment by igortern** [comment]
Hi Michal,
Thank you for the update. I'm looking into #1919, will let you know.
Regards,
Igor
