### ISSUE TITLE
Timeout not configurable

### ISSUE THREAD

**Issue by IvanAguiar95** [sysrepo/sysrepo#1928]
Hi,

We are needing to configure the timeout on the stack, aiming to have more time to process into the callbacks. We found a fixing for this issue [here](https://github.com/CESNET/Netopeer2/commit/2cc2accef400e3074e37cbe6e1c49032c88c982c).

Is there any way to update only this module to get this behavior without need to update all the stack?

We're using the current environment:

> libyang - v1.0.109
> sysrepo - v1.3.21
> libnetconf2 - v1.1.3
> Netopeer2 - v1.1.1

**Comment by michalvasko** [comment]
Hi,
you can try to cherry-pick that one commit, it may even be possible without any conflicts because I think this change is completely independent. However, that is quite any old *sysrepo* version you are using and I am surprised this is the only problem you encountered. So you may want to wait until next week when I hope to make another release and you can use it to update the whole stack.

Regards,
Michal

**Comment by IvanAguiar95** [comment]
We tried to apply a cherry-pick, however, it does not work properly, it conflicts to other properties during the installation. We got "to many arguments" on apply_changes.

**Comment by michalvasko** [comment]
Hi,
right, in the release you are using the last parameter was not yet present. So, you can simply remove `DATA_CHANGE_WAIT` `cmake` variable and then remove all the parameters `NP2SRV_DATA_CHANGE_WAIT` from the code.

Regards,
Michal

**Comment by IvanAguiar95** [comment]
The version `Netopeer2 - v1.1.1` and `Netopeer2 - v1.1.7` doesn't support the timeout.
However, it works fine on `devel` branch, possible also on the next release.

Thank you Michal, for your support :)

**Comment by michalvasko** [comment]
Hi,
there is a `cmake` [variable](https://github.com/CESNET/Netopeer2/blob/master/server/CMakeLists.txt#L44) that you can use to effectively adjust the number of workers.

Regards,
Michal
