### ISSUE TITLE
Netconf edit-config operaton with "replace" option doesn't delete old values.

### ISSUE THREAD

**Issue by jabilmplane** [sysrepo/sysrepo#1944]
Hi.

I'm doing some testing for sysrepo/libnetconf2/libyang/Netopeer2. And it seems that I have found several issues on the devel branch.

Per RFC6241, if edit-config operaton with "replace" option is used, new configuration should replace old one. So, I expect that old configuration is removed.

**Useful links:**
https://tools.ietf.org/html/rfc6241#section-7.2
https://discuss.tail-f.com/t/difference-between-merge-and-replace-attribute-in-edit-config/1568

**YANG model is:**
```
> get-schema --model test
MODULE
module test {
  namespace "urn:test";
  prefix e;

  container test {
    container cont1 {
      must "leaf1 != 33 and leaf1 != 66" {
        error-message
          "Values 33 and 66 are not valid";
      }
      leaf leaf1 {
        type int8;
        default "0";
      }
    }

    leaf leaf2 {
      when "../cont1/leaf1 > 10";
      type int8 {
        range "0..100";
      }
    }

    list list1 {
      key "id";
      leaf id {
        type int8;
      }

      leaf data {
        type string;
      }
    }
  }
}
```

**Steps to reproduce.**
**1. Create 3 list instances. test_cfg.xml file is:**
```
<test xmlns="urn:test">
  <cont1>
    <leaf1>12</leaf1>
  </cont1>
  <list1>
    <id>1</id>
    <data>"data1"</data>
  </list1>
  <list1>
    <id>2</id>
    <data>"data2"</data>
  </list1>
  <list1>
    <id>3</id>
    <data>"data3"</data>
  </list1>
</test>
```
 
**2. Apply configuration. Verify that all three instances have been created**
```
> edit-config --target running --config=/home/test/test_cfg.xml 
OK
> get-config --source running --filter-xpath /test:test 
DATA
<test xmlns="urn:test">
  <cont1>
    <leaf1>12</leaf1>
  </cont1>
  <list1>
    <id>1</id>
    <data>"data1"</data>
  </list1>
  <list1>
    <id>2</id>
    <data>"data2"</data>
  </list1>
  <list1>
    <id>3</id>
    <data>"data3"</data>
  </list1>
</test>
```

**3. Add “replace” operation to xml file. Edit test_cfg.xml file with following configuration**
```
<test xmlns="urn:test" xmlns:xc="urn:ietf:params:xml:ns:netconf:base:1.0"> 
    <list1 xc:operation="replace"> 
        <id>1</id> 
        <data>"data1 after replace"</data> 
    </list1> 
</test> 
```

4. Apply configuration. Verify that two instances have been deleted.

```
> edit-config --target running --config=/home/test/test_cfg.xml 
OK
```
**Current behavior:**
```
> get-config --source running --filter-xpath /test:test 
DATA
<test xmlns="urn:test">
  <cont1>
    <leaf1>12</leaf1>
  </cont1>
  <list1>
    <id>1</id>
    <data>"data1 after replace"</data>
  </list1>
  <list1>
    <id>2</id>
    <data>"data2"</data>
  </list1>
  <list1>
    <id>3</id>
    <data>"data3"</data>
  </list1>
</test>
```

**Expected behavior (list entries with ids 2 and 3 should be deleted because of "replace" operation):**
```
> get-config --source running --filter-xpath /test:test 
DATA
<test xmlns="urn:test">
  <cont1>
    <leaf1>12</leaf1>
  </cont1>
  <list1>
    <id>1</id>
    <data>"data1 after replace"</data>
  </list1>
</test>
```

Thanks in advance!

**Comment by bbergquist0930** [comment]
I think it is working as it should.  I believe you are applying the "replace" on this one list element.  Try changing your config to 

```
<test xmlns="urn:test" xmlns:xc="urn:ietf:params:xml:ns:netconf:base:1.0" xc:operation="replace"> 
    <list1> 
        <id>1</id> 
        <data>"data1 after replace"</data> 
    </list1> 
</test> 
```
The `test` node is now being "replaced" with the contents.  The `test` node is the parent container for the `list1`.

I could be wrong and have been wrong before but this does work.   It somewhat makes sense because for example if you do

```
<test xmlns="urn:test" xmlns:xc="urn:ietf:params:xml:ns:netconf:base:1.0"> 
    <list1 xc:operation="delete"> 
        <id>1</id> 
        <data>"data1 after replace"</data> 
    </list1> 
</test> 
```
This deletes the one list element that the "delete" is on.    Looking around I found no clear example, I did find this

[How can i use replace operation for the list defined in yang model](https://discuss.tail-f.com/t/how-can-i-use-replace-operation-for-the-list-defined-in-yang-model/2922)

but that is not really a good example, because the ambiguity in the statement 
>If you set the replace operation on “rts”, it will replace the whole configuration under “rts” with the new config. If this is what you want then it should work.

What is the meaning of `the whole configuration`?  Is it this specific list item configuration or all of the list items?

**Comment by michalvasko** [comment]
Hi,
I generally agree with what @bbergquist0930 said, this behavior is intentional. However, I also understand that your particular use-case is not described well in the specification so it leaves some room for interpretation. But interpreting it your way (an operation attribute on a list instance affects all instances of the list) would have other unexpected consequences so I dare say it is wrong. You can ask on the NETCONF mailing list if you want to make sure.

Regards,
Michal

**Comment by jabilmplane** [comment]
Your suggestions have a sense.
So, closing this issue.

Thanks!
