### ISSUE TITLE
Get operational data timeout

### ISSUE THREAD

**Issue by matth65** [sysrepo/sysrepo#1954]
Hello,

I have a few questions about sysrepo timeouts in the 'devel' branch.

1) I see that RPC_TIMEOUT has been added to Netopeer2, and RPC_TIMEOUT is configurable from cmake. I can increase the value of RPC_TIMEOUT, but it looks like I'm running into a timeout in sysrepo now.

[ERR]: SR: Callback event "operational" with ID 1 processing timed out.
[WRN]: SR: Event "operational" with ID 1 failed (Timeout expired).

I see that sysrepo also has a SR_OPER_CB_TIMEOUT. How do you recommend that I set the SR_XYZ_TIMEOUT values? Should I just set RPC_TIMEOUT and SR_OPER_CB_TIMEOUT to the same value?

2) Can I set the SR timeouts via cmake? I didn't see it in makefiles, but I just want to make sure.

3) I have an issue with timeouts on gets for large operational data sets. Other than increasing timeouts and perhaps making the backend faster, is there any way of breaking up the callbacks to avoid the timeouts? 

Regards,
Matt

**Comment by michalvasko** [comment]
Hi Matt,
what RPC are you executing when you get this timeout? I can easily add another configurable timeout into *netopeer2*. And yes, you can test it by setting `SR_OPER_CB_TIMEOUT` to some higher value. The only rule to stick to is making all these timeouts lower than `RPC_TIMEOUT` because otherwise the `RPC_TIMEOUT` would be the actual timeout value used.

As for breaking up the callbacks, it is definitely a good idea if they take such a long time. I am not sure what more to tell you in this regard, The operational callbacks can be greatly customized so the exact design is up to you. Basic rules are mentioned in the [docs](https://netopeer.liberouter.org/doc/sysrepo/master/index.html#oper_data).

Regards,
Michal

**Comment by matth65** [comment]
Hi Michal,

The RPC is just a simple <get/> of operational data. I have a proprietary YANG model that has several lists. I run into timeouts when testing scale with 100s or 1000s of entries in these lists. The timeouts occur when  performing a <get/> for the entire list at one time (i.e., subtree filter is set to filter on an entire list).

I did test by increasing both RPC_TIMEOUT and SR_OPER_CB_TIMEOUT. This allowed the <get/> to complete for some additional scale tests, but not all. I could keep increasing the timers to account for my largest scale, but I'm wondering if there is a better way to handle larger scale <get/> of operational data.

I can avoid the timeouts by modifying the client side. For example, the client could break up large gets using <get/> for the table keys, and then doing an individual <get/> for each entry in the table. I'm wondering if there's a better way of dealing with large data sets.

Regards,
Matt

**Comment by michalvasko** [comment]
Hi Matt,
I remember reading some proposals about operations that would allow to retrieve only index ranges of list instances on NETCONF mailing list but it did not get past that stage mostly due to complexity of designing such an operation, not to mention the actual implementation. So, there is nothing really you can do on NETCONF client level.

However, *sysrepo* is quite versatile and I am sure this can be solved somehow. But maybe before changing the subscriptions and the XPath they use, it may be worthwhile to try to optimize the way you are returning the data. Because, for example, using `lyd_new_path()` is really inefficient (albeit very simple and convenient) so you may want to switch to using `lyd_new()`, `lyd_new_leaf()`, and so on. Not sure what else to suggest but with increasing number of data provided you should get linear increase of time it takes, definitely not more.

Regards,
Michal
