### ISSUE TITLE
Q: SR_EDIT_ISOLATE performance

### ISSUE THREAD

**Issue by iljatab** [sysrepo/sysrepo#1957]
$ yanglint --version
yanglint SO 1.7.0

$ sysrepoctl --version
sysrepoctl - sysrepo YANG schema manipulation tool, compiled with libsysrepo v1.4.33 (SO v5.3.0)

$ netopeer2-server -V
netopeer2-server 1.1.21
compile time: Apr 15 2020, 12:13:51

Hi Michal,

I have a question regarding SR_EDIT_ISOLATE option usage with sr_set_item().
According to the docs: `However, note that it can adversely affect edit performance.`

I did some performance tests (using openconfig-interfaces.yang model) but couldn't find a significant performance difference with and without SR_EDIT_ISOLATE.
So I am just curious about the reason, is it because:
(1) using SR_EDIT_ISOLATE is really fast
(2) SR_EDIT_ISOLATE is really fast but may be slow only is some marginal cases
(3) there is some bug and even without SR_EDIT_ISOLATE things are slow

Could you also clarify what API calls are expected to be slower with SR_EDIT_ISOLATE - sr_set_item()/sr_del_item() or a final sr_apply_changes() call?

Attached is a trivial sample test app.
My test included creating 500 interfaces with attributes as per source file.

Thanks!

Ilja.

[sr_set_item_example.c.tar.gz](https://github.com/sysrepo/sysrepo/files/4557897/sr_set_item_example.c.tar.gz)

**Comment by michalvasko** [comment]
Hi Ilja,
I have not done any measurements of any kind so I cannot tell you the exact use-case. It is also quite probable that any higher performance cost would be completely hidden by other operations happening during applying an edit, which I would guess is your case.

My point was that when applying such isolated edits, each of them is searched for a match in data from top-level node instead of the closest already-found node. Meaning if you compare how long it takes to collect the actual changes when applying isolated vs. non-isolated edit, I think in your case it may take several times longer. But since hashes are used for this search, when using absolute numbers, whether you use this option or not is likely irrelevant.

Regards,
Michal

**Comment by iljatab** [comment]
Thanks for reply, Michal.

In the test I have done there was no back-end app involved - it was just a slightly modified application_changes_example.c from examples that did absolutely nothing.
So it supposed to be a sysrepo performance measurement, not the application logic.
But OK, I will continue...

Ilja.
