### ISSUE TITLE
How to perform delete of contaner using  sr_delete_item API.

### ISSUE THREAD

**Issue by iGovindY** [sysrepo/sysrepo#1964]
Hi

I want to delete a container C using  `sr_delete_item` API.

I tried passing below XPath but doesn't work
/module:L[key='4']/C
/module:L[key='4']/C/
/module:L[key='4']/C/*
/module:L[key='4']/C/.

where L is list and C is a container

Thanks
Govind

**Comment by michalvasko** [comment]
Hi Govind,
the very first path `/module:L[key='4']/C` should work. However, I am not sure what exactly you are trying to achieve because if `C` is a non-presence container, you cannot really delete it and all its descendants are deleted instead. This is an indirect consequence of how YANG non-presence containers are defined. It does not make sense to ask whether they exist or not. We implemented this in *libyang* in the way that they always exist as long as their parents exist (just like default values). And you cannot delete them (again, just like default values).

Regards,
Michal

**Comment by iGovindY** [comment]
Hi Michal,

Lets consider below yang
```
module: get_trials
  +--rw get_trials* [cid]
     +--rw cid              temp
     +--rw eid?             temp
     +--rw LL*              temp
     +--rw A
        +--rw B* [c]
           +--rw c          temp
           +--rw d?         temp <0>

```

below data exist in operational DB.
```
> get-data --datastore operational --filter-xpath  /get_trials:*
DATA
<get_trials xmlns="urn:sysrepo:get_trials">
  <cid>4</cid>
  <eid>78</eid>
  <A>
    <B>
      <c>5</c>
      <d>10</d>
    </B>
  </A>
</get_trials>
```
After that I try to delete using `sr_delete_item `

```
./sr_delete_item_example 
[INF]: Scheduled changes not applied because of other existing connections.
[WRN]: Cleaning up after a non-existent sysrepo client with PID 12686.
Choose <datastore 0:startup, 1:running, 2: candidate, 3: operational>
3
[INF]: Session 32 (user "root") created.
Enter <xpath-to-delete> 
/get_trials:get_trials[cid='4']/A
[INF]: No datastore changes to apply.
```

This call doesn't delete container A or its descendants as expected.

**Comment by michalvasko** [comment]
Hi,
meaning you set the shown data as push `operational` data and you are trying to further modify them?

Regards,
Michal

**Comment by iGovindY** [comment]
Yes.

**Comment by michalvasko** [comment]
Hi,
actually, just by looking at your output, why is there a crashed client? Does that client happen to set the previous `push` data? Because if so, they are removed as part of the cleanup and in that case the message makes sense. Do not forget `push` `operational` data exist only as long as the connection that was used to create them exists.

Regards,
Michal
