### ISSUE TITLE
Unable to connect if some other connection is processing a request

### ISSUE THREAD

**Issue by sriramkandukuri** [sysrepo/sysrepo#1974]
Hi,

I am getting timeout error while trying to connect to sysrepo if any other connection is processing some request say operational data get.

Is it expected? Or is there a way to add the connection and keept he request in wait list.

Thanks & Regards,
Sriram.K

**Comment by michalvasko** [comment]
Hi,
this is actually expected because almost any operation locks the shared memory for reading while a new connection needs to lock it for writing. I have thought about fixing this but it would require quite some effort so I am not sure when I will get to it. Also, I did not think it could really be a problem, just an inconvenience.

Regards,
Michal

**Comment by sriramkandukuri** [comment]
Hi Michal,

Thank you for the confirmation.

Thanks & Regards,
Sriram.K
