### ISSUE TITLE
Question on API changes and version numbers

### ISSUE THREAD

**Issue by bbergquist0930** [sysrepo/sysrepo#1980]
The API changed with commit 6ac00c645e5656fa3fd13bc7e84c9af96d30e979 which is the change to the `sr_validate` API.  When I updated our builds to use the latest version, this caused our builds to break.

I would not expect an API change without at least bumping the minor version number.   I am wondering if that will be done in the future?

**Comment by michalvasko** [comment]
Hi,
first, to explain a bit about our versioning scheme. There are 2 versions, __project__ version and SO __version__. You are right that only micro project version changed because I did not consider it too important and project version should tell you the "real" improvement of the project meaning you can expect major feature/behavior changes between 1.3 and 1.4 but mostly bugfixes or small improvements from 1.4.2 to 1.4.15, for example. And for API/ABI changes you should refer to the SO version, which has the exact policy [documented](https://github.com/sysrepo/sysrepo/blob/master/CMakeLists.txt#L43) (actually, the same is true even for the project version).

Now, I know I have still broken these rules because I have increased only the minor SO version with this change instead of the major one as it is a backwards-incompatible change. I am sorry about that and I hope this was the last time. The reason simply being that it was really just this one small change, which was mostly an oversight and should have been implemented this way long time ago and I expect the API will stay this way for some time now. I am afraid that in a year there could be SO version 20, which would be weird and so I decided how I did. Again, sorry, and if you want to make absolutely sure your project can be compiled with *sysrepo* then you should stick to a specific major/minor SO version. But generally only the major one is required not counting this one exception.

Regards,
Michal

**Comment by bbergquist0930** [comment]
Thanks for the explanation.   And such is the life of working with open source :)   I hope the bug fixes and testing that I have been doing have been helping to contribute back.

I just wanted clarification on what was to be expected.  Software versioning is not an easy task I know!
