### ISSUE TITLE
Deprecated containers shown in get

### ISSUE THREAD

**Issue by meghna-doshi** [sysrepo/sysrepo#2005]
Hi,
Did "get" from netopeer2-cli, following returned by sysrepo (devel version 1.4.38) even though ietf-yang-library.yang (revision 2019-01-04) shows these are deprecated. Is this expected behaviour when get on deprecated items is done.

Snippet shown here, there are many more entries of "module":
```

<modules-state xmlns="urn:ietf:params:xml:ns:yang:ietf-yang-library">
  <module>
    <name>ietf-yang-metadata</name>
    <revision>2016-08-05</revision>
    <namespace>urn:ietf:params:xml:ns:yang:ietf-yang-metadata</namespace>
    <conformance-type>import</conformance-type>
  </module>
  <module>
    <name>yang</name>
    <revision>2017-02-20</revision>
    <namespace>urn:ietf:params:xml:ns:yang:1</namespace>
    <conformance-type>implement</conformance-type>
  </module>
  <module>
    <name>ietf-inet-types</name>
    <revision>2013-07-15</revision>
    <namespace>urn:ietf:params:xml:ns:yang:ietf-inet-types</namespace>
    <conformance-type>implement</conformance-type>
  </module>
```

Regards,
Meghna

**Comment by michalvasko** [comment]
Hi,
yes, both `current` and `deprecated` nodes are returned, do you have an actual problem with it or just asking?

Regards,
Michal

**Comment by meghna-doshi** [comment]
Hi Michal,
Just asking.
So you mean this is as per standards?

Regards,
Meghna

**Comment by michalvasko** [comment]
Hi,
unfortunately, the standards do not specify the details regarding this (at least I could not find anything). You can easily ignore the deprecated data so it should not cause any problems.

What I am not sure is whether the deprecated definitions were kept only so that clients are able to load `ietf-yang-library` data from the old revision or even for the servers to retain support for clients using the old revision. We support even the latter because *libyang* is able to parse only known data meaning it can silently ignore the new data and work just with the old ones.

Regards,
Michal
