### ISSUE TITLE
Release build type

### ISSUE THREAD

**Issue by michalvasko** [sysrepo/sysrepo#201]
Hi,
currently sysrepo build fails if configured with cmake parameter `-DCMAKE_BUILD_TYPE=Release` on my machine and also in our travis build, so I think you introduced it in the latest release. Can you please look at it?

Regards,
Michal

**Comment by lukasmacko** [comment]
Hi Michal,

actual cause is that `REPOSITORY_LOC` is changed in release build. Even debug build fails if this variable is changed. Tests use a special reposistory in build directory and the debug build shares it by default, so we didn't notice. We will fix.

Workaround for you is to disable tests for now.
`cmake -DCMAKE_BUILD_TYPE=Release -DENABLE_TESTS=False ..`

Regards,
Lukas

**Comment by rastislavszabo** [comment]
Hi,
the actual issue is that in Release mode, if tests are enabled, you need to have the write access to `SUBSCRIPTIONS_SOCKET_DIR` (`/var/run/` by default). So building under root privledges (e.g. using sudo) should work as another workaound.

**Comment by michalvasko** [comment]
Hi Lukas,
I don't think that building sysrepo should require root privileges, but that is up to you (maybe disable tests in Release build type by default?). I used the workaround of disabling tests manually and will stay with it, thanks.

Regards,
Michal

**Comment by rastislavszabo** [comment]
Hi,
we agree - it is already fixed in master.
