### ISSUE TITLE
A question about  sr_module_change_subscribe and sr_apply_changes？

### ISSUE THREAD

**Issue by Julian-younger** [sysrepo/sysrepo#2010]
hi Michal,
   In my application scenarios like this，mydatastore synchronous data to sysrepo and sysrepo can also synchronous data to mydatastore，And  when  I  change  mydatastore  use API like  sr_set_item
，sr_apply_changes， And I don't want to trigger the callback of sr_module_change_subscribe function,will you have some good suggestions？Thanks very much！

**Comment by michalvasko** [comment]
Hi,
this is an unsupported use-case. That means that you will have to use some trick to get the functionality you want, a proper fix will be available in several months when we plan to implement custom datastore that is meant to support precisely this use-case. But for now you can, for example, use a flag to let your callback know they should not apply the changes because they already were. Or something similar.

Regards,
Michal

**Comment by Julian-younger** [comment]
thanks for you replay~
