### ISSUE TITLE
Questions with respect to using Sysrepo APIs

### ISSUE THREAD

**Issue by fxie00** [sysrepo/sysrepo#2013]
Hi,

I am new to Sysrepo. I have several questions with respect to using Sysrepo APIs and would appreciate any feedback/response.

1.	According to Sysrepo developer guide, there are two models for applications to provide operational data, push model and pull model. Is there any global configuration that the user needs to set for Sysrepo to operate in push model?

2.	Is it possible for an application to set or modify a “config false” item using sr_set_item and then for another application to retrieve the value using sr_get_items?

3.	Why isn’t there sr_set_items for setting multiple items? Can sr_set_item be used to configure a list such as ietf:interface (with many attributes of different types) or a presence container? Is it possible to use sr_set_item to create a nested object (an object with several sub-objects embedded)?

4.	In sr_val_s, there is no information for the size of the data unit. In sr_data_u, there are several types such as  anyxml_val, anydata_val, identityref_val, instanceid_val, binary_val, bits_val and enum_val, which are defined as char *. How do we know the end of the char *? Are they all null-terminate strings ended with ‘\0’?

5.	By default, a new thread will be created for each sr_xyz_subscribe call. How about other Sysrepo APIs such as connection/session, get/set, etc.. Do any of these APIs create a separate thread?

6.	Are files in startup datastore text files in XML format? Or they are byte streams of internal Sysrepo structures?

Thanks.

Feng

**Comment by michalvasko** [comment]
Hi Feng,
1. Not sure what you mean exactly, what would you like to configure, but no, there is none. You use the standard edit API but on the `operational` datastore.
2. Yes, the edit would then be considered `push` `operational` data. Get a standard retrieval, it does not matter how the data were written.
3. Because all the changes are only prepared when you set them, they are all applied together once you cann `sr_apply_changes()`, that should be clear from the documentation. And whether you set the changes item-by-item or together, it does not make any actual difference, that is why there is no specific multi-set API, it would be redundant. However, that is not entirely true and there is `sr_edit_batch()` that can set a change "tree", not just a single change. However, if you are just learning about *sysrepo*, you should avoid that function, to be correctly used it requires a fairly in-depth knowledge about NETCONF `edit-config`.
4. Yes, they all need to be `0`-terminated.
5. No, only subscriptions create new threads. In the documentation there is a section about threads and `connections` and `sessions`.
6. They are something in between, binary representation of what could also be XML formatted YANG data. That means you cannot directly use a test editor to look at them (or edit them, but that is strictly prohibited and may easily break *sysrepo*) but you can use `yangling` from *libyang* to easily transform the data to XML or JSON.

Regards,
Michal

**Comment by fxie00** [comment]
Thanks Michal for the quick and detailed response. This issue can be closed.

Feng
