### ISSUE TITLE
Sysrepo usage of protobuf in pre-releases

### ISSUE THREAD

**Issue by fxie00** [sysrepo/sysrepo#2025]
Hi,

I noticed that Sysrepod and GPB (Google Protobuf) are used in Sysrepo pre-releases. I know that Sysrepod and GPB may be removed and replaced by shared memory access in the formal releases. I have some questions:

1. With shared memory access, only internal clients (daemons in the same host as Sysrepo) can access Sysrepo APIs. How to support an external client? Sysrepo_plugind is suggested. What IPC mechanisms an external client should use with Sysrepo_plugind? Is it up to the external client to implement a specific plugin using whatever IPC mechanisms that the external client prefers?

2. Is it possible to use Sysrepod as the API server for external clients in formal releases?

3. In a pre-release, what tools are used to generate C code from sysrepo.proto. Is it the opensource package protoc with a c plugin or something proprietary?

4. Was the sysrepo.proto manually drafted? Are there any YANG models to describe the Sysrepo/Libyang structures?

5. Since sysrepo uses libyang structures extensively, why not just convert sysrepo/libyang structures to xml/json and carry it in IPC channels? The payload may be lengthy but no protobuf is needed.

Thanks.

Feng Xie

**Comment by michalvasko** [comment]
Hi,
1. Yes, only local clients can connect to *sysrepo*. This was generally true also for the legacy *sysrepo* with GPB, it was not meant to communicate remotely even though, since a simple file descriptor was used for this purpose, it was theoretically possible. External clients are meant to use *netopeer2* and connect using NETCONF, no IPC. Not sure what connection does *sysrepo-plugind* has to this problem.
2. There is no *sysrepod* in *sysrepo* 1.x. Any clients must be linked with *sysrepo* as it is just a library.
3. It was the `protoc` package.
4. Yes, it was written by hand and has no connection to YANG.
5. Yes, this is one of the internal changes between *sysrepo* 0.7.x and 1.x. The data are serialized not to any text format (XML/JSON) but to our proprietary LYB binary format (think something like CBOR), which is much more efficient.

Regards,
Michal

**Comment by fxie00** [comment]
Hi Michael,

Thanks again for the quick and detailed response. I have some further questions for item 5. You mentioned that LYB is used in release 1.x to serialize data. However, I know that sysrepod is removed from release 1.x. As a result, there is no protobuf/socket communication. Sysrepo APIs are implemented as regular function calls with libyang structure. If so, why do we need to use LYB to serialize data. For local function calls, C structures in binary format are used, right?

Best regards,
Feng

**Comment by michalvasko** [comment]
Hi Feng,
serialization is required for all IPC. Before, the data flow was `sysrepo client1` -> `sysrepod` -> `sysrepo client2` and sockets were used for the communication. In the current version, it is just `sysrepo client1` -> `sysrepo client2` so the communication is direct using shared memory but serialization is needed no matter what. Most API calls require some communication with other processes (all subscriptions).

Regards,
Michal

**Comment by fxie00** [comment]
Thanks. The issue can be closed.
