### ISSUE TITLE
What happened to sysrepo java bindings?

### ISSUE THREAD

**Issue by esend7881** [sysrepo/sysrepo#2026]
I found this http://www.sysrepo.org/bindings/java

About 80% of my project is in Java and using Java calls to subscribe sysrepo/netconf events is most preferred for me. However, it seems the code behind java bindings was once worked on, but not anymore? 

> CMake Warning:
>   Manually-specified variables were not used by the project:
>     GEN_JAVA_BINDINGS

I'm not sure if the code for the binding is part of another tag or not. Would getting those bindings back in the normal releases be as simple as taking the cmake related code from that tag, or were the java bindings abandoned and not usable?

**Comment by michalvasko** [comment]
Hi,
we are in the process of replacing all the bindings with a manually written ones so that they can be used comfortably in the corresponding language and no SWIG is required. We chose to port only C++ and Python bindings from the legacy *sysrepo* as they were used the most. However, we are not planning on writing Java bindings manually as we thought they were not used. So, if you really need them, you could write them and create a pull request.

Regards,
Michal

**Comment by esend7881** [comment]
Is there an example of the old Java bindings I could base it on? I haven't
written bindings before but I'm sure I can figure it out from some
examples.

**Comment by michalvasko** [comment]
Hi,
the old bindings are available in the old *sysrepo* normally but I do not think they can help you in any way. You would have to write them by hand unlike those old ones that are simply generated using SWIG from the C++ bindings. And you would also want to change the Java API itself because you can without SWIG, to make it convenient to use.

Generally, I think it should not be that difficult as *sysrepo* API is fairly small so a few weeks should be enough. However, you would need to start by thorough learning about general ways of writing Java bindings, what technology to use. You can look for examples in some other projects.

Regards,
Michal

**Comment by esend7881** [comment]
@michalvasko - I am seeing SWIG in much of the binding code:
https://github.com/sysrepo/sysrepo/blob/master/bindings/python/sysrepo.i
https://github.com/sysrepo/sysrepo/tree/master/bindings/swig_base

So when you mention a Java API should be written without SWIG, I am curious if there is an example of how you want it to be written?

Or, is the current binding code going to be revamped anyway?

**Comment by michalvasko** [comment]
Hi,
that is what I tried to explain, there is no suitable example in our projects. That is why I told you to learn about it yourself and look into other projects. To illustrate what I mean, you always need to use some technology for these bindings, we just do not want to use SWIG anymore. In *libyang*, there are already new Python bindings written using CFFI, but that is usable only for Python. You need to look at the options for Java.

As for the `legacy` *sysrepo*, yes, there are the old SWIG Java bindings. But it is abandoned for quite some months now and any changes are mostly from pull requests, we do not want to waste time on it anymore. So you are free to use it but do not expect any support from us. It is unnecessarily complex and inefficient, which will be more and more obvious compared to the current *sysrepo* because once we finish *libyang* 2.0 and use it in *sysrepo*, it should be even faster. SWIG is currently used only for Python bindings and once the CFFI-based are finished and tested for a long enough time, the old bindings will be completely removed with any SWIG requirements or references.

Regards,
Michal
