### ISSUE TITLE
Query on Notification streams

### ISSUE THREAD

**Issue by meghna-doshi** [sysrepo/sysrepo#2030]
Hi,
Need some information about how the notification streams are added to sysrepo, so that NETCONF Client can subscribe.
(sysrepo devel version 1.4.38)
1. Tried "get" from netconf client, following is snippet of the result, where looks like every yang which was subscribed with sysrepo, is considered a stream:
```xml
<netconf xmlns="urn:ietf:params:xml:ns:netmod:notification">
  <streams>
    <stream>
      <name>NETCONF</name>
      <description>Default NETCONF stream containing notifications from all the modules.</description>
      <replaySupport>true</replaySupport>
    </stream>
    <stream>
      <name>yang</name>
      <description>Stream with all notifications of a module.</description>
      <replaySupport>false</replaySupport>
    </stream>
    <stream>
      <name>ietf-datastores</name>
      <description>Stream with all notifications of a module.</description>
      <replaySupport>false</replaySupport>
    </stream>
```
2. So if application wants to add a new stream, how does application do it.

3. Also what is the rational behind adding each yang module as a stream? Does it mean that any notification defined in those modules, belong to that respective module stream, so will be notified only when that stream is subscribed to?
ex 
```yang
module ietf-yang-library {
.....
......
notification yang-library-update {
    description
      "Generated when any YANG library information on the
       server has changed.";
    leaf content-id {
      type leafref {
        path "/yanglib:yang-library/yanglib:content-id";
      }
}
```
So only when netconf client subscribes to ietf-yang-library stream, the above notification shall be sent to netconf client.

Regards,
Meghna

**Comment by meghna-doshi** [comment]
Hi,
Anything on this?

Regards,
Meghna

**Comment by michalvasko** [comment]
Hi,
sorry, this somehow slipped through my notifications, not sure how.

1. Yes, that is correct. It was the simplest solution and even makes sense since notifications for each module are stored in a separate file.
2. The streams are not customizable so the application has no way of creating its own stream.
3. Yes, you will get the notification of module `A` only if you are subscribed to stream `A` or `NETCONF`.

In general, you should not care much for these streams, they are supported only because there should be some streams. But you should always be fine subscribing to the `NETCONF` stream and using an XPath filter to get only the exact notifications you want to.

Regards,
Michal
