### ISSUE TITLE
errors when force power off the device

### ISSUE THREAD

**Issue by superandrewaaa** [sysrepo/sysrepo#2035]
i have call `sr_unsubscribe` when device shutdown or reboot normally，but when i force power off the device.
the program will not call `sr_unsubscribe`. there will be some residual files in the system. what should i do to  when device force power off to deal with these problems?

for  example: 
there are some residual  content in `ietf-keystore.persist` in `/etc/sysrepo/data`
and there are residual socks : `2127.yargFz.sock` in `/var/run/sysrepo-subscriptions/ietf-keystore`

when the device restart, there will be some errors as below:

```
 calhost sysrepod[1533]: [ERR] (pm_save_persistent_data:409) Unable to modify persist data tree.
Jun 23 14:54:13 localhost sysrepod[1533]: [ERR] (np_unsubscribe_destination:1178) Unable to remove subscriptions for destination '/var/run/sysrepo-subscriptions/ietf-keystore/2125.aIQVaa.sock' from 'ietf-keystore'.
Jun 23 14:54:13 localhost sysrepod[1533]: [ERR] (pm_save_persistent_data:409) Unable to modify persist data tree.
Jun 23 14:54:13 localhost sysrepod[1533]: [ERR] (np_unsubscribe_destination:1178) Unable to remove subscriptions for destination '/var/run/sysrepo-subscriptions/ietf-keystore/2125.aIQVaa.sock' from 'ietf-keystore'.
Jun 23 14:54:13 localhost sysrepod[1533]: [ERR] (pm_save_persistent_data:409) Unable to modify persist data tree.
```

**Comment by superandrewaaa** [comment]
@rjarry ，my sysrepo version is 0.7.7, is it a problem that has been solved?

**Comment by rjarry** [comment]
Hi @superandrewaaa ,

The legacy label means it affects the `legacy` branch. I don't know if that precise problem has been fixed in the `master` branch but Sysrepo was rewritten from scratch without any common code base.

By the way, the `legacy` branch no longer receives any maintenance.

See https://github.com/sysrepo/sysrepo#migration-from-sysrepo-version-07x-or-older and https://github.com/sysrepo/sysrepo/blob/master/CHANGES for more details.

**Comment by michalvasko** [comment]
Hi,
whatever problems you have with it will not be fixed in any way because like @rjarry said, the legacy *sysrepo* is no longer maintained. If you use the current *sysrepo* 1.4.x this situation should be handled as long as your app is not terminated while executing a *sysrepo* function.

Regards,
Michal
