### ISSUE TITLE
Questions on using sr_get_data/subtree

### ISSUE THREAD

**Issue by fxie00** [sysrepo/sysrepo#2037]
Hi,

I have questions in using sr_get_data/subtree. Any help will be appreciated.

1. In sr_get_subtree/data, should the returned lyd_node be freed after retrieving data from these nodes? The free operation is required for sr_get_item(s).

2. In sr_get_subtree/data, can special predicates such as wildcard be used in path/xpath? Is it possible to retrieve a list of data items/instances of the same type (such as all the interfaces on a router)?

3. In the manual for sr_get_data, there is a statement like "If the subtree selection process results in too many node overlaps, ...... As an example, a common XPath expression //. is normally used to select all nodes in a data tree, but for this operation it would result in an excessive duplication of data nodes."   My question is that there should be no overlapping in YANG trees, right? If so, how could there be overlapping nodes?

4. In sr_conn_flag_e, there is SR_CONN_CACHE_RUNNING. Where is the running datastore cached? Is it cached per connection? If so, how to make sure the cache is synchronized with the common datastore?

Best regards,
Feng Xie

**Comment by michalvasko** [comment]
Hi,
1. As the documentation mentioned, the returned data are "allocated dynamically", meaning you have to free it.
2. Again, as documented (if you follow the link to [paths definition](https://netopeer.liberouter.org/doc/sysrepo/master/index.html#paths)), all XPath expressions are accepted (except those not supported by *libyang*, which are axes, for example).
3. Once again, as documented, "subtrees" are selected. You need some basic XPath understanding for this but I can quickly illustrate with a small example.

```xml
<root>
  <node>value</node>
</root>
```
Having these data, you can use the expression `//.`. That results in __nodes__ `root` and `node`. However, since __subtrees__ are actually selected, you get subtree
```xml
<root>
  <node>value</node>
</root>
```
and
```xml
<node>value</node>
```
Obviously, you get the `node` twice, which is exactly what is meant by overlapping in the documentation. You should use (for example) expression `/*` instead, which will select only top-level nodes, but since they are subtrees, actually all the nodes get selected.

4. Yes, it is cached in the connection (meaning for all the sessions created on the connection) and its validity is handled internally, using the flag should be completely transparent as far as functionality is concerned but mainly data retrievals should be much faster (in case the datastore does not change much).

Regards,
Michal

**Comment by fxie00** [comment]
Hi Michal,

Thanks again for the detailed response. I have two minor follow-up questions:

1. for path and xpath, it seems that the main difference is that the path parameter in sysrepo carries instance identifier while xpath does not. Thus, path can refer to a single node/subtree while xpath may refer to a set of nodes/subtrees. Is this correct? Further, the manual mentions that it is possible to use predicates for a path. However, my understanding is that we can also use predicates in xpath, right?

2. why there is an option parameter for sr_get_data but not for sr_get_subtree? Further, the manual mentions that //. is used to select all nodes in a data tree. I checked several xml/xpath manual, it seems that //* is used to select all nodes instead of //. . But I do get your points about overlapping nodes. 

Best regards,
Feng

**Comment by michalvasko** [comment]
Hi,
1. Yes, hence the name path (single path) and xpath (full XPath as formally specified). You can use predicates even in path but generally only the same ones as in instance-identifier value, just to identify the instance. And of course you can use any predicates in XPath.
2. Because `sr_get_subtree()` is mostly just a legacy function that does not really serve any specific use-case, it is just simplified `sr_get_data()`, which is actually the only function you need for getting data as it allows full customization that is possible, hence the options. `//*` and `//.` should actually be completely similar expressions. Definitely so for YANG. As for general XPath, there may be a difference such that `//.` will not select only `element` nodes but also `text` nodes or something like that but you can safely ignore that when using *sysrepo*/*libyang*.

Regards,
Michal

**Comment by fxie00** [comment]
Got Michal's response quoted below. Thanks a lot for the detailed and timely response. This issue can be closed.

Hi,
1.	Yes, hence the name path (single path) and xpath (full XPath as formally specified). You can use predicates even in path but generally only the same ones as in instance-identifier value, just to identify the instance. And of course you can use any predicates in XPath.
2.	Because sr_get_subtree() is mostly just a legacy function that does not really serve any specific use-case, it is just simplified sr_get_data(), which is actually the only function you need for getting data as it allows full customization that is possible, hence the options. //* and //. should actually be completely similar expressions. Definitely so for YANG. As for general XPath, there may be a difference such that //. will not select only element nodes but also text nodes or something like that but you can safely ignore that when using sysrepo/libyang.
Regards,
Michal
