### ISSUE TITLE
Question: Creating application deamons that connect to sysrepo

### ISSUE THREAD

**Issue by chaichairiko** [sysrepo/sysrepo#2046]
Hi,
This is a question that has been asked in various ways: https://github.com/sysrepo/sysrepo/issues/1000 , https://github.com/sysrepo/sysrepo/issues/1651 , https://github.com/sysrepo/sysrepo/issues/359  but I dont understand from these a clear answer on how deal with the issue of remote applications.

The use case that interests me is created distributed applications, that is, applications that run in different containers which  communicate with sysrepo. Looking at the docs, the indirect approach of running a daemon with libsysrepo seems to be the way to go, but other than that, I dont see any documentation for how to implement this.

How can I connect remotely to sysrepo OR how do you recommend that I implement this use case?

**Comment by michalvasko** [comment]
Hi,
it was also answered there so you will have to actually specify your question if you expect any different answer from me.

Regards,
Michal

**Comment by chaichairiko** [comment]
Sorry, I was in the middle of editing the question and my internet disconnected ):

**Comment by michalvasko** [comment]
Hi,
oh, I see. So, *sysrepo* is not meant to run on any kind of distributed environment because it heavily relies on local IPC (shared memory). For remote access there is *netopeer2* and NETCONF and you can always use that.

However, it may be an overkill in a controlled environment (a cluster, for example) but there is nothing else available at the moment. So the only solution would be to write your own network protocol and then write a daemon similar to *netopeer2* that would translate this protocol messages into local *sysrepo* API calls just like *netopeer2* does for NETCONF. That is, in short, what I always answer for these questions.

Regards,
Michal

**Comment by chaichairiko** [comment]
Thank you for the quick response.

I understand remote access using netopeer2, with regards to sending the data, but my question is regarding the callbacks more than anything. 

Maybe this is what you meant to say, but I'll try ask in different manner (sorry if requires you to repeat the answer):
While sysrepo is meant to be local, must the applications be local as well? If so,
How will creating my own protocol work? since the application itself has to be local. 

My thought was create a PUB/SUB myself that will connect all the local sysrepo applications to a remote "neopeer/sysrepo" that will handle the data as if it came from the client (if that makes sense)

**Comment by michalvasko** [comment]
Hi,
I think we are talking about the same thing but I do not think you realize all the consequences of what you are suggesting.

Okay, so the idea is to basically have a remote application subscribed to some data changes. Going with the most straightforward implementation, you would want to change the local IPC communication using shared memory for some kind of remote communication. This is where the problem is. Conditional variables and mutexes are stored in the SHM and used for synchronization. I suppose you can still emulate this by sending some simple messages like `lock`, `signal`, and so on (the custom protocol I was talking about). However, be aware that the architecture is not 1:1 but 1:n (one originator, many subscribers), which makes the whole scenario much more complex. But, you could implement the protocol to support only 1:1 and that is why it seems to me as the best solution.

Note that to avoid all this you can use NETCONF and some of its mechanisms. The simplest one (albeit a messy and inefficient one) would be subscribing to `netconf-config-change` notification, which is generated for every configuration change with any details. But you could also define your own notification(s) and generate them as needed with whatever information needed, *sysrepo* should provide mechanisms and publish whatever information you would be interested in.

Finally, note that actually the functionality you are looking for is already standardized in [RFC 8641](https://www.rfc-editor.org/rfc/rfc8641.html). In brief, it is the same mechanism as `netconf-config-change` but with all kinds of options and settings added so that you can customize all the parameters of how to receive information about configuration changes. In other words, exactly the functionality that *sysrepo* change callbacks provide but with even more settings. And while we do not support this yet, it is currently planned for Q3/Q4 this year. So you may be better off just waiting until then.

Regards,
Michal

**Comment by chaichairiko** [comment]
This detailed answer helps us a lot. Thank you!
I'll be glad to help with anything development-wise regarding the future features

**Comment by michalvasko** [comment]
> I'll be glad to help with anything development-wise regarding the future features

Not sure what exactly you mean by that. We always appreciate testing and then reports of any problems but let us know if you are willing to actually help with the implementation.

Regards,
Michal
