### ISSUE TITLE
libsysrepo.pc

### ISSUE THREAD

**Issue by fxie00** [sysrepo/sysrepo#2051]
Hi,

I am compiling frrouting, which has a sysrepo plugin. I built sysrepo 1.4.66 from the git hub for FRRouting. FRRouting uses PKG_CHECK_MODULES to find required libraries. It seems that this utility may require a libsysrepo.pc file be generated and installed. I can't find such a file in my host.

So the question is that whether sysrepo build process should generate libsysrepo.pc? I have a Ubuntu 18.04 LTS VM. I started from scratch by installing all required packages. Thanks.

Feng Xie

**Comment by michalvasko** [comment]
Hi,
I believe the root cause will be the same as in https://github.com/CESNET/libyang/issues/1147. But I think there must be something wrong on your end, the file is always [generated](https://github.com/sysrepo/sysrepo/blob/master/CMakeLists.txt#L244) and [installed](https://github.com/sysrepo/sysrepo/blob/master/CMakeLists.txt#L253).

Regards,
Michal
