### ISSUE TITLE
sr_get_change_next() error in case of default empty string

### ISSUE THREAD

**Issue by gitter-runner** [sysrepo/sysrepo#2056]
Hi!

Ever since I upgraded from the 1.4.65 sysrepo to 1.4.70, I receive "Internal error" using sr_get_change_next(), whenever there's an empty-by-default (default "") string in the list that is about to be updated.

I attached a simple program which can reproduce the fault. As you can see the animals list is augmented with a string type leaf (nickname), whose default value is empty. If I change the default value to a proper string, the issue disappears.

[next_change_c.txt](https://github.com/sysrepo/sysrepo/files/4938605/next_change_c.txt)
[test_yang.txt](https://github.com/sysrepo/sysrepo/files/4938606/test_yang.txt)
[test2_yang.txt](https://github.com/sysrepo/sysrepo/files/4938608/test2_yang.txt)

libyang version: 1.0.184
sysrepo version: 1.4.90

Thanks!

**Comment by michalvasko** [comment]
Hi,
should work correctly with the latest *libyang*.

Regards,
Michal

**Comment by johnkaramp** [comment]
Hi @michalvasko, i face a similar issue with an "internal error, sysrepo.c:5758" in sysrepo `sr_get_change_next()`.

The yang leaf is a string with default an empty string "" and the sequence is the following:
1. writting "123456789", `apply_changes()` is called, the callback fails for some valid reason (iterator correctly finds the leaf change "123456789")
2. then there is a custom reset mechanism, in case of failure of `apply_changes()`, the old values are reset, so empty string is written "",  `apply_changes()`, which has no effect, because empty string is already there.
3. then i try to write again "123456789", and this time when `apply_changes()` is called, the callback has an internal error in sysrepo.c:5758

sysrepo version: v2.2.170 
libyang version: v2.2.8

**Comment by michalvasko** [comment]
The best advice I can give you is to update *libyang*/*sysrepo* to the latest release, there is a high chance it will fix your problem. Or you can provide a small example that reproduces the issue, I cannot help you without it.
