### ISSUE TITLE
reason for why `Schema_Node::find_path()` fails is not apparent

### ISSUE THREAD

**Issue by andrei-pavel** [sysrepo/sysrepo#2091]
Hello,

Sorry to bother!

I have a use case where my sysrepo subscriber gets an edit-config on the running datastore. I would like to have persistence so I'm trying to push to the startup datastore on the done callback. Whether I use a previously opened session or I open one on the spot, on a `Schema_Node::find_path()` call, I get:
```
throw std::runtime_error("No Context");
```
but what's weird is if I catch the `std::runtime_error` and I call `what()` on it, I get
```
Schema node not found.
```
for this xpath: `/ietf-dhcpv6-server:dhcpv6-server/vendor-config/kea-augments-to-ietf-dhcpv6-server:hooks-libraries[library='lib']/parameters/config/classification-group/groups`

The only thing special about the node is that it's augmented. This might be important because several calls to `Schema_Node::find_path()` have worked just fine until this node and this is the first node on which it fails and it happens to be the first augmented node.

My questions would be:
1. Do you think this is a bug?
2. Do you do something to alter the `what()` of the `std::runtime_error`?
3. Is there an easier way to programmatically push configuration to the startup datastore?

**Comment by michalvasko** [comment]
Hi,
looking at the *libyang* C++ bindings the `No context` exception is generated when a function fails, the cause is being retrieved from `struct ly_ctx` but it is `NULL`. Are you calling `find_path()` as a static function? Anyway, if you enable some logging you should see the exact problem printed, why the node is not found.

As for pushing the changes into `startup`, it depends what exactly you want to do. If you always want your `startup` to mirror the `running` (or at least for the whole module), you can use `sr_copy_config()` and not bother with each change separately.

**Comment by andrei-pavel** [comment]
Hi,

Managed to do it with `sr_copy_config()`, `Session::copy_config()` respectively.

I was calling `find_path()` as a member function / method. I wrote it as `Schema_Node::find_path()` to differentiate it from `Data_Node::find_path()`.

Thank you very much!
