### ISSUE TITLE
Question related to sr_get_items function

### ISSUE THREAD

**Issue by Roky7250** [sysrepo/sysrepo#2106]
Hi,
I am sysrepo with version 1.4.51 and netopeer2-server with version 1.1.24.

I have my test module called my-test.yang. Module is installed in sysrepo and contains one entry of list inside running and startup configuration:
```
          <test-entry>
            <id>1</id>
            <vids>1-10</vids>
            <type>static</type>
          </test-entry>
```

Now I am adding new entry and sending edit-config request, so my edit configuration contains next:
```
          <test-entry>
            <id>1</id>
            <vids>1-10</vids>
            <type>static</type>
          </test-entry>
          <test-entry>
            <id>1</id>
            <vids>9-25</vids>
            <type>static</type>
          </test-entry>
```
Keys of list are: id and vids.

Inside callback for `test-entry` I want to add part of the code that will check if vids of new test-entry is overlapping with vids of entries that I have inside my running configuration.

Problem is that when I use **sr_get_items** function inside callback, it returns all entries, including the one I added.
So I do not know if new entry was added by edit-config or it existed before inside configuration.

So my question is there any way of getting running configuration that does not contain my added entry (configuration that does not contain changes made in edit-config request)?
Meaning I need configuration that was before edit-config request, so I can get all data from that configuration and check if new test-entry is overlapping with some of the entries inside configuration.

Regards

**Comment by michalvasko** [comment]
Hi,
actually, it should be possible without much hassle. If you simply create a new session in the callback and use it to retrieve data, you should get the original data because the changes are stored only in the implicit callback session.

However, I am not sure from your issue whether you are aware of [this](https://netopeer.liberouter.org/doc/sysrepo/master/group__change__subs__api.html#ga613064e7a7431a30eff2b99b87af5348) function and the connected ones. They provide you with only the changes made so in the majority of use-cases it is the only data you need and you should not even call `sr_get_items()`, whether for the new or the old data.
