### ISSUE TITLE
Sysrepo(netopeer2-server) non-root startup, faces issues with sysrepo's "file system access control functionality"

### ISSUE THREAD

**Issue by starx1000** [sysrepo/sysrepo#2148]
Hi,

**Problems:**
  We recently try to import netopeer2-server as our netconf server and start it as non-root user to met security consideration.
  And netopeer2-server granted with linux capability cap_dac_override, looks like currently all things works normal.
>CAP_DAC_OVERRIDE
>Bypass file read, write, and execute permission checks.  (DAC is an abbreviation of "discretionary access control".)

Some issues about security:
 All SUB_SHM -> sr_sub* files in directory /dev/shm/ generated dynamically with permission 666, 
     we want it to be 660 or 600, which gives better security.
     As it is generated dynamically, now we have to start a POST script to monitor the /dev/shm/sr_sub* files and do "chmod 600" for it one by one..
     which looks not so good, and we think this could be solved with a better solution.

Other files e.g "shm lock file" generated before the server start and it is changed via chmod before the netopeer2-server start..

```c
/** permissions of main SHM lock file and main SHM itself */
#define SR_MAIN_SHM_PERM 00666

/** permissions of all subscription SHMs */
#define SR_SUB_SHM_PERM 00666
```
>https://github.com/sysrepo/sysrepo/blob/530e03ed819d6b2101b42c56cddaac2b0bfb9ae4/src/common.h.in#L188

----
**Suggestions**:
Here i thinks some changes for this that need your help:

1a.    Make this SR_SUB_SHM_PERM( and other 666 permissions) changeable via CMAKE just like SR_SHM_PREFIX_DEFAULT 

---
```c
/** permissions of main SHM lock file and main SHM itself */
#define SR_MAIN_SHM_PERM "@SR_SHM_PERM@"

/** permissions of all subscription SHMs */
#define SR_SUB_SHM_PERM "@SR_SHM_PERM@"
```

CMakeLists.txt
```
# shared memory file permission
if(NOT SR_SHM_PERM)
        set(SR_SHM_PERM 00666)
endif()
```

1b. Remove all umask(0000) in source code and make the permissions controllable via umask..
https://github.com/sysrepo/sysrepo/blob/8afd2e05cbc84ae16717d2718ff433c636673d7d/src/shm_sub.c#L58

```c
    um = umask(00000);

    shm->fd = shm_open(path, O_RDWR | O_CREAT | O_EXCL, SR_SUB_SHM_PERM);
    umask(um);
```

Another topic:
Since netopeer2-server implements full ietf-netconf-acm access control that bypasses sysrepo file system access control.
    Can sysrepo marks the " sysrepo file system access control" as a optional feature(or remove it) which can be controlled via CMAKE?
    Then we could disable it when build Sysrepo
     Still disable it would also need a default permission when creating the shm file, 
     it is mightbe 660?

-- 
>NACM

>This NETCONF server implements full ietf-netconf-acm access control that bypasses sysrepo file system access control. NACM is enabled by default, so users other than root will not be allowed to write any data but should be granted read and execute permissions unless the access was modified by a NACM extension. When deploying this server, it is strongly advised to configure NACM properly.

>https://github.com/CESNET/Netopeer2
--

Looking forward to your kind reply.  Many thanks..

Best regards.

**Comment by michalvasko** [comment]
Hi,
running *netopeer2-server* as a standard user is not supported right now, as you can see. Since it needs to access all *sysrepo* data (which can have various permissions and users as owners), it does not really make sense anyway (unless you use the DAC override, which is specific to Linux). Why exactly you cannot run the server as `root`?

> All SUB_SHM -> sr_sub* files in directory /dev/shm/ generated dynamically with permission 666,
we want it to be 660 or 600, which gives better security.

You are right about that. But it seems to me all these problems could be solved by a single new `cmake` option, which would allow to set the `umask` used by all the relevant calls in *sysrepo* API functions and would default to `00000`.

> Can sysrepo marks the " sysrepo file system access control" as a optional feature(or remove it) which can be controlled via CMAKE?

What exactly do you think would happen if the access control was disabled? Standard file access control is not optional and since *sysrepo* uses files for all the IPC, there is no way how to bypass it in *sysrepo*.

**Comment by michalvasko** [comment]
Hi,
> Many thanks, so this would need to introduce "NEW CMAKE OPTION"?
And small changes to sysrepo source code needed?
Could you please help to schedule to implement this ? thanks..
Or If you are busy with other emergency tasks, I have seen other methods in other threads there in libyang exists some processes like "others commit a merge request and you review and merge".
But I am a freshman to sysrepo, if you can provide some guideline docs would be better to solve this quicker...

That would be quite a simple change but I would like to make sure first that you have a use-case for it and I am not clear on that yet.

> netopeer2-server bypasses sysrepo file system access control...

... by means of requiring to be run as `root`, which simply takes advantage of the fact that `root` bypasses all permission checks. So it does not apply to you.

> then I think that disable "sysrepo file system access control" may also disable some root user checking inside sysrepo.c in
sr_session_get_user sr_session_set_user sr_set_diff_check_callback

You are right, there are a few explicit checks like this which could be skipped but those are not the main issue. The problem is that practically every API call needs to read/write to some file (many of them to more than one) and there is no way of skipping that.

So, in case every *sysrepo* applications (including any subscribers or just readers of configuration, simply any app that is linked with *sysrepo*) uses the same user, it should work. You should not need to call the functions that explicitly check whether the process owner is `root`. And to address any security concerns, allowing to change global `umask` should do the trick.

**Comment by starx1000** [comment]
Hi,
 many thanks.

>That would be quite a simple change but I would like to make sure first that you have a use-case for it and I am not clear on that yet.

Use case is 
  Start netopeer2-server and sysrepo-application(transportconfig.service) with non-root user _comsysnetconfig.
  with systemd control in Linux fedora. 
  Pre-configured TLS user and login used.  

Details below:

Background, virtual machine, Linux, fedora 32, systemd used for controlling services. 
1.	Create normal user “_comsysnetconfig”and group “_comsysnetconfig”  with shell /sbin/nologin and home directory /dev/null. 
2.	Using the user “_comsysnetconfig” to start netopeer2-server.service(Type=forking
) and transportconfig.service (sysrepo application)( Type=simple)
3.	Using the user “_comsysnetconfig” to start one-short service netopeer2-presetup.service, which is used to import YANG modules and XML configurations.
File permissions in /etc/sysrepo and /dev/shm/sr* is changed by “chown 600” in POST-actions of netopeer2-presetup.service.
4.	Unauthorized world-writeable files are not allowed; each file shall be writeable only by an associated user or group.
Command to be used for finding the offending (world-writeable) files: "sudo find / -type f -perm /002 | sort -u"
This means that file permissions with rw-rw-rw- is not acceptable. At least it is should be rw-rw-r--

   Then running files generated in /dev/shm, /etc/sysrepo/* should met the requirements.
   After the netopeer2-presetup.service, the remaing file permissions with “world-writeable”  should be only /dev/shm/sr_sub* files( which the permission is 666) and need to be changed to 600 to remove the world-writeable flags.

netopeer2-server.service 
```
Description=Netopeer2-server service
Requires=netopeer2-presetup.service
After=netopeer2-presetup.service

[Service]
Type=forking
Restart=on-failure
PIDFile=/var/run/netopeer2-server.pid
ExecStart=/usr/bin/netopeer2-server -v 3
User=_comsysnetconfig
Group=_comsysnetconfig
UMask=077

[Install]
RequiredBy=transportconfig.service
```

user details:

Name | Uid | Gid | Password | Shell | Home directory | Storage, Creator
-- | -- | -- | -- | -- | -- | --
_comsysnetconfig | 786 | _comsysnetconfig | * | /sbin/nologin | /dev/null | /etc

**Comment by michalvasko** [comment]
Okay, I have added the option for changing `umask`.

**Comment by starx1000** [comment]
hi, Thanks very much.
