### ISSUE TITLE
Query:sysrepo event notif subscribe

### ISSUE THREAD

**Issue by wangshdong** [sysrepo/sysrepo#2149]
Hi
I am facing some issues with some sysrepo features and need some clarification if possible.

I subscribe to Notif subscribe(sr_event_notif_subscribe) on the netopeer-service side，
parameter:
mod_ name:nc-notifications
xpath :/nc-notifications:replayComplete。

What method can trigger the subscription event to call the callback function。

**Comment by michalvasko** [comment]
Hi,
this notification is NETCONF-specific so you will not get it in any *sysrepo* application directly, it is only sent to NETCONF clients connected to the server. But instead of this notification, you will get a notification with `notif_type` `SR_EV_NOTIF_REPLAY_COMPLETE` when the [specified conditions](https://tools.ietf.org/html/rfc5277#section-3.3.2) are met.
