### ISSUE TITLE
Support for RFC 8808

### ISSUE THREAD

**Issue by mdoshi-com** [sysrepo/sysrepo#2183]
Hi,
Does sysrepo support RFC 8808 (https://tools.ietf.org/html/rfc8808)

Regards,
Meghna

**Comment by michalvasko** [comment]
No, `factory-default` datastore is not supported and cannot be added directly by an application.

**Comment by gotthardp** [comment]
Dobrý den / Hello, we are interested in contributing this feature. (In case it is not against some sysrepo concepts and in case nobody else is working on this.) Would you accept, or consider accepting a Pull Request (or a series of Pull Requests) introducing the `factory-default` datastore and the `factory-reset` RPC operation, please?
Of course, one can implement a factory reset also without direct sysrepo support, but since there is a RFC for this it might be nicer to have it "the standard way".

**Comment by michalvasko** [comment]
To our knowledge no one else is working on this feature and we would definitely appreciate PRs that would add this feature conforming to RFC 8808. Write me and email and we could discuss the exact design and how it would fit with *sysrepo*, thanks.

**Comment by michalvasko** [comment]
Supported in the latest *sysrepo*.
