### ISSUE TITLE
Order of hange data subscription callback calls?

### ISSUE THREAD

**Issue by iljatab** [sysrepo/sysrepo#2185]
$ yanglint --version
yanglint SO 1.9.15

$ sysrepoctl --version
sysrepoctl - sysrepo YANG schema manipulation tool, compiled with libsysrepo v1.4.86 (SO v5.6.2)

$ netopeer2-server -V
netopeer2-server 1.1.44
compile time: Oct  4 2020, 19:09:25

Hi Michal,

It looks like there's an issue with order of calling of change data subscription callbacks.

According to the docs for `sr_module_change_subscribe `:

*If there are changes made in several modules, the module order is determined by the **order in the changes** (it is kept).*

I applied changes for openconfig-network-instance and openconfig-interfaces in that order:

```
$ netopeer2-cli
...
> edit-config --target candidate --config=n.xml
OK
> edit-config --target candidate --config=i.xml
OK
> commit 
OK
>
```

So first we do changes for openconfig-network-instance and then for openconfig-interfaces.
However the first callback called in our application was for `openconfig-interfaces`, not for ` openconfig-network-instance`.

Did I miss something or is it a bug or maybe the doc is wrong?

[i.xml.gz](https://github.com/sysrepo/sysrepo/files/5391573/i.xml.gz)
[n.xml.gz](https://github.com/sysrepo/sysrepo/files/5391576/n.xml.gz)

Ilja.

**Comment by michalvasko** [comment]
Hi,
*sysrepo* doc is correct. When talking about changes, it naturally means changes applied by `sr_apply_changes()`. However, your use-case is issuing a NETCONF commit from the CLI. That translates into `sr_copy_config()` from `candidate` to `running` for *sysrepo* API, hence the difference in the behavior.

If you want to have a specific order, merge the 2 XMLs into one (with module data being order the way you want) and then issue `edit-config --target running` directly, then the order in the XML should be preserved because `sr_apply_changes()` is called.

**Comment by iljatab** [comment]
Thanks for clarification!
