### ISSUE TITLE
Q: Multiple subscriptions to the same node

### ISSUE THREAD

**Issue by peckato1** [sysrepo/sysrepo#2191]
Hello,

I'd like to ask a question regarding multiple operational data subscriptions on one node.
We use [ietf-hardware-state](https://tools.ietf.org/html/rfc8348#appendix-A) yang model. This model stores some hardware state info, like sensor readings. Unfortunately it stores all hardware (sensors) in one flat list (`/ietf-hardware-state:hardware/component`).

We'd ideally like to split subscriptions for this node between two connections (even two processes). One process would handle some of the hardware (this code needs to remain closed-source) and the second process would handle the rest of the sensors (some sysfs drivers, storage drives states, temperature measuring, etc.; this could be open-sourced). Also we are not fans of "big daemons" handling everything.
However, as I have understood (#1842) and tested (`[ERR]: Data provider subscription for "ietf-hardware-state" on "/ietf-hardware-state:hardware" already exists.`) we can't use multiple subscribtions to one node. 

I have managed to bypass this condition using predicates (e.g., `/ietf-hardware-state:hardware/component[name='b:*']` and `/ietf-hardware-state:hardware/component[name='a*']`). However, now I'm unable to query the `/ietf-hardware-state:hardware/last-change` node, it is not subscribed. Also it has some drawbacks: We'd have to somehow prefix the names of the sensors.

Is there a way how to use two subscriptions on one node for operational data? The behaviour I'd expect (or maybe *I'd wish*) is to run both callbacks and merge the obtained data (nodes).

Regards,
Tomas

**Comment by michalvasko** [comment]
Hi,
yes, I know this is now a completely valid use-case (it was not when I was writing the operational subscriptions initially) but allowing more subscriptions to a node would require some refactoring and I do not have the spare time for that right now. Also, the problem is only when you want to have the subscriptions in different processes, otherwise you can do the data merge in the callback.

So, I have this feature in my TODO but not with a high priority. One solution that may be possible is for the 2 subscriptions to subscribe to all the children of the `component` that they are providing the data for. But you would then need a 3rd subscription which would simply create empty `component` list instances. Also, I am not completely positive about this, but you may be able to hack your way around the limitation quite simply. Just use some redundant predicate on the second subscription (such as `[true()]`) because the main issue now is with the paths being exactly the same, it should not matter if they provide the exact same nodes.
