### ISSUE TITLE
questions

### ISSUE THREAD

**Issue by rydy** [sysrepo/sysrepo#2193]
Hi,
     I have the following questions:

    1, I plan to use c++(base on libyang-cpp) for sysrepo plugins development. Is that ok?
    2, Can't the 'sr_get_item/sr_get_items' interface be called during the 'sr_oper_get_items_subscribe' callback process?
    3,Is the libyang interfaces(lyd_insert、lyd_change_leaf) thread safe?
    4,Is the sysrepo interfaces(sr_set_item、sr_get_item) thread safe?

thanks

**Comment by michalvasko** [comment]
1. You are better off using the new [CFFI bindings](https://github.com/sysrepo/sysrepo-python) (even though not completely finished yet) because the current SWIG-based Python bindings will be deprecated.
2. It can.
3. It is as long as you are not modifying the same data tree. *sysrepo* getters will always provide you with your own copy of data.
5. Yes.

**Comment by rydy** [comment]
Hi
    I try to use  'sr_get_item/sr_get_items' interface  during the 'sr_oper_get_items_subscribe' callback process,  The return value is timed out all the time. Why is it happen? 
   key code as follow:
```
 /////////////////////////sr_oper_get_items_subscribe///////////////////////////
   //subscribe for providing the operational data(tx-array-carriers)
    rc = sr_oper_get_items_subscribe(s_session
        , "o-ran-uplane-conf-option8"
        , "/o-ran-uplane-conf-option8:user-plane-configuration/tx-array-carriers"
        , get_uplane_conf_tx_array_carriers_cb
        , NULL
        , SR_SUBSCR_CTX_REUSE
        , &s_subscription);
    if (rc != SR_ERR_OK) {
        goto error;
    }
  
//////////get_uplane_conf_tx_array_carriers_cb callback////////////////////////////
static int get_uplane_conf_tx_array_carriers_cb(sr_session_ctx_t *session
    , const char *module_name
    , const char *path
    , const char *request_xpath
    , uint32_t request_id
    , struct lyd_node **parent
    , void *private_data)
{
    (void)session;
    (void)module_name;
    (void)path;
    (void)request_xpath;
    (void)request_id;
    (void)parent;
    (void)private_data;

    int rc =SR_ERR_OK;

    SRP_LOG_INF("O-RAN-UPLANE-CONF-OPTION8: Get tx array carriers[%s] in the %s callback handling."
        , path
        , module_name);

    //get the value from sysrepo
    char* path_t = NULL;
    sr_val_t* values = NULL;
    size_t  value_cnt = 0;
    int  value_index = 0;
    struct lyd_node *tx_carries_list = NULL, *node = NULL;

    asprintf(&path_t, "/o-ran-uplane-conf-option8:user-plane-configuration/tx-array-carriers/*");
    rc = sr_get_items(session,  path_t, 0 , 0 ,  &values, &value_cnt);
    free(path_t);
    if (rc != SR_ERR_OK) {//error: sr_get_items  failed!User callback failed!
        SRP_LOG_ERR("O-RAN-UPLANE-CONF-OPTION8:  sr_get_items  failed!%s!", sr_strerror(rc));
    }

    return rc;

}
```

**Comment by michalvasko** [comment]
Right, that makes sense because in the callback that you are supposed to provide the data, you are actually asking the data from *sysrepo* (`sr_get_items()`), again, which can only call your callback, so you get a deadlock. You are supposed to generate the data instead, as in the [example](https://github.com/sysrepo/sysrepo/blob/master/examples/oper_data_example.c#L32).
