### ISSUE TITLE
The usage of sr_connect

### ISSUE THREAD

**Issue by myonlystarWang** [sysrepo/sysrepo#2201]
Hi michal,
    I have 10 modules and I have tried two ways of implementation:
    1. when I create the same number threads which service for each modules,I use `sr_connect`&`sr_session_start` individually in each thread,so there are 10 times connect&start
    2. when I pthread_create only one thread which service for all modules,I use `sr_connect`&`sr_session_start` individually in each module init as well,so there are the same number of times connect&start.

Is it different for multiple modules to use sr_connect&sr_session_start in single-threaded or multithreaded?
Should I use `sr_connect`&`sr_session_start` only once for all modules in **scenario 2**?But it works fine now.

BR,
wang

**Comment by michalvasko** [comment]
As is mentioned in the [docs](https://netopeer.liberouter.org/doc/sysrepo/master/html/conn_sess.html), you should always have only one connection in any application (because it is really expensive) and share it for all the threads. Because of that there are sessions, which are cheap and one actually needed for every thread.

**Comment by myonlystarWang** [comment]
Hi michal,
     Thanks for your quickly response and it is very useful for me!

BR,
wang

**Comment by myonlystarWang** [comment]
Finally, when closing a connection, all sessions and subscriptions made on this connection are automatically freed as well.
