### ISSUE TITLE
Modified system time reversal callback timeout

### ISSUE THREAD

**Issue by MickAbson** [sysrepo/sysrepo#2205]
Hi,
One of our model requirements is to modify Linux system time by editing the runtime. When I call the settimeofday function in the module_change callback to change the system time, it reports a timeout error.
After exploring the source code of sysrepo, I guess the exception is related to the pthread_cond_timedwait function.
I learned that the pthread_cond_timedwait function will return ETIMEDOUT directly if the system time suddenly increases during the waiting process.
Please help.
netopeer2-server:
`[INF]: SR: Published event "change" "o-ran-system-time" with ID 13 priority 0 for 1 subscribers.
[ERR]: SR: Callback event "change" with ID 13 processing timed out.
[WRN]: SR: Event "change" with ID 13 priority 0 failed (Timeout expired).
[INF]: SR: Failed processing of "rpc" event with ID 31 priority 0 (remaining 1 subscribers).
[ERR]: SR: Callback event "change" with ID 13 processing timed out.
[WRN]: SR: Event "rpc" with ID 31 priority 0 failed (User callback failed).
[ERR]: NP: Failed to send an RPC (User callback failed).
[INF]: NP: Session 5: thread 0 event new RPC.
[INF]: NP: Session 5: thread 0 event reply error.
`

netopeer2-cli:
`> edit-config --target running --config
ERROR
        type:     application
        tag:      operation-failed
        severity: error
        message:  Callback event "change" with ID 13 processing timed out.
`

version:
  netopeer2-server 1.1.34
  libsysrepo v1.4.66 (SO v5.5.8)
  libyang-1.0.176
  libnetconf2-1.1.26

**Comment by michalvasko** [comment]
Interesting problem that I am not sure I can help with. You can try setting the time on `SR_EV_DONE` event because then there is definitely less waiting on conditional variables. However, how to do this in a completely safe manner I do not know because there can be other *sysrepo* applications waiting. Maybe some separate process that would set the time at some reasonable time? Right after boot it should be safe, for example.
