### ISSUE TITLE
How to run netopeer2-cli operations from the scripts with out connection close

### ISSUE THREAD

**Issue by panniruram** [sysrepo/sysrepo#2206]
Hi @michalvasko,

Help me how to run multiple netopeer2-cli operations from the shall script.

Tried with below script, but once operations are completed session is exiting/disconnecting.
 With my scenario, need to execute bellow "user-rpc" operation periodically(every 60sec) to alive my supervision is operational with Server.

#!/bin/bash
netopeer2-cli  <<END 
connect
subscribe --filter-xpath /o-ran-supervision:supervision-notification --out out.xml
user-rpc --content test.xml --out out1.xml
END

**Comment by michalvasko** [comment]
Maybe someone else can provide better help than me because I am not that proficient in shell scripting. But I believe you can achieve this only by wrapping the whole *here* document in a loop of some sort. That way the CLI will connect/disconnect every 60s (if that is how you write the loop) but if you do not mind, it should work.

**Comment by panniruram** [comment]
Thanks
