### ISSUE TITLE
Key-less lists contain bogus elements when getting path + "//."

### ISSUE THREAD

**Issue by syyyr** [sysrepo/sysrepo#2210]
Hi, I found a bug with key-less lists. This is my schema:
```yang
module test-schema {
    namespace "http://example.com/ayyyy";
    prefix AHOJ;

    container users {
        config false;
        list userList {
            leaf name {
                type string;
            }
            leaf other {
                type string;
            }
        }
    }
}
```
Now I'll sub to the list and then retrieve some items of this list via `"/test-schema:users//.`.. This is the program I use:
```cpp
#include <iostream>
#include <libyang/libyang.h>
#include <sysrepo.h>
int main(int argc, char* argv[])
{
    sr_conn_ctx_t* conn;
    sr_connect(0, &conn);
    sr_session_ctx_t* sess;
    sr_session_start(conn, SR_DS_OPERATIONAL, &sess);
    sr_subscription_ctx_t* sub;
    auto cb = [] (sr_session_ctx_t *session, const char *module_name, const char *path, const char *request_xpath, uint32_t request_id, struct lyd_node **out, void *private_data) -> int {
        const auto data = R"(
{
    "test-schema:users": {
        "userList": [
            {
                "name": "John",
                "other": "Aneta"
            }
        ]
    }
}
)";

        *out = lyd_parse_mem(const_cast<ly_ctx*>(sr_get_context(sr_session_get_connection(session))), data, LYD_JSON, LYD_OPT_GET);

        return SR_ERR_OK;

    };
    sr_oper_get_items_subscribe(sess, "test-schema", "/test-schema:users", cb, nullptr, SR_SUBSCR_OPER_MERGE | SR_SUBSCR_DONE_ONLY, &sub);

    lyd_node* data;
    sr_get_data(sess, "/test-schema:users//.", 0, 1000, 0, &data);
    char* out;
    lyd_print_mem(&out, data, LYD_XML, LYP_WITHSIBLINGS | LYP_FORMAT);
    std::cout << out << "\n";

    return 0;
}
```
What gets printed out is the expected output BUT with some bogus elements:
```json
{
  "test-schema:users": {
    "userList": [
      {
        "name": "John",
        "other": "Aneta"
      },
      {
        "name": "John"
      },
      {
        "other": "Aneta"
      }
    ]
  }
}
```

I have found out, that this happens ONLY if you use `//.` in the path argument. Also, I always thought that `//.` was necessary so I always used, but without it, the bug doesn't happen. However, sysrepo/libyang accepts it, so I consider it a valid request. Also, if I delete the "other" field from the input data inside the callback, it works fine, so the bug appears only if there are at least two elements.

**Comment by michalvasko** [comment]
As for using `//.` for `sr_get_data`, I dare say it is well [documented](https://netopeer.liberouter.org/doc/sysrepo/master/html/group__get__data__api.html#ga48156c4baa7b99ab9da99e9fc2f5bb30). And regarding this bug, I would say it is a feature. By using `//.` you requested all the subtrees of `users`. I would argue that for your data the resulting output actually are all the subtrees.

The problem does not occur in lists with keys, for example, because *libyang* merge operation is able to put all the subtrees together into one tree again based on their keys. But for key-less lists, it is impossible to determine what are separate instances and what not so they are kept individually.

**Comment by syyyr** [comment]
I see. So the solution for me is to use a path without `//.`. Got it.

Is it really impossible to determine what are separate and non-separate instances? Correct me if I'm wrong, but what I THINK happens with `/test-schema:users//.` is that sysrepo calls `lyd_find_path` and gets three results: first, the whole `/test-schema:users` tree which would look the same as in my callback and then separate `/test-schema:users/userList/name` and `/test-schema:users/userList/other` results. Then, all of these are merged and that's where the duplicates happen. However, doesn't libyang know that the parent of the two latter results is the same as something that's already in the first result (simply by comparing pointers)? Looking at the algorithm in `sr_get_data`, I can see, that the first thing that happens is `lyd_dup` and AFAIK that will break the connection with the first result, so the information is lost. But if I understand correctly, the information about which trees belong to the same instance is available, it's just that sysrepo is not using, or maybe it is not able to use it.

For me, "common XPath expression //. is normally used to select all nodes in a data tree" doesn't mean I should get duplicates in the output. I can kind of understand that it is a feature from libyang's point of view, because with `lyd_find_path` what you get is a set of nodes and you could compare parents and find duplicates, because the results AFAIK would still be connected to the original. But if sysrepo merges the whole set together and produces duplicates, I feel that it's a bug.

**Comment by syyyr** [comment]
Anyway, I already have a solution for my problem, so it isn't THAT important to me, that this behavior changes. However I thought it was weird calling this a feature. I feel like it is a very unintuitive feature at best.

**Comment by michalvasko** [comment]
> I feel like it is a very unintuitive feature at best.

I definitely agree, hence the note in the docs not to use `//` because it produces these weird results. But there are no duplicates in some way, you must look at the output the following way.

This is how `/test-schema:users/userList` is printed:
```json
{
  "test-schema:users": {
    "userList": [
      {
        "name": "John",
        "other": "Aneta"
      }
    ]
  }
}
```

This is `/test-schema:users/userList/name`:
```json
{
  "test-schema:users": {
    "userList": [
      {
        "name": "John"
      }
    ]
  }
}
```

This is `/test-schema:users/userList/other`:
```json
{
  "test-schema:users": {
    "userList": [
      {
        "other": "Aneta"
      }
    ]
  }
}
```

So they are actually all the subtrees merged into one and then printed. The confusion is caused mostly by the fact that printing any nodes is always recursive meaning it is printed with all its children so the subtrees get lost.

**Comment by syyyr** [comment]
Ok, I think I understand the reason this happens. Last thing: I was wondering, if it can be solved from too, that is, if sysrepo can detect that some of the results are the same thing. It does "detect" lists with keys. It seems doable based on what I explained in my earlier comment (my second comment in this thread).

**Comment by michalvasko** [comment]
I do not think I understand what you mean. You are saying that if you select specific list instance with keys twice (using `//.`) for example, the instance appears twice in the data you get from *sysrepo*?

**Comment by syyyr** [comment]
No, like you said before, it works well (with no duplicates) with lists that have keys, so I was wondering, whether it could work the same way with key-less lists. I think it should be doable as long as you have access to the original tree.

But, if it isn't doable (or you don't want to implement that for whatever reason), then this issue can be closed. :)

**Comment by michalvasko** [comment]
Actually, ideally it should always work the way it does with key-less lists (based on the documentation which mentions selecting subtrees) but it does not really matter, I think. `lyd_merge` is simply used and that determines the current behavior, otherwise I would have to implement some special merge which just isn't worth it.
