### ISSUE TITLE
Query related data store lock

### ISSUE THREAD

**Issue by kavk7** [sysrepo/sysrepo#2232]
Hi Team,

Having a generic query as below.

If two threads are doing set/delete on same leaf, then calling "sr_apply_changes" API will take care of sequencing these edits internally without explicit lock by application ?

Say, 
from back-end application thread-1 is doing "sr_delete_item" on "ABC/leaf-1" and calls "sr_apply_changes".
same time, thread-2 doing "sr_set_item_str" on "ABC/leaf-1" and calls "sr_apply_changes".

Does sysrepo expect Application to lock data store in above case ? or "sr_apply_chagnes" API will take care of these scenarios ?

Thank you.

**Comment by michalvasko** [comment]
Yes, *sysrepo* should generally be thread-safe to a large degree meaning it should be completely thread safe except for some complex non-tested use-cases that must first be discovered in order to be fixed. But that should involve only calling various *sysrepo* functions in the callbacks. If you are not doing that, you should be completely safe.

**Comment by kavk7** [comment]
Okay, Thank you Michal.
