### ISSUE TITLE
Query: Example for sr_get_change_tree_next

### ISSUE THREAD

**Issue by satyakgec** [sysrepo/sysrepo#2239]
For example I have ietf_interfaces tree in my datastore.

At some point, if I change interface name then want to get notation for interface name only, but not the complete tree. How can we achieve that. 
As per sysrepo doc we can use "sr_get_change_next" or "sr_get_change_tree_next" in module-change callbacks. 

I will prefer "sr_get_change_tree_next" as here data are represented as libyang subtrees.
Can you help with some implementation example here (for api: sr_get_change_tree_next), I was trying below:

    const struct lyd_node **subtree = NULL;
    sr_change_iter_t *it = NULL;
    sr_change_oper_t oper;
    const char *   prev_value = NULL;
    const char *   prev_list =NULL;
    bool *prev_dflt = 0;
    rc = sr_get_changes_iter(session, "/ietf-interfaces:interfaces" , &it);
    if (rc != SR_ERR_OK)
    {
        SRP_LOG_ERRMSG("sr get changes iter failed");
        return rc;
    }
    rc = sr_get_change_tree_next(session,it,&oper,subtree,&prev_value,&prev_list,prev_dflt);  <<< Doubt
    char *data = NULL;
    rc = lyd_print_mem(&data, subtree, LYD_JSON, LYP_FORMAT|LYP_WD_ALL);

**Comment by michalvasko** [comment]
The idea is to get individual changes, not subtrees. So change this line
```C
rc = sr_get_changes_iter(session, "/ietf-interfaces:interfaces//." , &it);
```
and then you should rename `subtree` to simply `node` and work it that way, you will recursively get all the changed nodes in a subtree, so printing the node as subtree will get you misleading output.

**Comment by satyakgec** [comment]
> The idea is to get individual changes, not subtrees. So change this line
> 
> ```c
> rc = sr_get_changes_iter(session, "/ietf-interfaces:interfaces//." , &it);
> ```
> 
> and then you should rename `subtree` to simply `node` and work it that way, you will recursively get all the changed nodes in a subtree, so printing the node as subtree will get you misleading output.

Hi Michal,

Thank you for the input.
With below code I am able to get individual changes in a tree.

=============
rc = sr_get_changes_iter(session, "/ietf-interfaces:interfaces//." , &it);
if (rc != SR_ERR_OK)
{
    SRP_LOG_ERRMSG("sr get changes iter failed");
    return rc;
}
while(sr_get_change_tree_next(session,it,&oper,&node,&prev_value,&prev_list,&prev_dflt)==SR_ERR_OK)
{
    if ((oper == SR_OP_CREATED) || (oper == SR_OP_MODIFIED)) 
	{
        char *data = NULL;
        rc = lyd_print_mem(&data, node, LYD_JSON, LYP_FORMAT|LYP_WD_ALL);
		//call python module to print data json
        free(data);
    }
}
lyd_free(node);
==================

Could you please inform whether below understanding is correct (for ex: here  ietf-interfaces schema)
"/ietf-interfaces:interfaces//." ==> To get individual changes in the tree.
"/ietf-interfaces:interfaces " ===> To get complete tree along with the specific change.

**Comment by michalvasko** [comment]
Well, it is not really accurate. The main thing to understand is that you are simply using **XPath** to select specific nodes (which happen to be changes in this case). When you do, you get an iterator that you can use to get all the changes you selected, iteratively. That means that `/ietf-interfaces:interfaces` will get you only the change of that specific node, which is actually always `none`. However, because of how the iterator works (it skips these nodes), you do get a change, some child of this node that has a valid change other than `none` but strictly speaking, you should not get any. Also, you should not be printing the changes because, like I said, that will print misleading output that is actually confusing you and making it harder to grasp the general concept.
