### ISSUE TITLE
deviation with config giving error

### ISSUE THREAD

**Issue by mdoshi-com** [sysrepo/sysrepo#2259]
Hi,
We have a deviation statement added in commscope_3gpp-nr-nrm-nrcelldu.yang:

`deviation "/me3gpp:ManagedElement/gnbdu3gpp:GNBDUFunction/ep3gpp:EP_F1C/ep3gpp:attributes/ep3gpp:localAddress" {deviate replace {config false;}}`

When we try to do sysrepoctl -i commscope_3gpp-nr-nrm-nrcelldu.yang, 
we are getting following error (invalid keyword config):

```
 ERROR | SR stderr | sysrepoctl | Invalid keyword "config". |
| ERROR | SR stderr | sysrepoctl | Replacing a property that does not exist. |
| ERROR | SR stderr | sysrepoctl | Module "commscope_3gpp-nr-nrm-nrcelldu" parsing failed. |
sysrepoctl error: Failed to install module "/usr/local/cuduyang//commscope_3gpp-nr-nrm-nrcelldu.yang" (libyang error)
```

So if we change "deviate replace" to "deviate add" in the yang file, this works. But then we are getting error while running pyang (https://github.com/mbj4668/pyang/issues/715)

So we wanted to know, how "deviate add" works for sysrepo? Is sysrepo not using pyang tool? 
How to overcome this deadlock now?
zip attached with all dependent yangs.

Regards,
Meghna

[yang-files.zip](https://github.com/sysrepo/sysrepo/files/5687627/yang-files.zip)

**Comment by michalvasko** [comment]
Firstly, no, we are not using `pyang` at all, that would be incredibly slow. For all YANG-related tasks we use *libyang*.

Now, this issue is a result of some inconsistencies in RFC 7950 that were still not solved. According to the [grammar](https://tools.ietf.org/html/rfc7950#page-201) you can `add` or `replace` `config` using a deviation. But in case the `config` is supposed to always be implicit on a node (the only statement this would be true for) then it cannot be allowed to be used in `add`. So, right now *libyang* behaves according to the RFC and it will not be changed unless there are errata accepted that would change this behavior.

**Comment by mdoshi-com** [comment]
Hi Michal,
So as per your above explaination, if config is implicit on a node, then following should have worked, right? We just did "replace"

``deviation "/me3gpp:ManagedElement/gnb`du3gpp:GNBDUFunction/ep3gpp:EP_F1C/ep3gpp:attributes/ep3gpp:localAddress" {deviate replace {config false;}}`

Or did i not understand your explanation properly.

Regards,
Meghna

**Comment by michalvasko** [comment]
Actually, I was arguing that nothing in the RFC 7950 says implicit statements could be replaced with a deviation, I would think it says [the opposite](https://tools.ietf.org/html/rfc7950#section-7.20.3.2).

**Comment by mdoshi-com** [comment]
Hi Michal,
Following response we got from pyang team, 
`Config property is added implicitly. It can only be deviated replaced.`

So you are saying libyang has assumed that config is not there by default, so we have to use "deviate add" only.
Is this understanding correct.

So looks pyang and libyang have totally opposite interpretation of the rfc.

Regards,
Meghna

**Comment by michalvasko** [comment]
Yes, add should work normally. Also, `pyang` authors originally interpreted it the same way (that it must be set explicitly in order to be deviated with replace) but then one of the authors of RFC 7950 responded that `config` is inherited and set implicitly (you can find that answer in a referenced issue in the pyang issue you linked before).

That is not enough, however, we implement the standard and if there are mistakes in it, there should be errata filed and accepted. That did not happen for now so we keep the functionality as it is, conforming to the RFC.
