### ISSUE TITLE
sr_session_get_nc_id() returns zero

### ISSUE THREAD

**Issue by awesomenode** [sysrepo/sysrepo#2329]
Hi,

In callback registered by _sr_module_change_subscribe()_, when I call _sr_session_get_nc_id()_ for the callback provided session
it always returns zero despite the ID was set to a non-zero value on the change initiator session.
 
sysrepo version: 1.4.114
Note that it worked on sysrepo version 1.4.111.

Thanks!

**Comment by michalvasko** [comment]
Yeah, sorry about that, it is caused by a change. The function is still there (so it is not a NBC change) but the functionality changed, it is just a simple getter. What you want to use is a new function `sr_session_get_event_nc_id()`. It was a mess and I tried to fix it both in the code and the API, this is the result.

**Comment by awesomenode** [comment]
Thanks for the quick reply, using `sr_session_get_event_nc_id()` instead of `sr_session_get_nc_id()` works fine.
