### ISSUE TITLE
Possible to Update Sysrepo ietf-netconf@2011-06-01 to  ietf-netconf@2013-09-29 which the same as netopeer2-server

### ISSUE THREAD

**Issue by starx1000** [sysrepo/sysrepo#2342]
Hi,
  I found that sysrepo currently have imported ietf-netconf revision 2011-06-01,
  netopeer2-server will then replace it with 2013-09-29.
   
  Although this can works normally with update schemas,  I think it is a unnecessary  scenario since sysrepo and netopeer2-server are in the same group...
  
   this also causes a little delay in netopeer2/setup.sh for updating modules.
   
  Is that possible to update the sysrepo ietf-netconf.yang revision also to 2013-09-29 which is the same like netopeer2 server's revision? ..
  thanks. 
 module lists below:

https://github.com/sysrepo/sysrepo/blob/master/modules/ietf-netconf.yang
https://github.com/CESNET/netopeer2/blob/master/modules/ietf-netconf%402013-09-29.yang

**Comment by michalvasko** [comment]
This setup is intentional because the newer revision uses extension instances defined in *ietf-netconf-acm* and *libyang* requires the module to be implemented for this. We wanted to avoid the situation when, by default, *ietf-netconf-acm* would always be implemented (in NETCONF capabilities and everywhere) while its functionality not be supported.

However, the module no longer needs to be implemented in new *libyang* so this change makes sense once we migrate to it.

**Comment by starx1000** [comment]
thanks very much, I will close the ticket.
