### ISSUE TITLE
Procedure for upgrading Sysrepo

### ISSUE THREAD

**Issue by matth65** [sysrepo/sysrepo#2351]
Hello,

Is there a documented best practices/procedure for upgrading sysrepo and migrating the repository (.startup files, yang files, etc.) to a new version without losing the repository? 

I have a system installed with an older version of Sysrepo v1.4.87 from the development branch, and I'm attempting to upgrade to Sysrepo 1.4.104. However, the sysrepoctl and sysrepocfg tools fail with the following errors after upgrading the sysrepo binaries from v1.4.87 to v1.4.104. I'm not able to run the commands after upgrading the binaries to upgrade modules, etc.  The problem is resolved if I delete the sysrepo repository directory and start from scratch. The problem is also resolved if I remove sysrepo.startup. 

```
$ sudo ./sysrepoctl -l
[ERR]: Failed to find matching hash for a child of "module". (path: /sysrepo:sysrepo-modules/module)
sysrepoctl error: Failed to connect (libyang error)

$ sudo ./sysrepocfg -l
[ERR]: Failed to find matching hash for a child of "module". (path: /sysrepo:sysrepo-modules/module)
sysrepocfg error: Failed to connect (libyang error)
```

Regards,
Matt

**Comment by michalvasko** [comment]
No, there is no such information available for now. But it should be quite simply. As for YANG modules, you do not really have to anything with them, just so that they are available because you should always install all the modules again, you never know what changed exactly. As for data, you should simply perform `sysrepocfg --export=backup.startup -d startup` to "backup" the data and once you finish the upgrade, just do `sysrepocfg --import=backup.startup -d startup`. If you want to keep even `running` data, do the same for this datastore as well. But yes, to then remove the old no longer valid data you must do so manually, by simply removing the repository, for example.

**Comment by matth65** [comment]
Thank you very much for the quick response. The upgrade procedure that you provided works well.
