### ISSUE TITLE
sr_set_item_str api - way to handle callbacks for sr_module_change_subscribe

### ISSUE THREAD

**Issue by sandhyak88** [sysrepo/sysrepo#2359]
Hi,

Our plugin implementation has sr_module_change_subscribe for the model. Everytime sr_set_item_str is invoked, callbacks from sr_module_subscribe_change is invoked.

As part of notification, we have an explicit sysrepo edit for a parameter(done using sr_set_item_str), which in-turn is triggering sr_module_change_subscribe(which is invoking notification again-ending up with double notification).

    Is there any option to hide the trigger of sr_module_change_subscribe when triggering sr_set_item_str?
    Or
    Is there any way to identify sr_module_subscribe_change is being called as a part of edit from sr_set_item_str or edit-config from netopeer-cli?

Help would be appreciated !!!

Regards,
Sandhya

**Comment by michalvasko** [comment]
> Is there any option to hide the trigger of sr_module_change_subscribe when triggering sr_set_item_str?

There is not because it would be in direct conflict of the basic principles of *sysrepo*.

> Is there any way to identify sr_module_subscribe_change is being called as a part of edit from sr_set_item_str or edit-config from netopeer-cli?

There is some identification possible by calling `sr_session_get_event_sr_id()`, which should get you the *sysrepo* SID of the session that triggered the change. You should then be able to match this SID with the SID of the session in the notification callback and ignore. But for that you will need some additional data that you can either pass somehow to the callback using `private_data` or simply by a global variable.
