### ISSUE TITLE
Query: replayLogAgedTime support

### ISSUE THREAD

**Issue by iGovindY** [sysrepo/sysrepo#2365]
Hi 

does sysrepo+netopeer2 provide support for replayLogAgedTime defined in [rfc5277#section-3.3.1](https://tools.ietf.org/html/rfc5277#section-3.3.1).

`nc-notifications@2008-07-14.yang` file included with netopeer2 does not contain replayLogAgedTime leaf.

Am I missing something?

thanks,
Govind.

**Comment by michalvasko** [comment]
You are right, it should be there, I suppose, although we have not modified the module and it was downloaded from somewhere. In any case, the leaf is not mandatory and since *sysrepo* does not support any automatic aging of old notifications, it would never be set.

**Comment by iGovindY** [comment]
Thanks for the quick reply.

But as you mentioned in #2168
 > There is no clean-up mechanism implemented and there will be none in the near future. But it should not be too difficult to write your own script or something that will rotate the stored notifications if needed. 

If we have to write some script to rotate old notifications, then we should have a way to update `replayLogAgedTime`.
Otherwise, client will not be able to get the exact age of the currently stored notifications.

**Comment by michalvasko** [comment]
Right, I have added the leaf into the module as it should not cause any compatibility issues and was supposed to be there from the start. Now you can populate it yourself if you want to.

**Comment by iGovindY** [comment]
thanks for the fix, 

Since currently, all notifications for a yang are kept in a single file, I would like to know, how we could write a script/code which will rotate the old notifications every x interval,

like, remove all notifications that were generated before 12 hours.

**Comment by michalvasko** [comment]
I am sorry but you will have to figure it out yourself, should not be too difficult as the replay code is rather simple. It could definitely use some improvements but it seems the feature is not used much and we have other priorities. But if you were willing to provide a patch in a pull-request for this feature to be implemented in *sysrepo*, I would take a look and provide feedback.

**Comment by iGovindY** [comment]
Hi Michal,

Sure I can try to give a patch for notifications aging.
Do let me know your initial thoughts on the basic overview of notification aging support in sysrepo.

**Comment by michalvasko** [comment]
Okay, so here are my thoughts. There is not much to be said about the feature itself, but there are lots of configuration options and I suppose it is up to you which exactly you want to support. I will mention all I can think of and, ideally, you can support them all as well.

So, a separate thread (or a timer, simply something asynchronous) will definitely bee needed to perform the aging. The only daemon supplied with *sysrepo* is *sysrepo-plugind* so that is what I would use. You would probably not need to make it conditional by a `cmake` variable but is also a possibility.

As for all the configuration parameters, you should put them into `sysrepo-plugind` YANG module. The basic parameter would be the criteria for aging a particular module notifications. But a global settings could be defined as well, with the specific ones for a module, if set, taking precedence. I think both notification age and file size make sense, so one should be able to configure both and aging will occur once either applies. The question now remains how exactly to implement all this.

Firstly, what changes are needed in *sysrepo*. For any changes made in the stored notifications, the replay lock is needed so the least amount of changes is simply making this lock available in the API, I think. However, that would be a rather coarse solution so a better one would be having, generally, 2 functions, one for examining the notification state, the other modifying it in some way. For example, the *reader* could simply return information about notifications of a particular module, what is the oldest notification, how large are all the files with stored notifications, and so on, simply anything possibly relevant for the aging process. Based on this and the configured parameters, the *writer* would be called. To make it as generic as possible, its input should include either a timestamp before which all the notifications should be aged or the maximum size of the notification file and all the non-matching notifications would be removed and provided for a callback to this function, which could then do whatever it wants with them. Both the *reader* and *writer* should have an optional module name whether you want to perform the operation for all the modules or just a single one. Now that I think about it, the *reader* would not even be needed unless you want to also provide some state information defined in the YANG module, which could be useful.

The last issue is how exactly to implement the *writer* callback in `sysrepo-plugind`. Again going for the most generic approach I can think of, this callback should probably be in a plugin. The specific plugin file with this callback could be a new configuration parameter in the *sysrepo-plugind* YANG module. Also, a question is how exactly would the polling mechanism work. The simple approach would be periodic polling (periodic *writer* function calling) and this way checking whether any aging should be performed and immediately performing it. A more complex solution would be some push-based principle (using `inotify(7)`, for example). There is also the option of implementing the latter directly in *sysrepo* effectively having another kind of subscription on the stored notifications. That would be the most efficient solution but also the most difficult one to implement, I think (although most of that code is already in *sysrepo* and would just need to be adapted).

So, somehow implementing all this, a simple aging when some notifications would be simply removed (having no callback for the *writer*) would work out-of-the-box, only after enabling it by configuring the YANG module data. If even the callback was defined, arbitrary aging could be supported when the callback could do whatever it wanted with the notifications, such as compressing them and writing into a file somewhere, for instance. Now, as you see, it is a lot of work to do properly (reason why we have not implemented it ourselves) but like I said, it is up to you. But if you decide to go for this, I would definitely advise to start with the *sysrepo* *writer* and *reader* functions mentioned before. They should not be too complex and, most importantly, have a functionality of their own so tests for them can be written. If you need this notification aging and do not want to bother with all the `sysrpeo-plugind` stuff, you can implement only those 2 functions (or the stored notification subscription, of course) and then write your own daemon using those, we would still appreciate that and it would simplify writing any notification aging shipped with *sysrepo* if we (or someone else) decide to do it later.
