### ISSUE TITLE
Get username of the rpc call

### ISSUE THREAD

**Issue by samuele-az** [sysrepo/sysrepo#2369]
Get the username of the rpc call

I need to get the rpc call username, in sysrepo plugin. I connected the rpc cb, when I get the rpc call, I try to take the user from session, with the following functions:
`sr_session_get_user(session)`
`sr_session_get_event_user(session)`
but I always get "root" as user.

For this test I used the "netopeer2-server" and "netopeer2-cli". In the cli I'was connected with "myuser":

> connect --login myuser
Interactive SSH Authentication
Type your password:
Password: 

How can I get the username "myuser" in the sysrepo rpc callback?

**Comment by michalvasko** [comment]
Right, as it is now there is no (simple) solution for this because the `event` information you get in the callbacks is simply read from the originator session so it would have to have the NETCONF user set. But if it did, all the operations would be limited by *sysrepo* access control for that user meaning NACM would not be applied the way it should. In any case, *netopeer2* handles this by matching NETCONF session ID to NETCONF sessions, which have their username set correctly. And you can read NETCONF session ID in the callbacks using `sr_session_get_event_nc_id()`.

**Comment by samuele-az** [comment]
Yes I noticed that it is possible to retrieve the NETCONF session ID, from `sr_session_get_event_nc_id()`
Sorry, but I'm not expert with NETCONF, I couldn't find a way to retrieve NETCONF session from ID, in my sysrepo plugin.
Could you suggest me a method to do it?

**Comment by michalvasko** [comment]
> Could you suggest me a method to do it?

There is none. I was talking in general about how this problem is overcome in *netopeer2* itself. I am sorry but I can only suggest you make some modifications on your own to get the username because a proper solution would most likely need some new functionality in *sysrepo*.

**Comment by samuele-az** [comment]
Does this mean that sysrepo can't support O-RAN models? I am encountering this limitation against o-ran-usermgmt, for changing the user password. Or am I misunderstanding the meaning of the model?

**Comment by michalvasko** [comment]
I do not know anything about O-RAN models nor do I really care. They can require only YANG or NETCONF standardized features, anything else depends only on the implementation. And *sysrepo* callbacks are wholly in the implementation-specific area.

**Comment by maxrossello** [comment]
Hi @michalvasko, I see your point, but if I understand the problem properly, O-RAN assumes that the user doing the RPC is known, as it is actually known at Netopeer2. But AFAIK Netopeer2 does not publish a southbound API: it connects to Sysrepo only. When using the connection info through Sysrepo, the RPC user is faked to root for internal reasons, so it does not provide the same info to the plugins as available at NETCONF protocol. This is like omitting data that is needed to manage the whole NETCONF, therefore this "implementation specific side" is not powerful enough in its APIs to represent the whole story. What is the scope to provide the session user to the callback, if it is always root, then?

I believe that this limitation is not preventing O-RAN only. In any case, I am not sure if you are aware about the size of the 5G industry, but I can say that big players are looking at open source solutions to create open environments. Unfortunately, as you say, there's no workaround possible, so this specific limitation would put Sysrepo aside from this opportunity to spread as a component within a de-facto standard and make business.

If you just point to the relevant sections of code, is there any chance that this problem can be solved by someone else and you accept a merge request then?

Thanks a lot

**Comment by michalvasko** [comment]
> This is like omitting data that is needed to manage the whole NETCONF, therefore this "implementation specific side" is not powerful enough in its APIs to represent the whole story.

Probably useless to argue more because this is not the point anyway. The username should be available in the callbacks, which I do agree with. And because of this, despite not mentioning it, I have already added this feature into my TODO and will reply here once it is implemented. But we are very busy this month so hopefully at the beginning of the next I will be able to look at this.

> If you just point to the relevant sections of code, is there any chance that this problem can be solved by someone else and you accept a merge request then?

We always accept patches that meet our quality standards but I think this particular feature would be better written by us because there are some further requirements that need to be considered. Specifically, *sysrepo* is not limited only to working with *netopeer2* or any NETCONF server for that matter, so a generic solution is required.

**Comment by maxrossello** [comment]
> And because of this, despite not mentioning it, I have already added this feature into my TODO and will reply here once it is implemented. But we are very busy this month so hopefully at the beginning of the next I will be able to look at this.

this is great news @michalvasko , thanks a lot!
It is not a matter of days... important is that this is recognized as needed.
Thanks again!

**Comment by michalvasko** [comment]
Should now be supported in *sysrepo* v2.

**Comment by matth65** [comment]
Hi @michalvasko, I know this is an old thread. Specifically, which APIs were added for this feature, where the username is made available to the callbacks?

Best Regards,
Matt

**Comment by michalvasko** [comment]
Yes, it is related and described in detail [here](https://github.com/CESNET/netopeer2/#sysrepo-callbacks).
