### ISSUE TITLE
How is module-set-id is maintained?

### ISSUE THREAD

**Issue by matth65** [sysrepo/sysrepo#2378]
Hello,

I have a question about how the module-set-id is maintained when Netopeer2 and other Sysrepo change handler applications are not running (e.g., during install or upgrades of the NETCONF server).  I expected that using sysrepoctl to uninstall, install, or upgrade a YANG module would increment the module-set-id. However, I do not see the module-set-id increase when adding, removing, or upgrading modules in some cases. 

Is there a way to force the module-set-id to increment for these scenarios?

Regards,
Matt

**Comment by michalvasko** [comment]
Yeah, the ID is updated only within a single context and its changes and since *sysrepo* does not allow the context to change, this mechanism is completely bypassed. It should be fixed in *libyang* version 2 and then in *sysrepo*, once it uses it, but the current *sysrepo* and *libyang* will stay the way they are now, it is too big a change.

**Comment by matth65** [comment]
OK, thank you for the information.
