### ISSUE TITLE
Problem with sending notification

### ISSUE THREAD

**Issue by Volodymyr-Bahriy** [sysrepo/sysrepo#2397]
Hi,

I'm using Netopeer2 + Sysrepo (v1.4.58) as a netconf server solution for an application that handles some ORAN yang modules...

I have got an issue with sending notification `<supervision-notification xmlns="urn:o-ran:supervision:1.0"/>` - Failed to send notification.
The chain of method calls is as follows:
received noreply message - NetConfAgent::notifyEvent -> **SysRepoSession::eventNotifSend -> sr_event_notif_send -> sr_event_notif_send_tree**...
And in src/sysrepo.c (L4618)  new error info (SR_ERR_NOT_FOUND) added in case of positive scenario when the subscriber for notification is found:
```
    if (notif_sub_count) {
	sr_errinfo_new(&err_info, SR_ERR_NOT_FOUND, NULL, "Number of subscribers found:  %d.", notif_sub_count);
        /* publish notif in an event, do not wait for subscribers */
        if ((tmp_err_info = sr_shmsub_notif_notify(notif, notif_ts, session->sid, (uint32_t *)notif_subs, notif_sub_count))) {
            goto cleanup_shm_unlock;
        }
    } else {
        SR_LOG_INF("There are no subscribers for \"%s\" notifications.", lyd_node_module(notif)->name);
    }
```
It looks like the notification was handled in an inappropriate way after that. 

So, Can we omit the error info setting there?..

Thank you in advance for your support!

**Comment by michalvasko** [comment]
I am seriously confused. I am guessing you are asking me whether you can remove the `SR_ERR_NOT_FOUND` `error_info` creation in the code snippet you have there (because there is nothing like that on [sysrepo.c:4618](https://github.com/sysrepo/sysrepo/blob/v1.4.58/src/sysrepo.c#L4618)). As you can also see in the original code, it is not supposed to be there so you must have added it. And yes, it is causing the failure of the function.

**Comment by Volodymyr-Bahriy** [comment]
Ohh,
Yes, a forked version of sysrepo was used (my L4618 - origin L4608)... and, probably, that line was added accidentally by another contributor.
Thanks for the quick reply!
