### ISSUE TITLE
How to delete node in libyang:Data_Node or struct lyd_node?

### ISSUE THREAD

**Issue by MickAbson** [sysrepo/sysrepo#2403]
Hi,
  I call the function lyd_parse_path () to convert an XML file into a lyd_node tree, which I further construct into a libyang::S_Data_Node object.
Now I want to delete some nodes of the tree. How do I do this?
What I mean is how to delete a node from a lyd_node tree or libyang::S_Data_Node object. Is there an API that can be called?

**Comment by michalvasko** [comment]
Just call `lyd_free()` on the node (subtree) you want to free. But as for the C++ bindings, I guess you are supposed to simply call `Data_Node::unlink()` but there is a high chance it will not work correctly because the memory management of data trees in C++ is a complete mess. If you need to edit data trees, just use the C structures.
