### ISSUE TITLE
how to run OVEN example in netopeer2

### ISSUE THREAD

**Issue by xheke** [sysrepo/sysrepo#2408]
Hi Michael，

I can not find out netopeer2 doc like sysrepo.
I want to learn how to run `oven` example in netopeer2-client，
such as subscribe notification,  invoke rpc and edit config, etc.

invoke oven rpc in sysrepo：
```
<insert-food xmlns="urn:sysrepo:oven">
    <time>on-oven-ready</time>
</insert-food>
```

edit config in sysrepo：
```
<oven xmlns="urn:sysrepo:oven">
    <turned-on>true</turned-on>
    <temperature>200</temperature>
</oven>
```

subscribe notification in sysrepo：

`./notif_subscribe_example oven`

Could you kindly help to paste some simple netopeer2-client code like sysrepo above for test?

Thanks in advance,

**Comment by michalvasko** [comment]
There is no separate info because doing this is trivial, provided you know some basics about NETCONF.
 - to execute an RPC, use the `user-rpc` command and paste the same XML
 - to apply an edit, use the `edit-config` command (RPC) with the same XML
 - to subscribe to `oven` notifications, use the `subscribe` command, with stream `oven`.

**Comment by xheke** [comment]
thanks Michal, I got it.
