### ISSUE TITLE
NETCONF RPC post processing functionality

### ISSUE THREAD

**Issue by meghna-doshi** [sysrepo/sysrepo#2420]
Hi,
We have one requirement to do some actions (like datastore cleanup and restart application) once "reboot" rpc returns.
We are using  RPC subscribe (m_subscribe->rpc_subscribe (xpath, callback) for subscription.
Is there any way to tell application that RPC has completed and now application can take its actions.

Regards,
Meghna

**Comment by michalvasko** [comment]
No, such a functionality is not provided. However, you can quite easily implement this yourself. In the callback for the `reboot` RPC you can send a custom notification (`reboot-complete`) just before it returns. Then you can simply subscribe to this notification and learn when the reboot is completed.

**Comment by meghna-doshi** [comment]
Hi Michal,
Thanks, yes even we were thinking in those lines, just wanted to check if calling of a notification inside a RPC callback is fine or not.

Regards,
Meghna

**Comment by michalvasko** [comment]
It is fine, all such limitations should be [documented](https://netopeer.liberouter.org/doc/sysrepo/master/html/group__rpc__subs__api.html#ga1154cf0ed7f1284d953d614538ad8d7e).

**Comment by iGovindY** [comment]
Hi Michal, 

in case of `reboot-complete` notification callback we thought of deleting `/ietf-netconf-server:netconf-server/listen` config so that `netopeer server` stops listening on 830 port and connection to already connected clients are closed gracefully.

but what we observe is after deleting listen config, `netopeer server` didn't stop listening on port 830 until the connected client didn't initiate the `disconnect` command.

The query is how to gracefully close all connections with the client and stop the server from listening on port 830 before going for a reboot?

**Comment by michalvasko** [comment]
Based on what you said I do not know why the server would not stop listening, you should be able to change `running` configuration normally from an RPC callback. However, I do not think that helps you much and the best thing you can probably do is to terminate the server by sending it SIGTERM, it should do whatever it can to stop gracefully. But doing that from an RPC callback it is executing may be tricky, I do not know.
