### ISSUE TITLE
process  get operation data as edit-config

### ISSUE THREAD

**Issue by xheke** [sysrepo/sysrepo#2444]
If we want handle operation data one by one,  
does there has the same function in `sr_oper_get_items_subscribe` like `sr_get_changes_iter/sr_get_change_next` in `sr_module_change_subscribe`?

Thanks,

**Comment by michalvasko** [comment]
I am not sure what exactly you want because there is not much common in how `sr_oper_get_items_subscribe()` and `sr_module_change_subscribe()` work. But you probably want to nest the subscriptions, which is possible and documented [here](https://netopeer.liberouter.org/doc/sysrepo/master/html/subs.html#oper_subs).

**Comment by xheke** [comment]
Thanks Michal, I got it.
