### ISSUE TITLE
Error in ./application_changes_example for libyang

### ISSUE THREAD

**Issue by ankit7gup** [sysrepo/sysrepo#2451]
Hi,

While using latest sysrepo(master)-libyang(devel/master) version, getting below error while running example.

 Application will watch for changes in "examples".
[ERR]: Regular expression "[a-zA-Z_][a-zA-Z0-9\-_.]*" is not valid ("[a-zA-Z_][a-zA-Z0-9\-_.]*": unrecognised compile-time option bit(s)).

**Comment by michalvasko** [comment]
Hm, that is quite strange. How could there be an unknown option if you compiled *libyang* with PCRE2 header for the same installed version? Unless you did not. In any case, what `pcre2-devel` package version are you using?

**Comment by ankit7gup** [comment]
-- Found PCRE2: /usr/local/lib/libpcre2-8.so (found suitable version "10.36", minimum required is "10.21")

**Comment by michalvasko** [comment]
What distribution are you on? Like I asked, what devel package version are you using, not the version of the installed library. But based on the path I would say you have compiled and installed *libpcre2* yourself because probably only an older version package was available for your distribution. That would also explain what is happening, in case the old package is still installed. You have compiled *sysrepo* with headers from the older package but actually linked against the new library or vice-versa. Please make sure you have no incompatibilities like this, I cannot think of any other reason for this error.

**Comment by ankit7gup** [comment]
Yes, it worked now. Thanks  for the info and clarification.

**Comment by rydy** [comment]
> What distribution are you on? Like I asked, what devel package version are you using, not the version of the installed library. But based on the path I would say you have compiled and installed _libpcre2_ yourself because probably only an older version package was available for your distribution. That would also explain what is happening, in case the old package is still installed. You have compiled _sysrepo_ with headers from the older package but actually linked against the new library or vice-versa. Please make sure you have no incompatibilities like this, I cannot think of any other reason for this error.

hello, for Centos7，How do I get sysrepo to use the same header files and libraries？

**Comment by michalvasko** [comment]
Ideally, have only a single version of a library/headers installed. If not possible, you can always specify the paths for `cmake` so that it uses the correct ones. You can easily find some detail on that with a bit of searching or even reading the `FindX` `cmake` modules.
