### ISSUE TITLE
 In the abort event process, the user callback is not called

### ISSUE THREAD

**Issue by yangtian127** [sysrepo/sysrepo#2452]
When the user callback returns an error, enter the abort processing process.

functiion sr_changes_notify_store:
```C
/* publish final diff in a "change" event for any subscribers and wait for them */
if ((err_info = sr_shmsub_change_notify_change(mod_info, orig_name, orig_data, timeout_ms, cb_err_info))) {
        goto cleanup;
}
if (*cb_err_info) {
        /* "change" event failed, publish "abort" event and finish */
        err_info = sr_shmsub_change_notify_change_abort(mod_info, orig_name, orig_data, timeout_ms);
        goto cleanup;
}
```

In the abort process, the abort event is not passed to the user callback.

for example， <edit-config>:
```xml
<test>
<test-list>
  <name>1</name>
</test-list>
<test-list>
  <name>2</test>
</test-list>
</test>
```
create :/test/test-list[name='2'] return an error
When the user returns an error, all distributed table entries should be rolled back.
But in fact, only the <running> is rolled back and not distributed to the user plug-in callback.
This will lead to the inconsistency between the <running> and the actual running configuration data.

In the old version, when the user callback returned an error, the callback rolled back all the configuration data.

**Comment by michalvasko** [comment]
This is a [documented feature](https://netopeer.liberouter.org/doc/sysrepo/master/html/group__change__subs__api.html#ggad007e862874bda7141c58ca72d8c1067a6a7bc850ab09aeb7385a0e10f2391d3f). The problem is that one callback is usually handling several changes and it may fail because any of those changes fails to be applied. When a callback is called with `SR_EV_ABORT`, **all** the relevant changes are rolled-back (there is no way of knowing which were applied and which not). You have this information only in the callback itself when it fails. So, instead of simply returning an error, the failed callback should roll-back **only** the changes that were actually applied.
