### ISSUE TITLE
C++ bindings roadmap

### ISSUE THREAD

**Issue by andrei-pavel** [sysrepo/sysrepo#2460]
Hello,

1. Do you still plan to release the C++ bindings repo compatible with sysrepo 2? If so, do you have an approximate release date?
2. If we start integrating C++ bindings from sysrepo 1, is there any telling if these will remain roughly the same in v2 i.e. not many changes required?
3. Would you rather recommend that we instead use the C API in a C++ application?

Regards and thanks in advance,
Andrei Pavel

**Comment by michalvasko** [comment]
1. Yes, the plan is to have C++ bindings at some point but they will not be developed directly by us but probably @syyyr. And we cannot talk about any release date for now.
2. No idea but there should not be many changes needed. It is *libyang* C++ bindings that need to be reworked because they do not work well but that will probably be mostly transparent.
3. Yes, that sounds like a good idea because there is absolutely no telling when will the C++ bindings be ready.

**Comment by MickAbson** [comment]
Hello
     One year has passed, is the C++ binding compatible for sysrepo2 released now?

Regards and thanks in advance,
Fizz

**Comment by MickAbson** [comment]
@michalvasko 
Hello
One year has passed, is the C++ binding compatible for sysrepo2 released now?

Regards and thanks in advance,
Fizz

**Comment by michalvasko** [comment]
It is, to my knowledge, but this is a question for the authors of those bindings, not me.

**Comment by jktjkt** [comment]
@MickAbson see https://github.com/sysrepo/sysrepo-cpp

**Comment by MickAbson** [comment]
@jktjkt Thanks.
