### ISSUE TITLE
Annotations support in sysrepo

### ISSUE THREAD

**Issue by ankit7gup** [sysrepo/sysrepo#2462]
Hi Michal,

Wanted to know if annotations are supported in the latest sysrepo version?
If no, then if there is any plan to add in near future.

Thanks!

**Comment by michalvasko** [comment]
I suppose you mean storing your own custom annotation instances with values in datastores. They are used extensively internally but user annotations are not supported because no one ever requested it and hence there is also no plan to. The problem with them is also that there is no standardized way of handling them (how to create/modify/delete them exactly?).

**Comment by ankit7gup** [comment]
ok, I may give you one use case which is of interest to me as well, Let's say we have a set of base yang models which we may consider as a standard and cannot modify directly. Over it multiple vendors may want to limit/modify some info as per their own limitation or feature(s) they support. In that case we don't modify the base yang models and over it we apply the vendor specific data model individually. In such scenarios we can have annotations to help us.
For this we can have support for deviations and annotations..
