### ISSUE TITLE
Data set with sr_set_item_str not visible when getting operational data

### ISSUE THREAD

**Issue by kreivk** [sysrepo/sysrepo#2464]
Hello,

Currently, we are working with a yang model that has it's only container and most leafs inside of it labeled as **config false**. That model is o-ran_software_management, which represents a software inventory with multiple slots:
[o-ran-software-management.txt](https://github.com/sysrepo/sysrepo/files/6608658/o-ran-software-management.txt)

At the start of the program, we load the initial data for the model by parsing it from an xml file and applying it to running datastore with sr_apply(). Since most of the model is **config false**, we have made an operational data callback that parses the same initial xml to return data on get. When sr_get_data() function is called, the operational callback is called in the background and returns the data from the xml.

Now, we have also implemented an rpc handler that simulates installation of new software. This results with new data being set in the model using sr_set_item_str() and sr_apply(). If we then try to get these changes with sr_get_data() (to print them or something similar), they won't be visible since operational data callback will be called in the background and return the initial data from the xml.

We need to return data that actually reflects the current state of the model when get is performed. Do you have any suggestion how we could resolve this?

Thank you in advance,
Krešimir

**Comment by michalvasko** [comment]
One of the possibilities should be to switch the data in *pull* and *push* operational data. Meaning you can set the initial data as *push* (sr_set_item_str() and sr_apply()) and provide the new RPC data as *pull* (subscribe with a callback) because *pull* data always overwrite *push* operational data. You could also use single method in both cases. Later *push* data overwrite previous data and nested subscribed *pull* data overwrite the data provided by their tree parents.
