### ISSUE TITLE
Release notes on netconf 2.0 modules

### ISSUE THREAD

**Issue by meghna-doshi** [sysrepo/sysrepo#2483]
Hi,
We are looking for any release notes kind of document, summarizing high level changes done from 1.0 to 2.0 versions of 
1. libyang
2. netopeer2
3. sysrepo
4. libnetconf2.

Please share if you have any such document.

Regards,
Meghna

**Comment by meghna-doshi** [comment]
Hi,
Can somone please update something here.

Regards,
Meghna

**Comment by michalvasko** [comment]
I am sorry but there are too many other older issues I am working on, just wait a few more days, I am doing what I can.

**Comment by michalvasko** [comment]
So, I finally got to your question. Unfortunately, there are no official full changelogs because there are actually not that many changes, from the user perspective. For *libyang*, the most important ones are:

- data tree editing is much faster and works with non-validated and even invalid data trees
- data nodes are always ordered based on the order in YANG schemas (no performance penalty)
- O(1) complexity of XPath evaluation of simple (the most common) expressions
- many complicated use-cases in data/schema hitting the limits of libyang v1 should now work correctly
- new comprehensive diff format with new possibilities

As for the other projects, there should be something mentioned in the GitHub releases ([sysrepo](https://github.com/sysrepo/sysrepo/releases/tag/v2.0.1)) but they are generally minor changes and the most important one is always that they are based on *libyang* v2 and not v1.
