### ISSUE TITLE
Question about SR_EV_ENABLED

### ISSUE THREAD

**Issue by Abrahamma97** [sysrepo/sysrepo#2489]
Hi @michalvasko ,
I need to use a Sysrepo  Running and Startup along with Netopeer and have a few functionalities which I will be implementing as below. Can you say if this is the right manner.

1)Initial configuration to be in sysrepo is given by
sysrepocfg --import=startup.xml -d startup (Netopeer alternative will not be considered here)

2)For applications which need  to notify change during initial boot and change in every boot of device(Running copied internally by Sysrepo)
I will be using SR_EV_CHANGE and SR_EV_ENABLED together as they give the same functionality here i.e to check if either has come by using the  SR_SUBSCR_ENABLED flag while subscribing.

3)For applications which need  to notify change during initial boot and on working with netopeer but never with starting of next boot we should not use  SR_SUBSCR_ENABLED flag with subscribe right.

Can you please confirm My observations and Comment whether this is the correct manner or is there a better way when you have time.

**Comment by michalvasko** [comment]
Yes, I think what you wrote makes sense. Note that `SR_EV_ENABLED` is meant to be used for applications that always need their initial configuration after starting. Normally, they would have to retrieve the current data in *sysrepo* and configure themselves based on that, so that their behavior is consistent with the configuration in *sysrepo*. But this event allows them to ignore this initial setup because they will always get the full configuration in their standard subscription for configuration changes.
