### ISSUE TITLE
Use sr_set_item_example question

### ISSUE THREAD

**Issue by alexjiao2021** [sysrepo/sysrepo#2491]
Hi,
When trying sr_set_item_example to change values in `ietf_interfaces` module, there is an error reported as below:
![image](https://user-images.githubusercontent.com/84055495/122908357-9becd500-d386-11eb-8b01-896914b9e926.png)
I'm not sure where is this XPATH not right, seems the same as in `application_changes_example`.
Thanks.

**Comment by michalvasko** [comment]
Look at the first line when calling `sr_set_item_example`. Most likely, the single quotes `'` got lost in the shell and the expression is not correct without them. Try enclosing the whole XPath into `"`.

**Comment by alexjiao2021** [comment]
Thanks, it works, but it seems the print for `application_changes_example` not changing.
![image](https://user-images.githubusercontent.com/84055495/122911882-56320b80-d38a-11eb-80f0-e1c75d11fab4.png)

**Comment by michalvasko** [comment]
That is because you are setting the exact same value, in a strange manner as well. You have specified `name` as `KEYS_if_xyz_vlan0`, such an interface is already there according to the output. What is more, you are then trying to set the `name` by specifying its value separately, which is ignored in this case. You cannot set list keys separately, they must always be in a predicate for the list instance.

**Comment by alexjiao2021** [comment]
Thanks Michal.
Last question:
Is there any methods to set items with prefix using the examples?
For example, I want to set `type` as in below xml:
`<type xmlns:ianaift="urn:ietf:params:xml:ns:yang:iana-if-type">ianaift:l2vlan</type>`
But I got error as below:
![image](https://user-images.githubusercontent.com/84055495/122922011-c3976980-d395-11eb-9797-20bd1b5eb594.png)

**Comment by michalvasko** [comment]
In API, the JSON format of values is always expected, you are using XML. In JSON format you simply use the module name as the prefix, such as `iana-if-type:l2vlan`.
