### ISSUE TITLE
Can't access enum value via sysrepo C++ binding

### ISSUE THREAD

**Issue by vadim-platonov** [sysrepo/sysrepo#2493]
libyang has ability to access (set and get) enum value via libyang::Value::enm()->value(), but sysrepo has ability to access (set and get) only enum name, but not enum value.

This is not a bug, but request for helpful functionality.

**Comment by michalvasko** [comment]
You can get an `enum` value with information about its `value` using [this function](https://github.com/sysrepo/sysrepo/blob/libyang1/bindings/cpp/src/Session.hpp#L92).

**Comment by michalvasko** [comment]
> consider it will be better to have get enum value in sysrepo API.

That would require changing the `sr_val_t` structure and making it larger as there is no more space, to include both the enum name and value. So it is unlikely, since you can always use the preferred *libyang* structures.

> But how could I set enum value to the sysrepo storage?

There is probably only one way and it does not make much difference whether it is performed internally or you write your own function for it. You simply want to transform the value into enum name, which you can always do if you have the value and the schema node (type) of the data.

**Comment by vadim-platonov** [comment]
OK, thank you!
