### ISSUE TITLE
concurrent access of data store

### ISSUE THREAD

**Issue by saorav21994** [sysrepo/sysrepo#2495]
I am having 2 sessions with netopeer2-server at 2 different ports. 
Now I want to use 2 edit-config concurrently one from each session, but the server returns the following error for 1 of them - 
"locking subscription of “ietf-netconf-nmda:get-data” failed : previous event rpc with ID <id> was not processed."
screenshot attached.

my query is that is there any way I can use edit-config concurrently because both the edit-config requests are using completely diff yang modules (one of openroadm and another of openconfig) so they will never try to modify on the same data.
I tried going through other issues of similar nature but found no luck.
Any help would be greatly appreciated.
![git](https://user-images.githubusercontent.com/13297826/123089014-0b74ca00-d444-11eb-8d36-b469292bf2f3.PNG)

**Comment by michalvasko** [comment]
Not sure how relevant those `edit-config`s you mentioned are because the error is only regarding `get-data`. There cannot be 2 same RPCs executed at once because they are blocked on their subscriptions but unless you have lots of data to retrieve for `operational`, the default timeout should be enough. If not, you can increase it by specifying `-t <timeout>` parameter for the server, the timeout you have specified is only for the client.

**Comment by saorav21994** [comment]
@michalvasko what i wanted to say was that I tried both edit-config and get-data simultaneous calls. in get-data I received timeout but in edit-config the locking error was present. I mistakenly uploaded the get-data snapshot. Apologies for that. I am re-uploading the snapshot of edit-config.
On one session which got passed and returns SUCCESS (ok), I used the below through network-cli - 
` edit-config --target running --config=mc1.xml --rpc-timeout 55 `
On the other simultaneously through network-cli (different session) the following edit-config was fired - 
` edit-config --target running --config=configDisable.xml --rpc-timeout 55 `
The second one returned the locking error. The config files are perfectly fine and as per standard yang models. They work fine when executed serially. 

i know that 2same RPCs executed at once are blocked but I want to know if there is something we can tweak to try to make them concurrent. as both the edit-config are targeting completely different yang models (openroadm and openconfig respectively). the datastore is the same for both of them but the data is completely different as their yang models are different.

![Capture](https://user-images.githubusercontent.com/13297826/123130094-1b9fa000-d46a-11eb-8b44-adc22c7230e6.PNG)

**Comment by michalvasko** [comment]
> i know that 2same RPCs executed at once are blocked but I want to know if there is something we can tweak to try to make them concurrent

There is nothing you can do in the current architecture to change that. Only if you use only local *sysrepo* calls (or `sysrepocfg`) you could edit independent data concurrently. Also, what version of *sysrepo* are you using? Some older ones had problems with leftover events.

**Comment by saorav21994** [comment]
@michalvasko 
First of all thanks for your prompt responses. I am relatively new in this but I am trying to use it in software defined networking.

>  Only if you use only local sysrepo calls (or sysrepocfg) you could edit independent data concurrently

That means if instead of using netopeer-cli->edit-config command we use sysrepocfg command we can edit concurrently right? or am I missing something sir?

>  what version of sysrepo are you using? Some older ones had problems with leftover events.

sysrepo-plugind - sysrepo plugin daemon, compiled with libsysrepo v1.4.70 (SO v5.5.12). 
This is what I am using. Is there any concern or bug in this version which we are not aware of? What do you specifically mean by "leftover-events". Sometimes (not frequent) if  a rpc fails we fail to proceed further and timeout is given in further consecutive calls. Could this be related to this or there are any other problem in this version.

**Comment by michalvasko** [comment]
> That means if instead of using netopeer-cli->edit-config command we use sysrepocfg command we can edit concurrently right?

That is exactly what said, yes.

> libsysrepo v1.4.70 (SO v5.5.12).

Yes, that is really old considering it was released almost a year ago. You should best use the latest `libyang1` branch version 1.4.143 or even the latest `devel` version 2.0.12.

**Comment by saorav21994** [comment]
@michalvasko 

> I have told you in my very first reply but you seem to have ignored it, by specifying -t <timeout> for netopeer2-server. But note that this parameter is likely not available in the version you are using.

i tried it but as you said my version does not support it (I could not use the -t param). Thanks for clarifying on that.

So as a workaround can i operate 2 sysrepo datastores and netopeer2-server on the same machine. Since both of my yang models are completely different , so I think that if we use 2 diff sysrepo and netopeer  then parallelism in rpc's can be achived, as both the rpc's (lets say edit-config) will only target 2 different yang models at same time.,

Will the above be possible and if so can you jot in the steps to do it. Thank you for your prompt responses.

**Comment by michalvasko** [comment]
Having 2 instances of *netopeer2* installed is theoretically possible but not that simple to do and is a bad idea, generally. Is it really that important to you that the 2 modules data are edited simultaneously?

**Comment by saorav21994** [comment]
@michalvasko 

> Is it really that important to you that the 2 modules data are edited simultaneously?
Yes sir. You see our system specifications require that ` get ` be called at frequent pre-determined intervals. And we have 2 different non-dependent exclusive yang data models. So if I am not able to make rpc's for these 2 data models concurrent, this whole thing will not apparently serve any purpose to me. 
So I am trying to find any possible way to do the above.

> Having 2 instances of netopeer2 installed is theoretically possible but not that simple to do and is a bad idea, generally
Can you shed some light on how to run 2 sysrepo datastore and netopeer2 server on same machine, and what might be the pitfalls. Also if you have any suggestions considering my scenario please let me know. Thanks in advance.

**Comment by michalvasko** [comment]
It all comes down to the architecture of *netopeer2*. Some time ago the RPC callbacks were called directly by the server, which among other things meant the concurrency was limited only by *sysrepo* API, meaning 2 independent edit-configs would execute concurrently. However, it was fairly often requested that it was possible to set your own callback to the RPCs executed by *netopeer2*. For that purpose the architecture was changed and now every *netopeer2* RPC callback is actually called by *sysrepo*, with any other subscribed callbacks. And that part executes serially.

So, I do not think having 2 instances of *netopeer2*/*sysrepo* is a solution because it is not really supported. The only way it can work is by defining some environment variables that set different paths to all the used files making the 2 instances separate. However, you would have to use the same environment paths in all the plugins that would want to communicate with either of the instances which I think is a really bad idea and would result in chaos.

The simplest solution would probably be to create a patch for *netopeer2* that would make it call the RPC callbacks directly, like it used to.With some basic understanding of the code, it is a fairly simple change.
