### ISSUE TITLE
custom_ds_plugin question

### ISSUE THREAD

**Issue by berstrob** [sysrepo/sysrepo#2609]
Hi again,

i noticed that the custom data store feature was added, and since i did have to do some performance optimization (and keeping two data storage in sync is a nightmare anyway).
I tried some basic test (since i found no docu ), i did copy the ds_lyb.c file and striped it of all "functions" (so return OK , and added some debug  ), and tried to modify the test_modules test to use it to study the workings. 
the test_install_module 
```
const sr_module_ds_t mod_ds = {{"DS TEST", "DS TEST", "DS TEST", "DS TEST", "LYB notif"}};

static void
test_install_module(void **state)
{
    struct state *st = (struct state *)*state;
    int ret;
    const char *en_feats[] = {"feat", NULL};
    uint32_t conn_count;

    /* install test-module */

    ret = sr_install_module_custom_ds(st->conn, TESTS_SRC_DIR "/files/test-module.yang", TESTS_SRC_DIR "/files", NULL,&mod_ds );
    assert_int_equal(ret, SR_ERR_OK);

    /* apply scheduled changes */
    sr_disconnect(st->conn);
    st->conn = NULL;
    ret = sr_connection_count(&conn_count);
    assert_int_equal(ret, SR_ERR_OK);
    assert_int_equal(conn_count, 0);
    ret = sr_connect(0, &st->conn);
    assert_int_equal(ret, SR_ERR_OK);

    /* module should be installed with its dependency */
    ret = sr_remove_module(st->conn, "test-module");
    assert_int_equal(ret, SR_ERR_OK);
    ret = sr_remove_module(st->conn, "referenced-data");
    assert_int_equal(ret, SR_ERR_OK);
    ret = sr_remove_module(st->conn, "test-module");
    assert_int_equal(ret, SR_ERR_EXISTS);

    /* install main-mod */
    ret = sr_install_module_custom_ds(st->conn, TESTS_SRC_DIR "/files/main-mod.yang", TESTS_SRC_DIR "/files", en_feats,&mod_ds );
    assert_int_equal(ret, SR_ERR_OK);

    /* apply scheduled changes */
    sr_disconnect(st->conn);
    st->conn = NULL;
    ret = sr_connection_count(&conn_count);
    assert_int_equal(ret, SR_ERR_OK);
    assert_int_equal(conn_count, 0);
    ret = sr_connect(0, &st->conn);
    assert_int_equal(ret, SR_ERR_OK);

    /* check current internal data */
    cmp_int_data(st->conn, "main-mod",
    "<module xmlns=\"http://www.sysrepo.org/yang/sysrepo\">"
        "<name>main-mod</name>"
        "<enabled-feature>feat</enabled-feature>"
        "<plugin><datastore>startup</datastore><name>DS TEST</name></plugin>"
        "<plugin><datastore>running</datastore><name>DS TEST</name></plugin>"
        "<plugin><datastore>candidate</datastore><name>DS TEST</name></plugin>"
        "<plugin><datastore>operational</datastore><name>DS TEST</name></plugin>"
        "<plugin><datastore>notification</datastore><name>LYB notif</name></plugin>"
    "</module>"
    );

     ret = sr_remove_module(st->conn, "main-mod");
     assert_int_equal(ret, SR_ERR_OK);
}
```

worked like that so i notified the next "test_data_deps" the same way 

```
static void
test_data_deps(void **state)
{
    struct state *st = (struct state *)*state;
    int ret;
    uint32_t conn_count;

    ret = sr_install_module_custom_ds(st->conn, TESTS_SRC_DIR "/files/test.yang", TESTS_SRC_DIR "/files", NULL,&mod_ds);
    assert_int_equal(ret, SR_ERR_OK);
    ret = sr_install_module_custom_ds(st->conn, TESTS_SRC_DIR "/files/ietf-interfaces.yang", TESTS_SRC_DIR "/files", NULL,&mod_ds);
    assert_int_equal(ret, SR_ERR_OK);
    ret = sr_install_module_custom_ds(st->conn, TESTS_SRC_DIR "/files/iana-if-type.yang", TESTS_SRC_DIR "/files", NULL,&mod_ds);
    assert_int_equal(ret, SR_ERR_OK);
    ret = sr_install_module_custom_ds(st->conn, TESTS_SRC_DIR "/files/refs.yang", TESTS_SRC_DIR "/files", NULL,&mod_ds);
    assert_int_equal(ret, SR_ERR_OK);

    /* apply scheduled changes */
    sr_disconnect(st->conn);
    st->conn = NULL;
    ret = sr_connection_count(&conn_count);
    assert_int_equal(ret, SR_ERR_OK);
    assert_int_equal(conn_count, 0);
    ret = sr_connect(0, &st->conn);
    assert_int_equal(ret, SR_ERR_OK);

    ret = sr_set_module_replay_support(st->conn, "ietf-interfaces", 1);
    assert_int_equal(ret, SR_ERR_OK);
    ret = sr_set_module_replay_support(st->conn, "refs", 1);
    assert_int_equal(ret, SR_ERR_OK);

    ret = sr_remove_module(st->conn, "refs");
    assert_int_equal(ret, SR_ERR_OK);
    ret = sr_remove_module(st->conn, "ietf-interfaces");
    assert_int_equal(ret, SR_ERR_OK);
    ret = sr_remove_module(st->conn, "iana-if-type");
    assert_int_equal(ret, SR_ERR_OK);
    ret = sr_remove_module(st->conn, "test");
    assert_int_equal(ret, SR_ERR_OK);

    /* check current internal data */
    cmp_int_data(st->conn, "test",
    "<module xmlns=\"http://www.sysrepo.org/yang/sysrepo\">"
        "<name>test</name>"
        "<plugin><datastore>startup</datastore><name>DS TEST</name></plugin>"
        "<plugin><datastore>running</datastore><name>DS TEST</name></plugin>"
        "<plugin><datastore>candidate</datastore><name>DS TEST</name></plugin>"
        "<plugin><datastore>operational</datastore><name>DS TEST</name></plugin>"
        "<plugin><datastore>notification</datastore><name>LYB notif</name></plugin>"
        "<removed/>"
        "<inverse-deps>refs</inverse-deps>"
    "</module>"
    );
    cmp_int_data(st->conn, "ietf-interfaces",
    "<module xmlns=\"http://www.sysrepo.org/yang/sysrepo\">"
        "<name>ietf-interfaces</name>"
        "<revision>2014-05-08</revision>"
        "<plugin><datastore>startup</datastore><name>DS TEST</name></plugin>"
        "<plugin><datastore>running</datastore><name>DS TEST</name></plugin>"
        "<plugin><datastore>candidate</datastore><name>DS TEST</name></plugin>"
        "<plugin><datastore>operational</datastore><name>DS TEST</name></plugin>"
        "<plugin><datastore>notification</datastore><name>LYB notif</name></plugin>"
        "<replay-support>00000000000000000000000000000000000</replay-support>"
        "<removed/>"
    "</module>"
    );
    cmp_int_data(st->conn, "iana-if-type",
    "<module xmlns=\"http://www.sysrepo.org/yang/sysrepo\">"
        "<name>iana-if-type</name>"
        "<revision>2014-05-08</revision>"
        "<plugin><datastore>startup</datastore><name>DS TEST</name></plugin>"
        "<plugin><datastore>running</datastore><name>DS TEST</name></plugin>"
        "<plugin><datastore>candidate</datastore><name>DS TEST</name></plugin>"
        "<plugin><datastore>operational</datastore><name>DS TEST</name></plugin>"
        "<plugin><datastore>notification</datastore><name>LYB notif</name></plugin>"
        "<removed/>"
    "</module>"
    );
    cmp_int_data(st->conn, "refs",
    "<module xmlns=\"http://www.sysrepo.org/yang/sysrepo\">"
        "<name>refs</name>"
        "<plugin><datastore>startup</datastore><name>DS TEST</name></plugin>"
        "<plugin><datastore>running</datastore><name>DS TEST</name></plugin>"
        "<plugin><datastore>candidate</datastore><name>DS TEST</name></plugin>"
        "<plugin><datastore>operational</datastore><name>DS TEST</name></plugin>"
        "<plugin><datastore>notification</datastore><name>LYB notif</name></plugin>"
        "<replay-support>00000000000000000000000000000000000</replay-support>"
        "<removed/>"
        "<deps>"
            "<lref>"
                "<target-path xmlns:t=\"urn:test\">/t:test-leaf</target-path>"
                "<target-module>test</target-module>"
            "</lref>"
            "<inst-id>"
                "<source-path xmlns:r=\"urn:refs\">/r:cont/r:def-inst-id</source-path>"
                "<default-target-path xmlns:t=\"urn:test\">/t:ll1[.='-3000']</default-target-path>"
            "</inst-id>"
            "<inst-id>"
                "<source-path xmlns:r=\"urn:refs\">/r:inst-id</source-path>"
            "</inst-id>"
        "</deps>"
    "</module>"
    );
}
```

 but got that assert_string_equal error : 
```
[INF] Module "test" scheduled for deletion.
"<module xmlns="http://www.sysrepo.org/yang/sysrepo"><name>test</name><plugin><datastore>startup</datastore><name>LYB DS file</name></plugin><plugin><datastore>running</datastore><name>LYB DS file</name></plugin><plugin><datastore>candidate</datastore><name>LYB DS file</name></plugin><plugin><datastore>operational</datastore><name>LYB DS file</name></plugin><plugin><datastore>notification</datastore><name>LYB notif</name></plugin><removed/><inverse-deps>refs</inverse-deps></module>" != "<module xmlns="http://www.sysrepo.org/yang/sysrepo"><name>test</name><plugin><datastore>startup</datastore><name>DS TEST</name></plugin><plugin><datastore>running</datastore><name>DS TEST</name></plugin><plugin><datastore>candidate</datastore><name>DS TEST</name></plugin><plugin><datastore>operational</datastore><name>DS TEST</name></plugin><plugin><datastore>notification</datastore><name>LYB notif</name></plugin><removed/><inverse-deps>refs</inverse-deps></module>"
```

should the removed data store not be the same ` <name>LYB notif</name>`  or am i doing something wrong?
second question if i only want use my data store for "running" and "operational" since candidate are fine as they are, i properly do not have to implement all the functions related to that, am i right?

Regards Bernd

**Comment by michalvasko** [comment]
Yes, that seems strange but I cannot tell you what exactly is happening there. This custom DS feature has not really been tested much because I wanted to wait with that until we write our own DS plugin in addition to the default one. For now I wanted the LYB plugin to be tested, whether it works the same way it did before. So you are free to experiment with this but note that it is likely not ready and the API will probably change once we have the requirements from an actual use-case.

As for the second question, I have mostly answered already. What you say makes sense and I had the same idea but considered it useless to implement this (checks that the required functions are implemented for a particular datastore) before having actual custom DS plugins.

**Comment by berstrob** [comment]
Hey,
me again, hope you had great holidays , i did have some more time for tests and more thinking about it, and i think i might have a big problem.:

So i wanted to use the ds_plugin to read out my db directly (PostgreSQL but that does not matter ) , which works fine for the running /operational data , as long as it does not change. The `store_cb` does not have to do anything, since the callbacks will do all the work already (as they did before) .

The problem arises if the db gets changed externally (which is the main thing that happens and the number one reason i wanted to swap from my sub optimal solution): i do not really see i nice way to get the config-change notifications out in that case, maybe i am just not seeing it.

In "the old way" i do have the db send a notice and do apply the changes in my programm via sr_apply_changes    (without my checks and db changes: the call back just says ok if it trigger that way,but takes a while, for a config i know is valid), but that will not work since loading the module data will allready be the changed data form the db.  

I guess i have to instead just create the notices by my self (via sr_modinfo_generate_config_change_notif() with "a fake" mod_info ) or does that break anything?

Another idea i had was to use the `store_cb` to trigger  "a reload of the data" form the db and `load_cb` just "play it back" form local memory (my c structs) maybe that will break less, not sure if its even is faster/better then before then, since the main bottelneck was more or less the apply of the big data with lots of references ( openconfig-platform , like adding/deleting few 100 components at once, with will be done automatic, if somebody plugs stuff in/out) 

Regards Bernd

**Comment by michalvasko** [comment]
External changes of your datastore are generally out-of-scope of *sysrepo*, I do not think it can do anything to help you. Custom DS provides the advantage of 1) not having to store the configuration at 2 places and 2) keeping the configuration synchronized even on external changes (connected to the first point). If you want the external changes to also be reported by *sysrepo* (whether fully by calling the appropriate callbacks with the changes or only by generating the config-change notification), you need to implement that yourself.

As for handling these external changes, that is a creative task for you to figure out but using only the public *sysrepo* API should be enough. Ideally, you could "catch" the external changes and transform them into a *sysrepo* edit instead of writing into the datastore directly. If not possible, the solution depends a lot on the actual datastore. With a simple configuration file, you could monitor it for changes (`inotify(7)` or some polling) and then report them separately (get them by comparing your previous backup of the file and the new file). Databases should be able to provide some mechanisms to be used for this by themselves. If it has a journal or at least a log of all the changes, that can be helpful as long as you know which changes were done by *sysrepo* and which not. Like I said, this is for you to figure out.

**Comment by berstrob** [comment]
Yeah that is what i figured, just wanted to make sure i did not miss something easy /obvious or an intended way.

I do have the logic for catching the relevant changes (need to report them via snmp/webgui/log them and so on anyway, "catching the edit" before everywhere is would take years of effort i fear), that is how i did it until now, just have to make sure to not send them out double, but that should be easy doable *fingers crossed*. 

Thanks for your quick reply .

**Comment by michalvasko** [comment]
> have to make sure to not send them out double

If you do, the same data will be written to the database again, I think, so no harm done. Not sure how to avoid it nicely.

**Comment by matth65** [comment]
Hi Michal,

I have a question about the two points mention about the custom DS in the comment above.

> Custom DS provides the advantage of 1) not having to store the configuration at 2 places and 2) keeping the configuration synchronized even on external changes (connected to the first point). 

With regard to point (2), does this mean that external changes to the custom DS should be reflected through sysrepo to applications when performing get/load operations? In this case, I'm not referring to issuing sysrepo change callbacks, etc.  In this case, I'm referring to values in the custom DS being updated outside of sysrepo, and having sr_get_data() return the updated values from the custom DS.

I'm asking this because I've noticed that the srplg_ds_s::load_cb() is only called the first time data from the module is accessed. After that, it seems like sysrepo is working from cached data - even after modifications to the module data. For example, with Netopeer2, I see that the load_cb() is only called the first time a client issues `<get-config>` for a module. Note that tools like sysrepocfg do not have this issue because they run to completion for each request.

Does the custom DS have to invalidate the cache (increment mod_count or something ?) when external changes are made to the custom DS?

Best Regards,
Matt

**Comment by berstrob** [comment]
Hi, 
if you want Netopeer2 not to cache you can simply change ` rc = sr_connect(SR_CONN_CACHE_RUNNING, &np2srv.sr_conn);`  to `  rc = sr_connect(SR_CONN_DEFAULT, &np2srv.sr_conn);`  in the main.c (that is what i did for my tests).
Regard Bernd

**Comment by michalvasko** [comment]
Just wanted to mention that with custom DS plugins the caching really does not work and what @berstrob said is a fast workaround. I am working on a proper fix that will move the caching to the plugins themselves (optional feature, of course), which should simplify *sysrepo* internals as well.

**Comment by michalvasko** [comment]
Took me a while until I found a suitable mechanism for the data cache. In the latest `devel` you should be able to optionally implement your own caching specific to the datastore.
