### ISSUE TITLE
`sr_discard_oper_changes` should work recursively

### ISSUE THREAD

**Issue by syyyr** [sysrepo/sysrepo#2665]
Hi, I have found out that `sr_discard_oper_changes` doesn't discard operational nodes when using a parent xpath of the node. See this example code:
```cpp
#include <iostream>
#include <sysrepo.h>
#include <string>

void getDataAndPrint(sr_session_ctx_t* session, const char* xpath)
{
    sr_data_t* data;
    sr_get_data(session, "/test_module:myList", 0, 0, 0, &data);
    if (!data) {
        std::cerr << "{no-data}\n";
        return;
    }

    char* str;
    lyd_print_mem(&str, data->tree, LYD_JSON, LYD_PRINT_WITHSIBLINGS);
    std::cerr << "str" << " = " << str << "\n";
    free(str);
    sr_release_data(data);
}

int main(int argc, char* argv[])
{
    sr_log_stderr(SR_LL_INF);
    sr_conn_ctx_t* conn = nullptr;
    sr_connect(0, &conn);
    sr_session_ctx_t* sess = nullptr;
    sr_session_start(conn, SR_DS_RUNNING, &sess);

    // Schema:
    // list myList {
    //   key 'myKey';
    //   leaf myKey {
    //     type string;
    //   }

    //   leaf myStateLeaf {
    //     type string;
    //     config false;
    //   }
    // }

    // Set some list to running
    sr_set_item_str(sess, "/test_module:myList[myKey='aaa']", nullptr, nullptr, 0);
    sr_apply_changes(sess, 0);
    std::cerr << "AFTER SETTING\n";
    getDataAndPrint(sess, "/test_module:myList");

    // Set some state push-style operational data
    sr_session_switch_ds(sess, SR_DS_OPERATIONAL);
    sr_set_item_str(sess, "/test_module:myList[myKey='aaa']/myStateLeaf", "some state", nullptr, 0);
    sr_apply_changes(sess, 0);
    std::cerr << "AFTER SETTING PUSH OPER\n";
    getDataAndPrint(sess, "/test_module:myList");

    // Now discard operational changes under in the list. This unfortunately does nothing.
    sr_discard_oper_changes(conn, sess, "/test_module:myList[myKey='aaa']", 0);
    std::cerr << "AFTER DISCARDING TOP_LEVEL_LIST\n";
    getDataAndPrint(sess, "/test_module:myList");

    // Discarding the actual state leaf does get rid of it.
    std::cerr << "AFTER DISCARDING THE ACTUAL DATA\n";
    sr_discard_oper_changes(conn, sess, "/test_module:myList[myKey='aaa']/myStateLeaf", 0);
    getDataAndPrint(sess, "/test_module:myList");

    sr_session_stop(sess);
    sr_disconnect(conn);

    return 0;
}
```
In the example, doing `sr_discard_oper_changes(conn, sess, "/test_module:myList[myKey='aaa']", 0);` does not get rid of the data, only `sr_discard_oper_changes(conn, sess, "/test_module:myList[myKey='aaa']/myStateLeaf", 0);` works. I think that the first call `sr_discard_oper_changes` should get rid of the nested leaf.

**Comment by michalvasko** [comment]
It took me some time to figure out what is happening (mostly because the internal code is quite complex) but it seems the current behavior is intentional but we can discuss whether also correct. The whole point is that the XPath in `sr_discard_oper_changes()` selects nodes, not subtrees. So, you remove `myList` but there is still `myStateLeaf` change, which is kept, so you effectively do not perform any data change.

What is important to note is that every push data node has also its connection owner stored for it. Your API call did remove it from the `myList` node but for data of single connection is probably still does not make any difference, it may in case there are several connections storing the data. For this reason I would prefer to keep it the way it is, I can improve the docs and stress that nodes and not subtrees are being selected.

**Comment by syyyr** [comment]
Our use-case is this: we have some config false data inside a list which is config true. When a new insurance of the list is created, we want to set the push-style data and when the instant gets removed, we want to get rid of the data. An easy (and intuitive) way would be to just use `sr_discard_oper_changes()` on the list xpath and then we're done.

However, because the function does not work like that, which brings two problems:
1) we would have to save all of the xpaths (possibly even containers which are implicitly created as parents of leafs, not sure if that's the case)
2) the operation can't be done atomically because sr_discard_oper_changes() applies the change immediately and we have call it multiple times for all of the nodes

**Comment by michalvasko** [comment]
Not really, you can simply use `/test_module:myList[myKey='aaa']//.`, which changes the meaning to exactly what you want, the node and all of its descendants. Appending that should not really be a problem and it would still be possible to target single nodes.

**Comment by jktjkt** [comment]
One of the use cases we have for this is pushing a list with 16k items. Removing them one-by-one sounds like a nightmare.

**Comment by michalvasko** [comment]
Have you read my previous reply, like I said there, you can just append `//.` to any XPath and you will get the subtree-match instead of node-match functionality.

**Comment by jktjkt** [comment]
I haven't seen your reply, sorry. Using `//.` looks like like a usable stopgap measure, but I can imagine scenarios where this won't help (mainly related to the lack of atomicity, but also for more complex scenarios with more than one level of container nesting). The current version delegates this housekeeping, XPath tracking, etc., towards the user code, while I think it's better solved in the "YANG DB layer" which is sysrepo. That's why I would prefer the discard operation to work on subtrees, and to also be a subject to an explicit commit as well -- similar to how these edit items are created in the first place.

**Comment by michalvasko** [comment]
> That's why I would prefer the discard operation to work on subtrees, and to also be a subject to an explicit commit as well -- similar to how these edit items are created in the first place.

I have tried to explain why this is an incorrect analogy, but it is also impossible to implement with the current internal code. The prepare-apply-changes mechanism is used for "adding changes" to whatever datastore. But `sr_discard_oper_changes()` does the opposite, it removes performed changes. There are no internal mechanisms to be used for that, currently, hence I implemented it as a function directly causing the changes. Naturally, the mechanism can be added but I do not think it useful for now.

Try to use those subtree expressions if you have to but note that you also do not have to specify any XPath when all the changes made by the connection are discarded.
