### ISSUE TITLE
any equivalent/similar tool as mib2c/idl2c for sysrepo plugin develop?

### ISSUE THREAD

**Issue by love1900905** [sysrepo/sysrepo#2680]
Dear sysrepo experts,

I'm new to sysrepo/netopeer2, I would like to know whether C/C++ source code could be auto-generated based on yang file for sysrepo/netopeer2?

In snmp or corba develop, there is a tool [mib2c ](http://www.net-snmp.org/docs/man/mib2c.html) or idl2c, which will generate skeleton code then you can do real imeplemtation based on it. 

Does sysrepo have an equivalent/similar tool? 
e.g. my device need to support example [oven.yang](https://github.com/sysrepo/sysrepo/blob/master/examples/plugin/oven.yang),  after run the tool , skeleton of [oven.c](https://github.com/sysrepo/sysrepo/blob/master/examples/plugin/oven.c) could be auto generated.)

Thanks!

**Comment by michalvasko** [comment]
No, there is no such tool because it makes no sense and is impossible to write. All your plugin must include are 2 functions (with arbitrary functionality) and you will find their name/definition is the public headers. They are all that could be generated, in theory, but that is useless. The actual functionality (callback code) cannot be generated.

**Comment by love1900905** [comment]
> 

Hello Michalvasko,

The skeleton code I was expected mainly for the data types, as yang file might defines many complex container which contains many leaf or augment nodes.
And later I realized even for the data types, the actual functionality might vary depends on real imeplemtation, thus close this ticket. Thank your for your support.
