### ISSUE TITLE
Sysrepo (without PSHARED_PROCESS mutex) synchronization between single threaded multiple processes

### ISSUE THREAD

**Issue by RashmiEva** [sysrepo/sysrepo#2684]
Hi,

Since NETBSD doesn't support PSHARED_PROCESS for pthread_mutex,
I'm trying to have a sysrepo integrated in to a multiple single threaded process wherein no pthreads are present nor created. 

Since except sr_main_lock file , all synchronization mutexes are part of shared memory segment.
So I made some modifications in sysrepo wherein mutex_attrs are not set as PSHARED.
I'm hoping this integration should work seamlessly providing the synchronization between multiple processes.
[I'm considering the fact that pthread_mutex_t holds kernel threadID(gettid) as its value in owner field, which again will be same as process-id and unique across the system in this integration scenario].

I tried with 3-4 process just a have quick confirmation. 

Could you provide your inputs if you foresee any undefined behavior?

Thanks!!

**Comment by michalvasko** [comment]
From the manual
```
       PTHREAD_PROCESS_PRIVATE
              Mutexes created with this attributes object are to be shared only among threads in the same process that  initialized
              the mutex.  This is the default value for the process-shared mutex attribute.
```
meaning by default the mutexes can be shared only by **any number of threads** in a **single process**. The attribute needs to be changed if the mutex needs to be used by **any number of threads** in **several processes**. Meaning limiting every process to a single thread is irrelevant, the problem is with several processes. So if a platform does not support `PTHREAD_PROCESS_SHARED` mutexes, you cannot use them to synchronize processes, which is mostly what mutexes in *sysrepo* are used for.

This is all the official information I know about. Naturally, depending on the actual mutex implementation on a platform, it may work regardless.
