### ISSUE TITLE
Getting Oven Config with rpc command

### ISSUE THREAD

**Issue by spavell** [sysrepo/sysrepo#2695]
Hi,

I've installed the oven module example and I wanted to get the configuration instead of get-config with rpc.  

I tried several options but only one works but there is no oven module data in reply.
```
<get-config xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
    <source>
      <running/>
    </source>
</get-config>
```

If the namespace is "urn:sysrepo:oven"  it throws an error
```
<get-config  xmlns="urn:sysrepo:oven">
    <source>
      <running/>
    </source>
</get-config>
```

Error:
libyang[0]: Missing the operation node. (path: Line number 6.)
Session 1 [ERR]: Failed to create RPC, perhaps a required feature is disabled.
callback_tls_post: Failed to send the RPC

Please help to figure out how should the xml look like in order to get the oven configuration

Thanks,
Pavel

**Comment by michalvasko** [comment]
You will probably need to learn more about [NETCONF](https://datatracker.ietf.org/doc/html/rfc6241), not sure I can help you myself with these basics. But the first XML is correct, `oven` configuration may be empty, did you configure anything for it? The second XML is wrong because there is no `get-config` RPC defined in the `oven` YANG module.

**Comment by spavell** [comment]
Thanks, you are right I should learn more about netconf and you are also right about missing configuration. After configuring it as shown in example I can get it back with get-config
Thanks again
