### ISSUE TITLE
SR_SUBSCR_CTX_REUSE deprecated in latest sysrepo version

### ISSUE THREAD

**Issue by meghna-doshi** [sysrepo/sysrepo#2696]
Hi,
We see that SR_SUBSCR_CTX_REUSE is deprecated in sysrepo latest version 
sysrepoctl - sysrepo YANG schema manipulation tool, compiled with libsysrepo v2.1.15 (SO v7.1.3)

So the query is, what option to use in 
1. sr_module_change_subscribe
2. sr_oper_get_items_subscribe
3. sr_rpc_subscribe

so that the behaviour is like SR_SUBSCR_CTX_REUSE i.e 
`allow application to re-use an already existing subscription context previously returned from any sr_*_subscribe call instead of requesting the creation of a new one.`

**Comment by michalvasko** [comment]
I was hoping [this](https://github.com/sysrepo/sysrepo/blob/devel/src/sysrepo.h#L1209) was clear enough. It should imply that it can be directly used for more subscriptions without any flag, but you **must zero** it before the first subscription.

**Comment by mrsugaranil** [comment]
Hi Michal,

What should we "must zero" to use SR_SUBSCR_CTX_REUSE in new version? I am checking session id for module change callback, and I observe that in every change of YANG module node new session is created with different ID. Is there any extra advantage to use same session id (SR_SUBSCR_CTX_REUSE) per YANG module?

**Comment by michalvasko** [comment]
I have no idea what you are talking about and are probably missing 2 completely unrelated things. Session ID is simply an ID assigned to every *sysrepo* session for mostly internal use. The flag `SR_SUBSCR_CTX_REUSE` talked about here used to allow to create several subscriptions grouped in a single subscription structure but it is no longer needed. The point of putting several subscriptions together is generally saving some resources because then all the subscriptions are handled by a single thread but this may often be needed in some complex concurrent scenarios.
