### ISSUE TITLE
The possibility to install yang modules during operating system image build

### ISSUE THREAD

**Issue by jorgensigvardsson** [sysrepo/sysrepo#2726]
This is my scenario: I am building Linux images using [buildroot](https://buildroot.org). The image is built on a host system, and is never executed until it is deployed on the target system, and the target system boots.

I would like to be able to install the yang modules during image build on the host system, but that does not seem possible. sysrepo does not recognize the module, until I run `sysrepoctl -i /path/to/module` on the target system. If it is indeed possible to install modules at image build time, please guide me in the right direction. Setting feature flags is also of interest at image build time, as some target systems will have different features enabled.

I can build the image such that when the target system boots for the first time, it will execute the above command as part of the boot up sequence, so this is not a "show stopper" for me that I cannot install the module at image build time on the host system. It would however be very elegant.

Also, I'd like to thank you for a really good product! Thanks for all your efforts, much appreciated!

**Comment by jktjkt** [comment]
How does your `target/etc/sysrepo` look like right after you build and finalize your rootfs? In theory, all that you need is to invoke your hosts's `sysrepoctl` which is [already configured to point to your target's `/etc/sysrepo`](https://github.com/buildroot/buildroot/blob/cc9470c2d8134106792a5a0179fbd0c6ca4d37af/package/sysrepo/sysrepo.mk#L34). It might also be necessary to sequence this installation so that parallel build (and especially `BR2_PER_PACKAGE_DIRECTORIES`) won't throw a wrench into the machine. Also, there are also the SHM files where e.g. the `netopeer2` packaging [tries to make it parallel-build-safe](https://github.com/buildroot/buildroot/blob/cc9470c2d8134106792a5a0179fbd0c6ca4d37af/package/netopeer2/netopeer2.mk#L25), but I think that using a shared repo location and isolated SHM is a recipe for disaster; there *will* be subtle races.

As you correctly note, however, this is not sufficient if you require a different set of YANG modules (or different enabled features, etc) from a single image/rootfs. In that case, you need something to happen at runtime, and while you're there, you might just as well install everything from scratch IMHO.

That's why our [buildroot packaging](https://gerrit.cesnet.cz/plugins/gitiles/CzechLight/br2-external/) delegates everything to the target system. We have a read-only rootfs and a common image shared by several different models of HW. When the target system boots, a read-write overlay is set up over the empty repository location, and before any sysrepo-using daemons start, [all required modules are installed and configured](https://gerrit.cesnet.cz/plugins/gitiles/CzechLight/br2-external/+/refs/heads/master/package/cla-sysrepo/czechlight-install-yang.sh) via a shellscript which determines what gets enabled on this particular system. The configuration then gets [restored from a separate config partition](https://gerrit.cesnet.cz/plugins/gitiles/CzechLight/br2-external/+/refs/heads/master/package/czechlight-cfg-fs/), and everything is [configured with RAUC for seamless firmware updates with A/B firmware slots](https://gerrit.cesnet.cz/plugins/gitiles/CzechLight/br2-external/+/refs/heads/master/package/czechlight-rauc/) (which requires [some bootloader magic](https://gerrit.cesnet.cz/plugins/gitiles/github/trini/u-boot/+/6c6f9d924f93699e706f8c95f45a2c58c107b444%5E%21/)). Based on our past experience, we also setup up stuff so that any crash of any sysrepo-using service immediately [throws away the content of the shared repo location and restarts all services which access sysrepo](https://gerrit.cesnet.cz/plugins/gitiles/CzechLight/br2-external/+/refs/heads/master/package/reset-sysrepo/); this might or might not be required with today's sysrepo, but we've been carrying this code all the way back from 0.7. Oh, and we also [have patches to buildroot's packaging of sysrepo/netopeer2](https://gerrit.cesnet.cz/plugins/gitiles/github/buildroot/buildroot/+log/refs/heads/cesnet/2022-01-13); one of the things that is needed is *not* baking the SSH key into your rootfs image, so you need runtime configuration anyway, but there's more. Feel free to browse that repo. The `master` branch is based on libyang v1, and [the libyang v2 one is here](https://gerrit.cesnet.cz/c/CzechLight/br2-external/+/5437).

**Comment by jorgensigvardsson** [comment]
Thank you very much for your answer @jktjkt, I really appreciate that you took the time to answer!

I had not assumed that `sysrepoctl` would work "cross platform" like that. Amazing! I and my team have to figure out whether we can do a static install of yang modules/features or not. I think for a subset of all modules, we can and probably should (base functionality for all target models). I like the idea of having base functionality in an immutable "package".
