### ISSUE TITLE
Question: duplicated device instances? Is this possible?

### ISSUE THREAD

**Issue by kobi-ca** [sysrepo/sysrepo#2728]
Hello,

I have a general question regarding Netconf operation.

Let's say I have 2 devices in the system. 2 instances. Both implement the same Yang model.
For example, think about 2 dhcpd (though it might not make sense, it's just an example for this question).

Is there a way to refer to one of the instances when I want to configure it?

Another example - https://github.com/sysrepo/sysrepo/blob/master/examples/plugin/oven.c the oven plugin example.
The oven is a device, implementing Yang model. What happens if I have 2 shared libs implementing the same model.
Both have the callbacks implemented. Would sysrepo reject it?

thanks,
Kobi

**Comment by kobi-ca** [comment]
Hello Jan,

thank you for your reply!
You actually answered and clarified a lot of questions that I had in mind.
I did not have anything specific in mind but this use case raised questions on the mechanism of NC server implementation as we as how YANG models should be written in such case.
One thing I derived from your reply is that in such case, where I have multiple instances that have their configuration mapped to a YANG model, I better have an "instance-id" or something similar to distinguish between the multiple instances.

While typing the above, I came up with an example. I have 2 apps, they have configuration schema modeled with YANG. These Apps are identical instances which different instance IDs. They both are up and running for load balancing and similar.

If I have a NC client CLI and I'd like to invoke a config change to one instance only, I better have an identifier baked into the schema, right?
And my Apps (the NC client side of it) will look at a specific instance-id as part of the incoming payload - and will take action accordingly.

I'm very new to NC/Yang domain. So maybe the used terminology is not the best one and maybe some of my questions does not make sense. I'm in the learning stage. (OTOH I'm proficient in C++, Linux, Containers etc... and I managed to run examples and such).

As a side note - one thing I'm trying to do is to try mixing Sysrepo's ecosystem (NC client for example) with different NC servers in the market. And I'm specifically interested in using libyang-cpp as the underlying YANG data and schema handler. I really like what they did over there.

thank you again for your reply (late hour on your side if I read it correctly).

**Comment by jktjkt** [comment]
There are always options; you could encode these two "app instances" as a pair of YANG `container`s, for example. But in general, if you have *N* instances of an app running and you want to somehow manage them via sysrepo, the most obvious way would be simply using a YANG `list` where each "list instance" corresponds to an "instance of your app". I suggest watching some YANG modeling tutorials so that you get better understanding of the features of this modeling language (for example, `instance-identifier` is probably something else than you assume it is).

Here's what I would do if I were in your shoes:

1) Start by watching several YANG tutorials. This will help you understand what the language is capable of.
2) Take a look at some standard RFCs with YANG model examples (`ietf-system` and `ietf-interfaces` along with their extensions are good example). This should get you going in a direction that is aligned with the wider ecosystem. I.e., you will understand how people are using YANG to describe data and design models.
3) Only then start figuring out how `sysrepo`/`libyang` can help you.

**Comment by kobi-ca** [comment]
thank you @jktjkt !
