### ISSUE TITLE
Customized notification stream name[Question]

### ISSUE THREAD

**Issue by ankit7gup** [sysrepo/sysrepo#2755]
Hi Michal,

I wanted to know, Does sysrepo/netopeer2 support using a customized stream name for sending notifications. The same stream can be subscribed by the netconf client and used for receiving the notifications.

Thanks!

Regards,
Ankit

**Comment by ankit7gup** [comment]
Actually I have a requirement where the server has to send notifications on a stream with a particular name, and the client needs to subscribe only to that. 
Please let me know if this can be expected as a support feature sometime in future or else if we can have a workaround meanwhile.

Thanks!

**Comment by michalvasko** [comment]
> Actually I have a requirement where the server has to send notifications on a stream with a particular name, and the client needs to subscribe only to that.

That is quite a strange requirement. This feature is not planned because no one ever needed it and it would not even be that simple to implement. It would need detailed configuration of all the streams and what notifications to send on them, in addition to actually sending the correct notifications on the particular streams.

**Comment by ankit7gup** [comment]
Hi @michalvasko,

Just wanted to know if by any chance, the feature of customized stream name is supported now.

Thanks!

Regards,
Ankit

**Comment by michalvasko** [comment]
No, it is not and there are no plans to mostly because we have no use-case so we would not be able to design creating new streams (their configuration).
