### ISSUE TITLE
Using NACM with multiple modules

### ISSUE THREAD

**Issue by awesomenode** [sysrepo/sysrepo#2775]
Hi!

With NACM now (again) integrated into sysrepo, I have a problem, that I
use sysrepo with different management interfaces, so not only one
module needs and uses NACM.

The previous implementation had the diff check callback mechanism,
which worked fine when multiple modules made changes to the datastore,
but with the current devel version I don't see a way to make this
possible, because I get the following error when another module tries
to initialize NACM:
> 
> Operational data provider subscription for "ietf-netconf-acm" on /ietf- netconf-acm:nacm/denied-operations" already exists.
> Subscribing for providing "ietf-netconf-acm" state data failed.

Is there a plan to support multiple modules with the latest NACM
implementation? This would prove useful for using sysrepo with both
a NETCONF and a RESTCONF server.

Thanks!

**Comment by jktjkt** [comment]
OK, so this happens because each NACM-using session initialization now attempts to register ops pull data providers for NACM statistics, and this can only happen once among all sysrepo-using processes. A quick and dirty way would be an option which skips this statistics for, say, your RESTCONF server -- obviously at a cost that these statistics would only include NETCONF operations, not RESTCONF (or perhaps just `deviate not-supported` them altogether?).

If the statistics are important, then one way forward would be separating out these statistics into a `sysrepo-plugind` library. This library would register the ops pull CBs and return the statistics. For *gathering* the stats, this will need another mechanism -- perhaps a private RPC which the NACM-using operations would send instead of incrementing an internal counter like it's done now. Alternatively, each NACM-using session can instead set up a push ops data provider for a unique `list` with these stats -- and *push* these data anytime an operation is denied. The central plugin can then set up a subtree change CB that would simply track these writes, sum them up, and return the total number under the standard `/ietf-netconf-acm:nacm/denied-*` XPath.

I think I like that last approach. There will be no failing RPCs when the central stats plugin dies, and if coded properly, it will take care of short-lived, transient sessions (which fit well into the RESTCONF approach) just fine.

Just wondering, what plans do you have for the RESTCONF server, @awesomenode ? We started working on a [`rousette`, a RESTCONF server for `sysrepo`](https://github.com/CESNET/rousette), and that move of the NACM feature back into sysrepo was motivated by our feature request. Here's our [WIP-patch for NACM in RESTCONF](https://gerrit.cesnet.cz/c/CzechLight/rousette/+/5543) FIY. We would also love to get the YANG-push implementation which currently lives in Netopeer2 into something that can be reused for RESTCONF.

**Comment by awesomenode** [comment]
The RESTCONF server is just a possible use case in the future, right now the problem is that other interfaces (like CLI) would use NACM, when accessing data in sysrepo via a CLI command. With the latest sysrepo, it seems impossible at the moment. The CLI module also needs to initialize NACM, in my case.

Statistics are not really important for me right now, so any of the implementations which supports multiple modules would be fine.

**Comment by michalvasko** [comment]
I have not actually tested using NACM in several applications and the encountered problem is quite expected. I have come up with a solution that should fix it without changing the API (albeit it is a bit hacky) so please test it and report any problems.

**Comment by awesomenode** [comment]
Thank you! This seemed to have fixed it!
