### ISSUE TITLE
Change to oper store causes SR_OP_CREATED instead of SR_OP_MODIFIED

### ISSUE THREAD

**Issue by gotthardp** [sysrepo/sysrepo#2798]
Hello. I created an entry in the operational store. Then, when I modify this entry the subscribed modules get SR_OP_CREATED again, instead of receiving the SR_OP_MODIFIED. Is that an expected behavior?

Attached [test.diff.txt](https://github.com/sysrepo/sysrepo/files/8554730/test.diff.txt) shows a test that fails.

**Comment by michalvasko** [comment]
Module changes for the `push` operational data are a really obscure feature, let's say. I was coming up with the behavior as I was implementing it because the whole functionality is more complex that would be appropriate. In this particular use-case the interpretation is that the originator is simply creating the value and that is reported. Yes, it can already be in the `operational` datastore so the effective change may differ but since the source of the change can be from `running` datastore, or from `pull` or `push` oper data, so to simplify it, all of them are ignored. The other option would be to take some or all of the mentioned data sources into consideration but the problem with that is that 1) you woulod need to actually build the oper data to report the change 2) they can easily change without being reported (only the `push` changes are reported) so to avoid more confusion, the observed behavior is the one I have chosen.

**Comment by gotthardp** [comment]
Ok, thanks for the explanation.
