### ISSUE TITLE
Too many open files

### ISSUE THREAD

**Issue by hi-Mr-ye** [sysrepo/sysrepo#2800]
Hi @michalvasko
Why is this information being printed?At the same time, any operation fails.
This is a printed message:
![image](https://user-images.githubusercontent.com/90752673/165251776-402384f7-3e60-4d9a-8729-fc641395df54.png)

**Comment by michalvasko** [comment]
Most likely, you are not clearing up something after yourself and you simply hit the limit on your system for number of open file descriptors on a system.

**Comment by hi-Mr-ye** [comment]
If it comes from sysrepo, What needs to be cleaned up to solve this problem?

**Comment by michalvasko** [comment]
Unused connections, sessions, or subscriptions.

**Comment by hi-Mr-ye** [comment]
How do you check these things? And How to clean it up?

**Comment by michalvasko** [comment]
You are asking questions I think you should know the answers to but I will try to answer. You do not check anything, you call `sr_connect()` because you need a connection for some other function(s). Once you do not plan to call any such functions, you should call `sr_disconnect()` to get rid of the connection. The same goes for session and `sr_session_start()` and `sr_session_stop()`. Similarly, you create some subscriptions with one of the functions and you need to call `sr_unsubscribe()` once you do not want the subscription to continue.

Of course, you are most likely using some callbacks and if you are opening some files there and not closing them, it would result in the same error. However, what you do in the callbacks is fully in your control and up to you to do properly.

**Comment by hi-Mr-ye** [comment]
thanks! and How do I know the number of connections? number of sessions?

**Comment by hi-Mr-ye** [comment]
thakns! I just want to know which sessions and  connections are not killed
