### ISSUE TITLE
sr_oper_get_subscribe() and sr_rpc_subscribe()

### ISSUE THREAD

**Issue by wdl2015** [sysrepo/sysrepo#2816]
Hi experts, 

I have two apps (app1 and app2) connecting to same sysrepo DB. 

The app1 subscribes a callback to provide operational_get data to client,
        /* Subscribe for operational data retrieval */
        sr_rc = sr_oper_get_items_subscribe(srs, "ietf-hardware", "**/ietf-hardware:hardware/component**",
            _hardware_state_get_cb, NULL, 0, &sr_ctx_state);

The app2 subscribes a callback to handle RPC request from client.
        // subscribe callback for the download action.
        sr_rc = sr_rpc_subscribe(srs,
                "/ietf-hardware:hardware/component[name='Chassis']/bbf-software-management:software/software[name='exs1610app']/revisions/download/download",
                _swm_rpc_cb, NULL, 0, 0, &sr_ctx_swm_state);

The path (/ietf-hardware:hardware/component) that app1 subscribes is the base of the path that app2 subscribes. As a result the RPC action triggers from the client is always received by app1, app2 cannot receive the RPC action. 

Is it possible to make app2 receive RPC requests or at least both app1 and app2 receive RPC request?

Thanks much for your advice in advance.

Br
George

**Comment by michalvasko** [comment]
`app1` will never "receive the RPC action", just the operational data are being retrieved for its validation. And what do you mean `app2` is not receiving the RPC? The callback is not called but the action is successfully executed? Or do you see some error? Note that you are subscribing to specific parent data nodes of the action (`[name='Chassis']` and `[name='exs1610app']`) so if they differ, your callback will not be called.

**Comment by wdl2015** [comment]
Hi Michal, 

Thanks for your quick feedback. Below is my test result.
Start app1 and app2 processes
Trigger an RPC request in netopeer2-cli client on path "/ietf-hardware:hardware/component[name='Chassis']/bbf-software-management:software/software[name='exs1610app']/revisions/download/download"
From the app1 and app2 callback printout app1 receives this RPC request, app2 not.

After reading the sysrepo.org doc in more details I changed app1 to use SR_SUBSCR_OPER_MERGE option as su_oper_get_subscribe() parameter, then both app1 and app2 callback can printout the RPC request.

Is this the correct idea to make both app1 and app2 callback receive the RPC request?

Thanks a lot.

Br
George

**Comment by michalvasko** [comment]
> Is this the correct idea to make both app1 and app2 callback receive the RPC request?

No, you are quite far from that and you seem to have completely ignored my attempt to get you to understand how it should work properly.

You have not answered any of my questions, so please do, otherwise I do not understand why are you asking for help. So again, how exactly are you "triggering the RPC request"? What is the reply printed by the CLI after the RPC is sent?

**Comment by michalvasko** [comment]
You have finally posted the error, which is critical. [Here](https://datatracker.ietf.org/doc/html/rfc8342#section-6.2) are the requirements that you have not met in this case.

> One story is that an operational event with ID 2 is sent to app1 although I don't know why an operational event is sent.

Should be explained in the link. Specifically, you need the `operational` data for the validation of the action.

> One thing I cannot understand is that after I killed app1 then app2 callback was able to receive the RPC

Will probably be connected to the `operational` data and that what is provided by app1 (replacing the data from app2) is not suitable. Note that *sysrepo* is a global system datastore so whatever data app1 or app2 provides, it all ends up in a single datastore that is used for validation of all the RPCs/actions.

> In this kind of scenario RUNNING DB or OPERATIONAL DB should be used? Any guidelines for this? The sysrepo.org doc gives some hints, but I don't have a clear view on this yet, so would like to hear your comments.

Every datastore has its purpose and its specific behavior. But like I mentioned, you need to worry about `operational` with respect to RPC/action invocation. Not sure what docs you are talking about but [here](https://netopeer.liberouter.org/doc/sysrepo/master/html/index.html) is the official sysrepo documentation.

> At the beginning both app1 and app2 are using pull methods for the operational data. The app1 can do sr_oper_get_items_subscribe() successfully, while app2 fails to sr_oper_get_items_subscribe() due to they both subscribe to same node for operational_get. Is this true that only one operational_get subscription is allowed for one node?

Yes, this is a (intentional) limitation because like I said, the data gets replaced anyway so you should not need to do this although a flag to merge the data instead was later added.

> Now both app1 and app2 use the push method since the operational data in this scenario does not change frequently. Is the push method ok to use for this scenario?

You just need a particular `operational` datastore, how you manage to populate the desired data is completely up to you.

> Is it possible to subscribe RPC action with wildcard path as follows?

I have not noticed any "wildcard". Using `[name='app1-']` simply restricts the `name` value to `app1-`, nothing else. The paths are all XPath so the only wildcard is `*`. However, you do not even have to specify key values, you can simply subscribe to all the invocations of a particular RPC/action
```
/ietf-hardware:hardware/component/bbf-software-management:software/software/revisions/download/download
```

> Is the action path must be a specific path to an action node with type action like "action download"? Can I do it below?

You must always specify a path to an RPC/action, your example points to a list instance, which is invalid.

**Comment by wdl2015** [comment]
Hi Michal, thanks a lot for your professional advice. I am clear on most of the questions now. Need time to digest deeper on some of the items. Close this ticket at your convenience. Thanks much again. Br, George
