### ISSUE TITLE
command sysrepoctl -C and sysrepoctl -u deleted

### ISSUE THREAD

**Issue by congful** [sysrepo/sysrepo#2892]
Hi,

I upgraded sysrepo from V1.4 to V2.1. Two commands sysrepoctl -u (--uninstall <module> ) and sysrepoctl -C (--connection-count) were deleted. Could you please let us know the reason to  delete them? And in new software how could we uninstall a yang file and how to get connection count?

Thank you. 
[twocommandsdeleted.txt](https://github.com/sysrepo/sysrepo/files/9307926/twocommandsdeleted.txt)

**Comment by michalvasko** [comment]
What makes you think `-u` was removed? Regarding `-C`, it was removed because it is no longer needed, you can change the YANG context whether there are any connections or not. If you need this information for something else, try `# sysrepocfg -X -d operational -m sysrepo-monitoring`, which prints all the internal *sysrepo* state. You can learn the number of connections from that.
