### ISSUE TITLE
Installing lot of module is too slow

### ISSUE THREAD

**Issue by jeanseb6wind** [sysrepo/sysrepo#2918]
Hello @michalvasko,

We are using sysrepo to install module with `sr_install_module` and with lot of modules it becomes very slow (20 minutes for us).
Indeed, each time we install a new module, all others modules are recompiled. It's the same problem when enabling features.

Could we have a flag like LY_CTX_EXPLICIT_COMPILE in libyang, and call ly_ctx_compile ourselves when we are finished?

Thanks,
Jean-Sébastien

**Comment by michalvasko** [comment]
So it took a while because I first wanted to finish other simpler tasks and it was not trivial to support, either. However, there are now new API functions and also `sysrepoctl` support for installing/uninstalling several modules at once.

> Could we have a flag like LY_CTX_EXPLICIT_COMPILE in libyang, and call ly_ctx_compile ourselves when we are finished?

It is not that simple, `sysrepo` needs the context compiled to properly finish installing the modules.

**Comment by jeanseb6wind** [comment]
Thanks it works !
