### ISSUE TITLE
Real HA

### ISSUE THREAD

**Issue by lilililizheng** [sysrepo/sysrepo#2937]
hi，I would like to implement HA. Do you have any suggestions for incremental synchronization of data between the host and standby machines?

Currently I have an idea to send the xml received by the host directly to the standby machine and then use sysrepocfg --rpc with the standby machine, but netpeer2 ignores the non-netconf rpc. Then I thought of using sysrepocfg --edit, but this would require removing the rpc headers and operation nodes and just getting all the data nodes, but this seems hard to do, do you have any good suggestions?

**Comment by lilililizheng** [comment]
Or do you have any ideas on how to synchronize data with the sysrepo database?

**Comment by michalvasko** [comment]
I do not know what HA means so to properly help I would need to know exactly what you want. Nevertheless, based on what you described you want to somehow keep consistent data between *sysrepo* and your device. The best way to achieve this is by writing your own custom datastore plugin that will essentially not store the data in *sysrepo* at all but directly in your storage, it being whatever.

**Comment by lilililizheng** [comment]
HA indicates the active/standby mode. active The server is working. The standby server is in the monitoring preparation state。If I send a route to device A, I need that data to be synchronized to device b immediately

**Comment by lilililizheng** [comment]
Well, if I say master/slave, you might understand. There are two devices A/B, A works normally, and B takes over the work of A immediately when A goes wrong, so I hope to keep the data of A/B consistent at all times. Is there any way to make this happen? Or is this work done at the netconf level.

**Comment by michalvasko** [comment]
I see. Then there are several ways this can be achieved. In case you can change your devices, they do not need to have any configuration data themselves and just keep them stored in *sysrepo*. Then, both devices can normally access the data and there is only a single copy. If you want to keep the 2 storages of data in both devices A and B, it would be best if you implemented your own custom datastore plugin that would always the data into both storages keeping them always consistent. Any other solutions would be prone to some problems but depending on your requirements, they may also be possible.

**Comment by lilililizheng** [comment]
I don't understand the first way you mentioned, how two devices share a sysrepo, please understand, I use netopeer2 as the server. It is equivalent to two devices running at the same time. When A client is connected, the ip address of A is preferred. When A is powered off or a fault occurs, the ip address of B is changed to that of A. In the second way, the data will only be sent to one of the devices, so I need to listen for sysrepo changes and then send the changed data to the other device and write it to the database. The problem now is how do I write the data quickly to another device's database.

**Comment by lilililizheng** [comment]
<interfaces xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" xmlns="urn:ietf:params:xml:ns:yang:ietf-interfaces">
		<interface>
			<name>ens33</name>
			<type xmlns:ift="urn:ietf:params:xml:ns:yang:iana-if-type">iana-if-type:ethernetCsmacd</type>
			<enabled>true</enabled>
			<ipv4 xmlns="urn:ietf:params:xml:ns:yang:ietf-ip">
				<address nc:operation="delete">
					<ip>192.168.254.178</ip>
					<prefix-length>24</prefix-length>
				</address>
			</ipv4>
		</interface>
	</interfaces>
If the client sends the above xml to A, sysrepo senses the database change and executes successfully. If I can get the xml, I send it directly to B and execute sysrepocfg --edit

**Comment by lilililizheng** [comment]
If the client sends the above xml to A, sysrepo senses the database change and executes successfully. If I can get the xml, I send it directly to B and execute sysrepocfg --edit
![image](https://user-images.githubusercontent.com/106649263/196396689-1daeb51c-022e-463e-9019-878a4bbb15ef.png)

**Comment by lilililizheng** [comment]
Sorry, maybe some of the questions are sloppy because there is very little documentation for sysrepo. I'm still trying to learn

**Comment by michalvasko** [comment]
You mainly need to describe your architecture exactly, it is not about documentation or anything, there are just many ways the whole suite can be used and the solution depends on them. So the main question is, are your devices connected to the server remotely using **NETCONF** or are they connected locally directly to **sysrepo** and just listening for the changes?

**Comment by lilililizheng** [comment]
The client connects to my local directory through netconf. The server is written locally with netpeer2 and directly uses sysrepo as the database. If the client needs to deliver a configuration, the data is transferred to the server through netconf, and the server is responsible for parsing the xml and writing the data to sysrepo. Then the plug-in listens for the changes in sysrepo, obtains the changed data and operations, and then I execute (eg: ip addr add........)

**Comment by michalvasko** [comment]
But what about the devices A and B? Are they both locally connected to sysrepo listening for changes? Or are they NETCONF clients A and B connected to the server? I really cannot help you unless I understand exactly and I still don't.

**Comment by lilililizheng** [comment]
Yes, both A and B listen to their own sysrepo. Their workflow is exactly the same.

**Comment by michalvasko** [comment]
What do you mean their own? If they are on a single machine, it should be the same *sysrepo*.

**Comment by lilililizheng** [comment]
They are different devices

**Comment by lilililizheng** [comment]
A and B are two identical devices with their own servers, the sysrepo database. The same goes for running the program above

**Comment by lilililizheng** [comment]
Now the data of A has changed, and I know the ip of B, so I hope the database of B will also change. However, the data sent can only be changed data, not all the data in yang. For example, there are 10,000 pieces of data in the running library of A, and now one of them has been changed. I hope that this piece of data of B will also be changed. You don't want to send the entire database to B because there is a lot of data.

**Comment by michalvasko** [comment]
Okay, it is still not clear, so I will try to describe it the way you should have and you will correct what is wrong. You have 3 machines, NETCONF server A (with device A), NETCONF server B (device B), and a NETCONF client. You normally connect to A and edit its configuration, device A behaves accordingly. However, if server A becomes unusable (for whatever reason), you want to connect to server B and use that. But, at the same time you expect all the configuration changes you made in server A to be on server B? For that reason you were trying to send them from server A to server B on every configuration change? Does not really make sense to me but that is what I could understand.

**Comment by lilililizheng** [comment]
Yes, in a network device, this is very necessary, I have to make sure that users can always connect to the service and handle their requests

**Comment by michalvasko** [comment]
Alright, so then *sysrepo* will not help you because it operates strictly locally. And NETCONF does not have any special support for this scenario so what I would do is simply send all the edits to both server A and server B, is that not possible? I mean, you can also just send an edit to server A, which then connects to server B and sends the same edit there and vice versa.

As for the documentation, of course, there are doxygen [docs](https://netopeer.liberouter.org/doc/sysrepo/master/html/) linked in the README.

**Comment by jktjkt** [comment]
Netopeer2 and sysrepo are (mainly) implementations of the NETCONF protocol, which is why the feature-driven development usually focuses on NETCONF-level features. On the other hand, the NETCONF protocol does not deal with high availability (HA) and primary/secondary failover scenarios or hot-standby replicas. You're right that these are all relevant technologies, but this open source software stack currently does not implement that for you :).

If you are OK with a client-assisted solution, then you might probably implement something very close to this via the `confirmed-commit` feature -- but IIRC sysrepo currently doesn't support that.

If you're, however, looking for a server-side implementation, you will have to figure out the full architecture. NETCONF is not just about the content of a datastore (which can indeed be replicated without too much hassle given enough developer time). The devices themselves are stateful as well, there are the user-level RPCs, and nothing guarantees that their execution is deterministic -- and that means that it's super hard to turn this thing into a distributed system.

Imagine a NETCONF-driven card game. It makes sense to have a `huffle-cards` RPC which will perform a non-deterministic, fully random shuffling of the card deck. How would you replicate that to your hot-standby failover slaves?

**Comment by lilililizheng** [comment]
thanks
