### ISSUE TITLE
config data in json format

### ISSUE THREAD

**Issue by bpsinghtech** [sysrepo/sysrepo#2971]
Hi,

I have two interface on my device, one netconf interface. here neetopeer2 daemon receive config data in xml format and store it in sysrepo.  on config change, sysrepo calls the registered callbacks.

 Another interface is cloud interface where config data is received in json format over websocket protocol.
my problem is how to store this json data to sysrepo  since sysrepo works on xml data. 

Does sysrepo provide API which accept data in json format ? 

Or do I need to convert json data to xpath and call sysrepo API ? if yes, how can I convert json data to xpath and which sysrepo API to use  to store data in sysrepo? 

Or do I need to convert json data to xml format and  use a local netconf client which will make netconf connection with neetopeer2 and pass xml data  which will store xml data to sysrepo. If yes,  how can I can convert json data to xml format ?

Hope I am able to explain my problem.

Thank you.

Regards,
BPS

**Comment by jktjkt** [comment]
There might be some confusion going on here because sysrepo doesn't really work with XML data. It works with "data which conform to a set of YANG models", and these data are often serialized into either XML, or JSON. In both cases, though, it's not some arbitrary XML or arbitrary JSON data. The XML serialization is defined via RFC 7950 directly, while the JSON serialization is as per RFC 7951. There are other, experimental serializations such as CBOR, but that's not relevant here. Then there are the NETCONF protocol (as fully implemented by [@CESNET/Netopeer2](https://github.com/CESNET/Netopeer2/)) which uses the XML serialization over TLS or SSH connections, and the RESTCONF protocol (partially implemented by [@CESNET/rousette](https://github.com/CESNET/rousette)) which uses either JSON, or XML, both over HTTPS. As far as I know, there's no standard for "YANG over websocket".

In case you're looking for a RESTCONF server, I suggest to help finalise `rousette`, then you'll get a RESTCONF server which talks to `sysrepo`. If you have a custom, websocket-based protocol which is not a RESTCONF, then you'll have to write code which translates that proprietary API into sysrpeo calls -- but you can still use JSON there as long as your protocol's JSON serialization of YANG data conforms to RFC 7951.

**Comment by michalvasko** [comment]
Just parse the JSON data with `lyd_parse_data()` and pass the returned data tree to *sysrepo* using [`sr_edit_batch()`](https://netopeer.liberouter.org/doc/sysrepo/devel/html/group__edit__data__api.html#ga6661900582c6948622efb54a15ef8fa7) (followed by `sr_apply_changes()`).

**Comment by bpsinghtech** [comment]
Hi Michalvasko,

Thank you. 

Just to be clear:

Raw JSON config data received over websocket, pass this raw JSON data to   lyd_parse_data(). 
Pass returned data to  sr_edit_batch().
Then call  sr_apply_changes().

**Comment by michalvasko** [comment]
Yes, that is how you apply the data as an `edit` in *sysrepo*.

**Comment by bpsinghtech** [comment]
Thank you Michalvasko.  Will try and update you. 

And one more thing: Adapter, which register callbacks with Sysrepo, on config change Sysrepo calls those callbacks.  I believe no change required on adapter callbacks side. It will work as it is working with XML data received over Netconf interface.

**Comment by michalvasko** [comment]
Of course, what @jktjkt said, *sysrepo* internally always works with *libyang* data tree representations that abstract from any specific YANG data format.

**Comment by bpsinghtech** [comment]
Okay. Thank you very much. Will try and update.
