### ISSUE TITLE
How to use "replace" functionality for a subtree instead of entire module

### ISSUE THREAD

**Issue by MoshikaKarthesan** [sysrepo/sysrepo#2990]
I have 2 ACL rules under a single access-list
access-list acl
seq 10  permit ip any any 
seq 20  permit ip  any any

I'm trying to  modify seq 10 permit ip  any any to seq 10 permit ip any.
I'm setting the attributes using sr_set_item_str and applying using sr_apply_changes, but it performs merge operation hence I get no callback for the deleted attribute. I tried using sr_replace_config, but entire module is getting replaced. My requirement is to perform replace operation only for one acl rule.
Is it possible to perform that operation using any sysrepo API?

**Comment by michalvasko** [comment]
The `replace` operation is not supported in the API you are using because of problems with joining several dependent operations together. But *sysrepo* essentially supports everything that [edit-config](https://datatracker.ietf.org/doc/html/rfc6241#section-7.2) does by using [`sr_edit_batch`](https://netopeer.liberouter.org/doc/sysrepo/devel/html/group__edit__data__api.html#ga6661900582c6948622efb54a15ef8fa7). So just create the exact edit you want to apply and then use this function followed by `sr_apply_changes`. Use *libyang* for creating the edit, either step-by-step by appending the nodes using `lyd_new*` functions or by parsing XML/JSON data using `lyd_parse_data_mem` with the `LYD_PARSE_ONLY` flag.

**Comment by MoshikaKarthesan** [comment]
Is there any particular reason why only merge operation is used in sr_set_item_str and not replace. If there is an option to set operation to replace in sr_set_item_str, then can we use the combination if sr_set_item_str , sr_edit_batch and sr_apply_changes for replace operation?

**Comment by michalvasko** [comment]
> Is there any particular reason why only merge operation is used in sr_set_item_str and not replace.

Like I said

> The `replace` operation is not supported in the API you are using because of problems with joining several dependent operations together.

> then can we use the combination if sr_set_item_str , sr_edit_batch

You cannot combine these 2 approaches, for the same reason above. Just use `sr_edit_batch()` followed by `sr_apply_changes()`, there are no other options.
