### ISSUE TITLE
Host type deviation for Ngc Ip is allowing invalid entry as input.

### ISSUE THREAD

**Issue by Sailahari1999** [sysrepo/sysrepo#2993]
Hi,

Invalid input entry for Ngc-ip is validated at yang level.(Special characters is also allowed as a valid input after adding deviation host type).

netopeer2-server 2.1.41 (Version)

Steps to reproduce:

install my-yang.yang  (complete yang folder attached with all dependent yangs)
run netopeer2-cli and server
edit-config --target running --config=/tmp/valid_ip.xml ------> this works fine.
edit-config --target running --config=/tmp/invalid_ip.xml --------> this is also working fine, ideally this should fail at yang but it is accepting the input.

- deviation "/me3gpp:ManagedElement/gnbcucp3gpp:GNBCUCPFunction/ep3gpp:EP_NgC/ep3gpp:attributes/ep3gpp:remoteAddress" {**deviate replace {type ieft-inet-types:host;**}

Sample Invalid host names : 121.210.106.142& , domain test$.com , test@
[cucp-yang-7.2.61.zip](https://github.com/sysrepo/sysrepo/files/10518663/cucp-yang-7.2.61.zip)

**Comment by michalvasko** [comment]
Okay, I have managed to test it even though I had to modify some YANGs and the data files you provided so that all the `min-elements` were satisfied and the node names were correct (not the first time you have provided such a messy example). But the invalid values were correctly rejected just as I thought they would because a problem with unions has been fixed in *libyang* some time ago. Just use the latest release versions of all the libraries and it will work correctly.
