### ISSUE TITLE
Distinguish sysrepo callback triggered by netconf client or another sysrepo callback

### ISSUE THREAD

**Issue by satomhxl** [sysrepo/sysrepo#2994]
Hello, I want to know how to distinguish whether a sysrepo callback function is triggered by a netconf client or another sysrepo callback function, in a sysrepo plugin.

I tried to use `sr_session_get_orig_data()`, but it seems when a sysrepo callback function is triggered by another sysrepo callback, the `session->ev_data.orig_data` is empty.
Can I think that when `session->ev_data.orig_data` is empty, the sysrepo callback is triggered by another sysrepo callback?

Or is there any other suitable method？

Thank you very much.

**Comment by jktjkt** [comment]
Sysrepo is all about a collaborative access to a YANG database. Various sysrepo users are free to set these originator data, or to leave them unset. The NETCONF server, `netopeer2-server`, is one of these "sysrepo users", and it tries to play nicely by setting that optional data structure so that everybody else knows that the current operation was triggered over NETCONF for a particular user. What the other sysrepo users are doing (or not doing) is up to them.

> Can I think that when session->ev_data.orig_data is empty, the sysrepo callback is triggered by another sysrepo callback?

If there are no originator data, it means that the caller did not set any data. In practical terms, it means that the call did not originate via `netopeer2-server`. But you don't know whether it's a change which was pushed via another standalone session in response to the original data edit, via `sysrepocfg`, or via some sysrepo client which, say, polls some HW and pushes updated data. If you need to react to changes pushed via some sysrepo plugin, why don't you write that plugin in such a way that it sets some plugin-specific originator data?

Also, do not access the originator data directly; call `sr_session_get_orig_data()`.

**Comment by satomhxl** [comment]
Got it, thank you.

**Comment by michalvasko** [comment]
The main method of distinguishing various originators is by calling `sr_session_get_orig_name()`, which will be `netopeer2` in case it is the server (NETCONF originator). And only in that case you should be accessing the `orig_data` with their exact [meaning](https://github.com/CESNET/netopeer2/#sysrepo-callbacks), all this is mentioned in the netopeer2 README.

**Comment by satomhxl** [comment]
Yes, after checking related APIs I found `sr_session_get_orig_name()` and learned how to use it after some review.
Thank you again.
