### ISSUE TITLE
Is there any possibility to remove a value from range type value

### ISSUE THREAD

**Issue by amitnagraj** [sysrepo/sysrepo#3004]
Hi Michal,

I m using Sysrepo v2.0.47

I want to delete a single value from a range type value, for example:

```
{
  "example:cont" {
     "range-val": "1-5"
   }
}
```
I want delete 3 from this range, so the output would be:
```
{
  "example:cont" {
     "range-val": "1,2,4,5"
   }
}
```
Is it possible to achieve this or any yang type that i can use?

**Comment by jktjkt** [comment]
Are you asking about modifying the range *type* so that it doesn't accept a specific value? I'm asking because these JSON samples are *data*, not *schema*. If so, the answer is "it depends". Look at YANG-level `augment`, `refine` and `deviate` statements, or simply at using another type in your model.

**Comment by amitnagraj** [comment]
No i m asking about the json data only.
```
If so, the answer is "it depends". Look at YANG-level augment, refine and deviate statements, or simply at using another type in your model.
```
Will check this

Thanks,
