### ISSUE TITLE
how to use sr_delete_item function

### ISSUE THREAD

**Issue by hi-Mr-ye** [sysrepo/sysrepo#3008]
Hi!
use sr_delete_item function, but print error, :
![image](https://user-images.githubusercontent.com/90752673/219013464-f2b2b4f8-4543-47e1-9b49-bc9e0c5019b3.png)
![image](https://user-images.githubusercontent.com/90752673/219013852-8c5ab1b4-09b5-4959-89ca-376182cdf399.png)

why?
netopeer2-server print message is:
![image](https://user-images.githubusercontent.com/90752673/219009466-859a19d3-4719-4691-914b-069b4b1e18e8.png)
and netopeer2-server version:
![image](https://user-images.githubusercontent.com/90752673/219009611-0e60c99d-14b6-4b9a-b661-4790b2d9bdf3.png)

**Comment by michalvasko** [comment]
Is this code perhaps executed is a module change callback? When the data of the same module are being changed? Because that would result in a dead lock on the specific module lock.

**Comment by hi-Mr-ye** [comment]
yes. This code is executed in a callback. How can I solve it?

**Comment by michalvasko** [comment]
Deleting some data as a reaction to some other data being modified is a really strange thing to do which I would think points to a design error. In any case, if you wait with the changes for the `SR_EV_DONE` event instead of `SR_EV_CHANGE`, it could work (as long as this additional change is not again calling the same callback you are in, when you will get a dead lock again).
