### ISSUE TITLE
Does sr_get_items contain all required data during EV_CHANGE and EV_ABORT?

### ISSUE THREAD

**Issue by MoshikaKarthesan** [sysrepo/sysrepo#3025]
Can we retrieve data using sr_get_items during EV_CHANGE and EV_ABORT.

**Comment by MoshikaKarthesan** [comment]
In case of modification or deletion of an attribute, will sr_get_items contain the updated database information

**Comment by michalvasko** [comment]
> Can we retrieve data using sr_get_items during EV_CHANGE and EV_ABORT.

Yes.

> In case of modification or deletion of an attribute, will sr_get_items contain the updated database information

Yes.

**Comment by MoshikaKarthesan** [comment]
Step 1:
If I have an xpath in the format ,
a/b/c , a and b are keys and c is simply a leaf attribute

Step 2:
 I'm adding one more attribute to the same xpath, 
say, a/b/d , a and b are keys and d is simply a leaf attribute
I get a callback for creating d. Now sr_get_items will have the info of a,b,c and d.
At this point ,is there any API to get only the previous data i.e a,b and c only

**Comment by michalvasko** [comment]
Your description is confusing because `keys` is a term used for `list keys` and they can never have any children. But I think I can answer anyway, the only way to get some information about the previous data (before the change that is being processed) is to iterate over the changes, you always get information about both the new data and previous data (but not directly in the form of a tree).
