### ISSUE TITLE
Clarification on SR_SUBSCR_CTX_REUSE

### ISSUE THREAD

**Issue by MoshikaKarthesan** [sysrepo/sysrepo#3041]
"Flag changes:
 removed SR_SUBSCR_CTX_REUSE
- redundant because now the [out] subscription parameter must always be initialized to NULL on the first call."

Please can you explain what exactly has to be done for each module subscription since SR_SUBSCR_CTX_REUSE is deprecated.

**Comment by michalvasko** [comment]
I was hoping the documentation for this parameter makes it clear. As long as you initialize the subscription to `NULL`, the first subscription changes it to non-`NULL`, obviously, when it creates the subscription. Based on that can any following subscriptions distinguish between the first subscription and the following ones. So, in short, there is nothing you have to do instead of using the deprecated flag.
