### ISSUE TITLE
netopeer2-server print double free or corruption (out)

### ISSUE THREAD

**Issue by hi-Mr-ye** [sysrepo/sysrepo#3043]
Hi 
I saved the netopeer2-server print. and The following information is displayed when netopeer2-server stops running.
![image](https://user-images.githubusercontent.com/90752673/231070908-ae3b68ea-b5cf-4316-995c-4da424ecbd39.png)

Print that stops running for the second time
![image](https://user-images.githubusercontent.com/90752673/231070617-86a4f92e-4540-42df-afdf-c4a87cf07e92.png)

The test environment :
1:Eight hosts are connected to netopeer2-server
2:Run the user-rpc command together within three seconds
3:sr_rpc_subscribe function:
![image](https://user-images.githubusercontent.com/90752673/231076351-a15bbc93-2f0d-4c75-b5fa-6ebd91235944.png)
and It takes 7 seconds to run the rpc_pm_data function
Why does the netopeer-server stop Running?
Is it because of multiple user-rpc executions in a short period of time?

and my netopeer2-server versions:
![image](https://user-images.githubusercontent.com/90752673/231077424-83396784-31b8-4a7e-afc5-8ae6ced9843e.png)

**Comment by michalvasko** [comment]
Whatever the cause, this should definitely not happen but the version you are using is not even a specific release (version 2.1.49 has been released) so it would be best if you could update to the current latest release or `devel`). Other than that it may simply be an improperly handled timeout because no matter how many session you have, all the received RPCs must be executed serially.

So if the problem persists after updating, please include exact details regarding the steps taken to reproduce it. Are you simply subscribed to an RPC, which you execute more-or-less simultanously from 8 NETCONF clients?

**Comment by hi-Mr-ye** [comment]
"Are you simply subscribed to an RPC, which you execute more-or-less simultanously from 8 NETCONF clients?"
how should I understand it?
It's eight different ip addresses, so it's subscribed to 8 RPC?

**Comment by michalvasko** [comment]
I was simply referring to the 3rd bullet in your "test environment", if you just write an app calling `sr_rpc_subscribe` and running it locally, you are subscribed to it, which is all I meant. Not to be confused with the `subscribe` command in *netopeer2-cli*, which subscribes to NETCONF notifications, sorry for not mentioning it explicitly.

**Comment by hi-Mr-ye** [comment]
Thank you. I understand!
