### ISSUE TITLE
How to check or inform the program if a new subscription is occurred.

### ISSUE THREAD

**Issue by mustafatayf** [sysrepo/sysrepo#3044]
Hi everyone,

I am looking for a API function or approach in order to get the information of "whether anyone created a new subscription to 'notification' in the given yang module, or not".

I already try to use "sr_notif_subscribe(), sr_notif_subscribe_tree(), sr_oper_get_subscribe()" functions. However, I think all these functions are implemented for other purposes. For example, if I am correctly understood,  sr_notif_subscribe/tree functions called in case of received notifications.  

To short, what I want to do is; As a netconf server, 
- if a client start subscription to a "notification" on the yang module.
-  then a function will be called to take some actions.
- or a function periodically check for the existence of subscription to the given "notification" 

Lastly, I am not sure that; whether the sysrepo already include an implementation to handle my request or not.

Sorry for the possibly unclear question and,
Thanks in advance for your replies.

**Comment by michalvasko** [comment]
1) Whenever a notification subscription is created by a NETCONF server, the RPC `/notifications:create-subscription` (there is another newer RPC that is not used much) must be executed. You can subscribe to this RPC yourself in a *sysrepo* app just use a different priority than `0` because that is what *netopeer2-server* is using. But note the RPC does not include exact information as to what notifications are subscribed. There is only the stream and optionally a filter, which notifications those match is up to you to figure out but should not be difficult using some *libyang* functions.

2) Periodically checking existing subscriptions is also a possibility. There is `/sysrepo-monitoring:sysrepo-state/module/subscriptions/notification-sub` list with all the notification subscriptions of a module. However, it seems there is no information about the used filter so you would likely not be able to make sure a notification is really subscribed to this way.

**Comment by mustafatayf** [comment]
I will try to subscribe `/notifications:create-subscription` with lower priority.

Thank you
