### ISSUE TITLE
Netopeer2 release 2.1.49 shows performance drop on onu configuration response time

### ISSUE THREAD

**Issue by wlau** [sysrepo/sysrepo#3051]
https://github.com/sysrepo/sysrepo/issues/2843

We have tested our software with 1024 onus configuration using the fixes from the above thread, e.g. release set:
netopeer2 2.1.42
libyang 2.1.4
libnetconf2 2.1.25
sysrepo 2.2.12

The 1st onu config time is: 0.5 sec
The 1024th onu config time is: 32.3 secs

Recently, we moved to use a later set of libyang/netopeer2 library, and have noticed a significant drop in performance (~50%) on the 1024th onu.

netopeer2 2.1.49
libyang 2.1.30
libnetconf2 2.1.28
sysrepo 2.2.36

The 1st onu config time is: 0.5 sec
The 1024th onu config time is: 46.1 secs

Any idea what is the reason behind this performance degradation?

Thanks,
WaiMin

**Comment by michalvasko** [comment]
In all likelihood the cause is switching the default datastore from using LYB to JSON in *sysrepo*. But I have failed to reproduce any significant performance changes with this change, I could only see differences in ~5% at most. So if you provide a nice use-case reproducing this I could measure the performance and maybe finally actually see a significant difference.
