### ISSUE TITLE
building sysrepo as a static library

### ISSUE THREAD

**Issue by amamory** [sysrepo/sysrepo#3067]
Hi, 

The current cmake file is hardcoded to SHARED lib mode
https://github.com/sysrepo/sysrepo/blob/9333e0fc0ee25b3f955da94ab496287b442b7fcd/CMakeLists.txt#L331

I was wondering if there is a strong reason for this or it's more like a preferable mode.

cheers!

**Comment by michalvasko** [comment]
The reason is that you are the first to ever mention wanting to build *sysrepo* as a static library. I do not have much experience with those but I cannot think of a reason why it should not be possible so you may try it and even prepare a PR with the new option `ENABLE_STATIC` similar to *libyang*.

**Comment by amamory** [comment]
precisely ! libyang has this explicit option 'ENABLE_STATIC' and i was wondering why this was not true for sysrepo.
I'll do some tests here and let you know soon.
