### ISSUE TITLE
Does sysrepo support external DB instead of sysrepo datastore

### ISSUE THREAD

**Issue by anandrohit02** [sysrepo/sysrepo#3087]
I have few queries related to sysrepo datastore support
1. Does sysrepo supports external DB(like redis) interface to perform get/edit operations ?
2. Is there any plugin to interact with external DB instead of sysrepo Datastore ?

**Comment by michalvasko** [comment]
Yes, you can write a [plugin](https://netopeer.liberouter.org/doc/sysrepo/devel/html/sr_plugins.html) that will read/write data from anywhere including a database. We are currently working on a MongoDB plugin and unless you plan to write a really specialized functionality (for particular YANG module), I would not recommend this because it requires significant effort to map YANG data to database entries.

**Comment by anandrohit02** [comment]
> It requires significant effort to map YANG data to database entries
by mapping you mean:
1. getting sysrepo requests and preparing DB query for get/set data
2. and preparing response back to sysrepo

And any release plan for the MongoDB plugin?

**Comment by michalvasko** [comment]
It is mostly working now meaning it can store and load all the data. After that is completely finished, we will being optimizations so that it is reasonably faster than the current JSON datastore, hard to estimate how long will that take.

**Comment by anandrohit02** [comment]
How about the below query?
> It requires significant effort to map YANG data to database entries

by mapping did you mean:
1. getting sysrepo requests and preparing DB queries for get/set data
2. and preparing a response back to sysrepo

**Comment by michalvasko** [comment]
Yes, something like that.

**Comment by anandrohit02** [comment]
Few queries related to external DB support:
1. is the "SR_HAVE_INOTIFY" service used with the MongoDB plugin or any other method for cache?
2. Are you introducing any new callbacks or using the same sysrepo callbacks for the MongoDB integration?
3. How are you achieving config and operational data separation?
4. Can we use startup, running, and candidate storage with MongoDB or only for running?

**Comment by anandrohit02** [comment]
Few queries:
1. In Datastore plugin store API, are we printing complete data into running DB without checking which parameters are edited "lyd_print_fd"?
2. If yes, Is MongoDB plugin also adding complete data irrespective of parameters edited? or there are changes in sysrepo also?
3. Is there a way to pass only edited parameter to datastore plugin API, currently we are getting "mod_data" as complete data ?

**Comment by michalvasko** [comment]
1. You mean in the JSON File DS plugin and yes, it prints the whole data on every edit, which is an obvious inefficiency.
2. The main idea why a database is used is to avoid this complete rewrite of the whole datastore on every change.
3. If you look at the parameters, there are both `mod_data` and `mod_diff`, the latter is meant for exactly this, to communicate only the changes so that the plugin can store only those, if it can.
