### ISSUE TITLE
List item is missing from operational datastore after re-create

### ISSUE THREAD

**Issue by awesomenode** [sysrepo/sysrepo#3121]
Hi,

I ran into an issue with lists, when I delete and re-create an instance then it is missing from operational datastore while present in running.
 
I attached an example to reproduce the issue:
[reprod.zip](https://github.com/sysrepo/sysrepo/files/12129912/reprod.zip)

```
$ ./main  
RUNNING: OK 
OPERATIONAL: OK 
RUNNING: OK 
[ERR] No data found for "/ietf-interfaces:interfaces/interface[name='eth0']". 
OPERATIONAL: NOK
```
 
To remove any pushed oper data, `sr_delete_item()` is also called for operational datastore in the example.
The issue is present when there was no pushed data.
 
sysrepo version: 2.2.98
libyang version: 2.1.100

Thank you in advance!

**Comment by jktjkt** [comment]
Why are you explicitly deleting content from the `operational` DS in the first place? The default behavior is that the `operational` DS is populated by configuration data from the `running` DS to which a subscription exists, and on the top of that, `operational` data can be modified by any edits which target the `operational` DS directly ([docs](https://netopeer.liberouter.org/doc/sysrepo/master/html/#oper_ds)).

What your code is doing is the following:
- create `/ietf-interfaces:interfaces/interface[name='eth0']/type` in the `running` DS
  - it (implicitly) creates the list instance `/ietf-interfaces:interfaces/interface[name='eth0']` in `running`
  - this XPath has an active subscription, which means that the data appear in `operational` as well
- delete `/ietf-interfaces:interfaces/interface[name='eth0']` from `running` DS
  - this implicitly removes that thing from `operational` as well
    - **unless** you've also pushed some other data below `/ietf-interfaces:interfaces/interface[name='eth0']` directly to `operational` DS, in which case the `type` might be missing, but other data will remain until you discard them
- push a delete operation of `/ietf-interfaces:interfaces/interface[name='eth0']` to `operational`
  - because sysrepo internally tracks "the diff" or "all the edits" which together constitute the `operational` DS, this means that this delete now overrides any previous/implicit content of that XPath in `operational`, including whatever might be implicitly copied from `running`
- create `/ietf-interfaces:interfaces/interface[name='eth0']/type` in the `running` DS again
  - at this point the content of `operational` contains an implicit copy of stuff from `running`, and on top of that an explicit operation to delete the entire XPath `/ietf-interfaces:interfaces/interface[name='eth0']`
    - as a result, that subtree does not appear in the `operational` DS

Are you perhaps looking for [`sr_discard_oper_changes`](https://netopeer.liberouter.org/doc/sysrepo/master/html/group__conn__sess__api.html#gac099a7dbf7109ba64641e0f780125ec2) which "undoes" a push of some stuff to `operational`?

**Comment by awesomenode** [comment]
`sr_discard_oper_changes` is what I'm looking for, it solved my issue.

Thank you for your help!
