### ISSUE TITLE
Question regarding sr_discard_items()

### ISSUE THREAD

**Issue by awesomenode** [sysrepo/sysrepo#3126]
Hi,

I have multiple applications handling pushed operational data in a yang module.
 
With latest sysrepo version the function `sr_discard_items()` can be used to remove pushed operational data,
but only data created by the same application can be removed - in other apps the function does nothing.
 
Is there any way to delete data from other applications too, or is there any planned API enhancement that will make it possible?

Thank you in advance!

**Comment by jktjkt** [comment]
As [the documentation explains](https://netopeer.liberouter.org/doc/sysrepo/master/html/#oper_data), sysrepo implements the operational DS as a "series of edits" which are applied on top of each other. These edits are tracked on a per-session basis. Calling `sr_discard_items` *cancels an edit* -- think of it as an undo. It cannot remove data which "were already there".

If you want to override somebody else's edit and "delete data", you can push a change with `nc:operation` set to `remove`. Just keep in mind that this sequence of edits will still be applied in some order. If you keep pushing and "deleting" (in fact, overriding) more data, the result won't be pretty. You're effectively asking sysrepo to:
1. start with some initial state,
2. apply a change on top of that,
3. apply another change which undoes step 2
4. return the result

This can get costly, and it has a potential for long debugging in future. I encourage you to review your application design because a pattern where part A inserts some data and part B subsequently removes them looks a bit suspicious. In my opinion, the only reasonable use case for pushing a `nc:operation=remove` is when your application wants to explicitly say that something which went into `operational` as a copy of data from `running` is actually not supposed to be part of the `operational` DS. That use case should be a one-shot operation, and there's no other way to achieve that result.
