### ISSUE TITLE
Confusing argument handling for sysrepocfg

### ISSUE THREAD

**Issue by mchwalisz** [sysrepo/sysrepo#3132]
It is for me confusing how `sysrepocfg` handles optional arguments for import, export, edit, rpc. Currently they **require** lack of empty space after the argument for it to work. This is inconsistent and (for me more important) breaks the usual tab completion of shells.

Example (broken):

```
sysrepocfg -E vim -f json
sysrepocfg error: Redundant parameters (vim)
For more details you may try to increase the verbosity up to "-v3".
```
Although, `vim` should be treated as argument to `-E`, just like `json` is to `-f`.

Currently working example:

```
sysrepocfg -Evim -fjson
```

In this case, both are handled as expected.

**Comment by michalvasko** [comment]
That is how `getopt(3)` works, nothing we can do about that. The problem is only with parameters with optional arguments, how should `-E vim` be interpreted? Specifically, is `vim` the argument of `-E` or is `-E` without an argument and `vim` is a separate parameter? It is treated as the latter and only `-Evim` or `--edit=vim` is treated as the former.

**Comment by michalvasko** [comment]
Fine, I assumed that since it is the default behavior, it is what is expected but I guess not really. It has been improved.
