### ISSUE TITLE
Can we use APIs based on sr_val_t

### ISSUE THREAD

**Issue by Vinay-Nayak-444** [sysrepo/sysrepo#3219]
Hi

In this link : https://netopeer.liberouter.org/doc/sysrepo/master/html/group__utils__values.html#details

A note is mentioned "It is best not to use [sr_val_t] at all and use struct lyd_node instead. Then the full libyang API is available."
So, sysrepo going to support all the set/get APIs and iterator APIs based on sr_val_t in future also... ?? 
Can you clarify what is the purpose of this note?
sr_val_t based APIs are easier to use, Hence if sysrepo supports it, we would like to use them,  instead of using lyd_node based APIs

**Comment by michalvasko** [comment]
> So, sysrepo going to support all the set/get APIs and iterator APIs based on sr_val_t in future also... ??

For now, there are no plans for removal of this API but it cannot be completely ruled out in the future.

> Can you clarify what is the purpose of this note?
sr_val_t based APIs are easier to use, Hence if sysrepo supports it, we would like to use them, instead of using lyd_node based APIs

The purpose is to encourage users to use the libyang API because it is generally more efficient and provides way more features. The only advantage of `sr_val_t` is its simplicity as you observed yourself but once familiar with *libyang*, I dare say there is no advantage anymore.
