### ISSUE TITLE
Installation error on openWRT 23.05

### ISSUE THREAD

**Issue by Sandid-Hsan** [sysrepo/sysrepo#3285]
I am facing issues compiling netopeer2-server on openWRT. The status of netopeer2-server shows that is running but it is not the case sicne I can't find a running server and 830 port isn't listening. When I run netopeer2-server -d i got this output:
root@OpenWrt:/# netopeer2-server -d
[ERR]: LY: Not found node "cancel-commit" in path.
[ERR]: NP: Subscribing for "/ietf-netconf:cancel-commit" RPC failed (libyang error).
[ERR]: NP: Server RPC subscribe failed.

**Comment by michalvasko** [comment]
You need to update how you install the YANG modules and enable `confirmed-commit` feature in `ietf-netconf` (I assume you are not using the `setup.sh` script).

**Comment by Sandid-Hsan** [comment]
I don't seem to find the setup.sh script in openWRT after compiling the image and entering the terminal. Where can i find this script and should i run before or after compilation

**Comment by michalvasko** [comment]
It does not really matter when you install the required YANG modules but you must do so. Normally, it is performed as part of `make install`, `scripts/setup.sh` is being executed which installs these modules. You can run the script on the target system but it needs the YANG modules available and in directories defined as environment variables of the script.

As a new feature in *netopeer2* `devel` branch, there is an optional library built that can perform this installation in a C function instead of a script.
