### ISSUE TITLE
Question about sr_connect performance

### ISSUE THREAD

**Issue by awesomenode** [sysrepo/sysrepo#3290]
Hi,

I found that increasing number of applications and YANG modules can rapidly increase the total execution time of sr_connect() function calls during startup.
According to my investigation the most CPU time is used by parsing of YANG modules, so all applications does mostly the same in each sr_connect call.
 
My question is whether is there a way to make it more scalable, or is there any planned improvement for it (for example share the parsed data somehow between the apps)?
An improvement idea is to make it possible to create "pre-parsed" yang module cache which can be deployed to the target running sysrepo, saving the run-time YANG parsing overhead.

Thank you in advance!

**Comment by michalvasko** [comment]
You are right regarding your observation. I did implement considerable improvements in the time it takes to load some common YANG constructions but nothing else. There was the intention to add some such mechanism that you mentioned but the effort required would be significant with the result uncertain. Maybe you can provide all the YANG modules you are using and I can check whether there are not some obvious inefficiencies that could be fixed because we generally tried to optimize only processing YANG data, not YANG schemas.

**Comment by awesomenode** [comment]
Thank you for your answer. I have done some profiling on my setup but could not find any suspicious part.
I have higher number of modules therefore there is a large multiplier on execution time.

**Comment by michalvasko** [comment]
Okay, we plan to get back to this issue and implement a solution but it will not be anytime soon.
