### ISSUE TITLE
Is there a way to filter config data via a plugin?

### ISSUE THREAD

**Issue by nullromo** [sysrepo/sysrepo#3344]
### Question

Thus far I have been using the NACM to filter data on a per-user basis. However, the NACM structure has made sysrepo incredibly slow. See the section below for details.  But my question is, does sysrepo have any mechanism for filtering data without using the NACM? For instance, I have some rules in my system that User A can only access certain nodes. User A makes a get request in the running datastore. None of the `sr_oper_get_subscribe` callbacks happen, since it's config data. None of the `sr_module_change_subscribe` callbacks happen since it's not a change. So there is no hook for me to manually filter out the data that User A is seeing in their get request.

Is there any other way to filter the data besides the NACM? If not, is there a possibility of getting something like `sr_config_get_subscribe` in the future?

### NACM
I have a lot of entries in a YANG list, and I need user access for each one to be individually toggled. As a simple example, I have a list

```yang
list my-list {
    key id;
    leaf id {
        type uint16;
    }
}
```

Say there are hundreds or even thousands of items in that list. For the corresponding NACM rules, I need to have a separate `rule-list` for each one.

```xml
<rule-list>
  <name>access-item-1</name>
  <group>user-1</group>
  <group>user-7</group>
  <group>user-9</group>
  <rule>
    <name>access</name>
    <path xmlns:my-module="urn:my-module">/my-module:my-list[id='1']</path>
    <access-operations>*</access-operations>
    <action>permit</action>
  </rule>
</rule-list>
```

If there are 100 items in my list, I need to generate this rule-list 100 times and change the `id=` in the predicate of the xpath for each one. Then I can individually assign groups to each rule-list, which will effectively grant or revoke access to each individual list item.

This works, but it massively slows down sysrepo. Because there are so many rule-lists in the NACM, the datastore now takes forever to validate. Making any unrelated change _anywhere_ in the datastore takes multiple seconds in my case simply because all these thousands of rule-lists need to be validated each time.

Maybe I'm using the NACM wrong, but I don't see another way to specify access in the right way.

If I didn't have all these NACM rules, and I could write my own plugin to do the get operation permission filtering, I think the performance would massively improve. The filtering checks wouldn't take that long, and the datastore would be much smaller so the validation on each change would be fast. So that's why I'm asking the question above.

**Comment by jktjkt** [comment]
If you have a datastore with a list that holds thousands of items, and you add a rule to an NACM ruleset for each of these list entries, this leads to an *O(n²)* complexity because of the way how [NACM is defined to work](https://datatracker.ietf.org/doc/html/rfc8341#section-3.4.5). This quadratic complexity will still be there even if you somehow optimize sysrepo to have super-efficient XPath interpreter, or whatever.

If you *really* need such a granularity (why?), then maybe you could implement it the other way round -- have an NACM rule for each "class of users", and manipulate the XPath for these rules so that you match an appropriate node-set. Or maybe you can get by only using a single rule with the `USER` XPath variable?

What is your specific use case?

**Comment by nullromo** [comment]
My use case is I have a hardware switch with many ports on a system with many users. The administrator of the system can specify which users in the system are allowed to control each port. So if there are 1000 ports and 50 different users, each user might have a completely unique set of ports that they are allowed to operate, while all the other ports are hidden from them.

So for example, it could be the case that
- User A needs access to ports 1, 5, 7, 100-130, 275, and 984
- User B needs access to ports 1, 5, 7, 8, 11, 100-125, and 984
- User C needs access to ports 222 and 223
- User D is an admin and has access to all the ports
- User E needs access to every port in the system except port 99
- etc.

Yes there is a lot of overlap, and it may be possible to coalesce some rules. Right now I have 1 rule per rule-list, and one rule-list per port, and if 2 users need to access that port I just add them both to the rule-list. But as you say, I could make a rule list for each user and add ports to the user. However, I think the amount of rules would be the same. Adding a user to 999 separate rule-lists with 1 rule each vs. adding 999 rules to a single rule-list doesn't sound much different. At the end of the day, I don't actually know the configuration of users and access rules that a given instance of the system will need to handle, so I have to expect the worst case.

> manipulate the XPath for these rules so that you match an appropriate node-set

The xpath cannot contain logical operators, as far as I can tell. I tried using a path like `.../my-node[x='1' or x='2']` and I got the error `libyang[0]: Unexpected XPath token "Operator(Logic)", expected "]".`

> using a single rule with the USER XPath variable

This sounds kind of promising, but I don't fully understand. Could you please explain what you mean by this?

**Comment by jktjkt** [comment]
> My use case is I have a hardware switch with many ports on a system with many users. The administrator of the system can specify which users in the system are allowed to control each port. So if there are 1000 ports and 50 different users, each user might have a completely unique set of ports that they are allowed to operate, while all the other ports are hidden from them.

Then it looks like your use case is not-that-well-supported by the NACM standard, I'm afraid. Maybe you cen profile sysrepo to identify a performance hotspot that we can optimize, but it's still an *O(n²)* operation underneath, which will become a problem above a certain data size.

> > manipulate the XPath for these rules so that you match an appropriate node-set
> 
> The xpath cannot contain logical operators, as far as I can tell. I tried using a path like `.../my-node[x='1' or x='2']` and I got the error `libyang[0]: Unexpected XPath token "Operator(Logic)", expected "]".`

Right, sorry, I haven't realized that it's the [`instance-identifier`](https://datatracker.ietf.org/doc/html/rfc7950#page-205) behind the scenes. My suggestion clearly doesn't apply.

> > using a single rule with the USER XPath variable
> 
> This sounds kind of promising, but I don't fully understand. Could you please explain what you mean by this?

See e.g. [this example](https://github.com/CESNET/velia/blob/master/yang/czechlight-authentication.json), or the [NACM grammar](https://datatracker.ietf.org/doc/html/rfc8341#page-36) but since the syntax for the NACM `path` is really just an `instance-identifier`, this will likely not help you that much :(.

**Comment by nullromo** [comment]
> your use case is not-that-well-supported by the NACM standard

This is what I was thinking, unfortunately. But that's why I was hoping maybe there is a mechanism in sysrepo for filtering data in some other way, not using the NACM. If any such mechanism exists, please let me know.

**Comment by michalvasko** [comment]
Sorry, but all the reasonable suggestions have already been made, I cannot help, there is nothing additional to use.

**Comment by nullromo** [comment]
Thank you for the reply. From here my path forward is to store data outside of sysrepo to avoid the validation delay.
