### ISSUE TITLE
sr_connect() without elevated privileges

### ISSUE THREAD

**Issue by NamlaZz** [sysrepo/sysrepo#3380]
I am trying to use the APIs without sudo privileges. I used GDB to examine what happens to the connection pointer after passing it inside `sr_connect`. When using sudo, `sr_connect` returns with a value inside connection pointer but without sudo the connection pointer remains a nullptr.

Is there any way I could use the APIs without elevated privelages?

**Comment by NamlaZz** [comment]
I'm building latest sysrepo and libyang from source into debian packages and installing them with sudo dpkg install. The first connection after the installation with either `sr_connect` or running `sysrepoctl -l` without sudo gives the same error: `System function call failed`.

`sysrepoctl -l` without sudo gives:
`[ERR] access() on "/etc/sysrepo/yang" failed (Permission denied).
sysrepoctl error: Failed to connect (System function call failed)`

Does the act of installing with dpkg create the SHM for the root user so it can no longer be accessed as non-root?

**Comment by NamlaZz** [comment]
the [rules](https://github.com/sysrepo/sysrepo/blob/master/distro/pkg/deb/rules) file in sysrepo have overrode those paramters. I have also tried to manually set REPO_PATH to `/opt/sysrepo` rather than `/etc/sysrepo` but that didn't help either.

```
#!/usr/bin/make -f
#export DH_VERBOSE=1
export DEB_BUILD_MAINT_OPTIONS = hardening=+all

include /usr/share/dpkg/default.mk

%:
	dh $@

override_dh_auto_configure:
	dh_auto_configure -- \
		-DCMAKE_BUILD_TYPE:String="Release" \
		-DSYSREPO_UMASK=007 \
		-DSYSREPO_GROUP=sysrepo \
		-DNACM_SRMON_DATA_PERM=660
```

**Comment by NamlaZz** [comment]
That makes sense, thank you for the help! I set my user to be part of `sysrepo` group using `sudo usermod -a -G sysrepo $USER` and refreshed the terminal and It works now.

**Comment by irfanHaslanded** [comment]
See also https://github.com/sysrepo/sysrepo/pull/3365 which allows using sysrepo without needing group/perms for "testing" purposes.

**Comment by NamlaZz** [comment]
that's very helpful, thank you!

**Comment by NamlaZz** [comment]
let's say for a given dedicated production server, if I want to enable system-wide access to sysrepo `without root` directly after installing the debian packages (given that access control is enforced on the server itself rather than than on sysrepo).

I saw your code for enabling unit tests during build without sudo, would I be able to tweak it to make it work after installing for all system-wide users?

my use case is that I have sudo privileges for apt installing but no sudo privileges for adding users to group sysrepo

**Comment by jktjkt** [comment]
> (given that access control is enforced on the server itself rather than than on sysrepo)

That won't work. Sysrepo is designed to work with a certain privilege model, and Unix permissions are just one part of that. It's a part of this design to mandate that "anything" which talks to sysrepo should be part of a preconfigured Unix group. There's the NACM implementation, and then there's that concept of recovery UID/GOD, so I think it's fair to mandate existence and control of a special user and a special group.

> my use case is that I have sudo privileges for apt installing but no sudo privileges for adding users to group sysrepo

That's... rather unusual to say the least. Realistically, it's usually *much* easier to have your system reconfigured rather than trying to change an external project to accommodate a misconfigured system.

May I ask *why* is someone giving you enough access to install systemwide packages (!) and to (presumably) provision a NETCONF server for remote control of this system, with NETCONF-level access management and stuff, and at the same time they are not giving you a real root?

**Comment by NamlaZz** [comment]
> May I ask why is someone giving you enough access to install systemwide packages (!) and to (presumably) provision a NETCONF server for remote control of this system, with NETCONF-level access management and stuff, and at the same time they are not giving you a real root?

We work in tandem with the server maintainers, we provide the tools and software applications and they manage their servers.

I don't have root access at any given point. They install the packages as part of their setup, since we don't have root access and we've been explicitly informed that root would not be granted beyond installing packages it makes for a tricky situation

**Comment by jktjkt** [comment]
Ah, that's actually good news, then. Since you're the one who's creating these packages/build-recipes/whatever, simply make sure that these groups and user accounts are created during the installation of the packages. It's OK to not *have* a root access, but you obviously still have to have a say on *how* the SW is deployed.
