### ISSUE TITLE
Netopeer is Connecting to Dual Netconf session using a single IPv6 Address

### ISSUE THREAD

**Issue by Manoj-014** [sysrepo/sysrepo#3385]
I've tried to set up a Netconf session using Netopeer, and it resulted in creating multiple sessions at the same time using a single IPv6 address, both sessions are active and functional which is an issue and it never happened before, have a look at it.

I've attached the documents related to the issue,

Thank you

![image](https://github.com/user-attachments/assets/6a19f989-20dc-4792-b9a1-4080e568f144)
![image](https://github.com/user-attachments/assets/0442f7d0-7861-4407-91c0-ab5bffe610b7)

**Comment by jktjkt** [comment]
It is not clear to me what the problem is. What exactly are you doing, using what SW and which configuration? What do you expect to see, and what you're getting instead? Also, please post text logs rather than images, and if you're reporting a possible bug in Netopeer2 server (or client?), file it there and not against sysrepo (NETCONF-level sessions are not relevant to sysrepo).

What I *think* is shown in the first picture are two inbound, call-home sessions. Is that expected? If not, why not? How does the configuration of the `ietf-netconf-server` module look like?

On the second screenshot it looks like some model-specific XML. That doesn't look relevant to me.
