### ISSUE TITLE
Cancel RW parameters changes after failed notif   

### ISSUE THREAD

**Issue by Emilka1604** [sysrepo/sysrepo#3400]
Hi, @michalvasko !

Our custom application contists two parts: sysrepo callbacks part and main application part. Application do some validation and preparate work and return RPC reply to Netconf Client during SR_EV_CHANGE and SR_EV_DONE callback's stages. After that, application trigger long main process. Notification is send after this process's finish. If some problems appear, It is nesessary to cancel rw parameters values and return old values. Therefore we need to invloke functions some kind of sr_apply_changes from code which provocate repeated same callback trigger and we should create additional logic to serve these invocations. Could you, please, offer some more ellegant and convinient way to cancel rw parameters changes except increasing of default Netopeer server timeout. 

Versions:

Sysrepo 2.2.36 
Netopeer2 2.1.49 
Libnetconf2 2.1.28 
Libyang 2.1.30

![Example](https://github.com/user-attachments/assets/c29e3a08-edea-491f-8d5e-83b39ea06f48)

**Comment by jktjkt** [comment]
How much time does that "long process" actually take, and why cannot you apply your changes from `SR_EV_DONE`? In short, why do you need a custom, non-standard mechanism for signaling success/failure instead of simply using standard NETCONF operations?

Looking at your flow chart, there's no standard NETCONF notification for "your changes have been applied successfully". If you want to stick with standardized (and therefore also, interoperable) functionality, there are really only two options:

- Either the `<edit-config>` operation blocks, and it returns only after all changes have been performed. In sysrepo and Netopeer2, this is well supported by configurable timeouts, and by the two-hase commit via `SR_EV_CHANGE` and `SR_EV_DONE`. The NETCONF server will only say "ok done" after the callbacks have returned success. You do not have to deal with serialization of incoming changes, and you can rely on sysrepo's locking to solve any data races for you. There's no extra non-standard "yup, the config has been updated" NETCONF notification because the signaling is done on the standard NETCONF RPC layer.
- Or you can implement asynchronous config changes by maintaining the state of the `operational` NMDA datastore. You'll need some asynchronous queue of changes, and each `<edit-config>` simply appends a new item to be performed "later". Once changes are applied, you reflect that in the new state of the `operational` DS by pushing an update to sysrepo.

There are many problems with approach no. 2; nothing guarantees you that you'll be only processing one edit at a time, and you'll have to deal with all the associated logical data races. You'll also have to keep track of the previous state(s), and if applying some edits fail, you'll have to revert stuff yourself. In short, you're duplicating an existing feature that's available in sysrepo, and as a bonus, you have to invent a non-standard notification for communicating the result of these operations.

**Comment by michalvasko** [comment]
Yes, obviously bypassing standard mechanisms is never a good idea and is only asking for problems. But, having warned you, I may have a good idea, considering your use-case, if you are fine with operating on NETCONF level.

You could use `confirmed-commit` with a large timeout and if the confirming notification does not arrive in the timeout, the commit will automatically be reverted.

Operating on *sysrepo* level, it will be a mess. I guess you could store the diff you are applying and when the changes are actually not applied successfully, you can revert the diff, make it into an edit (a tricky part) and using it revert the changes.
