### ISSUE TITLE
problem facing while Feature enable in sysrepo using API

### ISSUE THREAD

**Issue by biswajit84** [sysrepo/sysrepo#3413]
Hi 
when I try to enable the feature using sysrepo command ie sysrepoctl -c o-ran-wg4-features -e SUPERVISION-WITH-SESSION-ID,
It works fine. But when I try to do the same using sr_set_item_str API, then its giving "libyang error ".
If you can find the mistake, then it will be helpful.
  ` ./sysrepoctl -V `
     `sysrepoctl - sysrepo YANG schema manipulation tool, compiled with libsysrepo v2.2.170 (SO v7.24.11) `

    `  const char *feature_xpath =  "/o-ran-wg4-features:module-features/feature[name='SUPERVISION-WITH-SESSION-ID']/enabled";
    rc = sr_set_item_str(session, feature_xpath, "true", NULL, SR_EDIT_DEFAULT);
    if (rc != SR_ERR_OK) {
        printf("Error setting feature state: %s\n", sr_strerror(rc));
    } else {
        printf("Feature SUPERVISION-WITH-SESSION-ID enabled successfully.\n");
    }

    // Apply the changes
    rc = sr_apply_changes(session, 0);
    if (rc != SR_ERR_OK) {
        printf("Error applying changes: %s\n", sr_strerror(rc));
    } `

**Comment by michalvasko** [comment]
I am curious to hear where you got the XPath `/o-ran-wg4-features:module-features/feature[name='SUPERVISION-WITH-SESSION-ID']/enabled` from because, needless to say, it is completely random and would never work. While there are some internal YANG data with a similar structure, changing a feature entails much more than just a this. That is why there is the dedicated `sysrepoctl` command or the API calls `sr_enable_module_feature()`, `sr_disable_module_feature()`. You cannot change feature state any other way.
