### ISSUE TITLE
Predicate '[*]' in sr_get_items xpath triggers unnecessary oper callbacks

### ISSUE THREAD

**Issue by awesomenode** [sysrepo/sysrepo#3419]
Hi,

I ran into an issue when getting items of pushed operational list, sysrepo also triggers oper data callback which is not part of the requested tree.

I attached an example to reproduce it:
[reprod.zip](https://github.com/user-attachments/files/17152089/reprod.zip)

```
$ ./test          
[INF] Datastore copied from <startup> to <running>. 
[INF] Connection 1 created. 
Creating config list item 
Creating operational list item 
Get operational list items 
get_oper_data_cb called for /test:c1/l1/c2 
[INF] Connection 1 destroyed.
```

Here when sr_get_items is called for `/test:c1/l1[name='item1']/c3/l2[*]` then oper callback registered for `/test:c1/l1/c2` is also triggered.
Without "[*]" predicate it works as expected.

libyang version: 3.4.2
sysrepo version: 2.11.7

Thank you in advance!

**Comment by michalvasko** [comment]
I am not sure what to do about this. Calling only the required callbacks is technically an optimization. The path you have the problem with does not make sense, the predicate is completely redundant so optimizing such a path is unnecessary. There are lots of other similar paths that would all select the same nodes but optimized is only the simplest one. It is not trivial to optimize more paths since it is all text-based.
