### ISSUE TITLE
SR_ERR_LOCKED when trying to apply changes

### ISSUE THREAD

**Issue by rbu9fe** [sysrepo/sysrepo#3444]
In our system we sporadically see the error `SR_ERR_LOCKED` when calling `sr_apply_changes` on the running datastore. I thought that the provided timeout would be respected when the lock is already taken by someone else, however, from looking to the code the timeout is only considered for the duration of the triggered callbacks, whereas a timeout of 0 is used for acquiring the lock [here](https://github.com/sysrepo/sysrepo/blob/a6f309eb9601b9ef28e95a74655d7e9eac3dcc7a/src/sysrepo.c#L3968).

Is my understanding correct?
Am I supposed to always explicitly obtain the lock using `sr_lock` with a non-zero timeout if I want to avoid an error?

**Comment by michalvasko** [comment]
If you follow that code further, you will see that if the timeout is `0`, `SR_MOD_LOCK_TIMEOUT` is actually used, which is 5000 ms. You are free to change it and verify that it fixes your issues but applying changes needs only READ lock for most of its work and WRITE lock should be held only for a short time so 5 seconds should be more than enough.

**Comment by rbu9fe** [comment]
But I get the `SR_ERR_LOCKED` immediately when calling `sr_apply_changes`. If the error were a timeout then I would get the corresponding timeout error. From looking to the code I thought `SR_ERR_LOCKED` is returned only when no locking should be performed. 

When I add `sr_lock` with a non-zero timeout before applying the changes then I run into the timeout waiting for the lock. So it seems like the desired lock is never released, however, there are only 2 threads active - one wants to acquire it in order to commit something and another one is currently committing something while holding the lock (via `sr_lock`). So perhaps the latter one is somehow blocked.

So far I was unable to reproduce it in a minimal setup but I'll try to reproduce it again at least to get a coredump to see the stack trace.

**Comment by michalvasko** [comment]
Well, yes, when working with DS locks (`sr_lock()`), there is no timeout and error is immediately returned because it is assumed the DS lock will be held for long. It could be changed, so that the same timeout is used as for the callbacks in `sr_apply_changes()`, I do not really have anything against that but also just calling `sr_lock()` and `sr_unlock()` right after that seems like a perfectly fine solution.

But, since you tried that and still got an error, I believe there is an issue with your code. Solve that, so that the lock is properly released, and it should all work fine.

**Comment by rbu9fe** [comment]
Ah thanks that explains the original error. If you think it makes sense to use the callback timeout also for waiting for the DS lock then it's fine for me. Otherwise a hint in the documentation would help that an error is returned is the DS lock is already held by someone else.

Regarding the timeout I'll come back to you when I know more.

**Comment by rbu9fe** [comment]
I'm now getting a lock before writing to the running datastore. With that, as mentioned above, there's a sporadic timeout when trying to get the lock. I was able to get a stack trace now. It shows that in the context of the plugin's change callback of the running datastore the code is querying more data from the running datastore using the callback's session. Normally that works just fine but in the error case there's already another pending change request (blocking at the `sr_lock` call).

Earlier we had a similar issue with the operational datastore, but now it's only about the running datastore. So are we not supposed to query more data from the running datastore from within a change callback? Since the datastore is already locked (`sr_lock`) I assumed this would be safe.

I'm not sure whether this is important but we're also using the ENABLED flag to patch an incoming request.

**Comment by michalvasko** [comment]
Okay, that seems fine, in general, but what do you need the DS locks for? While the commit (changes) is being processed, internal locks are held and no additional ones are required. DS locks are for special cases when you need to have the datastore for yourself for a longer period of time, which, I think, is definitely not common. It is actually support mainly because of the NETCONF `<lock>` and `<unlock>` operations, I would not expect for local *sysrepo* applications to use these locks.

**Comment by rbu9fe** [comment]
Currently I need to get the DS lock because `sr_apply_changes` immediately returns an error when there's another ongoing transaction. If the callback timeout were considered for getting the lock as well then I wouldn't need the explicit DS lock.

**Comment by michalvasko** [comment]
You mean on 2 concurrent `sr_apply_changes()` calls (and with no DS locks used), the second one immediately returns an error? That is not right, what is the error code and message?

**Comment by rbu9fe** [comment]
Mhh no you're right - the other client also holds a DS lock. So you're saying using explicit DS locks should generally not be necessary?

**Comment by michalvasko** [comment]
You should use them only if you need the datastore not to change between several calls of `sr_apply_changes()`.

**Comment by rbu9fe** [comment]
Then the only open question would be whether it's allowed or not from within a change callback on the running datastore to get more data using the callback's session. Depending on concurrent activities this may lead to a timeout.

**Comment by michalvasko** [comment]
I have nothing more to add, you said it exactly as it is. The general rule is that everything is allowed (meaning no API call should lead to a crash or a data race) but if you do not handle your threads correctly, you will get a timeout/dead lock, nothing I can do about that.

**Comment by rbu9fe** [comment]
I had the understanding that the API is thread safe in a way that there is not crash/deadlock when the threads use their own session. However, that doesn't seem to be true since that's guaranteed in our code. If you think it makes sense I can try to reproduce it in a minimal test.

**Comment by michalvasko** [comment]
You misunderstand. The API is thread-safe (no data races) when the sessions are not shared between threads, otherwise there are no guarantees and your application can crash or do anything, undefined behavior. 

If you stick to this rule, it is still not guaranteed there are no threading issues in your application itself. One simple example is when you have a subscription structure, which is subscribed to both `module changes` and provides `pull operational data`. If you then call `sr_get_data()` in the callback handling `module changes` that requires the operational data, you get a dead lock because the same thread that is blocked on `module changes` needs to handle the `pull operational data` request. **There is nothing *sysrepo* can do to prevent this issue.** It could perhaps be able to detect this but it is difficult and you can always have not just a single thread, but thread (subscription) `A` causing event in thread `B`, which in turn causes event in thread `A` and so on. One needs to think about how to organize their subscriptions and threads, *sysrepo* allows for maximum flexibility when each subscription can have its own thread, all the subscriptions using a single thread, or anything in between.

**Comment by rbu9fe** [comment]
Thanks for the detailed explanation! I do understand the issues with operational pull data, however, I'm lacking some background information about the internal read/write locks sysrepo requires for which operations. In my example the change callback of the running datastore is reading more data from the running datastore. Normally this works just fine but it may fail when there's another pending change request that is waiting to get the write-lock. This has nothing to do with the operational datastore.
Internally, the running datastore is write-locked for the callback's session so I assumed (or hoped) that using that session to get more data including the requested changes (!) would be fine since only a read lock would be required. But there are some other internal dependencies to the pending write request that I don't understand.

So overall, when it's not in your control when another application wants to write into sysrepo (e.g. one Netconf and one Restconf server) it seems not to be safe to call back into the datastore from within a change callback - no matter whether it's operating on the operational or running datastore.

**Comment by michalvasko** [comment]
More details about your use-case would be necessary, but I think the important locks in this case are the module data locks. When you changing data of a module, first its READ lock is acquired until the data are actually being written, then it is upgraded to a WRITE lock. But even before, it is a special READ UPGR lock, which does not allow another READ UPGR lock to be acquired, only normal READ locks (for reading the data). You have said there are at least 2 modules being modified so yes, they can block each other some way if you are handling changes of module A and also requesting changes of module B.
