### ISSUE TITLE
schema retrieval issue

### ISSUE THREAD

**Issue by rajnkamr** [sysrepo/sysrepo#345]
Not able to retrieve schema for few modules,existing and new.
performed sysrepoctl install for new module for example

sysrepoctl --install --yang=ensemble-config.yang --owner=root:root --permissions=644

Error: <get-schema> for module 'yang', revision '2016-02-11' failed
rpc-reply {
  rpc-error {
    error-type application
    error-tag invalid-value
    error-severity error
    error-message 'The requested format is not supported.'
  }
}
Error: <get-schema> for module 'ietf-yang-library', revision '2016-02-01' failed
rpc-reply {
  rpc-error {
    error-type application
    error-tag invalid-value
    error-severity error
    error-message 'The requested format is not supported.'
  }
}
Error: <get-schema> for module 'ensemble-config', revision '2016-08-16' failed
rpc-reply {
  rpc-error {
    error-type application
    error-tag invalid-value
    error-severity error
    error-message 'The requested format is not supported.'
  }
}

**Comment by rastislavszabo** [comment]
Could you please add relevant logs from sysrepo and netopeer? Thanks.

**Comment by rajnkamr** [comment]
attached log file [netopeer-cli-req.txt](https://github.com/sysrepo/sysrepo/files/498040/netopeer-cli-req.txt)

**Comment by rajnkamr** [comment]
logfile [netopeer2-sysrepo.txt](https://github.com/sysrepo/sysrepo/files/498044/netopeer2-sysrepo.txt)

**Comment by rastislavszabo** [comment]
Hi,
these seem to be issues / not implemented tasks in Netopeer2 server, so I tried the newest code from `devel-server` branch of Netopeer2:

- getting `yang` and `ietf-yang-library` schemas works in devel
- as of now, it seems that Netopeer2 does not monitor changes in modules installed in sysrepo. This feature is probably not yet implemented in Netopeer2. It means that you need to restart Netopeer after installing of a new module to sysrepo. If you want to prioritize it, please open an issue on https://github.com/CESNET/Netopeer2. Sysrepo already provides the API to support this feature.

FYI: In the next few days, the code from devel branches of sysrepo, libyang and netopeer2 will be merged to master, that's why I tried to reproduce on these branches.
