### ISSUE TITLE
Merge configuration diff of old yang to new yang.

### ISSUE THREAD

**Issue by CeciliaZhong-CC** [sysrepo/sysrepo#3451]
Hi team,

We store the configuration of all yang modules in startup database and copy into running database when the system boot to use, but always we need to update the yang modules such as modify the attributes of yang modules or delete unused node of yang modules, how can I merge these configuration created by old version yang modules to new version yang modules successfully by skipping the node which has these yang change? Are there any solution to implement it?

The related version we used as the follow:
libyang: 3.4.2						
libnetconf2: 3.5.1		
Sysrepo: 2.11.7
netopeer2: 2.2.31	

BR,
Cecilia Zhong

**Comment by michalvasko** [comment]
There is a function for this process, [`sr_update_module(s)()`](https://netopeer.liberouter.org/doc/sysrepo/devel/html/group__schema__api.html#ga31b8d9b7e3b49e61d8850a157641a24b) so you should use that to update the YANG modules and the data will be adjusted.

**Comment by CeciliaZhong-CC** [comment]
Hi michalvasko,

Thanks for the response! I will try with this API and I want to know that are there any document to introduce this process in detail? Or some related file?

BR,
Cecilia Zhong

**Comment by michalvasko** [comment]
There is not much documentation and we plan to improve this process significantly in the following years. Currently, all it does is load the previous YANG data skipping any unknown nodes (which were removed in the new updated YANG module). If you require more control over the process, you can:

- export the YANG data to XML/JSON,
- uninstall the YANG module,
- adjust the data based on your needs,
- install the new YANG module,
- import the adjusted data.

**Comment by CeciliaZhong-CC** [comment]
Hi michalvasko,

So it can load the previous YANG data skipping the nodes whose attributes have been changed, such as narrow the range but the previous value is not in the range?

BR,
Cecilia Zhong

**Comment by michalvasko** [comment]
No, such a change is not supported. The only adjustment performed is the one I mentioned, removing unknown nodes in the data that were deleted from the new YANG module.

**Comment by jktjkt** [comment]
In our case (an embedded controller within a DWDM optical gear), we're persisting the `startup` DS as a JSON blob. Whenever we boot a new version of the system, we have some domain-specific scripts which work at the JSON level directly, bypassing the YANG DB altogether. The input to these conversion scripts is the JSON blob and the "generation ID" of the system which last touched the configuration. The script then goes ahead, applies whatever rules there are for adjusting the data, and it outputs a new JSON which gets used as a new content for the current version/revision/generation-ID of the system.

We've been doing this for just a few months. Over the past 5+ years, we've tried many different ways to solve this, but all of our previous attempts (either relying on native sysrepo tools, or trying to perform the migration at the YANG level, etc) have failed us at some point. Have fun :).

**Comment by CeciliaZhong-CC** [comment]
Hi jktjkt,

Thanks for the detail response, so the parse script is completed by yourself for your special use case?

BR,
Cecilia Zhong

**Comment by jktjkt** [comment]
You can check what we have in our [buildroot packaging](https://gerrit.cesnet.cz/plugins/gitiles/CzechLight/br2-external/+/refs/tags/v2024.10.21/package/czechlight-cfg-fs/). We have the entire sysrepo DB in a `tmpfs`, so we're installing modules during each boot based on some out-of-band device model ID. Here's the core of it:

- [`cfg-migrate.sh`](https://gerrit.cesnet.cz/plugins/gitiles/CzechLight/br2-external/+/refs/tags/v2024.10.21/package/czechlight-cfg-fs/cfg-migrate.sh) performs the migration
- [`cfg-yang.sh`](https://gerrit.cesnet.cz/plugins/gitiles/CzechLight/br2-external/+/refs/tags/v2024.10.21/package/czechlight-cfg-fs/cfg-yang.sh) installs all the required YANG modules

Right now, we do not do any "real" migrations because we only switched to libyang v3 a few months ago, and we were able to call it a flag day. In the past, the migration was very [different](https://gerrit.cesnet.cz/plugins/gitiles/CzechLight/br2-external/+/febc9991a13351300356103ab70cb2d7a1f5e6ca/package/czechlight-cfg-fs/czechlight-migrate.sh), we had [a bunch of shell scripts which manipulated data in sysrepo directly](https://gerrit.cesnet.cz/plugins/gitiles/CzechLight/br2-external/+/febc9991a13351300356103ab70cb2d7a1f5e6ca/package/czechlight-cfg-fs/migrations/). That did not work well, but you can see in there what kind of changes we were prepared to deal with. In the end, the migration to a newer version of the IETF models (`ietf-netconf-server`, etc) made us pull the plug.
