### ISSUE TITLE
Floating point exception (core dumped) with decimal64

### ISSUE THREAD

**Issue by scalabeginner** [sysrepo/sysrepo#3454]
Hi!

We have got crash (because of Floating point exception) of any application which uses libsysrepo if use decima64 type and must "(. - 0.1) mod 0.1 = 0" expression. 

To reproduce bug:

**yang:**

```
module vts {
...

list Element {
    leaf fatalAttr {
      type decimal64 {
        fraction-digits 1;
        range "0.1 .. 99.9";
      }
      must "(. - 0.1) mod 0.1 = 0" {
        error-message "values must be entered in steps of 0.1 starting from 0.1";
      }      default "10.0";
    }
}

} // end of module vts

```
config.xml:
```
<?xml version="1.0"?>
<Element xmlns="urn:adro:vts">
    <fatalAttr>10.9</fatalAttr>
</Element>
```

**sysrepocfg --version**
sysrepocfg - sysrepo configuration manipulation tool, compiled with libsysrepo v2.10.1 (SO v7.27.1)

**sysrepoctl -i min_vts.yang --init-data config.xml -v3**
Floating point exception (core dumped)

**Comment by michalvasko** [comment]
The `mod` operation did not work correctly, should be fixed now. But your condition will almost certainly never be true because of `double` precision (or lack of it), you would have to use a number that can be expressed accurately such as `0.5`. However, you can completely remove the condition because it is generally guaranteed to be true (the intention of it). Since you specified `fraction-digits 1`, it means the number will always be divisible by `0.1`.

**Comment by michalvasko** [comment]
I am hoping we will still be able to make a new release this year so in a few weeks, ideally.
