### ISSUE TITLE
Is there any way to check the status of a subscribe?

### ISSUE THREAD

**Issue by hi-Mr-ye** [sysrepo/sysrepo#3457]
Hi
I used the sr_notif_send function and the print function to return a value of 13.
sr_log_set_cb function printf an error message:
Waiting for subscription of "openconfig-system" failed, previous event "notif" ID 1 was not processed.
At the same time, Netopeer2 server printf an error message:
[ERR]: SR: Waiting for subscription of "ietf-netconf-notifications" failed, previous event "notif" ID 1 was not processed.

Is there a problem with the subscribe? and Is there any way to check the status of a subscribe?

**Comment by michalvasko** [comment]
That is a bug, the subscription is stuck for some reason. The first thing is to update *sysrepo* and all the dependencies depending on the version you are using now. If that does not help, I would need more information about how you got into this state and ideally a way to reproduce it.

**Comment by hi-Mr-ye** [comment]
Okay, thank you for your reply.
I set SR_NOTIF_CB_TIMEOUT to 10000 and sr_notif_send function uint32_t timeout_ms value is 2000.
Why does the sr_notif_send function only return the result after 10 seconds instead of 2 seconds?

**Comment by hi-Mr-ye** [comment]
Can this problem only be solved by running the netopeer2 server program again?
> That is a bug, the subscription is stuck for some reason.
Is there any other way to solve it?
For example, the kill sub, modify sub, or resync sub commands in the netopeet2 cli tool.

**Comment by michalvasko** [comment]
> Why does the sr_notif_send function only return the result after 10 seconds instead of 2 seconds?

There are lots of internal timeouts and you can customize only the time waited for the callback. Normally, the callback should always return after those 2 seconds but an unexpected timeout is elapsed, like I said, as a result of a bug.

> Can this problem only be solved by running the netopeer2 server program again?

Yes, it should. But it may happen again so that is not a permanent solution.

**Comment by hi-Mr-ye** [comment]
Okay, thank you for your reply. I will continue to test whether it can be reproduced.

**Comment by scalabeginner** [comment]
> That is a bug, the subscription is stuck for some reason. 

Hi @michalvasko! Could you please tell what this means: subscription is stuck?
We came acrross to the issue: **"Waiting for subscription of "XXXX" failed, previous event "YYYY" ID ZZZZ was not processed."** too.

So we have got some regression tests of our product which detect this problem once an hour.
According to logs this happens when several applications try to write to operational datastore (different xpaths) at same time using same one module.

Is it a bug of sysrepo or probably do we do something wrong (like long callback handler or too many subscriptions)?
What we shall check first or tune in sysrepo?

I can create a different issue if needed.
Thanks in advance for any help.

**Comment by scalabeginner** [comment]
Hi @michalvasko 

We are using:

```
libyang v3.4.2
sysrepo v2.11.7
libnetconf2 v3.5.1
netopeer2 v2.2.31
```

This error "Waiting for subscription of "vts" failed, previous event "done" ID 43 was not processed" happened again. This is reproduced some time when several applications are updating operational datastore simultaneously at same time.

**Comment by michalvasko** [comment]
Depending on how long does it take you to return from the callbacks, the timeout may be valid. If there is too much contention, the thread trying to clear the DONE event may not get the lock. You can also try to increase the timeout for the `sr_apply_changes()` function.
