### ISSUE TITLE
The sysrepo client spawns new domain sockets for each subscription

### ISSUE THREAD

**Issue by darren-west** [sysrepo/sysrepo#359]
The client uses domain sockets to talk to the daemon, in particular it spawns a new sockets for each subscriptions. This makes it very difficult to use the subscriptions on anything that is not local to the sysrepo daemon. 

Could this not use one socket?

**Comment by rastislavszabo** [comment]
Hi,
Sysrepo was designed as a local datastore, remote datastore functionality has never been in our plans. NETCONF is preferred way of remote programmability.

Sysrepo uses multiple sockets due to authorization of notification delivery. Since each model can have different access permissions set, it must expose its own socket with appropriate access permissions.

**Comment by darren-west** [comment]
Hi
Thanks for responding. 
My issue is to do with running plugins, I intend to have complex plugins that are invoked upon notifications i.e. subtree change notifications etc. Each module is packed in a plugin and has supplement code.
How can I install my plugins remotely?
Running all the plugins on a single machine will cause a scaling issue.
What do you recommend? I intend to distribute my plugins across different machines for execution.
Are you suggesting that I develop plugins at NETCONF Server level? And if so how do I do this? 
Thanks

**Comment by rastislavszabo** [comment]
Hi,
the idea is: if you have `n` machines to manage via NETCONF, you would install netopeer2, sysrepo and the plugins on all of them. Then you can use some SDN controller software that is able to manage even cloud of such NETCONF servers in one transaction.
