### ISSUE TITLE
Edit config without subscriptions fails

### ISSUE THREAD

**Issue by plajjan** [sysrepo/sysrepo#387]
```
root@d6f1d02a4010:/# sysrepocfg --editor=vim ts-lw4o6
Cannot operate on the running datastore for 'ts-lw4o6' as there are no active subscriptions for it.
Canceling the operation.
```

shouldn't I still be able to edit the configuration in sysrepo despite there being no subscriptions for this particular model?

**Comment by jktjkt** [comment]
Check [the FAQ](https://github.com/sysrepo/sysrepo/wiki/Frequently-Asked-Questions-(FAQs)). You probably want to edit startup config, not the running one.

**Comment by plajjan** [comment]
Ok, I see, thanks!

I'm trying to understand the consequences of this however.. would be interesting to have the thoughts that led to this design.

**Comment by jktjkt** [comment]
I'm just a user, not an upstream developer. The way I understand it, sysrepo is responsible for keeping track of the configuration tree and validating it according to the constraints and rules in the YANG files. However, sysrepo itself has zero knowledge about the actual *meaning* of the configuration data. If it allowed the NETCONF users to modify the running configuration, these users might get the opinion that their changes actually got *applied* -- which however wouldn't be the case.

Suppose you want to change a system's hostname. In sysrepo, this is done by a [sysrepo-plugin-ietf-system](https://github.com/sysrepo/sysrepo-plugin-ietf-system) plugin running via ``sysrepo-plugind``. If this daemon is not running or if the corresponding plugin is not loaded, hostname changes do not really affect anything, and therefore they are disabled. Once that plugin gets loaded, these changes are now "live" because there is something which can react to them.

I was also confused by this at first, but now I understand the rationale.

**Comment by rastislavszabo** [comment]
Hi,

@jktjkt explained the rationale very well.

It makes no sense to make changes in running datstore while an application acting upon the changes is actually not running. Therefore we designed it this way: when an application starts and subscribes for changes in running, we copy the data for affected subtrees from startup to running and _enable_ them, which means that from this point on they can be modified. If the application stops or crashes, the subtrees will be again disabled in the running datstore.

**Comment by plajjan** [comment]
To me this sounds a bit like replicating the ideas of opstate (current discussion in IETF/NETMOD) but you've used running and startup to differentiate between applied and intended.

The whole point of opstate is to be able to query independently whether something is actually applied and not just part of the intended configuration. Even with the daemon running (thus you've copied startup -> running) there's no guarantee it's actually "running" just yet since it likely takes some time to apply the config.

From a provisioning perspective I think it's confusing because we always work with the running datastore (most of the time we trust the box to copy running -> startup when doing NETCONF commit which means we never even deal with the startup config). I think the approach you've taken differs from what pretty much all other implementations do, right?

I'm not convinced this is the proper way to do it, nor am I convinced it should change. Need to think more about it ;)

If we just flip it around, what is improved by the current behaviour? If sysrepo were to support opstate (whichever solution is picked in IETF) what benefits would the current behaviour bring?

**Comment by plajjan** [comment]
My original question has been answered and as I think the latter part has migrated into mailing form I will close this issue.
