### ISSUE TITLE
Docker image tag guidelines

### ISSUE THREAD

**Issue by plajjan** [sysrepo/sysrepo#404]
Hehe, I was about to open an issue on this a couple of days ago and wanted to suggest that we make the sysrepo-netopeer2 docker image build automatically.. but it seems it does already -yay \o/

I wonder from what though since there's no Dockerfile on this repo. Since automatically built, shouldn't it be built from this git repo so we actually get the latest changes?

Secondly, I would like to understand which tag is used for what. In the past I've seen these devel_201610xx images and honestly I'm not too keen on that structure.

I do think the git tags (v0.4.0 for example) should map to a docker image.

Question is what "latest" (which is the default you get when you pull a docker image) should point to? git master? This would make latest a moving target, so when someone complains about a bug in :latest we need the SHA sum of the image rather than it's tag name. Should we even bother with daily devel builds?

Thoughts?

**Comment by rastislavszabo** [comment]
Hi,
this repo now does have a dockerfile: https://github.com/sysrepo/sysrepo/blob/master/deploy/docker/Dockerfile :) It builds automatically into https://hub.docker.com/r/sysrepo/sysrepo/ image.

It is also now linked with https://hub.docker.com/r/sysrepo/sysrepo-netopeer2/ - each rebuild of sysrepo/sysrepo triggers rebuild of sysrepo/sysrepo-netopeer2:latest.

"latest" tag means the latest code from master branches. In the current phase of (quite rapid) development it is always recommended to use the latest code form master, so I don't think that we should even bother with other tags than `latest` (latest master) and `devel` (latest devel) for now.

If someone is about to report a bug, the best they can do is to provide the version output of `sysrepod -v` in case of bug in sysrepo and `netopeer2-server -V` in case of bug in netopeer.

If there was a need for having multiple tags, I would also suggest the git tags to be used: https://github.com/sysrepo/sysrepo/releases (e.g. `v0.4.0`) for sysrepo/sysrepo. But since the versions of sysrepo do not follow the versions of netopeer2, I don't know whether this tagging would be applicable for sysrepo-netopeer2 image. Actually, I would say that it should follow versions of netopeer2 rather than sysrepo.

Other tags of sysrepo/sysrepo-netopeer2 than latest and devel were added manually by @mislavn. I don't know about any practical reasons for having them there, but Mislav told me that these are just temporary and he will delete them later.

Apart from `latest` and `devel`, we may also have `ubuntu14.04_master` and `ubuntu14.04_devel` after migrating sysrepo/sysrepo-netopeer2 to ubuntu 16.04, which fits better for us (it contains all libraries we depend on in official repositories, so the build process is faster and the resulting image smaller). But the build of those cannot be triggered automatically, so @mislavn as the maintainer of sysrepo/sysrepo-netopeer2 will need to trigger their build manually from time to time.

**Comment by plajjan** [comment]
Ok, great. I saw the automatic build on docker hub but didn't find the Dockerfile at first (I assumed it would be in the root of the repo). Great work! :)

I agree on the latest part and understand the always-good-to-use-latest recommendation since it's such a young project.

What is difference between "master" and "devel" in git? Settings up so the release tags in git (like v0.4.0) become docker image tags is really easy on docker hub. Just regexp match the git tag and use the same for docker tag.

I understand versioning is hard when there are multiple components like sysrepo and netopper2, working closely together, but why would you say versioning should follow netopeer2 and not sysrepo version?

I think it's definitely time to move to 16.04. It's LTS and there's just no reason to stick to 14.04.

**Comment by plajjan** [comment]
Why wouldn't the tags propagate automatically? Docker hub has a provision to setup rules based on git tags or branches...

Right now you have devel_XXXXX - how about also having a :devel tag that simply uses the last commit on the devel branch. With the method described above it would be automatic.

For example, here's my config for another docker image;
![image](https://cloud.githubusercontent.com/assets/841628/19383855/bf34c84a-9206-11e6-9b8b-7312c174e779.png)
I match on git tags that look like semantic version tags (e.g. v1.2.3) and build that into a docker image with the same tag. The branch "master" is built into the docker image tag "latest". In your case you could do this differently, so you map git branch "master" to docker image tag "stable" and map git branch "devel" to docker image tag "devel", right?

**Comment by rastislavszabo** [comment]
Yes, we do have a similar setup up & running for sysrepo/sysrepo docker image: https://hub.docker.com/r/sysrepo/sysrepo/tags/ (including version tags that will be automatically added starting from the next version).

But tags from sysrepo/sysrepo do not automatically propagate to sysrepo/sysrepo-netopeer2. To only thing that I'm able to setup on dockerhub is that any rebuild of sysrepo/systrepo triggers rebuild of sysrepo/netopeer2:latest.

**Comment by plajjan** [comment]
Right, because the dockerfile for sysrepo-netopeer2 is not in this git repo. So what I'm suggesting includes moving that file into this repository. Put it in deploy/docker/Dockerfile.sysrepo_netopeer2 and then in docker hub you specify the path. So the same git repo builds two docker images.

I understand the versioning complexities with netopeer2 but it seems to me that what I suggest still  improves our situation, no? :)

**Comment by rastislavszabo** [comment]
@mislavn what do you think about this?
It would basically mean deleting https://github.com/sysrepo/docker-sysrepo-netopeer2 repo and start focusing only on two versions od sysrepo-netopeer2 dockerfiles - for the master and the devel branch. Then I would also suggest moving both to Ubuntu 16.04 and stop supporting 14.04 (to not require so many branches for the main sysrepo/sysrepo repository). I wouldn't have anything against this approach.

**Comment by mislavn** [comment]
I am OK with this. We can migrate the old  https://github.com/sysrepo/docker-sysrepo-netopeer2 repository to a new location.

Can we do this next Monday so I can sync with Luka where to move them?

**Comment by rastislavszabo** [comment]
@mislavn sure, take you time

**Comment by plajjan** [comment]
Just to clarify so we are in sync here; there would be two docker files, one for sysrepo and one for sysrepo+netopeer2. These would result in two different docker images. Each of these docker images would then have tags for latest (git master), devel (git devel) and potentially devel_X (for devel on a given date - but not automatically built and only if you wish to build these manually).

**Comment by mislavn** [comment]
> Just to clarify so we are in sync here; there would be two docker files, one for sysrepo and one for sysrepo+netopeer2. These would result in two different docker images. Each of these docker images would then have tags for latest (git master), devel (git devel) and potentially devel_X (for devel on a given date - but not automatically built and only if you wish to build these manually).

Yes.

**Comment by mislavn** [comment]
@rastislavszabo you can delete the https://github.com/sysrepo/docker-sysrepo-netopeer2 repo.

**Comment by rastislavszabo** [comment]
@mislavn can I also delete and re-create sysrepo-netopeer2 repo on dockerhub? It means that all the existing tags you created there manually will be lost: https://hub.docker.com/r/sysrepo/sysrepo-netopeer2/tags/

(sorry I did not have enough time to go back to this earlier)

**Comment by mislavn** [comment]
> @mislavn can I also delete and re-create sysrepo-netopeer2 repo on dockerhub? It means that all the existing tags you created there manually will be lost: 

I made local backups, so you can do it.

**Comment by rastislavszabo** [comment]
Hi,
done. I've created a new automated build: https://hub.docker.com/r/sysrepo/sysrepo-netopeer2/ (bsed on Dockerfile located here: https://github.com/sysrepo/sysrepo/tree/master/deploy/docker/sysrepo-netopeer2)

The image is now based on Ubuntu 16.04, which makes it much smaller and faster to build. Automated builds contain tags: `latest` - master branches and `devel` - devel branches, tags will be also generated for all upcoming sysrepo releases - based on github tags.

Since we need to run multiple processes in the docker iamge, I have included `supervisord` that takes care of the process management.
