### ISSUE TITLE
SR_DECIMAL64_T values require roundtrip to YANG in order to fetch a meaningful value

### ISSUE THREAD

**Issue by jktjkt** [sysrepo/sysrepo#421]
Sysrepo users have to take a detour to the YANG schema to fetch the expected number of decimal points and to process the resulting number, otherwise any data are off by N orders of magnitude.

As an example, [this](https://github.com/CESNET/Netopeer2/blob/master/server/operations.c#L50) and [this](https://github.com/CESNET/Netopeer2/blob/master/server/operations.c#L173) is how Netopeer2 processes the results. Sysrepo's examples do not perform this conversion and therefore they show wrong data.

I have never worked with libyang directly, so I have no clue on how to find the appropriate data node when all that I have is just a SR session and I'm in the middle of my ``module_change`` callback.

I would like to either get a pointer to the libyang data type from the ``sr_val_t``, or the ``sr_val_t`` should contain a tuple for each ``SR_DECIMAL64_t``: ``{int64_t number, uint8_t precision}``. The examples should be extended to show how to handle these data.

I wonder if ``double`` is actually safe to use in this context for data storage -- is it guaranteed to have the required precision by the C standard?

**Comment by jktjkt** [comment]
> I would like to either get a pointer to the libyang data type from the ``sr_val_t``, or the ``sr_val_t`` should contain a tuple for each ``SR_DECIMAL64_t``: ``{int64_t number, uint8_t precision}``. The examples should be extended to show how to handle these data.

I'll be happy to implement this. Is it an acceptable approach? If so, should I add a new struct to ``sr_val_t``, or should I replace the existing ``double``?

**Comment by milanlenco** [comment]
Hi Jan,
as you have already noticed the patch fixes the bug, but keeps the original design. The alternative that you suggested to store the 64bit decimal is I believe a preferred approach. We will certainly welcome if you decide to invest your time and re-implement it for the tuple variant.
In order to limit the amount of transferred data we shouldn't store any duplicate information into sr_val_t structure, so I would suggest to remove the `double` member then. For the cases when rounding errors are not an issue, I would also propose to add a helper into sysrepo/values.h (src/utils/values.c) for converting a value of type SR_DECIMAL64_T into a double. It could help to simplify less-demanding applications. Similarly, a decimal conversion helper for sr_node_t (a tree representation of data) -- sysrepo/trees.h (src/utils/trees.h) -- sr_node_t can be casted to sr_val_t, so you will be able to re-use the same code.
