### ISSUE TITLE
Can a change iterator be used after the event callback has returned? 

### ISSUE THREAD

**Issue by darren-west** [sysrepo/sysrepo#470]
When a change notification occurs it is possible to get a change iterator.
Is it possible to get this change iterator on the notification thread and pass it to different thread.
Once the new thread has the iterator can we then iterate the changes or is this not possible because the session passed in the callback is closed directly after?

My scenario is below: 

1) Receive a change notification, get the change iterator
2) Spawn a new thread
3) Allow the notification callback to return and subsequent callbacks to fire
4) Iterate over the change iterator
5) Close the iterator

**Comment by rastislavszabo** [comment]
Hi,
I believe this is related to the issue https://github.com/sysrepo/sysrepo/issues/349
It needs to be implemented as I'm describing there. Your scenario wouldn't work because once all notifications return, the commit will proceed (from verify to apply phase, or from apply phase to releasing the commit). Once commit context is released, you cannot use the session passed in the callback and iterate over changes anymore.

**Comment by darren-west** [comment]
Hi,
Makes sense. Thanks.
