### ISSUE TITLE
Validation does not fail on mandatory decimal64 field. 

### ISSUE THREAD

**Issue by darren-west** [sysrepo/sysrepo#510]
Hi,
I am having an issue with validation on commit. 

I have a yang model with the following list:

```
   list person {
      key name;
      leaf name { type string; }
      leaf birthday { type yang:date-and-time; mandatory true; }
      leaf weight {
        mandatory:true;
        type decimal64{
          fraction-digits 2;
          range "0.0 .. 150.0";
        }
      }
```
 

When I set a new person with a birthday and no weight on commit validation is successful, which i believe it shouldn't be.
When I do this the other way round setting a weight and no birthday this does causes a validation fail.

I understand this may be a libyang issue but I wondered if you have encountered an issue like this with decimal64 values.

Thanks in advance,
Darren

**Comment by milanlenco** [comment]
Hi Darren,

You have a typo in the yang model. Instead of `mandatory:true;` should be `mandatory true;`. Then it will report a validation error:
`[ERR] (srcfg_import_datastore:676) Input data are not valid: Missing required element "weight" in "person". (/test-module:person[name='Milan'])`

The syntax error should have been detected by libyang though. Please report it on their site if you have time, thanks.

Milan
