### ISSUE TITLE
Bulk operational data API

### ISSUE THREAD

**Issue by fanchanghu** [sysrepo/sysrepo#558]
I found that `sr_dp_get_items_cb` is called many times in a 'get' request for one subscriber if there are many state nodes in schema. However, this may cause problem when the state data is stored in another service, such as a remote host, we need send many messages to the remote host to get the state data. Can we just call 'sr_dp_get_items_cb' once with all needed xpaths, then the subscriber can return all state data once.

**Comment by fanchanghu** [comment]
By the way, it is not possible to provide all data in the first callback, become not all my state nodes are under the first node, such as `/A/B/f1`,  `/A/C/f2`.

**Comment by rastislavszabo** [comment]
Hi,
I probably misunderstood your concern on the mailing list. I thought that you are talking about nested data, e.g. for `/containerA/statenodeF1` & `/containerA/listB/statenodeF2`, and having subscription for `/A`, you would like to have the callback called only for `/containerA`, instead of  `/containerA` and  `/containerA/listB`.

What you are requesting can be implemented without changes in Sysrepo. You can configure callback for `/A/B/f1` to have greater priority, read all state data from external database in that callback (first callback that will be called), store retrieved data in `private_ctx` and fill the data in all subsequent callbacks from `private_ctx` instead of the external database.

**Comment by bhatkj** [comment]
Hi rastislavszabo,
  If possible, It would be really if we have one example describing the use of private_ctx.

**Comment by jktjkt** [comment]
@bhatkj , sysrepo doesn't care about the ``private_ctx``. As a C developer, you can put anything in there -- and you can alter your behavior based on what is already in there when a new callback is called.

As an example, check how the https://github.com/sysrepo/sysrepo-plugin-ietf-system/blob/master/system-plugin.c#L206 uses:

- one C function for rebooting or powering off the system,
- another C function for returning either uptime in seconds, or time since the start of the UNIX epoch,
- yet another C function for dealing with various fields of the uname data struct

**Comment by fanchanghu** [comment]
Hi,
Thanks for your reply, but there is still a problem, we must get all state data in the first callback, because we can not know how many nodes that need be got. This is inefficient when there are many state nodes in the schema.

**Comment by rastislavszabo** [comment]
@fanchanghu, so could you please provide the declaration of the new API that you are suggesting?

**Comment by fanchanghu** [comment]
I think the callback could be like this: 
`typedef int (*sr_dp_get_items_cb)(const char **xpaths, size_t xpaths_cnt, sr_val_t **values, size_t *values_cnt, void *private_ctx);`
The `xpaths` and `xpaths_cnt` are all the state nodes that one `get` operation needs. The callback is called only once for one `get` operation and one subscriber, then the subscriber could get all the state data by the given xpaths concurrently.

**Comment by rastislavszabo** [comment]
OK, we'll track this as an enhancement and may add this kind of API later. It would be most probably a new alternative "bulk" API, not a change of existing one.

**Comment by michalvasko** [comment]
Not relevant anymore, fixed.
