### ISSUE TITLE
Disable writable-running 

### ISSUE THREAD

**Issue by vishalwc** [sysrepo/sysrepo#571]
can we configure to disable writable-running?

**Comment by lukasmacko** [comment]
Hi,
It is mainly question targeting [Netopeer2](https://github.com/CESNET/Netopeer2) however I believe that @rkrejci  or @michalvasko can reply in this issue once you give us more detailed informations.

Could you briefly describe your use case and what is the motivation for this configuration request?
Regards,
Lukas

**Comment by vishalwc** [comment]
essentially we will not be using the writable:running  with fact that we use candidate datastore to configure and commit  write in running and external db so that both the data bases are sync 
the external database is our current implementation and we are moving to sysrepo now .

**Comment by rkrejci** [comment]
by "we will not be using" mean you as a NETCONF client? Because there can be other NETCONF clients connecting to the device and using writable-running. From the perspective of an application connected to the sysrepo and receiving configuration changes, it will always receive only the changes in running, no matter how they were performed (edit-config on running, copy-config or commit from candidate). So I don't see a reason to disable writable-running, am I missing something?

**Comment by vishalwc** [comment]
ODL Netconf client when finds wiriteable-running in capabilities it will do edit config directly on running 

however the server implementation is edit on candidate and  upon commit make changes to running datastore and external DB .
the sever design is NOT to allow direct changes on  running as it has external db to keep in configuration sync with sysrepo datastore

**Comment by lukasmacko** [comment]
Hi,
If you use sysrepo it is indistinguishable for a subscribed application whether the changes come from direct write to running or commit of candidate. The verification and apply callbacks are called either way.

What differences are you experiencing between direct-write to running and candidate commit from the subscribed application's point of view?

Regards,
Lukas

**Comment by rastislavszabo** [comment]
Closing, we do not plan to allow disabling writes to the running datastore in the sysrepo datastore itself.
