### ISSUE TITLE
proposal for new sr_set_item function.

### ISSUE THREAD

**Issue by mislavn** [sysrepo/sysrepo#591]
Hi,

at the moment I am working on sysrepo/snabb integration, and basically I need to map <xpath, value> to sysrepo, xpath and value are strings.

And I find it annoying that I need to check xpath data type, cast the value to the new type and send it to sysrepo.
Would it be a big problem to create a function:
int sr_set_item(sr_session_ctx_t *session, const char *xpath, const char *value, const sr_edit_options_t opts);

So sysrepo would behind the scene check if the string value is valid for the xpath and use the string instead of sr_val_t struct.

This is useful when sysrepo needs to get/set data from other configuration interfaces which usually have only strings (like uci in OpenWrt or snabb).

What do you think @rastislavszabo.

Regards,
Mislav

**Comment by rastislavszabo** [comment]
Hi,
yes we have nothing against the proposed API, e.g. `sr_set_item_str`. For getting values a conversion function from `sr_val_t` to string should be enough, as proposed in https://github.com/sysrepo/sysrepo/issues/284 .

**Comment by jktjkt** [comment]
User feedback -- I was in a same situation, my code was providing all data as untyped strings. In the end, I extended our non-sysrepo code to track the type information (using C++ variants) and added a pretty straightforward conversion using variant's type info.

At that time, I was wondering why SR doesn't at least provide a way of returning the expected data type for a given XPath that points to a leaf -- but then this is not that easy because of unions, for example. I realize that I could ask SR for the YANG scheme and use, e.g., libyang to parse the schema myself, but that sounded like too much work.

**Comment by rastislavszabo** [comment]
already merged into devel

**Comment by mislavn** [comment]
Great, I will update the C++ bindings.
