### ISSUE TITLE
make install fails 

### ISSUE THREAD

**Issue by vishalwc** [sysrepo/sysrepo#616]
CMake Error at examples/cmake_install.cmake:79 (message):
  Error: 1
Call Stack (most recent call first):
  cmake_install.cmake:146 (INCLUDE)

#603  was closed so opened this , the failure is with updated libyang

**Comment by lukasmacko** [comment]
Check `<repository>/data/ietf-interfaces.startup` and `<repository>/data/ietf-interfaces.startup` if they contain an identity defined outside of module without namespace (i.e:`<type>ethernetCsmacd</type>`) delete these files (or make them valid, see below). The issue is that libyang is not able to load them and update their content and the installation fails.
The correct way of using the identity is https://github.com/sysrepo/sysrepo/blob/master/examples/yang/ietf-interfaces.data.xml#L5

with libyang 0.11.87 and the latest sysrepo the installation passes.

**Comment by jktjkt** [comment]
Do we have some real users with deployed systems already? If not, then this is a non-issue. However, if we have people with field-deployed systems, then they effectively cannot upgrade because either the package won't install, or SR won't start, or the data would get lost. So this is actually a backward-incompatible change.

Do we promise to never make backward-incompatible changes at this point already? It's fine to say "nope, wait for 1.0 for that, and we're still doing our best anyway", but that decision should probably be documented somewhere.

(We don't have deployed systems yet at this point, so it's a non-issue for me personally. I'm just trying to make sure that SR rocks :).)

**Comment by joanlandry** [comment]
Is it possible to let me know what I need to use for type when do a set for an interface

I send this:
    value.type = SR_IDENTITYREF_T;
    value.data.identityref_val = "ianaift:ethernetCsmacd";
    rc = sr_set_item(session, xpath_buf, &value, SR_EDIT_DEFAULT);
    if (SR_ERR_OK != rc) {
       TRACE_LOG(TRACE_NETCONF, TRACE_INFO, "%s", sr_strerror(rc));
    }

Also tried:
    value.data.identityref_val = "ethernetCsmacd";

which also fails

and ideas what I need to put in value.data for type?


Which results in this error:
DBG] Processing set_item request.
[INF] Set item request running datastore, xpath: /ietf-interfaces:interfaces/interface[name='tun-1']/type
[DBG] Module ietf-interfaces already loaded
[DBG] libyang error: Failed to resolve identityref "ianaift:ethernetCsmacd".
[DBG] libyang error: Failed to create node "type" as a child of "interface".
[ERR] Setting of item failed /ietf-interfaces:interfaces/interface[name='tun-1']/type 29
[ERR] Set item failed
[ERR] Set item failed for '/ietf-interfaces:interfaces/interface[name='tun-1']/type', session id=1921866816.
[DBG] Circular buffer enqueue to position=6, current count=1.
[DBG] Thread id=140737317066496 will wait.
[DBG] New message enqueued into CM message queue.
[DBG] Circular buffer dequeue, new buffer head=7, count=0.

**Comment by joanlandry** [comment]
it looks like the ietf-interface type works if you send it as an rpc command and it goes through netopeer, but if you try to do a set via code sysrepo and pyang give an error on it.

**Comment by rastislavszabo** [comment]
> Do we have some real users with deployed systems already?

We are not aware of any.

We are still not feature complete. That being said, if a new feature requires a non-backward compatible change, we will do it. But we still try to introduce non-backward compatible changes only in new releases (e.g. 0.5.x, 0.6.x) - through the devel branch - to keep each version stable.

This issue was a bug in libyang that had to be fixed. Guys from CESNET were not expecting so dramatic impact, so they don't even informed us about the change in advance and we found it as a broken build in Travis.

**Comment by rastislavszabo** [comment]
make install works in clean build / repository.
