### ISSUE TITLE
Poor performance of notifications

### ISSUE THREAD

**Issue by jktjkt** [sysrepo/sysrepo#735]
On a 2016 notebook (Thinkpad T460s, Intel Skylake i5-6300U CPU, 24 GB of RAM, and a SATA SSD with XFS), emitting just 100 notifications takes between two to twenty-plus seconds, and the time keeps growing over time. My speculation is that this depends on the size of the current XML log in ``repository/data/notifications/$MODULE/`` which apparently gets rotated every ten minutes, according to its file name.

The time for emitting 100 notifications (and processing them in the same thread in my client app) grows like this:

- 2.7s
- 5s
- 9s
- 10.3s
- 12.5s
- 13.5s
- 15.7s
- 16.2s
- 17.3s
- 19.4s
- 20.5s
- 22s
- 23.5s
- 25s

After these attempts, the current 10-minute-log consumed 452kB on disk.

The notification is trivial, but it passes along a string:

```yang
  notification hi-there {
    description "Random notification";
    leaf message-text {
      type string;
    }
  }
```

As far as I know, nothing except my client is subscribed to these notifications. I have never run ``sysrepod`` after the ``repository/`` directory was re-created for these tests, and all testing relied on the "local" SR daemon.

I see that there's the ``SR_EV_NOTIF_EPHEMERAL`` flag which I do not use yet. My understanding of the whole NETCONF model might be wrong, so perhaps I do not fully understand the difference here. Suppose that I'm sending out notifications about a link-down event for some fancy router. The code which generates the notification IMHO cannot know whether there is some management system which is interested in these events --- it's just a piece of driver which monitors a local pin, for example. These events are probably very common and therefore irrelevant on an access switch, but I think that they should probably generate a proper "persistent" event which can be replied in case an external management system temporarily gets disconnected.

Opinion and thoughts are welcome.

**Comment by michalvasko** [comment]
Hi,
this is actually expected because after every notification the current log file (which can be up to the last 10 minutes as you observed) is parsed, the new notification is added into the parsed data tree, and the modified data tree is printed back into the file as a whole. It is true that using `SR_EV_NOTIF_EPHEMERAL` should cause the whole file modification to be skipped, but that way the notification will be forgotten for any later replay.

So, this whole mechanism can certainly be optimized, but there definitely are other priorities for us But, if you or someone else consider this critical, you are welcome to change the way notifications are stored or make it more effective.

Regards,
Michal

**Comment by michalvasko** [comment]
Fixed.
