### ISSUE TITLE
sysrepod -d does not work

### ISSUE THREAD

**Issue by michalvasko** [sysrepo/sysrepo#74]
Hi,
when starting freshly installed sysrepod to run on foreground (-d) it tries to parse some submodules, which is not possible, but without -d it starts fine. The full output:

    libyang[0]: Parser fails around the line 2.
    libyang[0]: Invalid keyword "submodule".
    libyang[0]: Module parsing failed.
    [WRN] (dm_load_schema_file:138) Unable to parse a schema file: sub-a-one@2016-02-10.yin
    [WRN] (dm_load_schemas:163) Loading schema file: sub-a-one@2016-02-10.yin failed.
    libyang[0]: Parser fails around the line 2.
    libyang[0]: Invalid keyword "submodule".
    libyang[0]: Module parsing failed.
    [WRN] (dm_load_schema_file:138) Unable to parse a schema file: sub-a-two@2016-02-02.yin
    [WRN] (dm_load_schemas:163) Loading schema file: sub-a-two@2016-02-02.yin failed.
    libyang[0]: Parser fails around the line 2.
    libyang[0]: Invalid keyword "submodule".
    libyang[0]: Module parsing failed.
    [WRN] (dm_load_schema_file:138) Unable to parse a schema file: sub-a-one@2016-02-02.yin
    [WRN] (dm_load_schemas:163) Loading schema file: sub-a-one@2016-02-02.yin failed.
    User defined signal 1

Regards,
Michal

**Comment by rastislavszabo** [comment]
Hi, 

the warnings from the attempts to load submodules are harmless (sysrepo does not know which yin files contain modules and which submodules and attempts to load all of them upon startup, those which cannot be loaded are just skipped. We will look into how we could ignore them more silently).

The crash due to signal is a bug in the debug mode, fill fix it soon.

Thanks for reporting!
Rasto

**Comment by michalvasko** [comment]
Thanks for the quick fix.
