### ISSUE TITLE
Duplicate dp_get_items callbacks for list nested in a container

### ISSUE THREAD

**Issue by jktjkt** [sysrepo/sysrepo#851]
I'm on CESNET/libyang@4999b32, sysrepo sysrepo/sysrepo@ed8b0a2. I have the following module:

```tree
module: czechlight-roadm-v2
    +--rw roadm
       +--rw channel-plan
       |  +--rw channel* [center-frequency]
       |     +--rw center-frequency          decimal64
       |     +--rw channel-width             decimal64
       |     +--ro approximate-wavelength    decimal64
       +--rw configuration
       |  +--rw channel* [center-frequency]
       |     +--rw center-frequency    -> ../../../channel-plan/channel/center-frequency
       |     +--rw mode                pass-mode
       |     +--rw voa-attenuation     attenuation
       |     +--rw description?        string
       +--ro optical-power
       |  +--ro channel* [center-frequency]
       |     +--ro center-frequency    -> ../../../channel-plan/channel/center-frequency
       |     +--ro input               measured-power
       |     +--ro drop                measured-power
       |     +--ro output              measured-power
       +--ro aggregate-power
          +--ro input     measured-power
          +--ro output    measured-power
```

and a ``dp_get_items`` callback that has been registered to provide data for ``/czechlight-roadm-v2:roadm``. When I ask for all data:

```c++
session->get_items("/czechlight-roadm-v2:roadm//*");
```

the callback is executed several times:

1) ``/czechlight-roadm-v2:roadm/channel-plan/channel[center-frequency='192.0']/approximate-wavelength``
2) ...
3) ``/czechlight-roadm-v2:roadm/channel-plan/channel[center-frequency='195.9']/approximate-wavelength``
4) ``/czechlight-roadm-v2:roadm/optical-power`` **<-- THIS**
5) ``/czechlight-roadm-v2:roadm/aggregate-power``
6) ``/czechlight-roadm-v2:roadm/optical-power/channel`` **<-- THIS**

I understand the reason behind items 1-3 and 5, but I would like to only get asked for either 4 or 6, but not both. Is there something that I'm doing wrong, or is it a bug in sysrepo?

In my ``.yang`` file, the entire ``container optical-power`` is marked as ``config false``. I don't see any behavior change when I move that to the embedded list; I'm still getting requests for both levels. For me, this is a problem because my code internally returns everything which is "below" a given XPath regardless of how many levels deep that might be.

**Comment by michalvasko** [comment]
Hi,
based on [this](http://www.sysrepo.org/static/doc/html/subscribtions.html) (rather hard-to-read documentation, but still) and the code, it seems to me this is intentional. Your callback will be called for every `list` and `container` and you are supposed to return everything except other nested `lists` or `containers` because they will be requested separately. The first callback is called on a `leaf` because its parent is not state.

It seems a bit strange, but I guess there were reasons for designing it this way. So, the documentation should be improved, but that is all.

Regards,
Michal

**Comment by jktjkt** [comment]
I've read that document before. It wasn't clear to me at all that one should not return data from nested lists or containers when asked for an upper-level container, though.

I do not understand why I get request **3**, though. There are no leaves at that level, the ``/czechlight-roadm-v2:roadm/optical-power`` contains just a single list, ``channel``. Why does sysrepo ask for an empty set of properties?

**Comment by michalvasko** [comment]
Because there is no check whether a `container` actually has some other nodes than `containers` or `lists`. You are supposed to simply return the container and nothing else. I guess the check could be added that non-presence containers with only containers and lists will not be requested from an application, if it helps.

Regards,
Michal

**Comment by michalvasko** [comment]
Not relevant anymore.
