### ISSUE TITLE
Question about intercepting modifications to the startup DS

### ISSUE THREAD

**Issue by jktjkt** [sysrepo/sysrepo#954]
I would like to write a plugin for basic configuration of IPv4 and IPv6 addresses to our HW's built-in NICs. The system in question is going to use `systemd-networkd` and we do not plan to handle dynamic device discovery -- just a list of addresses for now.

I have troubles mapping the concept of **startup** and **running** NETCONF datastores into this system's capabilities. The good thing is that `systemd-networkd` allows running with two sets of configuration, one in `/etc/` (for startup) and another in `/run` (for the running DS), so I could always just generate a config file and re-start my network-managing daemon upon any change.

However, sysrepo's documentation says that `sr_module_change_subscribe` is only about changes in the running datastore. How can I receive notifications about the startup DS so that I can produce configuration which is going to take place at the next fresh boot?

I would like to avoid relying on the auto-copying from startup to running because that would mean that my config is only applied once `sysrepod` and `sysrepo-plugind` start up successfully. I can imagine all sorts of interactions with `netopeer2-server` causing `sysrepod` to get stuck or to restart (something that I've seen in the past few months), and I would hate to see that my network configuration is not taking any effect. This cannot be solved by always writing the `/etc/` config based on the running DS because changes in the running DS are not supposed to be made persistent.

**Comment by jktjkt** [comment]
Perhaps the scenario with `ietf-interfaces` and `systemd-networkd` makes stuff a bit more complicated. Another nice example is `ietf-system` with its user and password management. On a typical Linux system, there's no difference between the "current" and "next boot" users/password databases unless I go the extra mile of implementing a custom NSS module.

Should I always rewrite `/etc/shadow` based on the content of the running DS? That would rely on `SR_SUBSCRIBE_EV_ENABLED` to occur "soon enough" during the next boot.

**Comment by michalvasko** [comment]
Hi,
this seems as a relevant use-case although, based on my understanding, not really supported by NETCONF (which, however, does not matter much). So, the best solution seems to be subscribing to `ietf-netconf-notifications:netconf-config-change` notification, which should be generated by *sysrepo*. It is not too efficient because you will receive notifications for any configuration change, so you will have to filter only the ones interesting for you.

In future, we will most likely implement subscribing also to `startup` datastore changes but do not want to do so at the moment. The reason is that we will add new datastores support later (`intended`, `operational`) and it seems natural to do this change together. Hope the proposed solution will suit you for now.

Regards,
Michal

**Comment by jktjkt** [comment]
Sounds great, thanks!

**Comment by rkrejci** [comment]
Hi, I see one other workaround for now. It's not 100% reliable, but when sysrepo/daemon works correctly, it should work as well - when the plugin/daemon is being terminated, it can get the startup data and store them as a startup file for systemd. In case of plugin this can be done as part of the cleanup function.

**Comment by michalvasko** [comment]
Fixed, possible to subscribe to all the datastores.
