### ISSUE TITLE
Question about setting capabilities 

### ISSUE THREAD

**Issue by dragon01134** [sysrepo/sysrepo#961]
### Description
Hi i am trying to add support for a new module. But our device cannot support startup and running datastore functionality so it has to be only running . i am wondering Is this something we can implement through sysrepo. 
If yes, how i can  do that ?(I went through sysrepo api, and also able to use sysrepo api to get changes,what i really need is how i will add subscription for any changes since here startup datastore is not there).

I tried disabling startup feature, but it doesn't reflect unless i first enable and then disable. 
  

Thanks!

**Comment by michalvasko** [comment]
Hi,
it is not possible to disable `startup` in *sysrepo* because it seems there is no reason to. You can have whatever device you want, it is solely up to *sysrepo* to store a configuration in a file and when the device is enabled (its model in *sysrepo*), the startup configuration is applied and from then also the running configuration. So, why would you need to disable `startup`?

Regards,
Michal
